### ISSUE TITLE
Vector 21 disables activation of rail accessories

### ISSUE THREAD

**Issue by mrkiel14** [acemod/ACE3#2940] opened 2015-12-05 03:32 UTC
ACE3 Ver: 3.4.0

Description: When Vector 21 is in active binocular slot within inventory, rail accessories (lasers, flashlights, etc) cannot be activated. Upon dropping Vector 21, rail accessories can now be activated.

Reproduce: Open the editor, place a unit and give them a Vector 21 in active binocular slot in inventory, along with a rifle complete with laser or flashlight rail accessory. With rifle selected, try to activate rail accessory. Drop Vector 21 on ground or place in backpack (anywhere BUT in active binocular slot), then again try to use rail accessory.

**Comment by PabstMirror** [comment] 2015-12-05 03:36
All binocular items will do this when equipped.  Same core issue as #2916
Already fixed in release branch and we hope to have hotfix done soon.

**Comment by commy2** [comment] 2015-12-05 09:49
Duplicate of https://github.com/acemod/ACE3/issues/2917

**Closed by commy2** 2015-12-05 09:49 UTC
