### ISSUE TITLE
After update 1.54 cant kill soldiers (required 8-10 and more hits!)

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2908] opened 2015-12-01 22:28 UTC
Likely damage system (Nexus update 1.54) has been changed and now using ACE3 you can't kill a soldier immediately. It takes minimum 8-10 and more shots and hits! 
If you disable ACE3 then everything is working fine, for killing a unit requires 1-3 shots as before this crazy update.
As seems to me, after the 1.54 required to update ACE3 mod also.

ACE3 Version: 3.3.2
ArmA Version 1.54

**Comment by commy2** [comment] 2015-12-01 22:36
duplicate of #2600, #2768, #2903 and #2905

**Comment by alganthe** [comment] 2015-12-01 22:40
RHS's units broken, can't fix.

**Comment by mickeymen** [comment] 2015-12-01 22:51
BIS again and again broke your game(

**Comment by jokoho48** [comment] 2015-12-01 22:57
Update is Released

**Closed** 2015-12-01 22:57 UTC
Labels: duplicate

**Comment by mickeymen** [comment] 2015-12-01 23:02
SUPER FAST UPDATE!!! Thanks

**Comment by mickeymen** [comment] 2015-12-01 23:14
I downloaded ACE3 3.4 but the problem still exists! I can't kill a soldier with a few shots. To kill him requires 10-15 shots!

**Comment by prowox** [comment] 2015-12-01 23:20
One shot kills now,
Vanilla https://www.youtube.com/watch?v=JDCVt3D3sgE
Massis Units https://www.youtube.com/watch?v=ykFDIAU2H-I

**Comment by jokoho48** [comment] 2015-12-01 23:31
can someone else confirm? with Vanilla Units and not with some other mod?

**Comment by audiocustoms** [comment] 2015-12-02 05:23
Confirmed...
Arma: latest (v1.54.133570)
CBA_A3: latest (v2.2.0.151130 - PWS)
ACE3: latest (v3.3.2 - PWS)

Vanilla:
Navid 9.3mm, 10m distance, one shot kill to GA Carrier GL Rig, insta kill

ACE3/CBA_A3:
Navid 9.3mm, 10m distance, complete mag to naked body (chest), not even blinking. only a headshot could take the unit down.

I don't wanna be rude, NOT AT ALL! 
But a serious question: do you test this kind of stuff before releasing? If so, how do you do that? It would be nice to see a demonstration or checklist how you test your work.

**Comment by mickeymen** [comment] 2015-12-02 05:41
Unfortunately 3.3.4 has the same problem. Place  in the editor a BLUFOR squad and the player as the commander. Shoot at their soldiers and you will see the problem

**Comment by jonpas** [comment] 2015-12-02 06:28
>I don't wanna be rude, NOT AT ALL! 
But a serious question: do you test this kind of stuff before releasing? If so, how do you do that? It would be nice to see a demonstration or checklist how you test your work.

@audiocustoms You do realise the update was released very shortly after Arma 3 update, just to make it compatible due to the changes in vanilla? You are still talking about 3.3.2

**Comment by mickeymen** [comment] 2015-12-02 06:32
I hope you will soon do a normal update to solve this problem

**Comment by jonpas** [comment] 2015-12-02 06:51
@mickeyman

Can you verify it happens with CBA+ACE3 only? Content mods (those that add vests for example) will have issues until fixed on their side due to change BI made with hitpoints/armour.

**Comment by mickeymen** [comment] 2015-12-02 06:56
I have no mods. Only @DragonFyre. It's like you know only sound mod

**Comment by commy2** [comment] 2015-12-02 10:55
I can not confirm. Works fine here.

**Comment by audiocustoms** [comment] 2015-12-02 11:07
ok, false alarm. works as it should with all up to date (v3.4.0). i have to apologize

**Comment by commy2** [comment] 2015-12-02 11:10
Did you try with 1.52 : D ?  That obviously won't work.

**Comment by audiocustoms** [comment] 2015-12-02 11:39
no, latest A3, latest CBA but ACE wasn't up to date on PWS the time i tested

**Comment by mickeymen** [comment] 2015-12-02 12:26
"That doesn't mean anything. It can still change anything by accident." 

No that's exactly what it means! If the mod is SOUND MOD, then this means it has no influence on damage model! 
I tried to disable DragonFyre mod, but he problem still is present

**Comment by bux578** [comment] 2015-12-02 12:28
> If the mod is SOUND MOD

The problem is, if the author fucks something up in config it has influence on everything else. Being a sound mod doesn't not mean it doesn't affect anything else.

**Comment by mickeymen** [comment] 2015-12-02 13:25
@bux578 Ok, but in the our case the DragonFyre mod is clear ;)

**Comment by mickeymen** [comment] 2015-12-02 13:35
I updated CBA and problem disapear! The old version CBA addon was reason of this problem!

**Comment by commy2** [comment] 2015-12-02 23:02
>No! that's exactly what it means! If the mod is SOUND MOD, then this means it has no influence on damage model

Just for the record. This assumption is completely wrong.

**Comment by mickeymen** [comment] 2015-12-03 15:58
@commy2 Ok, ok;)
