### ISSUE TITLE
AI Units Have Unlimited Medical Supplies 

### ISSUE THREAD

**Issue by Gator3719** [acemod/ACE3#7765] opened 2020-06-16 21:28 UTC
**Mods**
- **Arma 3:** `1.98.146373` [Most recent Steam version]
- **CBA:** `3.15.1` [Most recent Steam version]
- **ACE3:** `3.13.2` [Most recent Steam version]

**Description:**
AI units have unlimited medical supplies. Units that spawn with medical supplies never consume them and have an unlimited amount of them. Units without medical supplies seem to have an unlimited amount of them. 

This behavior allows units to immediately bandage themselves when they are shot and therefore can only be killed by multiple, rapid shots to extremities (where the unit bleeds out or becomes unconscious before being able to bandage all of their wounds) or by immediate fatal wounds.

**Steps to reproduce:**

1. Open ARMA 3 with only ACE and CBA active.
2. Create a new mission in Eden editor.
3. Place a player unit and several AI units. (Civilians for units which do not spawn with medical equipment and soldiers for a unit that has medical equipment.)
4. Shoot an AI unit in the leg or arm, they will immediately bandage/heal that body part. 
5. Shoot the same AI in an extremity again. They will again bandage/heal that body part. If you shoot them twice before they are able to began healing, they will heal both wounds one after the other as long as they do not bleed out.
6. Repeat ad-nauseam. (You can shoot AI dozens of times in extremities and they will fully heal them.)

**Expected behavior:**

Units without medical equipment would not be able to treat wounds. Units with medical equipment would consume that equipment as they treat wounds as would players.

**Where did the issue occur?**

- Eden editor. Both with and without Zeus module and mods.

**Log Files:**

[Report.txt](https://github.com/acemod/ACE3/files/4789184/Report.txt)

**Comment by Drofseh** [comment] 2020-06-16 22:28
IIRC this is by design

**Comment by synixebrett** [comment] 2020-06-17 01:04
A setting would be nice that by default is unlimited equipment.

**Comment by BaerMitUmlaut** [comment] 2020-06-17 06:23
Duplicate of #7377.

**Closed by BaerMitUmlaut** 2020-06-17 06:23 UTC
Labels: kind/bug
