### ISSUE TITLE
Waking up instantly after being knocked unconscious

### ISSUE THREAD

**Issue by moonmanmove** [acemod/ACE3#2682] opened 2015-10-04 02:16 UTC
ACE3 Version: 3.3.2 stable

Mods:
@CBA_A3
@ace

Placed ACE3 Modules:
Advanced medical

Description:
If you get shot you always wake up instantly after

Steps to reproduce:
Start a dedicated server
Down someone, preferably a player
they will instantly wake up after being knocked unconscious

RPT log file:
not needed

This didn't seem to be a problem with previous versions

**Comment by L0rn1x** [comment] 2015-10-07 08:56
yes, the same here. 

Last version seems to have overstated the self revive mechanism when a player is hit in a not lethal part.
the only way to stop the waking up is to hit the player in his head.
the player remains down only when he lose to much blood.

Maybe something related to this:
"Low levels of pain will decrease over time (#1954)"

Low level limit is "too high"?
Heavy wounded players could have low level of pain?

**Comment by moonmanmove** [comment] 2015-10-10 20:23
to add more info to this, what i mean is when someone gets knocked unconscious no matter what the source they will wake up after about 10-20 seconds, no one ever stays unconscious even with low blood. will this be fixed for 3.4.0?

**Comment by Cyruz143** [comment] 2015-10-11 01:54
Dupe of https://github.com/acemod/ACE3/issues/2494

**Comment by headedhorseman101** [comment] 2015-10-17 17:32
Happens in advanced med too.

**Comment by commy2** [comment] 2015-10-18 07:54
Closing as duplicate. Please use the other issue.

**Closed by commy2** 2015-10-18 07:54 UTC
Labels: duplicate
