### ISSUE TITLE
Ace Unit Attributes Medic, Doctor, Engineer, ect resetting to default or swapping settings with other units

### ISSUE THREAD

**Issue by Snak3Doc** [acemod/ACE3#4902] opened 2017-02-15 06:19 UTC
**Arma 3 Version: 1.66.139586
**CBA Version: 3.1.2.161105
**ACE3 Version: 3.8.3

**Mods:**
- @CBA_A3
- @ace

**Description:**
- I set the ace attribute options for medics and engineers in a playable squad, after doing this i save the mission and go to double check the units and all the ACE options have ether reset to default, swapped engineers and medics around, or made the unit both a medic and an engineer. The main problem this causes is the medics dont have the the ability to give IV's.

**Steps to reproduce:**
- place down any 4 units (tried with medics and engineers as well as other units) through the attribute ace options set 2 as medics and 2 as engineers, now when going back through the units to check their settings, all the medic and engineer settings will have swapped, reset or doubled up.

**Where did the issue occur?**
- Editor, Dedicated windows server

**Placed Modules:**
- None

**Comment by AACO** [comment] 2017-02-15 17:17
I've seen this issue before with some of the custom 3DEN components I've put together before. Looking at the medical/engineering code it seems to be an issue with using missionNamespace when storing 3DEN values.

How to reproduce:
1. Place 5 units down in 3den.
2. Edit a single unit's attributes to be a medic/engineer.
3. Open one or two other unit's attribute, don't change anything, but save the attributes.
4. Save the mission
5. Look at the SQM, the units that you just opened, but didn't edit will now be marked as a medic/engineer

I can put together a PR later with how I fixed it (stored the variable on the control level, instead the missionNamespace level)

**Comment by Snak3Doc** [comment] 2017-02-16 02:51
ahh awesome thanks i found a temporary way around it using "this setVariable ["Ace_medical_medicClass", 1];" in the medics init

**Closed** 2017-02-18 18:27 UTC
