### ISSUE TITLE
Virtual Arsenal on the one point, generates a few AI-units.

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2618] opened 2015-09-26 22:49 UTC
ACE3 Version: 3.3.2
Stable

**Mods:**
* `@CBA_A3`
* `@ace`
* `@DragonFyre`

**Placed ACE3 Modules:**
None

**Description:**
If you shoot in the Virtual Arsenal the AI, then you notice that on the one place located is a few units simultaneously. One bot, will fall dead, while others will remain in erect position. I counted 3 units inside each other. Thus, as I understand at loading VA, on the one point are spawned a few bots.
In vanilla game, I never noticed such a problem

**Steps to reproduce:**
Open virtual arsenal and shoot in the AI (several times).

**Where did the issue occur?**
Virtual Arsenal

**RPT log file:**
Not needed

**Comment by nic547** [comment] 2015-09-27 00:04
![2015-08-11_00001](https://cloud.githubusercontent.com/assets/7825979/10120491/db64f00e-64bb-11e5-8e1e-8650f72b57cf.jpg)
AFAIK ace can't do anything about this, as va doesn't work to well with ace medical

**Comment by alganthe** [comment] 2015-09-28 06:57
BI's fault on this one it's unfortunately not something that can be fixed.

**Comment by commy2** [comment] 2015-09-28 21:01
I suspect that this is caused by https://github.com/acemod/ACE3/issues/1859

**Comment by PabstMirror** [comment] 2015-11-28 19:51
Should be closed with PR #2876 as this is probably a dupe of #1859

**Closed** 2015-11-28 19:59 UTC
Labels: BIS' fault
