### ISSUE TITLE
ACE3 - Menu blanked-out menu options problem

### ISSUE THREAD

**Issue by sparxz** [acemod/ACE3#2256] opened 2015-08-24 18:58 UTC
ISSUE: ACE3 - Menu blanked-out menu options.
Help much appreciated with my first bug post    ;-)

ARMA3 1.44.130654
(indicate if stable or dev, if dev indicate the commit the version is based on)  ? ? ? ? ? Not sure,
please see screenshot.

**Mods:**
* @cba_a3 = Current version: 1.1.23.150604 RC7 Hotfix 2
* @ace3 =v3.2.1.0  -  04 Aug 15
[No other MODS loaded apart from above]

**Placed ACE3 Modules:**  = NONE

**Description:**
Loading up ARMA3with a most bare-bones options to test ACE3, I am getting a blanked-out
menu option.The only thing that slightly interacts with the mouse in ACE-OPTIONS COLORS TAB SETTINGS,  but no change is seen or applied.

**Steps to reproduce:** =  Every loading of ACE

**Where did the issue occur?**
I only use single Player(learner ;-) )
Seems to have occurred after I did an upgrade of CBA & ACE3 around same time.
I have removed all Mods down to minimal, and this error still occurs.
When I first noticed it ACE Menu would appear as 'under' AGM options,
and inaccessible without disabling AGM first.
ACE would be slow on WIN-KEY, or only show first Icon and not span out as normal.
Eventually I ended up with the ACE Menu not even loading on MAIN Menu.

**RPT log file:**
Client' arma3launcher.rpt   ->        http://pastebin.com/wg2tCECE

Four sequential Screenshots  ->   http://imgur.com/a/aRAUZ

**Comment by jokoho48** [comment] 2015-08-24 19:00
please attacht the RTP file form ArmA 3 not form the Launcher

**Comment by PabstMirror** [comment] 2015-08-24 19:01
Look for a file like

arma3_2015-08-23_23-09-59.rpt

The most recent file that starts with *arma3_*

**Comment by jonpas** [comment] 2015-08-24 19:01
Looks like a duplicate of #2240 

Check your CBA as well, looks like a mix of 2 versions.

**Comment by jokoho48** [comment] 2015-08-24 19:04
@jonpas  i use a Modified Version form CBA where i had crashed my PFH :D

**Comment by PabstMirror** [comment] 2015-08-24 19:21
`Version: 1.44.130654`

We do not support that version of arma.
They have been adding commands that we have been using


Right click on arma in steam, goto properties, and then updates tab and make sure steam is updating the game for you.

If you NEED to be using 1.44, you could maybe try our 3.0.0 release, but I think even that came out after 1.46.

**Comment by sparxz** [comment] 2015-08-24 21:33
Thanks,
Found Rep log:
http://pastebin.com/QMzW8WYB

Captured as far as Main menu.

In my case Log was dumped to:
C:\Users\name\Documents\Arma 3 - Other Profiles\Sparxz

Will try to find if I have conflicting CBA now.

**Comment by jokoho48** [comment] 2015-08-24 21:36
yeah you must update our ArmA 3 or use 3.0.0 for using ACE without issues

**Comment by sparxz** [comment] 2015-08-24 21:46
Thanks how do I update ArmA 3 with out loosing out too much on settings etc.
Also the lowest version of ACE available is 3.0.1 on PlayWithSix.

**Comment by jonpas** [comment] 2015-08-24 21:47
> Right click on arma in steam, goto properties, and then updates tab and make sure steam is updating the game for you.

That's how you update, you won't loose any settings.

**Comment by sparxz** [comment] 2015-08-24 22:07
Did not download via Steam(don't really use it!) only used it to launch occasionally.
This what I get:
  http://imgur.com/fEtpVaW

No update tab,

**Comment by cptnnick** [comment] 2015-08-24 22:08
Looks like we got ourselves a pirate! Arma 3 is a Steam-only game. Try
buying the game and using the up to date version, and see if you still have
errors.

**Comment by sparxz** [comment] 2015-08-24 22:09
Will try that. Thanks. Did not know.

**Closed** 2015-08-24 22:11 UTC
Labels: invalid
