### ISSUE TITLE
Microdagr issue

### ISSUE THREAD

**Issue by Hailstorm12** [acemod/ACE3#4090] opened 2016-07-12 02:42 UTC
**Arma 3 Version:** `1.62.137494` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.6.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@aceX`

**Description:**
Microdagr disappears after looking through vector (binoculars in general?)

**Steps to reproduce:**
- put microdagr in inventory, look through vector, look out of vector, microdagr disappears until you press the key to bring it up again.

**Where did the issue occur?**
- Editor (Singleplayer) 

**Placed Modules:**
- None

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

https://gist.github.com/Hailstorm12/63d348910b6acae25c2980b11af3cc3c#file-gistfile1-txt

**Comment by PabstMirror** [comment] 2016-07-13 18:12
I can't reproduce by just using the vector, but I can if I hit reload
So I think it's a dupe of #4088 as the microDagr checks `canInteractWith`

**Comment by commy2** [comment] 2016-07-13 18:16
Do I have to do anything in https://github.com/acemod/ACE3/pull/4096 or does it work with that PR?

**Comment by PabstMirror** [comment] 2016-07-13 18:20
That should close this, as it removes the addCanInteractWithCondition.

At least in my testing that was the only way to reproduce this.

**Comment by commy2** [comment] 2016-07-13 18:21
OK.

_cough_ Fixed in #4096.

**Closed by commy2** 2016-07-13 18:21 UTC
Labels: bug, can't reproduce
