### ISSUE TITLE
AP not damaging/destroying reactive armor

### ISSUE THREAD

**Issue by SnagleTooth** [acemod/ACE3#9563] opened 2023-10-23 12:04 UTC
Arma 3: 2.14.150957 stable
CBA: 3.16.0.231017 stable
ACE3: 3.16.0 stable
RHSAFRF and ACE3 Compat

**Description:**
The reactive armor on the tanks don't get destroyed by AP rounds, only HEAT rounds. Advanced Vehicle Damage enabled.

**Steps to reproduce:**

1. Enable Advanced Vehicle Damage
2. Shoot any tank with ERA ( T-90AM, T-72B3, T-80U etc) using AP rounds
3. ERA Takes no damage/not destroyed

**Expected behavior:**
The ERA is supposed to be destroyed, otherwise it keeps providing extra protection to the tanks making them excessively strong.

**Where did the issue occur?**
Editor

**Additional context:**
I'd assume the line 335 in https://github.com/acemod/ACE3/blob/master/addons/vehicle_damage/functions/fnc_processHit.sqf would have to be changed

**Comment by johnb432** [comment] 2024-07-08 13:57
Duplicate of #8720.

**Closed by johnb432** 2024-07-08 13:57 UTC
Labels: kind/bug
