### ISSUE TITLE
Unable to decrease compass size on Map after moving it around

### ISSUE THREAD

**Issue by Kowgan** [acemod/ACE3#1285] opened 2015-05-18 07:18 UTC
ACE3 Version: 3.1.0

**Mods:**
* @cba_a3
* @ace3
* @ACRE2
* @UOMaps
* @UOMods

**Placed ACE3 Modules:**
* ---

**Description:**
* If the player moves the small sized compass around the map, then double click it to increase its size, he won't be able to return the compass to its original size by double clicking it again.
The issue won't happen if the player never changes the small sized compass' position.

**Steps to reproduce:**
* Open map
* Move the small sized compass around
* Double click the small compass to make it bigger
* Double click the big compass to make it smaller; fail.

**Where did the issue occur?**
* Multiplayer, Singleplayer.

**RPT log file:**
* ---

**Comment by alganthe** [comment] 2015-05-18 09:19
It seems to be a BI issue I have it from time to time in vanilla.

**Comment by jaynus** [comment] 2015-05-18 15:00
@esteldunedain @KoffeinFlummi  Is this BIS fault?

**Comment by deleyt** [comment] 2015-05-18 15:31
http://feedback.arma3.com/view.php?id=19471

It happened for me after using AGM and it still haunts me. Weird thing is, if I use AGM or ACE3 now, the issue is solved. When I use vanilla again the problem is back (huh?).

**Comment by Kowgan** [comment] 2015-05-18 17:22
Funny thing. I never had that issue on Vanilla or CSE. It happened after installing ACE. Luck, I guess?

Well, thanks for the info, guys.

**Comment by bux578** [comment] 2015-05-18 17:37
For reference, same issue got reported while AGM still was a thing:
https://github.com/KoffeinFlummi/AGM/issues/1462

**Comment by jaynus** [comment] 2015-05-18 21:02
Closing.

**Closed by jaynus** 2015-05-18 21:02 UTC
Labels: BIS' fault, bug
