### ISSUE TITLE
AI fire at unconscious enemy

### ISSUE THREAD

**Issue by gripen888** [acemod/ACE3#8041] opened 2020-12-11 16:11 UTC
**Mods (complete and add to the following information):**
- **Arma 3**:  `2.00` [steam]
- **CBA:** `3.15.1` [steam workshop]
- **ACE3:** `3.13.5` [steam workshop]

**Description:**
AI will **sometimes** ignore the fact that enemy (AI or Player) is unconscious and fire at him. Sometime 2-3 shots. Other times 3-4 mags.
Like the AI is sometimes not satisfied with unconscious enemy and want him dead *just to be sure*.
This create very unpleasant experience when "**Player Fatal Injuries**" set to **Never**. You end up with player patient having enormous number of wounds.

**Steps to reproduce:**
1. Create any new mission and place yourselft as zeus.
2. Spawn 2 squads (enemy to each other). 
3. You should see this behavior in about 33% of firefights.

**Expected behavior:**
If AI really wana *hard-kill* enemy and is not satisfied with unconscious, there should be some addon settings that let me adjust this behavior or idealy turn it off.

**Where did the issue occur?**
- any SP or MP mission

**Log Files:**
- https://pastebin.com/Fi8uweL3

**Additional context:**
I also noticed that sometimes the unconscious soldier is recolored as civilian. Not sure if this hase anny connection tho.

Edit1 - updated log

**Comment by Drofseh** [comment] 2020-12-11 16:28
I recommend not using the `-noLogs` startup parameter, it makes your log file useless

**Comment by gripen888** [comment] 2020-12-11 22:19
My bad. Log updated

**Comment by YetheSamartaka** [comment] 2020-12-16 14:40
If AI fires 1-5 shots, that is perfectly all right and "realistic". I've talked with many people that are enlisted and it is "standard procedure". However what is not nice and "realistic" is that sometimes AI will fire all magazines, sometimes even though person is already dead - that is quite problematic. Surely it would be nice for many communities to have tick-box to turn off such behaviour and also fix that "all-mags fired" bug" for those communities that are perfectly fine with this "procedure".

**Comment by ZeusWrath** [comment] 2021-01-07 13:26
"AI fire at unconscious enemy" - is this a problem or is it a bug?  AI should shoot at unconscious if that AI is nearby!

My ACE3 experience shows that AI, on the contrary, will not shoot at unconscious, which is not realistic behavior in war. 
[My ticket is closed](https://github.com/acemod/ACE3/issues/8020) and you see the opposite
this is strange

**Comment by gripen888** [comment] 2021-01-07 13:35
As I wrote before - AI shooting sometimes at unconscious is fine, as long there is some hard cap on shots fired. 2-3 shots are perfectly ok. 4 **mags** is **not**. For what i noticed, only status the AI will be satisfied is dead enemy - with you will never get if you have **player fatal injuries** set to **never**

**Comment by BaerMitUmlaut** [comment] 2021-01-13 22:43
To clarify: The bug described here is caused by AI not recognizing that their target is unconscious. The intended behaviour is that AI ignore unconscious units and this goal will not change.

Note that executing unconscious soldiers is a war crime and not standard procedure.

**Comment by BaerMitUmlaut** [comment] 2021-09-28 07:02
If you have this issue consistently, you should make sure that you don't run any AI mods or scripts that might interfere.

**Comment by MoshPit86** [comment] 2021-09-28 09:13
Well, I am obviously not the only person that has encountered this issue in the past, even with vanilla AI and no other mods loaded. And since all the related GitHub issues are still open and marked as 'bug', I was just wondering if anyone got behind that and if this is intended to be fixed sometime. If it wasn't related to ACE, these issues would've been closed / marked as discussion by now, wouldn't they?

**Comment by gripen888** [comment] 2021-09-28 09:37
I did some testing this morning and can confirm the bug **is still present**, but the behaviour seems diferent. Spawn squad -> spawn enemy unit. Squad shoot at enemy and put it to unconscious. If unit was able to return fire (even one bullet), unit will not be relolored and stay on original side as unconscious. If unit was not quick enough to return fire, it will recolour as civilian. Squad will continue to supress unconscious for few seconds (enemy or civ), and then stop. **And now** - if any ai from squad come close enough to unconscious **enemy** ai (1 meter or less), the whole squad will start shoting again on unconscious enemy. If unconscious is recolored as civilian, the squad will not target him anymore (even if standing on top of him). The solution could be making sure that any unconscious unit will be recolored as civilian 100% times. (AI mods like LAMBS_Danger make the bug more problematic due to change of tactics. It makes AI go to chceck unconscious unit -> then the bug will occure again.) 
But the bug is still present even without any other mods.

**Comment by gripen888** [comment] 2021-09-28 13:29
My buddy from group found a workaround for this bug. 
You neet to insert this code to "initServer.sqf" in folder with mission.

```SQF
["ace_unconscious", {
    (_this select 0) setCaptive (_this select 1);
}] call CBA_fnc_addEventHandler;```
 
This will set all unconscious units as captive, therefore ai will not be shoting at them (excluding final supress).
We will be testing if its not gonna conflict with something. I guess its better then nothing for now.

**Comment by BaerMitUmlaut** [comment] 2021-09-28 16:02
@MoshPit86: I have no idea why you think I am saying this is not bug within ACE. I am saying that if you have this issue *consistently*, that means all the time, with every unconscious unit, then it is probably the fault of another mod.

All bugs are intended to be fixed, unless there is a "status/wontfix" tag on it. There is a pull request linked above, but it has not been approved and is not merged.

@gripen888: Setting the unit as captive has a bunch of unwanted side effects and was thus removed when we changed this behaviour. It might behave better or it might behave worse, depending on what other scripts and mods you use. I would currently not recommend this.

**Comment by Mike-MF** [comment] 2023-09-19 00:53
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Closed by Mike-MF** 2023-09-19 00:53 UTC
Labels: kind/bug
