### ISSUE TITLE
[ACE Hearing] No ear ringing and deafness with close explosions

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#2422] opened 2015-09-14 11:56 UTC
ACE 3.2.1

Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
None/ACE Hearing

Description:
There is no ear ringing and deafness when something blows up near you.

Steps to reproduce:
Spawn a mortar and shoot near yourself (50-100). You will hear explosion and probably it will hurt you but no ringing and deafness.

Where did the issue occur?
Tested in SP

RPT log file:
None

**Comment by PabstMirror** [comment] 2015-09-14 20:58
Dupe of #1988
Should be fixed in next release.

**Closed by PabstMirror** 2015-09-14 20:58 UTC
Labels: duplicate
