### ISSUE TITLE
Medical vehicle boost training only occurs in passengers seat

### ISSUE THREAD

**Issue by grester** [acemod/ACE3#3562] opened 2016-03-08 03:29 UTC
**Arma 3 Version:** `1.56` (stable - hotfix)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- The medical location boost training on vehicles only happens in passengers seats. I'm not sure if it is intended to be this way as most vanilla medical designed vehicles have plenty of passenger seats, but quite a few mods such as RHS, medical oriented vehicles sometimes only have 2 seats one of them being the driver. Resulting the patient to ocuppy the passenger seat and the player ends up on the driver seat.
Could this functionality be expanded to other seats as well or perhaps add a tickbox to the medical vehicles module to manually set this? I haven't posted this in feature requests as I'm not sure if it is indeed a bug/mistake.

**Steps to reproduce:**
- Open the editor and place a unit, make sure it is set as player and is not assigned as a medic.
- Place an empty vehicle and set it as a medical vehicle, through attributes or old module sync way.
- Place "Medical settings ACE" module and set "Medical Level" and "Medics setting" to "Advanced" and "Locations boost training" to Enabled
- Play scenario, enter the vehicle previously placed as driver
- Self-diagnose pulse, message saying "You find a normal heart rate" appears implying the player hasn't been boosted to medic training

**Where did the issue occur?**
- Tested on: Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- Medical settings ACE

**RPT log file:**
- [Arma RPT Copy](http://pastebin.com/wAX3GvYz)
- [Ace Debug Dump](http://pastebin.com/NjsvLtuL)

**Comment by esteldunedain** [comment] 2016-03-08 03:36
Looking at the code, the driver, gunner or commander of the vehicles are not boosted to medic, which is of course by design.

**Comment by J-Ziegler** [comment] 2016-03-13 17:03
Presumably the idea is that those other parties are busy doing their jobs? 

But they can't perform them while treating anyhow.

**Comment by Glowbal** [comment] 2016-06-16 12:54
Closing. This is done by design.

**Closed** 2016-06-16 12:54 UTC
Labels: by design, discussion
