### ISSUE TITLE
Warning Function name unit network id - spam

### ISSUE THREAD

**Issue by TimelessInfinity** [acemod/ACE3#3622] opened 2016-03-24 08:24 UTC
**Arma 3 Version:** `1.56` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- (Spawning Units method)

**Description:**
- This is a little bit tricky and need a bit more to explain. I have the last days spend much time to figure out what is going on and of course Iam not sure whether it is right to post it here. I want to do so in another Issue Tracker may from ALiVE but the issue pops only up when ACE is in the modset, additional the error is not there when ACE +CBA is alone. So maybe you see the bad circumstances for me where i should post.

- Try to explain the error.
In the last weeks I was not up to date with my Server, so the Issue Iam sure dont occur bevore ACE 3.5.0.
In all MissionSetups when Units Spawn in the "Warning name Function" spam the RPT for every Unit they spawn in/out or die. When the Mission use a "caching" system and you fly with Zeus is the RPT spam heavy. The same with Zeus spawn Units or only a Spawn Script in the same Mission.

- Figure down where it comes from
Only ACE+CBA and may the Spawn Script or Zeus dont occur this "heavy" error.
But in Singleplayer/Editor the "light" one is this and this one have no server/performance issue.
`WARNING: Function 'name' - O Alpha 1-3:5 has empty name`

-  Now ACE + one of the "spawn in/out" solution above create the error.
`WARNING: Function 'name' - 637fa040# 164212: o_soldier_01.p3d has no unit
 - network id 0:0
 - person `

- Only CBA+any kind of spawn/missionmaker solutions (Alive/MCC/Zeus/SpawnScript etc.)
Dont occur this Error. I mean both errors dont pop up.

Why this broke the Mission on our Server? (I dont know whether it is this error, nothing more there to find.)

This may only to see in ASM. You need to see the Engine Simulation Cycles.
I have linked 1 Screenshoots but they need a little explain what i have done.
This is Missionstart only 7-10minutes.
When the blue line (AI) goes up i fly to cached AI, you see the simulation cycles broke down to 5 or 8 and AI line blue pops in. The CPS stay there so long the AI is active. In this case Iam alone on the Server, when there are player the Server is gone.
The only error Message is the Warning function, i found nothing more in the last 3days of work on this. When i load the same setup but without ACE then is all normal. 50CPS/FPS, no Warning error.
The mission from the ASM screens are little, and in this case this was only 100 AI + 1 player.

- Iam aware that this is not the best step to figure out from where the error occur. 
Of course i try so many tests the last days and only ACE + CBA the error NOT occur.
So I dont know what i can do to better figure out what is the problem.
All Missions need Units, and of course there are many tools for it, but every kind of Spawn Unit in Mission solution + ACE pops up this error and let the Server goes down dependent to the circumstances from the player.
Additional Iam "google" so much but nothing to find in this case. I think may the problem is something big on my own ServerAdmin site....but i hope i figure out that this is not the case :/

- Information, RPTs, logs etc
The RPT logs are 3, i decide one spawn solution above, but i can deliver more RPTs for every kind of setup you guys need or want.
RPTs are ACE+CBA without the error (only the "light" one)
ACE+CBA+Alive with error
Alive+CBA not the "light" or the "heavy" error pops up

This RPTs are Singleplayer/Editor, but is the same on Dedicated Server (sure i can upload this)
ASM Picture is dedicated.

**Steps to reproduce:**
- Spawn Units with Zeus / a Spawn Script / ALiVE / MCC
- Spawn in / out (cached) or the death from Units create the error

**Where did the issue occur?**
- Dedicated /  Singleplayer / Editor (Singleplayer)

**Placed Modules:**
- Doesnt Matter which modules, place minimal one or two
- May a hint, ACE in the Modset is load but no Module in the Misson placed the error not occur, but now only test it in the Editor.

**RPT log file:**
- ACE+CBA          http://pastebin.com/2MwF9Xwr
- ACE+CBA+Alive http://pastebin.com/vgctACvV
- CBA+Alive          http://pastebin.com/bNcjWYVD

- ASM                   http://www.pic-upload.de/view-30127535/asm.jpg.html

**Comment by esteldunedain** [comment] 2016-03-24 11:56
@TimelessInfinity, as for this:

```
WARNING: Function 'name' - O Alpha 1-3:5 has empty name
```

we've seen this error before. Apparently AI units are being spawned without a name by the engine in certain circunstances. So when ACE tries to get their name (e.g. for drawing nametags), that warning is thrown. However, it doesn't create any further problem in our code base. This is an engine bug, and should be reported to BIS.

Regarding this:

```
 7:31:22 WARNING: Function 'name' - 39c8e040# 165813: o_soldier_01.p3d has no unit
 7:31:22  - network id 0:0
 7:31:22  - person`
```

I'm not sure, but most probably it is related to the above; seems like an issue i nthe engine too. However, ACE only uses the `name` function twice each time a unit is created and once every time you remote control a unit. Given that the error is thrown many times per second, I suspect that might be ALIVE's fault.

All in all, I'm not sure we can do anything about these issues. 

@commy2, what do you think?

**Comment by SzwedzikPL** [comment] 2016-03-24 13:58
Spawned AI do not have a proper `ACE_Name` becouse of this error. It can be fixed by adding one more check after 1-2 sec after unit init

Example: http://i.imgur.com/kM5lVc4.png

**Comment by TimelessInfinity** [comment] 2016-03-24 14:43
@esteldunedain thanks for comment.

I'm want to try to explain a little bit more, maybe is there a hint for you guys. And may things are not "clear" enough cause english is not my mother tongue.

In all Missions is ACE the "Base" can i say. But all Missions are not playable anymore. When i kick ACE from the Mission then are all Missions playble, but this is NOT an option for us.
Again, i choose Alive but the error pops up too with other Unit spawn methods/solutions.

The thing from my view is, that i cannot explain why the impact is so big on a dedicated server cause a Unit name is not given.
Example from the ASM picture above. When AI goes up and CPS down, then there are may 100Units spawned. In the RPT there are many Warnings from the example above, but this warnings are not in a loop, they are not spam continuously - but the CPS stay down.
So may this Warning is not related to this "Impact"? 
Maybe there is something in the background?

In the picture you see that the CPS goes up, at this moment the AI is despawned/cached.
This makes sense when the Server Hardware may a little bit to low to handle 100Units, but this is a bigger machine, in normal Missions there a lot more Units.
At this point are 100%performance in the same Mission with ACE.

When we say lets play nevertheless and iam want spawn with Zeus the same begins with less Units.

Cause ALiVE:
Its not my opinion to bring here other mod related stuff in. But in this case i need some modification for spawning Units when ACE is active.
What i want say, there are many many updates in the last weeks since 3den, from BIS site and all bigger mods. So i can confirm this error was not there for 3den or BIS hotfix or ACE/Alive patches.
But of course may is there a change from Alive that this error let pops up but only in combination with the name function from ACE? Or otherwise.
But when Zeus or a script spawn in then the error pops up too.

Additional (maybe not topic related)
You talk about the Zeus Remote control.
When i go remote in a Unit and the CPS is down, the error was spam in the rpt and so on.
Then can i only walk, not shoot anymore or something like that.
Additional, its not possible with a remote controlled Unit go in a Vehicle where a player sit in.
In this case i switch out from the remote Unit to my player Unit and a second after that i switch in Zeus mode and was kicked to the end of the map (water) with the Zeus camera.

Additional 2
I can make a few more tests, or missions or what ever.
When anyone say what i can do. Maybe for more "Informations", time and server are there.

Additional 3
No idea where should post this:
"3.5 Milestone, very nice job all in all what you guys do here, thanks for all the hard work"

**Comment by esteldunedain** [comment] 2016-03-24 14:54
@TimelessInfinity, the bottomline is that that warning is thrown by the engine; it's not documented and we don't really know what's causing it.

I'm quite sure both ACE and Alive are launching valid scripting commands, because no sqf errors are being displayed. Hence, the problem is on BIS's end, in the engine itself. In my opinion they are the ones responsible for solving it, or at the very least debugging what's causing this so we can try to work around their bugs.

**Comment by TimelessInfinity** [comment] 2016-03-24 16:58
@esteldunedain, ok I understand this.

But can anyone confirm that this issue is a "new" one since the last updates?
Is BIS knowing about it? Should I report this?

First I have thought i go back to ACE 3.4 and CBA, but it seems this is not possible when its on BIS site.

One think Iam wondering, anybody who use anykind of Spawn Unit/Missionmaker solution with ACE should have this problem, but I cannot find anything related to this. And this is not an issue where you can play further on dedicated server, this let the server crash.
So, I think a little bit more this is eventually on my own site.

**Comment by commy2** [comment] 2016-03-24 19:40
This has been the case since Arma 2.

**Comment by commy2** [comment] 2016-03-24 19:47
This is also __NOT__ the reason your server crashes. You'll have to contact BI for them to fix crashes. 
I repeat: this cannot be the cause of a server crash.

**Closed** 2016-03-29 13:48 UTC
Labels: BIS' fault, bug
