### ISSUE TITLE
Unable to interact with ace modules first setting.

### ISSUE THREAD

**Issue by dragonspride1995** [acemod/ACE3#5164] opened 2017-05-14 00:09 UTC
**Arma 3 Version:** `1.68.1412-5` (stable)
**CBA Version:** `3.3.1` (stable) 
**ACE3 Version:** `3.9.1` (stable)

**Mods:**
```
- ace Steam http://steamcommunity.com/sharedfiles/filedetails/?id=463939057
- CBA_A3 Steam http://steamcommunity.com/sharedfiles/filedetails/?id=450814997 
- ALiVE Steam http://steamcommunity.com/sharedfiles/filedetails/?id=620260972 
- ASR AI3 Steam http://steamcommunity.com/sharedfiles/filedetails/?id=642457233 
- BloodLust Steam http://steamcommunity.com/sharedfiles/filedetails/?id=667953829 
- CSA38 mod - Czechoslovak army 1938 (Munich crisis) Steam http://steamcommunity.com/sharedfiles/filedetails/?id=641305739 
- CUP Terrains - Core Steam http://steamcommunity.com/sharedfiles/filedetails/?id=583496184 
- CUP Terrains - CWA Steam http://steamcommunity.com/sharedfiles/filedetails/?id=853743366 
- CUP Terrains - Maps Steam http://steamcommunity.com/sharedfiles/filedetails/?id=583544987 
- DynaSound 2 Steam http://steamcommunity.com/sharedfiles/filedetails/?id=825181638 
- Enhanced Movement Steam http://steamcommunity.com/sharedfiles/filedetails/?id=333310405 
- Enhanced Soundscape Steam http://steamcommunity.com/sharedfiles/filedetails/?id=825179978 
- Enhanced Visuals Steam http://steamcommunity.com/sharedfiles/filedetails/?id=880703327 
- IFA3_AIO_LITE Steam http://steamcommunity.com/sharedfiles/filedetails/?id=660460283 
- Immerse Steam http://steamcommunity.com/sharedfiles/filedetails/?id=825172265 
- Kurt's Survival System (KSS) Steam http://steamcommunity.com/sharedfiles/filedetails/?id=828121231 
- LEN - Waffen SS Infantry pack for IFA3 LITE Steam http://steamcommunity.com/sharedfiles/filedetails/?id=823581498 
- LEN - Weapons pack for IFA3 LITE Steam http://steamcommunity.com/sharedfiles/filedetails/?id=825222328 
- MCC Sandbox 4 - Mission Making The Easy Way Steam http://steamcommunity.com/sharedfiles/filedetails/?id=338988835 
- Sabre Planes - Iron Front Integration Steam http://steamcommunity.com/sharedfiles/filedetails/?id=868574512 
- Sabres Military Aviation Steam http://steamcommunity.com/sharedfiles/filedetails/?id=756352410 
- Sabs Aircraft Lib Steam http://steamcommunity.com/sharedfiles/filedetails/?id=631771505 

```

**Description:**
- While adding Ace Module(s)', unable to change first setting.

**Steps to reproduce:**
- Place Module
- Enter Module
- Attempt to change first setting.
 Youtube Video Available. {https://www.youtube.com/watch?v=mRrz2cdRCB0}

**Where did the issue occur?**
- 3D Editor (Multiplayer)

**Placed Modules:**
- Advanced Medical Settings [ACE]
- Basic Medical Settings [Ace]
- Medical Menu Settings
- Revive Settings [Ace]
- Set Medical Class [Ace]
Other
- Set Cost [Default]
- Set Attributes - object
- Set Attributes - groups
- Set Attributes - players
- gamemaster

**RPT log file:**
- https://pastebin.com/59408dtq
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by jonpas** [comment] 2017-05-14 01:40
This is a vanilla bug, try changing your UI size, it usually fixes it.

**Comment by dragonspride1995** [comment] 2017-05-14 01:59
Specifically US size, or do you mean Interface size?

**Comment by dragonspride1995** [comment] 2017-05-14 01:59
Specifically UI size. or do you mean interface size?

**Comment by jonpas** [comment] 2017-05-14 02:25
U**I** = User **Interface**, so yes, I guess. :D

**Comment by dragonspride1995** [comment] 2017-05-14 02:26
I confirm that was the problem, That seems to have fixed it. Thankyou <3

**Comment by tbeswick96** [comment] 2017-05-14 13:49
An easier workaround than changing UI size is to drag the window a small amount using the coloured bar at the top of the window.

**Comment by PabstMirror** [comment] 2017-05-14 15:12
IIRC this is in the 1.70 dev changelog somewhere
So should be fixed properly in a few days

**Comment by kripto202** [comment] 2017-05-16 19:10
it is fixed on today's changelog

**Comment by SilentSpike** [comment] 2017-05-16 22:01
Can close once someone has confirmed in-editor :+1:

**Comment by PabstMirror** [comment] 2017-05-17 02:42
Looks like it's working fine now

**Closed by PabstMirror** 2017-05-17 02:42 UTC
Labels: fault/BI

**Comment by dragonspride1995** [comment] 2017-05-18 11:51
Thankyou all.
