### ISSUE TITLE
ACE 3 not letting Arma 3 save

### ISSUE THREAD

**Issue by dwrinn** [acemod/ACE3#3597] opened 2016-03-18 17:26 UTC
Hi,
My name is Dan Wrinn,  I downloaded ace # and now when ever I go to load a saved game arma 3,  the game shuts down and I get the following error message: 
 
 

 
 
Have you ever seen this message before and if so how do I fix it.  I trid downloading it off steam and your web site. I attached a copy of the error report in a zip file.
Thanks 
 
Dan Wrinn

[Arma3Launcher_Exception_20160317T024610.txt](https://github.com/acemod/ACE3/files/180106/Arma3Launcher_Exception_20160317T024610.txt)
![ace](https://cloud.githubusercontent.com/assets/17932742/13886346/d9c3c8b8-ed0c-11e5-9f75-04d8ae2bfe1a.png)

![ace](https://cloud.githubusercontent.com/assets/17932742/13886371/efb6f456-ed0c-11e5-9bca-3b9770a7099d.png)

**Comment by 654wak654** [comment] 2016-03-18 17:28
How did you manage to not use the [issue template](https://github.com/acemod/ACE3/blob/master/.github/ISSUE_TEMPLATE.md)?

**Comment by dwrinn** [comment] 2016-03-18 17:38
I deleted it. Do you want me to resubmit using the template?

Dan

**Comment by jonpas** [comment] 2016-03-18 18:14
> I deleted it. Do you want me to resubmit using the template?

What else do you think the template is there for?

**Comment by commy2** [comment] 2016-03-18 20:57
The screenshots are of no help. A proper RPT file is required.

**Comment by commy2** [comment] 2016-03-20 10:58
Closing as dup of #3397 as no information provided seems to indicate a different issue.

**Comment by commy2** [comment] 2016-03-20 10:59
Closing as as a duplicate of #3397 as no information provided seems to indicate a different issue.

**Closed by commy2** 2016-03-20 10:58 UTC
Labels: duplicate
