### ISSUE TITLE
Possible cookoff-related server/client lockup issue

### ISSUE THREAD

**Issue by brndd** [acemod/ACE3#4519] opened 2016-10-07 04:15 UTC
**Arma 3 Version:** `1.64`
**CBA Version:** `3.1.0`
**ACE3 Version:** `3.7.0`

**Mods:**
- `@CBA_A3`
- `@ace`
- CUP Terrains
- CUP Core
- RHSUSAF
- RHSGREF
- RHSAFRF

**Description:**
- Upon destroying an RHS ZSU-23-4 with a Javelin, FPS hit absolute rock bottom for about half a minute, the dedicated server completely locked up, and client RPT was spammed with about 21,000 lines of the following:

``` [ACE] (cookoff) WARNING: no valid selection for cookoff found.  File: z\ace\addons\cookoff\functions\fnc_cookOff.sqf Line: 31```

**Steps to reproduce:**
- Fire a Javelin at an RHS mod ZSU-23-4. Cannot reproduce, however.

**Where did the issue occur?**
- Dedicated multiplayer

**Placed Modules:**
- None

**RPT log file:**
- https://gist.github.com/brndd/653a0bd3bceacde81e9689484a2a4ca0

**Comment by commy2** [comment] 2016-10-07 05:08
Duplicate of https://github.com/acemod/ACE3/issues/4515
Fixed in https://github.com/acemod/ACE3/pull/4487

**Closed by commy2** 2016-10-07 05:08 UTC
