### ISSUE TITLE
Explosive charges damage underpowered on tanks

### ISSUE THREAD

**Issue by DLEGION** [acemod/ACE3#3834] opened 2016-05-29 05:10 UTC
**Arma 3 Version:** `1.58` (stable)
**CBA Version:** `2.x.x` (stable) (updated with steam at today date)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- The damage of some explosives (Demolition charge and satchel charge at least) seems way underpowered used on tanks (leopard and other MBT), needs like 8 demo charges to seriously damage a leopard tank for example, and infinite charges will still not kill it (make a secondary explosion). In vanilla ARMA3 it takes 1 single demo charge to seriously damage a tank and 3 demo charges to cause a secondary explosion for the same tank, and 1 satchel charge destroys it with secondary explosion.

**Steps to reproduce:**
- Load the editor, set up a player with explosives or an item with arsenal, place a leopard tank (or another MBT), attach to it a demoilition charge....and see the results!

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal. everywhere the same.

**Placed Modules:**
- No additional module placed.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by Armilio** [comment] 2016-05-29 17:17
It's fine like it is. It's a no-sense that an explosive makes more damage than a antitank mine or than a antitank missile. Indeed they continue to have a weak anti-explosive armour: with the rhs tanks, that are better crafted vehicle, you can damage only the tracks with the explosives. Against vanilla tanks one satchel basically makes all the tank parts red.

**Comment by DLEGION** [comment] 2016-05-30 07:04
Oh...so its by design ? Honestly i still think that a well placed charge (exhaust,gun,ecc ) should do some serious damage, probably at least equal if not more than a "random hitting " at missile or at mine. Anyway i noticed that sometime a AT rocket destroy a tank in 1 hit, and sometimes do not damage it at all ! Is that normal too ? Maybe it bounced off ? 
Thanks for your answer and help !

**Comment by DLEGION** [comment] 2016-05-30 09:59
ah ok, thanks for the info man !
Was used to vanilla ARMA3 and this seemed like a bug!

thanks !


________________________________
Da: Armilio <notifications@github.com>
Inviato: domenica 29 maggio 2016 19.17
A: acemod/ACE3
Cc: DLEGION; Author
Oggetto: Re: [acemod/ACE3] Explosive charges damage underpowered on tanks (#3834)


It's fine like it is. It's a no-sense that an explosive makes more damage than a antitank mine or than a antitank missile. Indeed they continue to have a weak anti-explosive armour: with the rhs tanks, that are better crafted vehicle, you can damage only the tracks with the explosives. Against vanilla tanks one satchel basically makes all the tank parts red.

-

**Comment by Armilio** [comment] 2016-05-30 10:47
> after many tests, i noticed that:

>    RPG does NOT damage tanks at ALL. 6 rockets (3 of each type) to a tank with absolutely NO results (everything as white). I expected at least a bit of damage to tracks or turrets. mah.
>     NLAW shot to leopard side = no damage at all. NLAW to perfectly back of a leopard got engine RED. more shots makes no difference at all.
>     TITAN with AT missile kills a tank every shot (merkava tanks sometimes survive but badly damaged)
>     TITAN AP missile doesnt work for me, at least i cannot lock it to anything,any idea of what i do wrong with it?

Yeah, the vanilla tanks are like RPG-proof, even the Titan would make little to them if wasn't for the ACE top-down attack. But they may be disabled by an explosive. Bad crafting that depends on the model (basically only tanks APFSDS ammo can completely penetrate a vanilla tank, but i guess that explosive damage overrun the model armour) and on the armour config values. I don't know if ACE-team can do something about that.

**Comment by esteldunedain** [comment] 2016-05-30 11:46
Isn't the Leopard a BWmod tank?

As far as I understand this issue is due to inconsistency in vehicle armor parameters between Vanilla, RHS, BWmod, etc. Some of those params are part of the model, so we can't patch them either.

I don't see a way of fixing it from our side, sorry.

**Comment by commy2** [comment] 2016-05-30 11:56
The AAF MBT is a Leopard 2SG
![http://www.dishmodels.ru/picture/glr/11/11972/g11972_3334894.jpg](http://www.dishmodels.ru/picture/glr/11/11972/g11972_3334894.jpg)

**Comment by esteldunedain** [comment] 2016-05-30 12:04
Aha, ok. So leaving BWMod aside, I think we still cannot change the vanilla vehicle armor. And decreasing the satchel charge explosive damage would probably mess with damage to soft vehicle, structures, etc.

**Comment by DLEGION** [comment] 2016-05-30 13:15
I dont use vehicle mods, just vanilla. In fact i menaged to increase pipebomb damage, to the point that now 3 well placed charges or 6 badly placed always destroy a tank. Isnt possible to do the same for the rpg and nlaw ? 
Just an idea. Thanks guys !

**Comment by Armilio** [comment] 2016-05-30 13:38
>Aha, ok. So leaving BWMod aside, I think we still cannot change the vanilla vehicle armor. And >decreasing the satchel charge explosive damage would probably mess with damage to soft vehicle, >structures, etc. 

I know i know, the only way to do a decent fix is to modify the model, starting from the hitpoints positions, and it's not a easy job. The problem of the vanilla tanks are well-explained in the wiki:

https://community.bistudio.com/wiki/Arma_3_Damage_Description

> -In vanilla A3, the effects of armor are largely ignored by the damage system.
> 
> -More accurately: armor penetration is present, but its significance is overwhelmed by the global hitpoint effect, this due in part to the way hitpoint "spheres" are placed in many Arma vehicles. **the effects are particularly dramatic for high damage-value weapons and for indirectHit weapons**.
> 
> -Caliber-based ballistics work very well, **but caliber is bugged for rockets & missiles (it can't be added)**.
> -Nor can the submunition feature be used as a workaround (it is also bugged for missiles, and limited/unreliable for anything other than high-trajectory artillery shells).
> -A script-based approach must be used to enable those weapon types to penetrate armor correctly. RAM contains such an approach.

**Comment by DLEGION** [comment] 2016-05-30 14:56
Ah ok thanks for the detailed explation ! I would have helped but unfortunately modify the models is too much for my few time !
Thanks !

**Comment by DLEGION** [comment] 2016-08-13 06:37
heey guys !
i noticed yesterday with a friend a little "problem" ....
as you know i edited the pipebomb damage to something more realistic to the point that 2-3 well placed charges can blow up any tank...and thats what is loaded on my dedicated server.
but a friend of mine, that has un-edited ACE3 3.6.2  noticed that while 2-3 of my charges were blowing up tanks, he needed something like 6-8 of them !!!  

...so ...there is something wrong...like server taking the client pipebomb (un-edited) info instead of the server (edited) one !
any idea ? thanks !

**Comment by esteldunedain** [comment] 2016-08-13 23:31
@DLEGION, you need to modify configs on ALL clients+server because CONFIG DATA IS NOT BROADCASTED OVER THE NETWORK. Each client uses their own.

BTW, having different config entries on client and servers can create desync under some conditions.

**Comment by DLEGION** [comment] 2016-08-14 10:46
aah ok thanks !

**Comment by DLEGION** [comment] 2016-08-14 11:31
may i ask you a little explanation please?
 i love ACE for many features, but absolutely cannot live with some features/bugs (like player damage system). seems i got lucky editing ACE_medical because players can join and play no problem, but removing a module (like javelin) seems to broke compatibility (players got connection problems and cannot join).
the very disappointing thing is that a player with no ACE3 at all can join no problem !
can you suggest me how safely remove the unneded modules and keep compatibility ?
huge thanks !

**Comment by commy2** [comment] 2016-08-14 11:35
Remove them on the clients too.

**Comment by esteldunedain** [comment] 2016-08-14 12:01
@DLEGION, as a rule of thumb client and server need identical pbos. The are some exception, but they are much rarer than people think. It's preferable to just stick to using the same pbos everywhere.

**Comment by DLEGION** [comment] 2016-08-14 13:57
ah ... ok :(
thanks man for the info!

**Comment by DLEGION** [comment] 2016-09-11 15:51
heey guys !
i had some free time, and got a closer look to explosives. 
being "hit" value totally unuseful (at least seems so) i had to do some fine tweaking about "indirecthit" value.
i finally made it to what seems correct and realistic for me (1 poorly placed M112 dont destroy a tank, but a very good placed one does, same for the SLAM, more types of detonators for bouncer mine and SLAM ecc.. ecc..) !
i wish to share my results, so here's the link:

http://www.mediafire.com/download/qxwd18zb7ztbe79/ace_explosives.pbo

hope it help realism and gameplay ! bye !

**Comment by madpat3** [comment] 2017-11-23 17:09
@commy2 https://camo.githubusercontent.com/042c48c6cedf56c80a66f8c76a69fe196172b7f8/687474703a2f2f7777772e646973686d6f64656c732e72752f706963747572652f676c722f31312f31313937322f6731313937325f333333343839342e6a7067

actually it's a prototype of the unproduced leopard 3:
https://www.contra-magazin.com/wp-content/uploads/2017/01/Leopard2-MBT-620x330.jpg

**Comment by jonpas** [comment] 2018-11-18 16:13
BI/3rd party mod fault, don't see us fixing it this late in ACE3 development due to major rework needed, closing.

**Comment by Mike-MF** [comment] 2023-09-11 00:54
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Closed by Mike-MF** 2023-09-11 00:54 UTC
Labels: fault/BI, fault/3rd party mod
