### ISSUE TITLE
IR Laser/Laser/Flashlight won't work

### ISSUE THREAD

**Issue by narrundo** [acemod/ACE3#2952] opened 2015-12-06 04:57 UTC
ACE3 Version: 3.4.0
-

Mods :
-

@CBA_A3
@ace
@AllinArmaTerrain
@MCCSandbox
@RHSAFRF0.3.9.1
@RHSUSAF0.3.9.1

Placed ACE3 Modules:
-
none

Description:
-

using ACE 3 IR Laser/ Laser or Flashlight won't work when pressed L, tried to change keybinding and still do nothing. This problem also occurs on vanilla attachments and RHSMod attachments. Problem vanished when I unplug ACE 3 addon.

Steps to reproduce:
-
equip primary weapon, add Flashlight or IR Laser attachment, then press L by default or toggle switch for lights on/off.

Where did the issue occur?
-
Tested on dedicated server, haven't tried on SP or Editor

**Comment by narrundo** [comment] 2015-12-06 06:08
solved , problem caused by MCC Sandbox mod

**Comment by narrundo** [comment] 2015-12-06 06:09
solved , problem caused by mcc sandbox mod

**Comment by commy2** [comment] 2015-12-06 09:21
Nope. Bug in ACE. Duplicate of https://github.com/acemod/ACE3/issues/2917

**Comment by commy2** [comment] 2015-12-06 10:10
Close as up. Fix soon.

**Closed by commy2** 2015-12-06 10:10 UTC
Labels: bug, duplicate
