### ISSUE TITLE
Spectator - Smoothing

### ISSUE THREAD

**Issue by jameslkingsley** [acemod/ACE3#3197] opened 2016-01-20 17:10 UTC
It would be nice to have some _optional_ smoothing applied to the camera movement (as seen in [F3](https://github.com/ferstaberinde/F3)'s spectator). It makes it easier for recording cinematics and is generally nicer for the eyes. I'm not sure what the math is for it, but it's like an [easing function in JavaScript](http://easings.net/) for example [easeInOutCubic](http://easings.net/#easeInOutCubic) smooths the animation on both start and end points.

**Comment by SilentSpike** [comment] 2016-01-20 18:30
This is something I've considered implementing, I don't think it's very hard to do but just haven't got around to investigating and testing an implementation yet.

It's also a feature request :stuck_out_tongue: It can stay open though

**Comment by esteldunedain** [comment] 2016-01-20 18:30
:+1:

**Comment by BaerMitUmlaut** [comment] 2016-01-21 15:11
Shouldn't that just be [`camCommand "inertia on"`](https://community.bistudio.com/wiki/camCommand)? Never experimented with that command but it may be worth a try.

**Comment by SilentSpike** [comment] 2016-01-21 16:14
Yes, although it first requires the camera code to be rewritten using the `cam` commands (which I recall having odd experiences with)

**Comment by jameslkingsley** [comment] 2016-01-21 16:25
Is it possible to use the old camera.sqs code since that supports the Bulldozer controls by default so there would be instant controller support?

**Comment by commy2** [comment] 2016-01-21 16:27
>camera.sqs
O_O

**Comment by SilentSpike** [comment] 2016-01-21 16:32
I mean, if you want to use that why don't you just use that instead? :smile:

**Comment by BaerMitUmlaut** [comment] 2016-01-21 17:31
Silent, that should not be a problem. You are using a camera, thus using that command should be fine, if it works at all... I know some camera commands are completly broken though.

**Comment by nomisum** [comment] 2016-02-09 16:01
I would appreciate that feature. One of the things CSSA3 is still better in as of now.

Inertia - Command works just fine.

**Comment by SilentSpike** [comment] 2016-02-09 17:10
@BaerMitUmlaut Yeah I've tried it before, and the command works, however I seem to recall that it didn't move as expected even though the code was otherwise the same as now

**Comment by SilentSpike** [comment] 2016-05-12 19:55
It's been so long since I looked at this that I can't remember what my issues were with the `cam` commands, but a recent dev branch changelog means I'll probably look into it again once it's in stable:

`Fixed: The camSetDir script command was working incorrectly`

**Comment by SilentSpike** [comment] 2017-08-12 14:01
An update on this:

The spectator overhaul that is now merged to master is using a `camcurator` camera object so that it can make use of the engine driven movement controls associated with that (massively reduces code complexity and overhead). Unfortunately a side effect of this is that `camCommand "inertia on"` is not supported by that camera object.

I won't close the issue as unsolvable as it's possible there's still a method of implementing this (perhaps we can make our own camera object that supports everything we need?).

**Comment by nomisum** [comment] 2017-08-12 14:34
the easiest thing would be a call on https://community.bistudio.com/wiki/BIS_fnc_cameraOld which is a really basic camera with inertia toggle and zoomability. would be sufficient for most cases.

**Comment by Mike-MF** [comment] 2023-09-11 00:49
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Closed by Mike-MF** 2023-09-11 00:49 UTC
Labels: kind/feature request, exp/advanced, help wanted

**Comment by nomisum** [comment] 2023-09-11 06:19
ftr as i got pinged

streamator also uses custom self made smoothing that might be inspiring: https://github.com/TaktiCool/Streamator/blob/bc3f0848836b4ebc12e4870612d9bbc6783b1065/addons/Streamator/Spectator/fn_cameraUpdateLoop.sqf

however i dont expect any work here as apparently not an issue for most.
