### ISSUE TITLE
My default Arsenal settings are gone

### ISSUE THREAD

**Issue by ir0n1e** [acemod/ACE3#5950] opened 2017-12-22 00:12 UTC
rma 3 Version: 1.80
CBA Version: current
**ACE3 Version:**current

Mods:
CBA RHS BWA3 ACE

Description:

It is not possible to see things at night with NV attached
Steps to reproduce:
Play it
Where did the issue occur?
Everware

Well, my loadouts are gone, how to get them back? Import function or something? Or warning?

**Comment by jonpas** [comment] 2017-12-22 00:19
Duplicate of #5941, please read https://github.com/acemod/ACE3/issues/5941#issuecomment-353359679. This will be a functionality in the UI in a future update. You can also remove `ace_arsenal.pbo` temporarily to access Vanilla Arsenal in Eden. Your loadouts are not gone, ACE Arsenal is separate from Vanilla Arsenal.

**Closed by jonpas** 2017-12-22 00:19 UTC
