### ISSUE TITLE
Overpowered Vest / wrong armor values / broken feature ?

### ISSUE THREAD

**Issue by xJenny99x** [acemod/ACE3#2719] opened 2015-10-09 06:45 UTC
ACE3 Version:
3.3.2 Stable

Mods:

    @CBA_A3
    @ace

Placed ACE3 Modules:
None

Description:

https://www.youtube.com/watch?v=0Vk8z3TFPBI

Where did the issue occur?
Multiplayer on a dedicated server and in singleplayer.

Steps to reproduce:
Shoot a unit with a vest which armor is maxed ( arsenal stats )

Notes:
Not entirely sure what causes this and why.
Is it intentional ? Is this realistic ?

**Comment by commy2** [comment] 2015-10-09 09:43
Duplicate of #2624

**Closed** 2015-10-11 07:15 UTC
Labels: duplicate
