### ISSUE TITLE
[Medical] Players / AI wake up almost instantly after passing out

### ISSUE THREAD

**Issue by Cyruz143** [acemod/ACE3#2494] opened 2015-09-17 23:29 UTC
ACE3 Version: 3.3.1 (Stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Placed ACE3 Modules:**
- None.

**Description:**
- Players / AI wake up almost instantly after passing out, bug persists from 3.2.1.

**Steps to reproduce:**
- Open editor, place a few vanilla units, shoot at them till they pass out, wait for instant wake up. RPT has nothing of interest in but attached for sanity checking. Had to do this quite a few times as they usually die in one shot.

Also happens on server in dedicated MP, values set below:

```

class ace_common_forceAllSettings {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_common_checkPBOsAction {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_common_checkPBOsCheckAll {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_common_checkPBOsWhitelist {
    value = "[]";
    typeName = "STRING";
    force = 1;
};
class ace_finger_enabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_finger_maxRange {
    value = 4;
    typeName = "SCALAR";
    force = 1;
};
class ace_frag_Enabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_frag_SpallEnabled {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_frag_maxTrack {
    value = 500;
    typeName = "SCALAR";
    force = 1;
};
class ace_frag_MaxTrackPerFrame {
    value = 50;
    typeName = "SCALAR";
    force = 1;
};
class ace_frag_EnableDebugTrace {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_hitreactions_minDamageToTrigger {
    value = 0.1;
    typeName = "SCALAR";
    force = 1;
};
class ace_interaction_EnableTeamManagement {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_laserpointer_enabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_magazinerepack_TimePerAmmo {
    value = 1.5;
    typeName = "SCALAR";
    force = 1;
};
class ace_magazinerepack_TimePerMagazine {
    value = 2;
    typeName = "SCALAR";
    force = 1;
};
class ace_magazinerepack_TimePerBeltLink {
    value = 8;
    typeName = "SCALAR";
    force = 1;
};
class ace_map_BFT_Interval {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_map_BFT_Enabled {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_map_BFT_HideAiGroups {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_map_mapIllumination {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_map_mapGlow {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_map_mapShake {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_map_mapLimitZoom {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_map_mapShowCursorCoordinates {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_maptools_EveryoneCanDrawOnBriefing {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_level {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_medicSetting {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_enableFor {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_enableOverdosing {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_bleedingCoefficient {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_painCoefficient {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_enableAirway {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_enableFractures {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_enableAdvancedWounds {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_enableVehicleCrashes {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_enableScreams {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_playerDamageThreshold {
    value = 1.2;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_AIDamageThreshold {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_enableUnconsciousnessAI {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_remoteControlledAI {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_preventInstaDeath {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_enableRevive {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_maxReviveTime {
    value = 120;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_amountOfReviveLives {
    value = -1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_allowDeadBodyMovement {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_allowLitterCreation {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_litterCleanUpDelay {
    value = 300;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_medicSetting_PAK {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_medicSetting_SurgicalKit {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_consumeItem_PAK {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_consumeItem_SurgicalKit {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_useLocation_PAK {
    value = 3;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_useLocation_SurgicalKit {
    value = 2;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_useCondition_PAK {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_useCondition_SurgicalKit {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_keepLocalSettingsSynced {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_healHitPointAfterAdvBandage {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_painIsOnlySuppressed {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_allowUnconsciousAnimationOnTreatment {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_moveUnitsFromGroupOnUnconscious {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_menu_allow {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_repair_engineerSetting_Repair {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_repair_engineerSetting_Wheel {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_repair_repairDamageThreshold {
    value = 0.6;
    typeName = "SCALAR";
    force = 1;
};
class ace_repair_repairDamageThreshold_Engineer {
    value = 0.4;
    typeName = "SCALAR";
    force = 1;
};
class ace_repair_consumeItem_ToolKit {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_repair_fullRepairLocation {
    value = 2;
    typeName = "SCALAR";
    force = 1;
};
class ace_repair_engineerSetting_fullRepair {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_repair_addSpareParts {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_repair_wheelRepairRequiredItems {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_spectator_filterUnits {
    value = 3;
    typeName = "SCALAR";
    force = 1;
};
class ace_spectator_filterSides {
    value = 3;
    typeName = "SCALAR";
    force = 1;
};
class ace_spectator_restrictModes {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_spectator_restrictVisions {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_vehiclelock_DefaultLockpickStrength {
    value = 10;
    typeName = "SCALAR";
    force = 1;
};
class ace_vehiclelock_LockVehicleInventory {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_vehiclelock_VehicleStartingLockState {
    value = -1;
    typeName = "SCALAR";
    force = 1;
};
class ace_viewdistance_enabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_viewdistance_limitViewDistance {
    value = 10000;
    typeName = "SCALAR";
    force = 1;
};
class ace_weather_enableServerController {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_weather_useACEWeather {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_weather_syncRain {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_weather_syncWind {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_weather_syncMisc {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_weather_serverUpdateInterval {
    value = 60;
    typeName = "SCALAR";
    force = 1;
};
class ace_winddeflection_enabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_winddeflection_vehicleEnabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_winddeflection_simulationInterval {
    value = 0.1;
    typeName = "SCALAR";
    force = 1;
};
class ace_winddeflection_simulationRadius {
    value = 1500;
    typeName = "SCALAR";
    force = 1;
};
class ace_zeus_zeusAscension {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_zeus_zeusBird {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_zeus_remoteWind {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_zeus_radioOrdnance {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_zeus_revealMines {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_zeus_autoAddObjects {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_captives_allowHandcuffOwnSide {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_captives_requireSurrender {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_captives_allowSurrender {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_cargo_enable {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_explosives_RequireSpecialist {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_explosives_PunishNonSpecialists {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_explosives_ExplodeOnDefuse {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
```

**Where did the issue occur?**
- Multiplayer and Editor

**RPT log file:**
- http://pastebin.com/WVKFMqe3

**Video**
- https://www.youtube.com/watch?v=QQldqd6GQhc

**Comment by Cyruz143** [comment] 2015-09-17 23:49
Should note that it's only players that have it happen in MP because we disable AI unconsciousness so can't comment if AI have the same issue in MP that they do in the editor, based off of what happens to the players, it's extremely likely it's the same.

**Comment by Armilio** [comment] 2015-09-19 21:27
I confirm this bug, people wake up after 5-15 seconds. It's very annoying because ephinefrine and the medics in general became pretty useless. A strange thing is that few rare times happen that players remain down; other times, player wakes up and immediately goes uncoscius again, passing out for the pain.

**Comment by ryuanesha** [comment] 2015-11-29 21:34
Our community has experienced this bug since September. As one of our regular medics, I've made a few noteworthy observations.

I believe the cause of the issue is that velocity wounds are not affecting vitals. Many times after someone has been shot their BP and HR are still flawless despite having a wound. I suspect that if a round knocks them out, their vitals are still normal and thus they instantly awaken.

Last night two people were knocked unconscious for the first time since September, however this was caused by blow-back from AT being fired too close to a building. One bled out, the other was bleeding out from many lacerations to the leg. The significance is that after many months of sponging bullets with this bug, it wasn't produced by blow-back damage.

**Comment by Khaosmatic** [comment] 2016-04-07 22:53
Can verify that this is still present in basic medical, advanced from my last time using it seemed to work properly.

Is it to do with the blood loss level as ACE uses that to determine consciousness does it not?

**Comment by Armilio** [comment] 2016-04-09 12:44
> Can verify that this is still present in basic medical, advanced from my last time using it seemed to >work properly.

I tested it with the advanced system, with IA, and it's the same. Works only when you shoot in the two legs, probably because that makes loss a lot of blood.

**Comment by PabstMirror** [comment] 2016-04-10 17:15
@Glowbal - Right now GVAR(painCoefficient) only effects the visual effects, should it apply to the `getVariable GVAR(pain)` added to a unit?

If we did that change, then by tweaking the coefficent it would make pain a bigger factor in Unconscious Conditions.

**Comment by PabstMirror** [comment] 2016-04-12 00:48
For unconscious, we have 
 * short term - the quick knock down, right after taking damage - representing getting the wind knocked out of you, but not something you would need medication for
 * long term - bleedout, but this can take several minutes to do anything

But we really don't have anything at the mid level. I think that someone with serious injuries should become combat ineffective faster.
Ref issues #3302 #3167

Possible ideas to fix:
 * Increase bleeding when taking a lot of damage (PR #3632) 
 * Add a setting for a coefficent of pain added on damage, fewer shots would be needed to get knocked down because of pain.
 * Increase the knock down time depending on new damage take / how much existing damage is present
 * Add a pain stage bellow unconscious that would leave a unit partially disabled; possibly limit to crawl / `player setCustomAimCoef 100`.

**Comment by Cyruz143** [comment] 2016-04-12 12:25
@PabstMirror Agree 100%, I really like the "getting the wind knocked out of you" when you blackout and wake back up instantly, just want a bit of a middleground as the medics basically giving morphine and doing bugger all else at the moment in basic medical.

**Comment by Armilio** [comment] 2016-04-12 14:27
I like all your ideas, @PabstMirror . What i would like to see is the necessity to use epinephrine in more knock down situations, like: if after calculations, the theoretical knock down seconds are more than x, it become a knock down that need epinephrine to wake up the patient. This in the basic system, in the advanced system probably it's just a matter of making vitals goes down faster with serious wounds.

But if you don't want to modify how actually ephinephrine works, just more situations where it's needed that someone else help you while you are on the ground, wounded / unconscious. Maybe something like that even if you are conscious but seriously injuried, you can't heal yourself. Because now it's more common — and practical — the Rambo-style self-healing. The best would be that the combat medic it's needed, but if not, at least making useful the buddies help.

**Comment by DLEGION** [comment] 2016-04-27 23:48
hi all.
i have the same problem... AI gets unconscious-conscious in few seconds ! plz how keep it unconscios ?

**Comment by Glowbal** [comment] 2016-06-15 11:05
Might be fixed with #3916 and #3917.

**Comment by ViperMaul** [comment] 2017-01-16 23:03
Do we have any feedback confirming this is indeed fixed?

**Comment by thojkooi** [comment] 2018-07-18 18:49
Unconsciousness is redone in the rewrite. Closing this - if this is still an issue in the rewrite (#4064), please open a new issue.

**Closed by thojkooi** 2018-07-18 18:49 UTC
Labels: kind/bug, status/needs testing
