### ISSUE TITLE
Players able to interact while unconscious after they left cardiac arrest state

### ISSUE THREAD

**Issue by HexTFAC** [acemod/ACE3#7448] opened 2020-01-11 11:54 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96` [Stable]
- **CBA:** `3.13.0` [Stable]
- **ACE3:** `3.13.0` [Stable]

**Description:**
As a player leaves the cardiac arrest state and enters the unconscious state, they are able to perform self-aid through the ACE3 Self-Interactions Menu

**Steps to reproduce:**
- Render player into cardiac arrest
- Solve for cardiac arrest
- Render into an unconscious state
- Allow player to observe self-aid options

**Expected behavior:**
Player should be unable to render aid to self while unconscious.

**Where did the issue occur?**
- Dedicated Multiplayer

**Log Files:**
N/A

**Additional context:**
N/A

**Screenshots:**
Video currently in production.

**Comment by LockAndLoafCat** [comment] 2020-01-12 21:50
I've had the same issue. My screen will even remain black sometimes and I can still self-interact.

**Comment by Whigital** [comment] 2020-01-17 16:11
https://github.com/acemod/ACE3/blob/5c774f5fe6557299c3ee0685137e01fd63fb8eed/addons/medical_statemachine/functions/fnc_leftStateCardiacArrest.sqf#L25

https://github.com/acemod/ACE3/blob/5c774f5fe6557299c3ee0685137e01fd63fb8eed/addons/medical_status/functions/fnc_setCardiacArrestState.sqf#L32

Shouldn't that be set to `true` when leaving `cardiacArrest` state ?

**Comment by SilentSpike** [comment] 2020-01-18 12:37
@Whigital That could very well be the cause this issue - well spotted. 

I think on leaving cardiac arrest we actually just shouldn't call that function at all, unconscious state doesn't change because it's only possible to go from cardiac arrest to death or unconsciousness.

**Comment by SilentSpike** [comment] 2020-02-04 11:19
This is now hopefully fixed on master, will close once confirmed

**Comment by PabstMirror** [comment] 2020-02-22 22:03
Should be fixed by #7503

**Closed by PabstMirror** 2020-02-22 22:03 UTC
Labels: kind/bug
