### ISSUE TITLE
Javelin (Titan) / NLAW Switch Fire Mode to Direct causes launcher to be holstered on back

### ISSUE THREAD

**Issue by JerikTelorian** [acemod/ACE3#8841] opened 2022-03-09 23:21 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** `2.08` Steam Release, Updated 03/08/2022
- **CBA:** `3.15.6` Steam Workshop Release, Updated 10/5/2021
- **ACE3:** `3.14.1` Steam Workshop Release, Updated 11/26/2021

**Description:**
When an NLAW or Titan/Javelin is equipped and in Top-Attack mode, Switching fire mode (CTRL+Tab) holsters the weapon without changing fire mode to Direct.

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1.) Equip an NLAW or Titan/Javelin Launcher
2.) Draw the launcher weapon
3.) Switch fire mode to top attack. Note the change in the UI indicating the weapon is in Top-Attack mode.
4.) Switch fire mode to Direct. Note that the weapon holsters. The UI may indicate that the weapon mode was switched to Direct mode, however if the weapon is drawn the UI will indicate that it is in Top-Attack mode.

**Expected behavior:**
The player should be able to switch freely between Direct and Top-Attack modes, without holstering the launcher.

**Where did the issue occur?**

Virtual Arsenal and Editor (Singleplayer)

**Log Files:**

The game does not crash.

**Additional context:**

**Screenshots:**

A video clip demonstrating the behavior with an NLAW.

https://www.youtube.com/watch?v=qd9YjVsiDrw

**Comment by PabstMirror** [comment] 2022-03-10 06:29
I think firemode switching on launchers broke in vanilla in 2.08

**Comment by PabstMirror** [comment] 2022-03-10 19:13
https://feedback.bistudio.com/T163651
KK:
> Should be fixed in 149026 (and hotfixed)

So we just need to wait for arma patch

**Comment by PabstMirror** [comment] 2022-03-18 20:08
Recent hotfix semi-fixed this
- The vanilla cycle weapon mode key (`F`) now works
- ACE's cycle weapon mode keybind (`Ctrl-Tab`) does not

With nlaw/titan you could use either so just remember to use the F and it should be functional

dedmen from slack:
> The 2.08 hotfix that was pushed breaks ACE attack profile changing from missile guideance (because of the new persistent firemode change where if you switch away from launcher and back to it, the firemode should stay what it was before)
We will add a new script command so you can rewrite that code to do it in a better way, as the current brute-force till we find a index that has what we want is a bit oof. It also sends a network message for every action execution.
https://github.com/acemod/ACE3/blob/master/addons/missileguidance/functions/fnc_cycleAttackProfileKeyDown.sqf#L82

**Comment by johnb432** [comment] 2024-07-26 12:33
I can't reproduce the issue and I believe #8879 resolved the issue. Therefore, I'm going to close it, but you can reopen if it's still an issue.

**Closed by johnb432** 2024-07-26 12:33 UTC
Labels: kind/bug, fault/BI
