### ISSUE TITLE
RHS RPK's have wrong ammo w/ RHS-ACE compat

### ISSUE THREAD

**Issue by FPFalcon** [acemod/ACE3#8234] opened 2021-04-28 03:05 UTC
**Mods (complete and add to the following information):**
Arma3 latest
CBA latest
ACE3 latest
RHS suite 
Custom RHS-ACE3 Compatability mod
all stable versions

**Description:**
This bug has been isolated to the RHS-ACE compatibility mod,  In the most recent RHS update, two new RPKs were added, however, the ammunition for the RPKs is incorrect, instead of having the correct 30- 45- 60- round banana mags. The compat. switches it to PKM box ammo.  This is only apparent with ACE and the ACE compat. loaded. If RHS is the only one running then the RPK uses the correct ammo.  Although the correct mags are available in the additional ammo menu, they will not work with the RPK.  I don't know where to bug is, or where it came from, but it is from the compatability script, which I have tested with multiple RHS-ACE compatability mods.

**Steps to reproduce:**

1. Have only the mods described above active
2. _Click ... go to any arsenal vanilla or ACE
3. Select ether RPK from RHSAFRF
3. _See that the ammo to choose from is the PKM box ammo and not the 30- 45- 60- round AK mags.  Observable both in the direct weapon ammo menu, or any inventory ammo menu.

**Expected behavior:**
It should be a fairly simple fix, all that needs to happen is the compat. actually read the RPK ammo instead of the PKM ammo.

**Where did the issue occur?**
Virtual arsenal / ACE arsenal / Editor(SP) / Dedicated server mission / Zeus enhanced Arsenal

**Log Files:**
[Arma3_x64_2021-04-27_22-49-44(1).txt](https://github.com/acemod/ACE3/files/6388783/Arma3_x64_2021-04-27_22-49-44.1.txt)

**Additional context:**

**Screenshots:**
With the compat.
![20210427225440_1](https://user-images.githubusercontent.com/81844958/116340264-e0a42780-a7ac-11eb-81e7-0b8224f54484.jpg)
![20210427225353_1](https://user-images.githubusercontent.com/81844958/116340274-e4d04500-a7ac-11eb-805a-ac00273eb94e.jpg)
Without ace compat.
![20210427225857_1](https://user-images.githubusercontent.com/81844958/116340325-ffa2b980-a7ac-11eb-8bac-515ceb967afe.jpg)

**Comment by Drofseh** [comment] 2021-04-28 03:47
duplicate of #8221 fixed in #8223

**Closed** 2021-04-28 04:37 UTC
Labels: kind/bug

**Comment by FPFalcon** [comment] 2021-04-28 18:05
Thanks, I only checked open issues, not the closed ones.
