### ISSUE TITLE
ace_ui.pbo causing hidden round count

### ISSUE THREAD

**Issue by brnnnrsmssn** [acemod/ACE3#4256] opened 2016-08-18 02:31 UTC
**Arma 3 Version:** `1.62.137494` (stable)
Launcher version: 1.5.137506
Game version: 1.62.137494
Branch: main / beta branch not specified
**CBA Version:** `CBA_A3 v3.0.0.160713 (steam workshop)` (stable)
**ACE3 Version:** `3.6.2 (steam workshop)` (stable)

**Mods:**
- `@CBA_A3`
- `@ace` (loaded as a local file copied from the steam workshop)

**Description:**
- the "ace_ui.pbo" is causing the round count of the current magazine to not display.

**Steps to reproduce:**
- copy ace3 from steam workshop to local directory, allowing for the removal of pbos
- unload all mods other than cba and ace3 (local) to isolate the issue
- remove all files in the addons folder except: main, modules, common, and ui pbos
- launch game to the point where you control the player character
- check for displayed round count

**Where did the issue occur?**
- Singleplayer / Virtual Arsenal

**Placed Modules:**
- 'None'
  [ace3_uipbo_roundcount_issue.txt](https://github.com/acemod/ACE3/files/424021/ace3_uipbo_roundcount_issue.txt)

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by jonpas** [comment] 2016-08-18 02:39
This is a feature by `ace_reload.pbo`, ref. http://ace3mod.com/wiki/feature/reload.html

**Comment by Glowbal** [comment] 2016-11-26 10:44
Closing, as this is by design.

**Closed by Glowbal** 2016-11-26 10:44 UTC
Labels: by design
