### ISSUE TITLE
Player frozen when carrying another player and then receiving damage to the legs

### ISSUE THREAD

**Issue by Gikerl** [acemod/ACE3#7466] opened 2020-01-13 17:36 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** `1.92` 
- **CBA:** `3.12.2`
- **ACE3:** `3.13.0`

**Description:**
Carrying an unconscious player and then receiving damage to the legs will freeze the player's movement. They cannot move until dropping the person from their back. Afterwards, they will be able to move with a limp.

**Steps to reproduce:**
- Carry an unconscious person
- Get shot in the legs
- Player is no longer able to move

**Expected behavior:**
Players should either drop the unconscious person automatically or be allowed to slowly carry the person.

**Where did the issue occur?**
- Dedicated Multiplayer

**CBA settings:**
This CBA setting might contain further mods. But I verified it with just ACE & CBA running.
https://gist.github.com/Gikerl/439b214e56fe1e9dcaa53aa504a71ba3

**Comment by Gikerl** [comment] 2020-01-13 22:03
This seems to be an inconsistent bug. I could not reproduce this today. Yesterday this issue was persistent.

**Comment by bux** [comment] 2020-01-14 07:00
You didn't add your RPT file

**Comment by Gikerl** [comment] 2020-01-20 13:02
@bux Could you label this as a suggestion as previous ACE version show the same behaviour.

**Comment by johnb432** [comment] 2023-08-19 12:14
Carrying has been addressed in #9251.

However, dragging has the same issue.

@LinkIsGrim, I'm thinking me or you could make a PR based off of #9251 but for dragging instead.
The drag action would have to be removed from the medical menu.

This would mean that you can't move patients when limping though, so I'm not sure if it's a good solution.

**Comment by Mike-MF** [comment] 2023-09-19 01:56
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Closed by Mike-MF** 2023-09-19 01:56 UTC
Labels: kind/bug, help wanted
