### ISSUE TITLE
Check PBOs module not part of ACE_Settings

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#1123] opened 2015-05-12 15:41 UTC
ACE3 Version: 3.0.0.2 ab580dd1c7bb0dba710a42f0193bb312eceac0c0

**Mods:**
* `@cba_a3`
* `@ace3`

**Placed ACE3 Modules:**
N/A

**Description:**
When you Export Configuration for use in userconfig, `Check PBOs` module does NOT get exported. That happens because the module doesn't have it's insides in `ACE_Settings`.

**Steps to reproduce:**
* Place `Allow Config Export` module
* Place `Check PBOs` module (and set it to different values if you want)
* Export Config
* `Check PBOs` module is not there

**Where did the issue occur?**
Singleplayer - Editor

**RPT log file:**
N/A

**Comment by Glowbal** [comment] 2015-05-12 15:56
This is caused by missing settings. Also checkPBO contains a couple of spawns, could also be cleaned up.

**Comment by Glowbal** [comment] 2015-06-04 19:58
Merged in #1236

**Closed by Glowbal** 2015-06-04 19:58 UTC
Labels: bug
