### ISSUE TITLE
Removing IR strobes from vehicles doesn't remove the strobe effect.

### ISSUE THREAD

**Issue by Cephel** [acemod/ACE3#1615] opened 2015-06-13 18:31 UTC
ACE3 Version: b17b44b8699fffc7e13090bbece2cba7f42b2ea0

**Mods:**
* @cba_a3
* @ace3
* @acre2

**Placed ACE3 Modules:**
* *None.*

**Description:**
*See Title.*

**Steps to reproduce:**
* *Attach IR grenade to car.*
* *Remove IR grenade from car.*
* *Strobe effect persists.*

**Where did the issue occur?**
*Multiplayer*

**RPT log file:**
*Invalid.*

**Comment by PabstMirror** [comment] 2015-06-13 19:12
I couldn't reproduce, but I see how it could be possible.
I increased the delay to delete the strobe after moving it offscreen.

Should be fixed, but please let me know if it happens again.

**Closed by PabstMirror** 2015-06-13 19:12 UTC
Labels: Bug fix
