### ISSUE TITLE
Incorrect Advanced Medical Behaviour

### ISSUE THREAD

**Issue by legman** [acemod/ACE3#1833] opened 2015-07-10 20:46 UTC
ACE3 Version: 3.1.1 (stable)

**Mods:**
* @cba_a3
* @ace3
* @tfr

**Placed ACE3 Modules:**
* @ace_medical_settings
* @ace_advanced_medical_settings
* @ace_zeus

**Description:**

Since the last patch 3.1.1 any type of damage (minor or severe) will cause the player to have damaged legs and be unable to move faster than walking pace. Said damage will also cause the player to groan and have blurred vision (vanilla damage system) despite being fully healthy in ACE3.

The only way to revert this is with a PAK or **setDamage 0** which are essentially the same thing. Now I am assuming this is a bug and not intended behaviour as it seems that **handleDamage** is letting something through that is causing players to be wounded with the vanilla damage system along with ACE3s.

Like I said above this has only started happening ALOT since the last patch - if it is intended behavior then it really isn't enjoyable as you 90% of the team ends up walking around within 5 minutes of combat.

Some of the settings we use that may be affecting the medical system
* Allow AI Unconscious = *disabled*
* Prevent instant death = *true*
* Medic system enabled for = *players & AI*
* Enabled advanced wounds = *true*
* Zeus Mission

**Steps to reproduce:**
* Start a Zeus mission on a dedicated server
* Get damaged by something
* Notice you can no longer run

**Where did the issue occur?**
Multiplayer

I know this is a vague report so if there are any questions I will answer them to the best of my ability. Like I said it feels like the ArmA damage system is kicking in when it shouldn't be and affecting game play.

**Comment by jonpas** [comment] 2015-07-10 20:56
Fixed in #1692

**Comment by legman** [comment] 2015-07-10 21:28
Fantastic news!

**Comment by Glowbal** [comment] 2015-07-16 08:50
No, this is actually intended behaviour. There is a new setting in the advanced medical module to disable this behaviour. "remove blood stains" I think it's called but we may look into a better fitting name soon.

The blurred vision is a bug and is fixed in the PR that @jonpas linked. Everything else is indented.

**Closed by Glowbal** 2015-07-16 08:50 UTC

**Comment by legman** [comment] 2015-07-16 09:40
So let me get this straight, if I set **Remove Blood Stains** to *true* then we will no longer be walking around after being shot every-time?

**Comment by legman** [comment] 2015-07-16 09:41
Also what about when people are instant killed regardless of **Prevent Instant Death**?
Is that intended because it seems to be quite random!

**Comment by Glowbal** [comment] 2015-07-16 13:16
>  So let me get this straight, if I set Remove Blood Stains to true then we will no longer be walking around after being shot every-time?

Yes.
