### ISSUE TITLE
shooting angle for infantry need to be possible from -90°/+90°

### ISSUE THREAD

**Issue by cych** [acemod/ACE3#5570] opened 2017-09-29 17:16 UTC
**Arma 3 Version : 1.76.142872 (stable)
**CBA Version : 3.4.1 (stable)
**ACE3 Version :: 3.10.2 (stable)

**Mods:**
```
- CBA_A3
- ace
- RHS esacalation
- dynasound 2
- Blastcore standalone
```

**Description:**
currently a soldier aiming at the sky or at the ground can't aim at +90° or at -90°  meaning he got a dead angle where he can't aim.

the request is to change this angle limitation 
![shooting angle](https://user-images.githubusercontent.com/12052664/31027506-a762f6f8-a54a-11e7-9c3c-0cb75c088074.jpg)

to make possible to aim up to +90°  / -90°

**Steps to reproduce:**
spawn with an infantry unit aim at the sky or at the ground you can see your barrel can't cover a full 180° angle.  Inreal life it's perfectly possible to aim verticaly in both directions.

**Where did the issue occur?**
- mission editor.

**Placed Modules:**
no.

**Comment by AACO** [comment] 2017-09-29 17:53
Have you confirmed the issue is with ACE by trying this with no mods? I don't believe this is related to ACE. If it's a requested feature it should go in #3594

**Comment by jonpas** [comment] 2017-09-29 17:57
We already increase it to 80° [here](https://github.com/acemod/ACE3/blob/master/addons/movement/CfgVehicles.hpp#L4). Changing it to 90° looks super retarded if I remember correctly.

**Comment by commy2** [comment] 2017-09-29 18:47
Would 90 also make you spin super fast?

**Comment by cych** [comment] 2017-09-29 19:17
with ACE only same issue. shooting angle limited to 80°.   

i don't see why allowing 90° angle would look super retarded.  in fact there is lot of situation where you should be able to aim and you can't because of the angle setting : 

EG : you are on top of a tower with a ladder, there is enemy climbing the ladder, you can't aim to him because the angle doesn't allow it.  same with opposite situation, you can't aim to a enemy ontop of a structure above you.

**Comment by jonpas** [comment] 2017-09-29 19:22
Because of the animations.

**Comment by cych** [comment] 2017-09-29 19:23
having a weird animation is worst than not having the possibility to aim.

**Comment by jonpas** [comment] 2017-09-29 19:30
No clue, feel free to test, that's the only config entry you have to modify. And then there is `minGunElev` IIRC.

**Comment by badkneegrow** [comment] 2017-10-01 03:48
> Inreal life
cows don't glow inreal life

**Comment by dedmen** [comment] 2017-10-02 07:11
For reference https://feedback.bistudio.com/T71574

**Comment by commy2** [comment] 2017-10-02 07:28
Increasing it to 80 already is something. I'd say close this (feature request) and anyone can feel free to make (and test) a pull request.

**Closed** 2017-10-02 13:34 UTC
Labels: kind/feature request, status/wontfix
