### ISSUE TITLE
Mortar HE rounds bug

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#616] opened 2015-04-15 09:50 UTC
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
None

**Description:**
Shooting HE round make player hurt and cause recoil, other rounds does not.

**Steps to reproduce:**
Place vanilla mortar.
Start shooting HE rounds, some will hurt you, all of them will cause recoil and jiggle whole mortar with player inside. Almost like in Alpha/Beta times.
Switch to smoke or flare rounds, start shooting, no recoil at all.

**Where did the issue occur?**
Singleplayer

**RPT log file:**
Inside RPT I have found only this that looks suspicious:
11:41:23 Ammo class Sh_82mm_AMOS lacks proper explosive properties definitions for frag!

**Comment by Glowbal** [comment] 2015-04-15 09:55
I am familiar with this issue. RTP log will not show anything relevant.

Could you please check if it also occures with advanced medical enabled or only basic?

**Comment by Glowbal** [comment] 2015-04-15 10:01
https://www.youtube.com/watch?v=lGrcGkW_bmI <- probably this.

**Comment by gienkov** [comment] 2015-04-15 10:08
Yeah, happens on Advanced medical too, but looks like less often?

**Comment by PabstMirror** [comment] 2015-04-15 16:39
This happens in vanilla, but is more noticable in ACE because of medical system.

https://github.com/acemod/ACE3/pull/384 - should fix

**Comment by commy2** [comment] 2015-04-15 16:49
Is this the same issue I had with auto grenade launchers?

**Comment by esteldunedain** [comment] 2015-04-15 16:53
> Is this the same issue I had with auto grenade launchers?
Probably, although you may have been hit be a frag

**Comment by jaynus** [comment] 2015-04-15 19:27
This is really hard to reproduce. Does anyone have a good repro case?

**Comment by Glowbal** [comment] 2015-04-17 19:55
This is fixed by #384 

To reproduce:
* Place mortar on stratis airfield runway.
* Jump into mortar, do not move sight.
* Fire round.

To best debug this, attach a handleDamage eventhandler.
```player addEventhandler ["handleDamage", { hintsilent format["HandleDamage: %1", _this]; diag_log format["handleDamage: %1", _this]; }];```

Using `vehicle player setMass 250` will fix it.

**Closed by Glowbal** 2015-04-17 19:55 UTC
Labels: BIS' fault, bug

**Comment by jaynus** [comment] 2015-04-17 23:40
Should we setMass on all static weapons via a getIn handler?

**Comment by Glowbal** [comment] 2015-04-18 08:09
We could. The PR I referenced does it on init for local static weapons.
