### ISSUE TITLE
Rallypoint are missing XEH, potentially the same for other ACE objects

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#3385] opened 2016-02-21 17:40 UTC
ACE 3.4.2 and CBA 2.3.1

Rallypoint are missing XEH

We used to do this, which is no longer support in CBA 2.3+:

```c++
    class ACE_Rallypoint_West_Base: Flag_NATO_F {
        XEH_ENABLED;
    };
```

**Comment by bux578** [comment] 2016-02-21 17:47
Is there anything else in ACE that is not working correctly with commy's XEH?

**Comment by esteldunedain** [comment] 2016-02-21 17:53
Oops, apparently yes. `XEH_ENABLED` is also used in:
- ACE_cargo
- ACE_concertina_wire
- ACE_dragging
- ACE_explosives
- ACE_interaction
- ACE_medical
- ACE_rearm
- ACE_refuel
- ACE_sandbag
- ACE_sitting
- ACE_spottingscope
- ACE_tacticalladder
- ACE_tripod

**Comment by PabstMirror** [comment] 2016-02-21 18:02
Can you make sure you have the most recent CBA files in p:\x\cba. 
XEH on the flags seems to be working for me.

**Comment by esteldunedain** [comment] 2016-02-21 18:04
@PabstMirror, the issue is with ACE 3.4.2 and CBA 2.3.1

**Comment by commy2** [comment] 2016-02-21 19:12
This was already fixed on master.
https://github.com/acemod/ACE3/pull/3277/files#diff-2c49281a73fa92c700ba964c6ab3f9c2R1410

**Comment by commy2** [comment] 2016-02-21 19:22
Confirmed on master (and CBA 2.3.1)

**Closed by commy2** 2016-02-21 19:22 UTC
Labels: critical bug

**Comment by esteldunedain** [comment] 2016-02-21 19:34
Perfect!
