### ISSUE TITLE
"...not signed by a key accepted by this server"

### ISSUE THREAD

**Issue by DolfLorbeer** [acemod/ACE3#7733] opened 2020-05-24 11:57 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98.146373
- **CBA:** `3.15.1
- **ACE3:** `3.13.2
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
Error occurres when joining any Arma 3 server with ace and CBA_A3:
"\steamapps\common\Arma3\!Workshop\@ace\addons\ace_advanced_ballistics.pbo are not signed by a key accepted by this server. To play on this server, remove listed files or install additional accepted keys"

I already reinstalled the addon, repaired it, reinstalled Arma 3, reinstalled the server, updated the server with all mods. The folder in ace with the bkey file is alright and updated.

![20200523180249_1](https://user-images.githubusercontent.com/65852253/82753475-35ce0100-9dc6-11ea-87e1-2267cb926be0.jpg)

**Where did the issue occur?**
- Arma 3 Vanilla Game server (I tried 3 different host services, there is the same problem. The problem has been occurring since friday. Before that everything worked at any time.

**Comment by bux** [comment] 2020-05-24 12:12
Where is the RPT?

**Comment by DolfLorbeer** [comment] 2020-05-24 13:03
[Arma3_x64_2020-05-24_13-33-49.zip](https://github.com/acemod/ACE3/files/4673551/Arma3_x64_2020-05-24_13-33-49.zip)
I´m sorry, here is the RPT, I hope thats the right one.

**Comment by DolfLorbeer** [comment] 2020-05-24 13:04
> Where is the RPT?
[Arma3_x64_2020-05-24_13-33-49.zip](https://github.com/acemod/ACE3/files/4673558/Arma3_x64_2020-05-24_13-33-49.zip)

I´m sorry, here is the RPT. Hope thats the right one.

**Comment by Blutze** [comment] 2020-05-24 13:36
You're probably in the right directory, but that file ends way too early. Even just getting to the main menu without any mods is ~60 KB and ~700 lines, before closing the game.

**Comment by DolfLorbeer** [comment] 2020-05-24 15:37
> You're probably in the right directory, but that file ends way too early. Even just getting to the main menu without any mods is ~60 KB and ~700 lines, before closing the game.

[arma3server_x64_2020-05-23_23-33-02.zip](https://github.com/acemod/ACE3/files/4673803/arma3server_x64_2020-05-23_23-33-02.zip)

This one is an RPT file from the server. I can´t find another one in my data, I´ve got a screenshot of the files. That one is the only one with the current date.
I can start Arma 3 with these two mods without problems, ace does work fine in the editor.
![screenshot 132348077029447351](https://user-images.githubusercontent.com/65852253/82758159-332ed400-9de5-11ea-99ea-d8285b13672f.png)

**Comment by BaerMitUmlaut** [comment] 2020-05-24 17:03
>I can´t find another one in my data

You're probably running the game with the `-noLogs` parameter.

**Comment by commy2** [comment] 2020-05-24 17:03
This is obviously not a bug in ACE. Why is this on the ACE issue tracker?

**Comment by DolfLorbeer** [comment] 2020-05-24 17:14
> > I can´t find another one in my data
> 
> You're probably running the game with the `-noLogs` parameter.

That was the problem, thanks! I changed the parameter and connected again on the server. Now I have an bigger file.
[Arma3_x64_2020-05-24_19-10-01.zip](https://github.com/acemod/ACE3/files/4674031/Arma3_x64_2020-05-24_19-10-01.zip)

**Comment by DolfLorbeer** [comment] 2020-05-24 17:16
> This is obviously not a bug in ACE. Why is this on the ACE issue tracker?

I thought it´s a problem with ace because every other mod works fine.

**Comment by commy2** [comment] 2020-05-24 19:25
It's not. Delete `E:\SteamSpiele\steamapps\common\Arma 3\!Workshop\@ace` on client as well as `C:\cygwin\home\zap533815\g250156\arma3\@ace` and C:\cygwin\home\zap533815\g250156\arma3\Keys\` on server, and download and install everything over again.

Then consider stop using Steam, as Valve is a garbage company, and also in future, ask for help for setting up your server on the A3 discord instead.

**Comment by DolfLorbeer** [comment] 2020-05-25 10:30
> It's not. Delete `E:\SteamSpiele\steamapps\common\Arma 3\!Workshop\@ace` on client as well as `C:\cygwin\home\zap533815\g250156\arma3\@ace` and `C:\cygwin\home\zap533815\g250156\arma3\Keys\` on server, and download and install everything over again.
> 
> Then consider stop using Steam, as Valve is a garbage company, and also in future, ask for help for setting up your server on the A3 discord instead.

First, thank you very much for your help! I´ve done what your said. And I found out that now the same problem is occurring with CBAA3 too. Nothing works, and I don´t know what to do anymore.
This is the wrong forum, I try to come to the A3 Discord server

Thanks for your help! And stay safe and healthy.

**Closed** 2020-05-25 10:41 UTC
Labels: status/missing-rpt
