### ISSUE TITLE
Pylon Ammo bug

### ISSUE THREAD

**Issue by CPTMiller** [acemod/ACE3#6131] opened 2018-02-07 19:52 UTC
**Arma 3 Version:** `1.8.143869` (stable / rc / dev)
**CBA Version:** `3.6.1` (stable / dev + commit hash)
**ACE3 Version:** `3.12.1` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- RHS USAF
```

**Description:**
- When reconfiguring pylons on a helicopter. It doesnt reset the previous build, so pilot will still see the ammo left for previous weapons pylon build. 

**Steps to reproduce:**
- Put down a attack helicopter. 
- Reconfigure pylons with weapons. 
- Reconfigure again with different weapons.
- Get into pilot seat and watch the ammo from previous build is still there.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- N/A

**RPT log file:**
- Nothing appears in RPT Log.

**Comment by PabstMirror** [comment] 2018-02-08 19:02
Sounds like duplicate of  #6088
Will be fixed by PR #6100

**Closed by PabstMirror** 2018-02-08 19:02 UTC
Labels: status/duplicate
