### ISSUE TITLE
playerInventoryChanged event can be made to trigger continuously

### ISSUE THREAD

**Issue by nsgundy** [acemod/ACE3#897] opened 2015-04-28 16:49 UTC
ACE3 Version: 3.0.0.1 at commit 28a8fbc

**Mods:**
* @cba_a3
* @ace3

**ACE3 modules loaded:**
* ace_common
* ace_dragging
* ace_interact_menu
* ace_interaction
* ace_main
* ace_medical
* ace_modules

**Placed ACE3 Modules:**
* None

**Description:**
If I use the `append` command in a certain (probably incorrect) way in the `playerInventoryChanged` event, that event will keep firing continuously.

**Steps to reproduce:**
In editor with VA map loaded, execute the following code in the debug console:
```` sqf
["playerInventoryChanged",{
  (_this select 1) call {
	_a = _this select 17;
	_a append (_this select 3);
	systemChat str diag_tickTime;
  }
}] call ace_common_fnc_addEventHandler;
````
Then open the inventory and remove an item from the uniform (for example Morphine injector). You will see the output of `diag_tickTime` flooding the systemChat, until you remove the last item in the uniform. As soon as you add the first item to the uniform, flooding starts again.

If I alter the above code slightly, like so
```` sqf
["playerInventoryChanged",{
  (_this select 1) call {
	_a = [] + (_this select 17);
	_a append (_this select 3);
	systemChat str diag_tickTime;
  }
}] call ace_common_fnc_addEventHandler;
````
I only get the output of `diag_tickTime` displayed once per inventory manipulation as expected.

So I take it that the issue was caused by me not really knowing how to properly code in SQF, but it is also curious that what I did made the `playerInventoryChanged` event trigger continuously.

Not sure if there can /  should be defensive code in place to prevent this from happening.

**Where did the issue occur?**
Editor

**Comment by PabstMirror** [comment] 2015-04-28 19:38
It's an interesting bug, arrays are passed by reference and `append` modifies an array.
So everytime the inventory changes, you modify the internal variable we use, which means it won't match next frame...repeating forever.

We could send a copy of the variable to the localEvent, but that has some cost and isn't nessacary for any of our code.

I think the best bet is to tell users to make a copy for themselves if they need to modify the array. e.g.
```
["playerInventoryChanged",{
    _player = _this select 0;
    _newInventory = +(_this select 1); //makes a copy of the array
    //modify _newInventory safely
  }
}] call ace_common_fnc_addEventHandler;
```

**Comment by commy2** [comment] 2015-04-28 19:41
The inventory of a player is stored in the GVAR(OldPlayerInventory) array. This array is passed as a reference to all scripts defined as `playerInventoryChanged` event. The array contains some other arrays.
The thing is that arrays are stored as pointers to arrays in SQF. The difference between `append` and `+` is, that you create a new array with simply addition, while you modify the original array with `append` (The left one only in case of append).
In your first variant you actually changed the subarray with index 17 (all assigned items) and therefore GVAR(OldPlayerInventory) as a whole. The game detects that change on the next frame and repeatadly triggers the eventhandler, which again modifies the array, etc.

If you want all assigned items without changing the internal variable, you'd have to do something like this:

```
["playerInventoryChanged",{
    _unit = _this select 0;
    _items = [];
     _items append (_this select 3); // vest
     _items append (_this select 17); // assigned items
  }
}] call ace_common_fnc_addEventHandler;
```

**Comment by jaynus** [comment] 2015-04-28 19:42
Closing as not a bug, and more of an educational session. We specifically abuse and implement pass-by-reference mechanics all over ACE on purpose; to reduce allocation overhead. This is by design.

**Closed by jaynus** 2015-04-28 19:42 UTC
Labels: invalid

**Comment by nsgundy** [comment] 2015-04-28 20:28
Thanks guys, much appreciated! Definitely easy enough to steer clear of once you know what is going on. I ended up using `+` instead of a bunch of `append`s since there wasn't any difference in performance. FYI, [this is the function](https://github.com/Riouken/cTab/blob/94c4dae72a2ce34fd252c8d7f9549ecd35d8e58e/%40cTab/addons/cTab/functions/fn_onPlayerInventoryChanged.sqf) I am registering with that event.

**Comment by esteldunedain** [comment] 2015-04-29 01:13
@nsgundy, I'm glad "playerInventoryChanged" is getting picked up by the community; best event ever (certainly puts `take` and `put` to shame).
