### ISSUE TITLE
Command bar missing

### ISSUE THREAD

**Issue by isenhand** [acemod/ACE3#4319] opened 2016-09-02 15:57 UTC
**Arma 3 Version:** `latest` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.6.2` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Command bar missing when team leader. No option to turn it back on found in ACE options. Will return when switching to spectator mode and the back again

**Steps to reproduce:**
- run the game, always missing. 

**Where did the issue occur?**
- Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) 

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.
none

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by isenhand** [comment] 2016-09-02 16:13
testing a bit more. It appears the "user interface" menu option is missing. But not always. I tried another scenario and it appears then. See screen shot
![no user interface](https://cloud.githubusercontent.com/assets/18241087/18210472/f4c7d19e-7138-11e6-9b2e-bf0ba9c3bd4c.PNG)

**Comment by jonpas** [comment] 2016-09-02 16:55
Please provide RPT, we can't help you otherwise, especially as it looks like it's some edge-case issue.

**Comment by isenhand** [comment] 2016-09-02 17:14
[arma3_2016-09-02_17-59-59.zip](https://github.com/acemod/ACE3/files/452574/arma3_2016-09-02_17-59-59.zip)

**Comment by kripto202** [comment] 2016-09-02 17:18
one thing to keep in mind that the server can set specific UIs to be turned off and make sure your settings doesn't matter.

**Comment by isenhand** [comment] 2016-09-02 17:20
this is just on my own machine running in editor.

**Comment by jonpas** [comment] 2016-09-02 18:40
You wrote:
```
Mods:
- @CBA_A3
- @ace
```
But this is very much not true, please reproduce with only `@CBA_A3` and `@ace` as stated in issue reporting guidelines.

**Comment by kripto202** [comment] 2016-09-02 18:44
> this is just on my own machine running in editor.

my statement still stands it can also be in the editor as long as the module is placed down and set that way.

**Comment by isenhand** [comment] 2016-09-03 05:51
<<But this is very much not true>>

In what way not true? As far as I'm aware they are the latest up dates.

**Comment by isenhand** [comment] 2016-09-03 05:52
<< it can also be in the editor>>

One scenario produces this problem but if I run another scenario I don't have the problem. Will check what the difference is asap.

**Comment by Glowbal** [comment] 2016-09-03 06:48
This is most likely the result of a conflicting addon. Your RPT log shows you are loading a lot of addons. We cannot help you until you can reproduce your issues where you load just CBA and ACE3, without any other modifications.

I'd suggest you start a process of elimination to figure out what mod is breaking. I'd start with disabling HiddenIdentityPackV2 and/or TacticalBeards. 

I will close this issue. If you can reproduce with just CBA and ACE3 loaded, please feel free to reopen and we can take a closer look. At this time, there is nothing we can do.

**Closed by Glowbal** 2016-09-03 06:48 UTC
Labels: need more info
