### ISSUE TITLE
High-Command module causes addon mismatch on dedicated server

### ISSUE THREAD

**Issue by stice2k** [acemod/ACE3#2134] opened 2015-08-12 21:14 UTC
ACE3 Version: 3.2.1 Release

**Mods:**
* @cba_a3 (1.1.2.3)
* @ace3 (3.2.1)

**Placed ACE3 Modules:**
* None

**Description:**
As soon as there is a High Command module i can't join a mission on my dedicated (linux) server. The error message contains:

![2015-08-12 22_55_36-arma 3 stice admin _f__steamgames_steamapps_common_arma 3_arma3 exe_ -exthread](https://cloud.githubusercontent.com/assets/8117623/9236713/b00d4f8e-4146-11e5-843a-cad274b801cf.jpg)

(i removed ace_zeus and ace_scopes myself, there is no difference when all modules are available)

Server @ace folder and Client @ace folder are 100% identical.

Both singleplayer and listen server work fine with high command modules.
After removing the high command module, dedicated server is working fine too. Rather large missions with lots of ace content are working perfectly.

**Steps to reproduce:**
![2015-08-12 23_02_56-arma 3 _f__steamgames_steamapps_common_arma 3_arma3 exe_ -exthreads 7 -skipintro](https://cloud.githubusercontent.com/assets/8117623/9236784/308eee24-4147-11e5-835d-0b15937a1dc0.jpg)

* Create a simple mission
* Add player
* Add High-Command module
* Export mission and try it on a dedicated server (cant tell if windows dedicated works fine)

**Where did the issue occur?**
* Only dedicated

**RPT log file:**
http://pastebin.com/wGs8LDgZ

**Comment by gienkov** [comment] 2015-08-12 21:38
You use it for... ?

**Comment by stice2k** [comment] 2015-08-12 22:11
Dynamic High-Command, receiving command over all human squad-leaders at runtime (hcSetGroup).

**Comment by PabstMirror** [comment] 2015-08-12 22:21
On windows dedicated server I cannot reproduce, but I really don't understand why it would be limited to linux.

Do you still have access to the client's RPT?

Near the bottom there should be something like 
```
 [ACE] ERROR: Client/Server Version Mismatch. XXXXXX
and/or
[ACE] ERROR: Client/Server Addon Mismatch. Client has extra addons: YYYYYY
```

**Comment by stice2k** [comment] 2015-08-12 22:56
Yes, still have them. Here is the client rpt from that session.

http://pastebin.com/raw.php?i=FAp3Rax2

**Comment by Deviat** [comment] 2015-08-17 02:28
Having a similar issue with a mission with the high command module also. Singleplayer and listen servers work fine. @ace client and dedicated folders are mirrored exactly, but on the dedicated server it reports a client mismatch. Dedicated server is also a linux box.

**Comment by Tirpitz93** [comment] 2015-08-21 23:44
I am having the same issue, mission works fine without high command as soon as its added, I get kicked for mismatch. dedicated server running on windows (10).

**Comment by PabstMirror** [comment] 2015-08-29 17:43
With new CBA and arma 1.50 is this still happening?

**Comment by Uncobob** [comment] 2015-08-30 12:50
Occurs on windows dedicated here @1.50 and latest CBA. As soon as I remove High command from the mission, Ace3 works fine.
Is it possible to override this kick behavior?

**Comment by Glowbal** [comment] 2015-08-30 14:28
Could you give us your mission file where this issue happens, @Uncobob ?

**Comment by Uncobob** [comment] 2015-08-31 02:05
Sure, keep in mind it's a work in progress (and a modification of someone elses mission). I was simply trying to add ACE3 and high command support to it and happened to test it on dedicated.

http://www.mediafire.com/download/z6lxfysik5wvicc/co40_liberationBOB.altis+%288%29.zip

Mod params:
-mod=@CBA_A3;@ACE3;@ALiVE;@dragonfyrelite;@st_stamina_bar;@sthud_a3;@rhs_usf3;@rhs_afrf3;@leights_opfor;@cTab;@ASR_AI3;@task_force_radio;

**Comment by jonpas** [comment] 2015-08-31 02:16
From http://ace3mod.com/wiki/user/how-to-report-an-issue.html 
> If you've found an issue with ACE3 please make sure that ACE3 is really the cause of the problem. To do this try to reproduce the issue with using only `@CBA_A3` and `@ace` on a newly created mission.

> It's not a valid to simply remove `@ace` from the mod list to confirm that ACE3 is the culprit.

So @Uncobob please test as I copied above, any other mod could be interfering with the High Command module and in return cause issues when ran together with ACE3.

**Comment by Uncobob** [comment] 2015-08-31 02:37
Tested with CBA_A3 and ACE3 and the issue still occurs.

**Comment by Rockfrog** [comment] 2015-08-31 22:37
I get the same error suddenly.  If I remove High Commander, problem goes away.

Interestingly enough, it didn't exhibit this error this time last week on the same mission file with the same mods, so I'm guess it's 1.50 related, as it's the only thing which has changed since then.

**Comment by commy2** [comment] 2015-08-31 22:42
I'll take a look.

**Comment by commy2** [comment] 2015-08-31 23:22
Can't reproduce. Followed the steps in the OP, but everything is working fine.

**Comment by commy2** [comment] 2015-08-31 23:23
I'd appreciate if someone can upload a simple repro mission. mediafire link no longer works.

**Comment by Uncobob** [comment] 2015-09-01 02:39
The mediafire link is still active, but I don't think giving you a mission will help since the behavior occurs when you create a new mission with just CBA, ACE3 and high command.

I suggest creating a debug version that prints the server and client mod list from ace_common/fnc_checkFiles.sqf so that we can manually compare them on a dedicated which refuses to work. 
publicVariable QGVAR(ServerAddons);

I would have tested it myself but I can't recompile the pbo with what I'm using.

**Comment by bux578** [comment] 2015-09-01 06:43
@commy2 mediafire link works for me aswell.

**Comment by commy2** [comment] 2015-09-01 06:57
Mediafire still doesn't work for me. (Unknown error occured. Please try again.)
Added debug messages to current master.
Could reproduce error. Doesn't happen every time. Seems pretty random.

Server:
```
 8:47:49 [ACE] DEBUG: ServerVersion - 3.2.2.0
 8:47:49 [ACE] DEBUG: ServerAddons - ["ace_optionsmenu","ace_winddeflection","ace_common","ace_weather","ace_main","ace_modules"]
```

Client:
```
 8:52:06 [ACE] DEBUG: ServerVersion - 3.2.2.0
 8:52:06 [ACE] DEBUG: ServerAddons - ["ace_optionsmenu","ace_winddeflection","ace_common","ace_weather","ace_main","ace_modules"]
 8:52:06 [ACE] DEBUG: ClientVersion - 3.2.2.0
 8:52:06 [ACE] DEBUG: ClientAddons - ["ace_optionsmenu","ace_winddeflection","ace_main","ace_modules","ace_apl","ace_common","ace_difficulties","ace_disposable","ace_finger","ace_flashsuppressors","ace_fonts","ace_frag","ace_gforces","ace_goggles","ace_grenades","ace_hitreactions","ace_huntir","ace_interact_menu","ace_interaction","ace_inventory","ace_laser","ace_laser_selfdesignate","ace_laserpointer","ace_logistics_uavbattery","ace_logistics_wirecutter","ace_magazinerepack","ace_map","ace_maptools","ace_markers","ace_medical","ace_medical_menu","ace_microdagr","ace_missileguidance","ace_missionmodules","ace_mk6mortar","ace_movement","ace_mx2a","ace_nametags","ace_nightvision","ace_noidle","ace_noradio","ace_norearm","ace_optics","ace_overheating","ace_overpressure","ace_parachute","ace_protection","ace_ragdolls","ace_realisticnames","ace_recoil","ace_reload","ace_reloadlaunchers","ace_repair","ace_respawn","ace_safemode","ace_sandbag","ace_scopes","ace_sitting","ace_slideshow","ace_smallarms","ace_spectator","ace_s
 8:52:06 [ACE] ERROR: Client/Server Addon Mismatch. Client has extra addons: ["ace_apl","ace_difficulties","ace_disposable","ace_finger","ace_flashsuppressors","ace_fonts","ace_frag","ace_gforces","ace_goggles","ace_grenades","ace_hitreactions","ace_huntir","ace_interact_menu","ace_interaction","ace_inventory","ace_laser","ace_laser_selfdesignate","ace_laserpointer","ace_logistics_uavbattery","ace_logistics_wirecutter","ace_magazinerepack","ace_map","ace_maptools","ace_markers","ace_medical","ace_medical_menu","ace_microdagr","ace_missileguidance","ace_missionmodules","ace_mk6mortar","ace_movement","ace_mx2a","ace_nametags","ace_nightvision","ace_noidle","ace_noradio","ace_norearm","ace_optics","ace_overheating","ace_overpressure","ace_parachute","ace_protection","ace_ragdolls","ace_realisticnames","ace_recoil","ace_reload","ace_reloadlaunchers","ace_repair","ace_respawn","ace_safemode","ace_sandbag","ace_scopes","ace_sitting","ace_slideshow","ace_smallarms","ace_spectator","ace_spottingscope","ace_switchunits","ace_
```

**Comment by commy2** [comment] 2015-09-01 07:00
Seems like the HC module breaks the `activatedAddons` commad on server (including local host).

```
"ace_apl" in activatedAddons
-> false

isClass (configFile >> "CfgPatches" >> "ace_apl")
-> true
```

**Comment by bux578** [comment] 2015-09-01 07:07
@commy2 I've uploaded it to the ace3 google drive: https://drive.google.com/file/d/0BziAWKFDzWk9ZVZuQWloOWFpeWM/view?usp=sharing

**Comment by PabstMirror** [comment] 2015-09-01 07:25
module `execVM`'s a3\modules_f\hc\data\scripts\hc.sqf
which has line:
`activateAddons ["A3_Modules_F_Marta"];`

Manually calling that 
`count activatedAddons` goes from 659 to 561 and 
`"ace_apl" in activatedAddons` from true to false

it seems to wipe out all of CBA and ACE.

execVM is probably why it isn't always reproduceable.

Really feels like a BIS problem, didn't they get rid of the ability to activate addons dynamically a few patches ago?

**Comment by PabstMirror** [comment] 2015-09-01 07:37
What about `configProperties [configFile >> "CfgPatches", "true", true];` instead of `activatedAddons`?

**Comment by commy2** [comment] 2015-09-01 10:58
Or `configClasses`. Issue should be fixed now.

**Comment by stice2k** [comment] 2015-09-01 11:17
Can confirm, using the new ace_common the High-Command Module no longer causes said error.

Thanks for fixing.

**Comment by bux578** [comment] 2015-09-01 11:19
It has not been merged yet. Please leave this open.

**Closed** 2015-09-01 15:05 UTC
Labels: bug
