### ISSUE TITLE
Explosive attachment

### ISSUE THREAD

**Issue by aLmAnZio** [acemod/ACE3#1268] opened 2015-05-17 16:44 UTC
It seems to be a rare occurance, as I was only able to reproduce it once... But I spawned myself on Stratis on the hill above the airbase along with all modules loaded, all ammo boxes and a Merkava tank.

I used a demolition charge, and while placing it, it looked like the charge and the tank had improper collition detection causing me to be able to flip the tank over and push it around with the demolition charge. Despite several attempts to capture it with FRAPS, I wasn't able to reproduce the bug again after the one initial sucessfull atempt right after I encountered it first.

**Comment by jaynus** [comment] 2015-05-17 17:19
Please follow this format in the future for issue reporting: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

This is probably a duplicate of #1243 or #365

**Closed by jaynus** 2015-05-17 17:19 UTC
Labels: duplicate, invalid
