### ISSUE TITLE
Advanced Medical - Stitching not working/showing

### ISSUE THREAD

**Issue by RSpeekenbrink** [acemod/ACE3#3442] opened 2016-02-27 14:25 UTC
**Arma 3 Version:** `1.56 (EDEN) stable`
*(indicate if stable, rc or dev*)

**ACE3 Version:** `3.4.2 Release`
*(indicate if stable or dev, if dev indicate the commit the version is based on)*

**Mods:**
* `@CBA_A3`
* `@ace`
* `@TFAR`
* `@CUP_Terrains`

**Placed Modules:**
* All modules in mission: http://pastebin.com/jCrBZsvc
(Medical Modules Used: Ace 3 medical menu, Ace 3 medical settings, Ace 3 advanced medical settings)

**Description:**
When fully threated a patient (AI or Player) I wont get the option to Stitch the wounds. I have a surgical kit on me.

**Steps to reproduce:**
Put down modules & enable advanced wounds, reopenable, surgeon kit for ANYONE, etc
Put down AI / Player, shoot person in the leg
Threat the patient
after that you can't stitch the wounds

**Where did the issue occur?**
Editor, Singleplayer, Multiplayer

**RPT log file:**
http://pastebin.com/tzF0UKQa

**Comment by jonpas** [comment] 2016-02-27 14:29
Settings are not set to advanced medical, because:
```
15:02:58 [ACE] (common) WARNING: Setting [ace_medical_medicSetting_PAK] out of bounds -1 (values[] count is 3)(
15:02:58 [ACE] (common) WARNING: Setting [ace_medical_medicSetting_SurgicalKit] out of bounds -1 (values[] count is 3)(
15:02:58 [ACE] (common) WARNING: Setting [ace_medical_consumeItem_PAK] out of bounds -1 (values[] count is 2)(
15:02:58 [ACE] (common) WARNING: Setting [ace_medical_consumeItem_SurgicalKit] out of bounds -1 (values[] count is 2)(
15:02:58 [ACE] (common) WARNING: Setting [ace_medical_useLocation_PAK] out of bounds -1 (values[] count is 5)(
15:02:58 [ACE] (common) WARNING: Setting [ace_medical_useLocation_SurgicalKit] out of bounds -1 (values[] count is 5)(
15:02:58 [ACE] (common) WARNING: Setting [ace_medical_useCondition_PAK] out of bounds -1 (values[] count is 2)(
```
Duplicate of #3339, BIS broke it in 1.56, hope there will be a hotfix soon.

**Closed by jonpas** 2016-02-27 14:29 UTC
