### ISSUE TITLE
Check for trench possibility inverted on some maps

### ISSUE THREAD

**Issue by Lujan1405** [acemod/ACE3#5613] opened 2017-10-12 20:49 UTC
**Arma 3 Version:** current (stable)
**CBA Version:** `3.4.1` (stable / dev + commit hash)
**ACE3 Version:** `3.10.2` (stable / dev + commit hash)

**Mods:** 
```
- CBA_A3
- ace
- CUP Terrains Complete
- Celle
```

**Description:**
- On some maps (noticed again today on Celle) the check if you are able to dig a trench is inverted. It is possible to dig up the streets but not to put a trench down on the grass next to it. This only occurs on some maps with Celle beeing one of them (I´ll check tomorrow for the others we had that issue and update if needed)

https://imgur.com/a/k8p3A

**Steps to reproduce:**
- Set a player on celle
- Give him the entrenching tool
- Try to dig a trench on the streets vs on the grass

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- None

**RPT log file:**
- https://pastebin.com/5hNVkEhW

**Comment by BrenSilent** [comment] 2017-10-13 08:53
Okay. I just got a few minutes so i tested Altis, Beketow and the CUP Bystrica.

Altis is the same like Celle. Trench possible on streets. Not on grass.
Beketow is kinda strange. Uploaded the images under the following link (will add further pics there)
Bystrica is kinda special too. Picture is there too:

https://imgur.com/a/bgpYp

I´ll test some more maps from cup some mod-maps and all four vanillas asap

**Comment by commy2** [comment] 2017-10-13 10:57
https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_canDig.sqf#L31
This is the logic used. Streets tend to be very dusty and grass not so much. Maybe should work more with the white- and blacklist.
https://github.com/acemod/ACE3/blob/master/addons/common/script_component.hpp#L24-L36

**Comment by BrenSilent** [comment] 2017-10-13 11:25
Okay that explains why it is allowed on the streets of bystrica but not on the sidewalk. getposATL select 2 on the sidewalk is 0.1.

And on altis there is a lot of "drygrass" which might be needed in the whitelist. 

But i am currently standing on Alits in a "green" area (surfacetype is "grass") and i still cant dig.
https://imgur.com/z7bj9hw
https://imgur.com/JWLfQqF

**Comment by jonpas** [comment] 2017-10-14 20:34
Altis streets and grass:
```
22:23:15 [ACE] (common) TRACE: 50956 Surface: _surfaceType=dirt, _surfaceDust=0.5 z\ace\addons\common\functions\fnc_canDig.sqf:30
```
Not too sure what to do about streets, method we use uses `soundEnviron` entry which returns `dirt` in this case.
Grass was fixed (whitelisted `"grass"`) in #5453 which will be released with 3.11.0.

Bystrica streets:
```
22:27:44 [ACE] (common) TRACE: 69877 Surface: _surfaceType=normalExt, _surfaceDust=0.1 z\ace\addons\common\functions\fnc_canDig.sqf:30
```
Blacklist surface type seems to be the best solution.

Don't have Celle or Beketov downloaded now, but if you can get me surface types and see if some other surface you shouldn't be able to dig on doesn't have the same one (like Altis streets), I'll add it.

**Comment by SilentSpike** [comment] 2017-12-03 16:41
We just need the surface types to blacklist in order to fix this, going to set milestone to ongoing until we know them.

**Comment by jonpas** [comment] 2019-03-24 21:17
Unassigning myself, don't have time to look into those maps myself.

**Comment by Rod6er** [comment] 2019-12-20 18:54
Ok so I asked the map maker for beketov and here are the surface types
http://pastebin.com/aTt1C38U

**Comment by Mike-MF** [comment] 2023-09-19 00:58
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Closed by Mike-MF** 2023-09-19 00:58 UTC
Labels: kind/bug
