### ISSUE TITLE
Review realisticname

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#5166] opened 2017-05-15 22:38 UTC
Realistic weapons in general could use a lookover

- We rename the "macer" to the maverick, jets expansion adds a "macer II"
- Some Renamed weapons are too long for some HUDs (e.g. "AIM-132 ASRAAM")
- Seems weird putting "9K121 Vikh" on a blufor vehicles compared to vanilla "Scalpel"
- Both vanilla "DAR" and "Shrieker" are now called Hydra

**Comment by JANXOL** [comment] 2017-06-03 09:13
From what I have seen, some vehicle names have also reverted with jets expansion. Thunderbolt is wipeout again, kasatka is orca, etc.

**Comment by SilentSpike** [comment] 2017-06-03 12:33
@JANXOL That has already been fixed in master :smiley: Will be in 3.10

**Comment by Mike-MF** [comment] 2023-09-11 00:34
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Closed by Mike-MF** 2023-09-11 00:34 UTC
Labels: kind/task
