### ISSUE TITLE
Serious Damage Problem

### ISSUE THREAD

**Issue by DLEGION** [acemod/ACE3#4393] opened 2016-09-13 22:27 UTC
**Arma 3 Version:** `1.62` stable
**CBA Version:** `3.0.0` stable
**ACE3 Version:** `3.7.0` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
hate to repeat myself, anyway seems necessary : the problem:
you need 18 (6.5mm) bullets to drop a soldier. and its an average value. often you need even more bullets. and i used a "standard" caliber, with weapons like .338 lapua magnum or 0.50 BMG its even more ridicolous!
look by yourself :

https://www.youtube.com/watch?v=EdGXU5PTXRg

this is NOT realistic for me . sorry.
a single 6.5mm bullet in an arm OR a leg will make ANYONE fall on the ground screaming in pain if not fall on the ground unconscious. we all agree that the wound soldier will eventually die by blood loss, but for sure that soldier would be incapacitated.

- Some versions ago ( i started edit ACE3 by myself in 3.5.1) i noticed and pointed your attention on this "problem" (at least it is for me and my friends, and its a serious game breaking one! ).
now with 3.7.0 i hoped in some sort of fix or at least a setting that allow you to choose from "realistic" to COD/battlefield actual values. 

**Steps to reproduce:**
- simply run advanced medical in virtual arsenal or editor, shoot some soldiers to notice the problem.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal, everywhere.

**Placed Modules:**
- None

**Comment by gienkov** [comment] 2016-09-13 22:39
IIRC VA have severe issues with ACE3 and it basically shouldn't be your test ground for testing stuff.

**Comment by commy2** [comment] 2016-09-14 08:34
Don't test on the VA soldiers.

**Comment by DLEGION** [comment] 2016-09-14 10:45
ok about VA, but as i saied its exactly the same for normal play ( Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal, everywhere ).
so please stop negate the problem existance , thanks :)

PS: with my edit, even in VA it works perfectly.

**Comment by commy2** [comment] 2016-09-14 11:55
duplicate of #3302 Please don't open duplicate issues. thanks.

**Closed by commy2** 2016-09-14 11:55 UTC
