### ISSUE TITLE
Prevent Instant Death not working, have check all previous threads.

### ISSUE THREAD

**Issue by Grizmatki** [acemod/ACE3#3818] opened 2016-05-23 03:45 UTC
**Arma 3 Version:** `1.58` (stable / rc / dev)
**CBA Version:** `Stable` (stable / dev + commit hash)
**ACE3 Version:** `Stable` (stable / dev + commit hash)

**Mods:**
@ACE3
@ALiVE 
@CUP Terrains 
 @ToraBora
@ CBA
@ BC Phoenix 
 @DAR HMMWV  
@ FSF Sacventral 
@ Leights Opfo
@ MCC  
@ Nimitz 
@ RHS AFRF3 
@ RHS USF3 
@ RHS GREF 
@ TFAR 
@ TAW View Distance 
@ POMI PMC 
@ Clafghan 
@Fallujah 
@ KaluKhan 
@ Al Rayak|
@ cTab 
@ mb_Rocks 
@  mb_veg_adv 
@ opx_objects  
@ razmisc 
@ F/A18 
@ ewk_cigs 
@ MELB
@ Murshun cigs
@ 3cb_baf_weapons 
@ rh_acc
@ tf47_launchers_rhs
@ l3_gpnvg18 
@ kunduz 
@ EODS 
@ Ares
@ CPM
@ NIArsenal Core
@ NIArsenal G3 
@ NIArsenal AR15
@ NIArsenal AWP 
@NIArsenal G36
@ ARC_Patches 
@ ADR-97 
@ VSM
**Description:**
The instant death is seemly working randomly under exact same situations. Getting shot by a 7.62 has a chance of making you instant die or going unconscious even when prevent instant death is on. Having prevent instant death seems to do nothing to stop the issue. 

To be clear, I understand prevent instant death does not protect against everything. It should however prevent instant death against a 7.62 rifle when shot in the chest.

**Steps to reproduce:**
Launch in MP server, have people join, have them get shot.

**Where did the issue occur?**
 Dedicated 

**Placed Modules:**
Most modules placed down, except kick/warn. Advanced medical, Medical menu, Medical settings all tuned toward advanced/no instant death. We have test syncing the revive module to the medical settings (recommended in another thread) and have had no luck.

**RPT log file:**
- Will add soon

**Comment by bux578** [comment] 2016-05-23 03:57
>If you have found an issue with ACE3 please make sure that ACE3 is really the cause of the problem. To do this try to reproduce the issue with using only @CBA_A3 and @ace on a newly created mission.

**Comment by commy2** [comment] 2016-05-23 06:49
^ ths is very important

also,duplicate of #3538

**Closed by commy2** 2016-05-23 06:49 UTC
