### ISSUE TITLE
Wipe glasses anim pulls out primary weapon if not selected

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#3638] opened 2016-03-30 04:24 UTC
- Wipe glasses when pistol or launcher selected. Rifle on back magically moves to floating infront of player.

Just graphical glitch that looks funny, no lasting effects after animation.

![image](https://cloud.githubusercontent.com/assets/9376747/14131893/228db6f2-f605-11e5-9c4a-5af292c60e74.png)

I don't know if we can make additional .rtms for each weapon type, or should just restrict wiping when we don't have a primary weapon.

**Comment by CorruptedHeart** [comment] 2016-03-30 05:05
Psh, who doesn't want to have more guns?

I think the animations might have to be redone from scratch, I don't think I still have the source files for it.

**Comment by jonpas** [comment] 2016-04-12 05:27
This is technically a duplicate of #1122, but I marked it as duplicate and replaced by this.

**Closed** 2016-04-12 13:59 UTC
Labels: bug
