### ISSUE TITLE
Latest Build of ACE causes a ilegal Instruction error

### ISSUE THREAD

**Issue by enderrrrrrrrrr** [acemod/ACE3#1630] opened 2015-06-15 09:38 UTC
ACE3 Version: 3.1.0
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
irrelevant 

**Description:**
Trying to enter a game causes a crash with the following error

The exception Illegal Instruction
An Attempt was made to execute an ilegal instrcution.
(oxc0000001d) occurred in the application at location 0x0f023282.

On termination i get 

Exit code:0xc0000001d / -1083841895
reason: unkown

**Where did the issue occur?**
Both

**RPT log file:**
http://pastebin.com/g1ipaPcg

**Comment by Glowbal** [comment] 2015-06-15 09:51
From the rtp:
```
Distribution: 0
Version 1.46.131175
Fault time: 2015/06/15 06:34:48
Fault address:  0F023282 01:00012282 C:\Users\Carson\AppData\Local\Temp\Rar$DRa0.632\@ace\ace_advanced_ballistics.dll
file:     Arsenal
world:    VR
Prev. code bytes: 00 00 00 8B F8 03 CE 2B FA 8B C7 83 E0 1F 2B F8
Fault code bytes: C5 F4 57 C9 03 F9 EB 0F C5 F5 74 01 C5 FD D7 C0
```

**Comment by Glowbal** [comment] 2015-06-15 09:53
The fix for this should be branched off `release`.

I will be able to take a look at this later today as well.

@enderrrrrrrrrr Do you get this every time? How do we reproduce this?

**Comment by Glowbal** [comment] 2015-06-15 10:46
@enderrrrrrrrrr you seem to be using the mods from some temp location.
`C:\Users\Carson\AppData\Local\Temp\Rar$DRa0.632\`

Could you try to load it from for example the A3 root directory instead?

**Comment by whiztler** [comment] 2015-06-15 13:19
Been testing 3.1.0 with my missions. Could not reproduce the issue
ACE 3.1.0. + CBA_A3 latest, Altis, Stratis, Takistan, VR

**Comment by enderrrrrrrrrr** [comment] 2015-06-15 18:08
>@enderrrrrrrrrr Do you get this every time? How do we reproduce this?

@Glowbal Yes Every time. I'm not sure how you reproduce it as it started happening at the latest release whenever i attempted to enter any type of game. I get about halfway through the load screen and the crash happens.

>@enderrrrrrrrrr you seem to be using the mods from some temp location.
C:\Users\Carson\AppData\Local\Temp\Rar$DRa0.632\

@Glowbal I had originally loaded it from my A3 directory but i wanted to make a fresh crash without any of my own mods impacting the crash report so i made a temp directory with just ace and CBA3. It happens just the same if i have it in the a3 directory.

@whiztler when i googled the illegal exception error it brought up something to do with the ballistics file and that it only happened on a certain percentage of machines. It may be possible that it is a similar issue for this and then only a certain number of machines are effected.

**Comment by esteldunedain** [comment] 2015-06-15 18:20
We think we know what's causing this. The dll will be recompiled tonight.

**Comment by enderrrrrrrrrr** [comment] 2015-06-15 18:24
@esteldunedain Okay thanks

I made a video of the issue in case that helps: http://www.twitch.tv/enderrrrrrrrrr/b/669339632

**Comment by esteldunedain** [comment] 2015-06-15 18:26
@enderrrrrrrrrr, we think your processor is from the faulty batch that doesn't support avx instructions. We usually compile extensions in a way they don't use those, but yesterday the ab extension was compiled wrong for some reason.

**Comment by enderrrrrrrrrr** [comment] 2015-06-15 18:32
@esteldunedain I have a i7-4770k if i have a faulty cpu i would like to see if i can get the manufacturer to replace it. What is the issue that i would list in my complaint to them? Thanks for your help.

**Comment by esteldunedain** [comment] 2015-06-15 18:38
I'm really not an expert, but it may be related to this :https://github.com/acemod/ACE3/issues/1042

**Comment by enderrrrrrrrrr** [comment] 2015-06-15 18:47
@esteldunedain thanks!

**Comment by Glowbal** [comment] 2015-06-15 20:38
#1640

**Comment by esteldunedain** [comment] 2015-06-15 20:40
@enderrrrrrrrrr, please try replacing the dll by this one:

https://github.com/acemod/ACE3/blob/fix-ab-extension/ace_advanced_ballistics.dll

and report back.

**Comment by enderrrrrrrrrr** [comment] 2015-06-15 23:33
@esteldunedain 

No love, same error.

**Comment by enderrrrrrrrrr** [comment] 2015-06-15 23:37
Pastebin for new .dll crash: http://pastebin.com/cVCVfGZn

**Comment by enderrrrrrrrrr** [comment] 2015-06-16 21:51
@esteldunedain So the new version of that .DLL that they updated to Seems to have fixed the problem. Will continue testing to make sure.

**Comment by esteldunedain** [comment] 2015-06-16 21:55
Great to hear!

**Comment by enderrrrrrrrrr** [comment] 2015-06-16 22:48
As far as i can tell the latest .DLL fix seems to have resolved the issue. Thanks for your help guys. I'll let one of you guys close it in case theres anything you want to add to the issue.

**Closed** 2015-06-16 22:49 UTC
Labels: critical bug
