### ISSUE TITLE
class CommanderOptics in cfgVehicles.hpp gets cleared and causes errors

### ISSUE THREAD

**Issue by audiocustoms** [acemod/ACE3#2814] opened 2015-11-02 12:28 UTC
https://github.com/acemod/ACE3/blob/master/addons/vehicles/CfgVehicles.hpp

Line 16 and Line 25 must be:
class CommanderOptics : CommanderOptics {};
Otherwise the entries from vanilla Arma3 gets cleared.
This causes turret errors with mods using 
class LandVehicle and class Tank as baseclass like CUP

**Comment by commy2** [comment] 2015-11-02 23:06
Negative. This is normal class inheritance from what I see.

**Comment by commy2** [comment] 2015-11-02 23:07
Are you from CUP? Can I take a look at your configs. I'm pretty sure these errors are caused by something else.

**Comment by SilentSpike** [comment] 2015-11-03 00:42
Yeah it's a dummy class, doesn't overwrite anything.

**Comment by TheConen** [comment] 2015-11-03 01:57
`class CommanderOptics;` is an external class reference, not an inheritance. The proper inheritance would be `class CommanderOptics: CommanderOptics{};`
`class CommanderOptics` creates an empty dummy class which can be used to inherit from if the actual class is not known currently. It acts like the `extern` keyword in C/C++, telling the engine that the class exists somewhere else.
 E.g. if in a vehicle mod you would want to inherit from the  vanilla Hunter, you would write
```
class B_MRAP_01_F; // external class reference because this class is not known in this mod
class myNewHunter: B_MRAP_01_F { //correct inheritance with changing attributes
author = "me";
};
```
If we wouldn't want to change any attributes (like we don't wan't do to in this case), it would be
```
class B_MRAP_01_F; // external class reference because this class is not known in this mod
class myNewHunter: B_MRAP_01_F {}; //correct inheritance without changing attributes
```
It is correctly done in e.g. line 7, 13, 19, 33, 47, 55, 63, 83, 89, 93, 103, 120, 139, 141, 148, 154, 156, 161, 165, 170, 179, 186....... I could go on like this, but I think you get the idea.

If there is an external class reference inside another class which has the name of a subclass of this class, this subclass gets overwritten with an empty class - like in line 4, 9, 16, 25, 73, 198, 250, 255, 260, 265, 338 (interestingly the seemingly correct vesion is commented out in some of those cases).

**Comment by NeoArmageddon** [comment] 2015-11-03 11:55
We directly inherit from Tank_F and Tank without modifying the base classes. Everthing fine with vanilla A3 but when ACE is loaded, all entries in subclasses like commanderobjects are undefined.  I checked both configs with a BISim employee and the coclusion was, that the ACE config probably redefines (completely clears) some subclasses. The problem seems to arise when the classes are nested too deeply.

**Comment by commy2** [comment] 2015-11-03 13:06
Show me the configs. Pretty sure they are wrong.

**Comment by commy2** [comment] 2015-11-03 13:15
I checked again with the 1.50 configs. Correct inheritance is:
(line 19)
```
	class LandVehicle: Land
	{
		class CommanderOptics: NewTurret
		{
		};
	};
```

(line 25)
```

	class Tank: LandVehicle
	{
		class Turrets
		{
			class MainTurret: NewTurret
			{
				class Turrets
				{
					class CommanderOptics: NewTurret
					{
					};
				};
			};
		};
	};
```

Which is exactly what we do. The suggestion to replace them with `class CommanderOptics : CommanderOptics {};` would be wrong.

**Comment by commy2** [comment] 2015-11-03 13:20
Google brought me to this issue:
https://forums.bistudio.com/topic/179326-community-upgrade-project-cup/?p=2932788

I just assume that what we are talking about. Currently downloading the mod to resolve the isse.

**Comment by NeoArmageddon** [comment] 2015-11-03 16:36
The inheritance you posted above differes from the one I found, where it doesn't derives from NewTurret (commented out). I am at my phone, so can't do much here right now.

**Comment by commy2** [comment] 2015-11-03 16:45
I found a couple of Updating base class issues. Those are definitely the reason for this issue. Currently doing further investigations on what PBOs in CUP_Vehicles are the cause.

CBA_A3 + CUP
```
17:41:04 Updating base class ->MainTurret, by a3\air_f\config.bin/CfgVehicles/Helicopter_Base_H/Turrets/CopilotTurret/
17:41:05 Updating base class Turrets->, by a3\air_f_beta\config.bin/CfgVehicles/Plane_Base_F/Turrets/
17:41:05 Updating base class ->CommanderOptics, by a3\armor_f_beta\config.bin/CfgVehicles/Tank_F/Turrets/MainTurret/Turrets/CommanderOptics/
17:41:05 Updating base class ->SlotInfo, by a3\weapons_f_mark\config.bin/UnderBarrelSlot/
17:41:05 Updating base class KIA_RHIB_Cargo->DefaultDie, by CUP\WaterVehicles\CUP_WaterVehicles_Zodiac\config.bin/CfgMovesMaleSdr/States/Zodiac_Dead/
17:41:05 Updating base class Optics_Commander_02->Optics_Armored, by CUP\WheeledVehicles\CUP_WheeledVehicles_BTR90\config.bin/Optics_Commander_03/
17:41:05 Updating base class UnderBarrelSlot->asdg_UnderSlot, by x\cba\addons\jr\config.bin/CfgWeapons/srifle_EBR_F/WeaponSlotsInfo/UnderBarrelSlot/
17:41:05 Updating base class CowsSlot->asdg_OpticRail1913, by x\cba\addons\jr\config.bin/CfgWeapons/srifle_GM6_F/WeaponSlotsInfo/CowsSlot/
17:41:05 Updating base class CowsSlot->asdg_OpticRail1913, by x\cba\addons\jr\config.bin/CfgWeapons/srifle_LRR_F/WeaponSlotsInfo/CowsSlot/
17:41:05 Updating base class UnderBarrelSlot->asdg_UnderSlot, by x\cba\addons\jr\config.bin/CfgWeapons/srifle_DMR_01_F/WeaponSlotsInfo/UnderBarrelSlot/
17:41:05 Updating base class CowsSlot->asdg_OpticRail1913_short_MG, by x\cba\addons\jr\config.bin/CfgWeapons/LMG_Mk200_F/WeaponSlotsInfo/CowsSlot/
17:41:05 Updating base class PointerSlot->asdg_FrontSideRail, by x\cba\addons\jr\config.bin/CfgWeapons/LMG_Mk200_F/WeaponSlotsInfo/PointerSlot/
17:41:05 Updating base class UnderBarrelSlot->asdg_UnderSlot, by x\cba\addons\jr\config.bin/CfgWeapons/LMG_Mk200_F/WeaponSlotsInfo/UnderBarrelSlot/
17:41:05 Updating base class CowsSlot->asdg_OpticRail1913_short_MG, by x\cba\addons\jr\config.bin/CfgWeapons/LMG_Zafir_F/WeaponSlotsInfo/CowsSlot/
17:41:05 Updating base class PointerSlot->asdg_FrontSideRail, by x\cba\addons\jr\config.bin/CfgWeapons/LMG_Zafir_F/WeaponSlotsInfo/PointerSlot/
17:41:05 Updating base class CowsSlot->asdg_OpticRail1913, by x\cba\addons\jr\config.bin/CfgWeapons/arifle_MXC_F/WeaponSlotsInfo/CowsSlot/
17:41:05 Updating base class PointerSlot->asdg_FrontSideRail, by x\cba\addons\jr\config.bin/CfgWeapons/arifle_MXC_F/WeaponSlotsInfo/PointerSlot/
17:41:05 Updating base class MuzzleSlot->asdg_MuzzleSlot_556, by x\cba\addons\jr\config.bin/CfgWeapons/arifle_TRG20_F/WeaponSlotsInfo/MuzzleSlot/
17:41:05 Updating base class ->Turrets, by CUP\AirVehicles\CUP_AirVehicles_MV22\config.bin/CfgVehicles/Plane_Base_F/Turrets/
```

**Comment by commy2** [comment] 2015-11-03 17:08
Can confirm that it's caused by an updating base class error in CUP, _NOT_ ACE.

CBA only: no error
ACE: no error
CUP: see above
ACE + CUP:
```
18:03:56 Updating base class ->CommanderOptics, by a3\armor_f_beta\config.bin/CfgVehicles/Tank_F/Turrets/MainTurret/Turrets/CommanderOptics/
18:03:56 Updating base class CommanderOptics->CommanderOptics, by z\ace\addons\vehicles\config.bin/CfgVehicles/Tank_F/Turrets/MainTurret/Turrets/CommanderOptics/
```

**Comment by commy2** [comment] 2015-11-03 17:34
First issue is, that CUP vehicles are accessing the `Tank` and `Tank_F` base classes before they are defined by the game files. There should be `A3_armor_f_beta` added to the requiredAddon in CfgPatches in each vehicles config.cpp.

**Comment by commy2** [comment] 2015-11-03 17:52
I think I identified the issue in `CUP_TrackedVehicles_T55`

```
class CfgVehicles
{
	class LandVehicle;
	class Tank: LandVehicle
	{
		class HitPoints;
		class Turrets
		{
			class MainTurret;
		};
		class ViewOptics;
	};
	class Tank_F: Tank {
		class Turrets
		{
			class MainTurret;
			class CommanderOptics;
		};
	};
```

This introduces `class Tank_F\Turrets\CommanderOptics` which does not exist in the base game. Due to this config being loaded before certain vanilla configs (see above) this confuses the name-based inheritance system of the .cpp. This class has to be removed and intended inheritance has to be used. I'm not certain if this was the only PBO that has this issue. I'll further investigate.

**Comment by commy2** [comment] 2015-11-03 18:14
Can confirm that the UBC issue is only caused by the T55's config. I suggest changing these few first classes to the same all other vehicles in CUP use. Example T72:

```
	class LandVehicle;
	class Tank: LandVehicle {
		class NewTurret;
		class Sounds;
		class HitPoints;
	};
	class Tank_F: Tank {
		class Turrets {
			class MainTurret:NewTurret {
				class Turrets {
					class CommanderOptics;
				};
			};
		};
	};
```

From past experience I'm pretty sure that this fixes the initial issue some users had with CUP and ACE.

**Comment by commy2** [comment] 2015-11-03 18:18
>The inheritance you posted above differes from the one I found, where it doesn't derives from NewTurret (commented out). I am at my phone, so can't do much here right now.

The config I posted and the one from ACE are equivalents.

**Comment by NeoArmageddon** [comment] 2015-11-03 18:27
Thanks for the help!
Seems like pboProject failed to find the correct references (probably because of that T55 config).
Somebody will report back here if the problem is fixed with your proposed changes.

**Comment by commy2** [comment] 2015-11-03 19:19
I found another issue in 2 other PBOs.
`CUP_TrackedVehicles_AAV` and `CUP_TrackedVehicles_ZSU23` both use:

```
	class LandVehicle;
	class Tank: LandVehicle
	{
		class CommanderOptics;
	};
```

This class is never used and has to be deleted.

Removing the AAV, ZSU23 and T55 removes the initial error (`No entry 'bin\config.bin/CfgVehicles/B_APC_Tracked_01_rcws_F/Turrets/CommanderOptics.primaryObserver'.` popup)

**Comment by commy2** [comment] 2015-11-03 22:36
When playing around with these files I also noted that the AAV is missing `"A3_Armor_F_Beta"` in requiredAddons.

**Comment by commy2** [comment] 2015-11-12 15:52
@audiocustoms
@NeoArmageddon

Any news on this? I've seen the new CUP update, but had no time to check stuff yet.

**Comment by audiocustoms** [comment] 2015-11-20 08:52
Sorry for the late answer and yes, we were able to fix it. THX for the big help you guys gave

**Comment by commy2** [comment] 2015-11-20 12:22
Nice! :+1: 
We are all doing our best here.

**Closed by commy2** 2015-11-20 12:22 UTC
