### ISSUE TITLE
Unable to Rearm Vehicle With 'Entire Vehicle'

### ISSUE THREAD

**Issue by aristenn** [acemod/ACE3#6129] opened 2018-02-06 23:19 UTC
**Arma 3 Version:** `1.80.143869` (stable)
**CBA Version:** `3.6.1.180131` (stable)
**ACE3 Version:** `3.12.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
When attempting to rearm a vehicle with the Rearm setting set to "Entire Vehicle' the progress bar pops up and disappears almost instantly. When returning to the vehicle, the rounds have not been rearmed.

https://youtu.be/5WDUmltgdkA

**Steps to reproduce:**
- Go into editor
- Place down A-10
- Place Ammo HEMTT
- Shoot some rounds from the A-10's GAU-8
- Attempt to perform rearm on A-10 using the HEMTT

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- A-10D, HEMTT Ammo, Repair Specialist

**RPT log file:**
- RPT -  https://gist.github.com/aristenn/e2011ca68869be7915a3279f28a7c7c5
- ACE Debug - https://gist.github.com/aristenn/00e223c9dab6168e62e7d86e047ca5b1

**Comment by dedmen** [comment] 2018-02-07 08:38
Sounds like #5944 but no script error and that one has already been fixed.
Only thing I can imagine is https://github.com/acemod/ACE3/blob/2ed9eaca2f65ed4773a3df80fab99f065a137c05/addons/rearm/functions/fnc_rearmEntireVehicle.sqf#L31

**Comment by aristenn** [comment] 2018-02-09 19:55
The issue seems to happen regardless of how far the vehicle is from the rearm vehicle (Within ranges that the ACE action appears).

Furthermore, if the vehicle is out of reach, why am I getting the ACE action to perform the rearm?

**Comment by Bosenator** [comment] 2018-02-19 16:47
I am also getting this error on a third party vehicle with a third party rearm truck on a dedicated server. Same symptoms.

**Comment by senevoldsen** [comment] 2018-04-26 10:55
I think I have something on this one - but I might have made a mistake.

Let *Truck* be the ammo truck, *Vehicle* the vehicle we are trying to rearm, and player is obvious. Instead of REARM_ACTION_DISTANCE I will just write 9.

Then in https://github.com/acemod/ACE3/blob/f35f80ee828adb4c9dbbcd8f285f9a9a0cb02d59/addons/rearm/functions/fnc_initSupplyVehicle.sqf#L44 the actions are only added if canTakeAmmo is true. That is only true if the `(player distance Truck) < 9`.

The target vehicle shown in the list is then added in addRearmActions. A Vehicle is only considered at all if `(Vehicle distance Truck) < 20` in https://github.com/acemod/ACE3/blob/0644ad9ca2fadd28711dd614be296542a834bc3e/addons/rearm/functions/fnc_addRearmActions.sqf#L20

As @dedmen writes earlier, in order for the loading to proceed we must have during the entire loading time that `(player distance Vehicle) < 9`.

That leaves the are where  the Player is close to the Truck (<9m), and the Truck is within 20m of the Vehicle, but the player is away from the Vehicle (>9m). This also coincides with my personal experience that you need to get close to the vehicle you wish to rearm to avoid the progress bar disappearing immediately.

**Comment by dedmen** [comment] 2018-11-18 13:00
Needs to be labeled as bug to make the bot not close it.

**Comment by Mike-MF** [comment] 2023-09-19 01:37
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Closed by Mike-MF** 2023-09-19 01:37 UTC
Labels: kind/bug
