### ISSUE TITLE
ACE Virtual Arsenal problem

### ISSUE THREAD

**Issue by Warden3-8** [acemod/ACE3#7599] opened 2020-03-13 13:23 UTC
**ACE :**
- **Arma 3:** Latest, Stable
- **CBA:** Latest update
- **ACE3:** Latest update

**Description:**
The Virtual Arsenal from ACE Mod launched by Main Menu act like a single player scenario and not like the Virtual Arsenal anymore.

**Steps to reproduce:**
- Launch ArmA 3 with the latest version of the game, CBA and ACE (latest version of mods too)
- Click on "ACE Virtual Arsenal" in the Main Menu
- The Virtual Arsenal is broken, in the menu when start but act like a scenario when hit Escape. No more VR entities and VR obstacles and vehicles are loaded since the beginning.

**Expected behavior:**
The ACE Virtual Arsenal should be usable like before.

**Where did the issue occur?**
- ACE Virtual Arsenal

**Log Files:**
No log file for this issue.

**Additional context:**
Nothing else to report.

**Screenshots:**
Screenshots not needed.

**Comment by jonpas** [comment] 2020-03-13 13:49
Duplicate of #7584, already fixed for next update.

**Closed by jonpas** 2020-03-13 13:49 UTC
Labels: kind/bug

**Comment by Warden3-8** [comment] 2020-03-13 14:05
Oh, sorry. I searched before posting, but not visibly enough. Thanks.
