### ISSUE TITLE
Titan Compact bug

### ISSUE THREAD

**Issue by kamkill01011** [acemod/ACE3#4527] opened 2016-10-08 15:53 UTC
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.7.0` (steam)
**ACE3 Version:** `3.1.0` (steam)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- All Titan MPRL Compact launcher direct the missile at a wrong location with AT missiles (always on the right, sometime closer, some time futher), only with Titan MPRL Compact other Titan and the NLAW works fine. https://youtu.be/_OTpY0JB2lI

**Steps to reproduce:**
- Take any Titan MPRL Compact launcher, lock on a vehicle, shoot (TOP or DIR)

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Placed Modules:**
- 'None'

**RPT log file:**
- http://pastebin.com/UqeRMM8t

**Comment by bux578** [comment] 2016-10-08 16:33
Can not repro. It works fine for me on Stratis (see video) and VR.

[![IMAGE](http://img.youtube.com/vi/TBaAb0rl0N0/0.jpg)](http://www.youtube.com/watch?v=TBaAb0rl0N0)

**Comment by bux578** [comment] 2016-10-08 16:36
Apart from what you've written, you're using more mods than just CBA and ACE.
Please try it with only CBA and ACE3.

**Comment by kamkill01011** [comment] 2016-10-08 16:54
I have already tried with only ACE3 and CBA and had the same result. I played on dedicated server and I was the only one to have this problem.

**Comment by commy2** [comment] 2016-10-08 16:56
Please reproduce without any other mods loaded and upload the RPT file of that session.

**Comment by kamkill01011** [comment] 2016-10-08 17:01
http://pastebin.com/sZVm5yjt

**Comment by PabstMirror** [comment] 2016-10-21 03:47
#4562 might fix this, I have seen missiles fly just up and never come down because of seeker problems.

**Comment by kamkill01011** [comment] 2016-11-10 19:09
I had another bug (with spotting scoipe) so I created a new profile and tested, using the new profile resolved the bug I have with the spotting scope and the one with the Titan. Please tell me if a can provied any file to help you find out why I had those problems.

**Comment by PabstMirror** [comment] 2016-11-16 01:03
Should be fixed by the seek last pos feature in #4562

**Closed by PabstMirror** 2016-11-16 01:03 UTC
Labels: can't reproduce, need more info
