### ISSUE TITLE
ACE 3 Medical Vehicle crashes only working with normal medical

### ISSUE THREAD

**Issue by xJenny99x** [acemod/ACE3#1451] opened 2015-05-31 10:52 UTC
ACE3 Version: 3.0.1
**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
//ACE 3 Medical
_module = _group createUnit ["ACE_moduleMedicalSettings", [0,0,0],[],0.5,"NONE"];
_module setVariable ["level", 2];
_module setVariable ["medicSetting", 2];
_module setVariable ["allowLitterCreation", true];
_module setVariable ["litterCleanUpDelay", 1800];
_module setVariable ["enableScreams", true];
_module setVariable ["playerDamageThreshold", 1];
_module setVariable ["AIDamageThreshold", 1];
_module setVariable ["enableUnsconsiousnessAI", 0];
_module setVariable ["preventInstaDeath", true];
_module setVariable ["bleedingCoefficient", 1];
_module setVariable ["painCoefficient", 1];
_module setVariable ["keepLocalSettingsSynced", true];

//ACE 3 Advanced Medical
_module = _group createUnit ["ACE_moduleAdvancedMedicalSettings", [0,0,0],[],0.5,"NONE"];
_module setVariable ["enableFor", 0];
_module setVariable ["enableAdvancedWounds", false];
_module setVariable ["enableVehicleCrashes", true];
_module setVariable ["medicSetting_PAK", 1];
_module setVariable ["consumeItem_PAK", 1];
_module setVariable ["useLocation_PAK", 0];
_module setVariable ["medicSetting_SurgicalKit", 1];
_module setVariable ["consumeItem_SurgicalKit", 0];
_module setVariable ["useLocation_SurgicalKit", 0];

**Description:**
Crashing a car with advanced medical makes my screen bloody and my characther wounded as it happens in vanilla Arma 3. These wounds can only be fixed by scrolling the mouse (action menu) on a medical tent ( classname "MASH" ).

<br/>

This does not however occur with the normal medical system, in which case I was able to fix myself up with just one bandage.

**Steps to reproduce:**
Using advanced medical system, crash any car into a wall, try to fix urself.

**Where did the issue occur?**
Editor and dedicated server.

**RPT log file:**
n/a

**Comment by gienkov** [comment] 2015-05-31 20:47
Duplicate of #1354

**Comment by Glowbal** [comment] 2015-06-01 17:17
Thank you for your report. This is a duplicate as @gienkov pointed out. I will close this and track all progress on #1354
.

**Closed** 2015-06-01 17:45 UTC
Labels: bug, duplicate
