### ISSUE TITLE
Recoil feedback

### ISSUE THREAD

**Issue by TwistedFromArma** [acemod/ACE3#844] opened 2015-04-24 22:03 UTC
ACE3 Version: 3.x.x

**Mods:**
- @cba_a3
- @ace3

**Placed ACE3 Modules:**
- *NONE

**Description:**
_recoil seems way too low. especailly for the bigger calibres._

**Steps to reproduce:**
- *here we have a case of the recoil making the shooting very simplified and easy. 7.62 in full auto has very low recoil. this certainly should not be the case.

even machine guns like the navid can be used with laser accuracy while standing. with minimial mouse movement. this takes the skill away.

when i am at the range i need to focus, have my cheekweld right, pull slow on the trigger, have proper sight alianment, etc. on every shot. if not the grouping goes to hell. here its shoot, have the rifle autoreturn to almost eactly the same point, and click, and repeat. already arma 3 is very easy compared to the real experience. 

**Where did the issue occur?**
*with the current ace 3 recoil.pbo enabled

**RPT log file:**
_Add a link (pastebin.com) to the client or server RPT file._Hi
- more info follows

Love the mod. cant wait for its relase.

I know i have test an unofficial version, so i am guessing that you guys havnt finished with them yet, but at the moment, the recoil seems crazy low.

ACE 2 increased vanilla recoil for the right reasons.

but here we have a case of the recoil making the shooting very simplified and easy. 7.62 in full auto has very low recoil. this certainly should not be the case.

even machine guns like the navid can be used with laser accuracy while standing. with minimial mouse movement. this takes the skill away.

when i am at the range i need to focus, have my cheekweld right, pull slow on the trigger, have proper sight alianment, etc. on every shot. if not the grouping goes to hell. here its shoot, have the rifle autoreturn to almost eactly the same point, and click, and repeat. already arma 3 is very easy compared to the real experience. 

https://www.youtube.com/watch?v=uJQok7Wm5dU

I'd really like to see ace 3 emphasising skill required in firing through the recoil. right now the current configs make it way too easy and its doing a lot of the hard work a user should be doing - aka managing the rifle a bit more and keeping it on target..

thanks for a great mod! and running it in such a community friendly way. straight to the top of everyones books.

**Comment by alganthe** [comment] 2015-04-24 22:07
please use [this form](http://ace3mod.com/wiki/user/how-to-report-an-issue.html)

**Comment by commy2** [comment] 2015-04-25 03:57
Thanks for the feedback.

I tweaked the recoil in this branch:
https://github.com/acemod/ACE3/pull/848

Compared to now it has slightly less kickback and way more rotation. Also adjusted the default values of machine guns, because BI seems to favor them for some reason (2 times less recoil in vanilla compared to other weapons).

**Comment by commy2** [comment] 2015-04-25 05:32
Also added stuff from TMR that was in AGM.

**Comment by commy2** [comment] 2015-04-26 19:00
Pull request merged. Awaiting feedback.

**Comment by alganthe** [comment] 2015-04-26 22:13
The recoil is more natural now, the barrel doesn't recenter perfectly anymore, it's in a pretty good state now in my opinion.

**Comment by ulteq** [comment] 2015-04-27 22:05
@TwistedFromArma, what do you think about the latest changes (https://github.com/acemod/ACE3/pull/848)?

**Comment by ulteq** [comment] 2015-05-11 16:50
Some of the weapons still need tweaking for my taste:

MX series -> ~5-10% more recoil
HK 121 -> ~20-30% less/different recoil
LWMMG -> ~20-30% less/different recoil

**Comment by Tachii** [comment] 2015-05-16 15:00
Well, imho weapon recoil shouldn't be that low as it's now. Here what i'm talking about:
Ace:
```
class recoil_mx: recoil_default 
{
    muzzleOuter[] = {0.06,0.2,0.4,0.3};
    kickBack[] = {0.028,0.056};
    temporary = 0.012;
};```

Vanilla:
```class recoil_mx: recoil_default
{
    muzzleOuter[]={0.30000001,1,0.40000001,0.30000001};
    kickBack[]={0.02,0.039999999};
    temporary=0.0099999998;
};```

As you can see muzzle movement up&right will be x5 less in ACE then in Vanilla. I agree that Vanilla recoil doesn't look good because it lasts long kinda, weapon movement lasts for a while, it should be less i guess, but it does it work, it makes it harder to shoot with long burst or in full-auto. So maybe it will be a good choice to keep vanilla muzzle-movement vectors as they are, but instead lower the time that movement lasts after the shot.

**Comment by Bummeri** [comment] 2015-05-18 23:15
I also feel the recoil is too easy to handle currently. Minimum effort is needed to counteract the current recoil effect and there is no real incentive to use single shot over full-auto.

The cam shake is a nice touch but as soon as you realize that it has no effect on your aim you start longing for more upwards recoil.

MGs are particularly bad right now and supporting your weapon properly is not incentivized by the current implementation.

**Comment by Heavygunner96** [comment] 2015-05-25 22:02
I agree that we need more upward recoil. Otherwise it's just to easy to control and doesn't feel realistic.
The vanilla recoil is IMO far better.

**Comment by bux578** [comment] 2015-05-26 06:45
Then again try engaging targets beyond CQC/CQB range: 300m - 400m and there's more than enough recoil even when deployed.

**Comment by esteldunedain** [comment] 2015-05-26 20:01
I also think the current implementation has too much shake and too little kickback.

**Comment by Tachii** [comment] 2015-06-30 07:51
So? Time passes and nothing changes. It makes me sad how easy ACE made recoil control.

**Comment by Tachii** [comment] 2015-06-30 16:03
Is anyone even monitoring this thread?

**Comment by esteldunedain** [comment] 2015-06-30 16:06
@Tachii, sorry, nobody is actively working on this atm.

**Comment by Tachii** [comment] 2015-06-30 16:07
@esteldunedain too sad :(

**Comment by Mike-MF** [comment] 2023-09-11 00:24
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Closed by Mike-MF** 2023-09-11 00:24 UTC
Labels: status/discussion
