### ISSUE TITLE
ACE 3 - Personal Aid Kit (PAK) Not listed during treatment

### ISSUE THREAD

**Issue by ender2078** [acemod/ACE3#3478] opened 2016-02-29 22:05 UTC
**Arma 3 Version:** `1.56`
*(Stable)

**ACE3 Version:** `3.4.2`
*(Stable)*

**Mods:**
* `@CBA_A3`
* `@ace`
* ...

**Placed Modules:**
* *ACE-Medical Settings, ACE-Set Medic Class, ACE-Advanced Medical Settings*

**Description:**
* *Another editor and myself spent 10+ hours troubleshooting an issue where PAK was not available as a treatment option in advanced medical, even the surgical kit was available if allowed in the module. Checking with other players using the same mods and versions, they informed that they were not having the issue. We even tried reverting to previous version of ACE3 and CBA, and a combo of each. Finally it was determined through trial and error that the issue lies in the 3D editor when placing the modules, as another similar issue reported on here said regarding some advanced medical settings, it does not appear that it is correctly writing some of the adv. medical settings into the mission SQM while using the 3D editor. In this case it appears that the PAK settings were not correctly being written. Once we switched to the 2D editor the problem was immediately resolved and PAK was available again. *

**Steps to reproduce:**
* *Place down the necessary modules/systems in the 3d editor, allow advanced medical, set your medic class to "B_medic_F" and place down a NATO Combat Life Saver as player, and another unit (any) as AI, allow the settings to apply to both Players and AI, allow PAK use to anyone/anywhere (or assign to the medic only), preview the mission, spawn in a PAK and attempt to use PAK on the AI player.*

**Where did the issue occur?**
* *Dedicated Server and Single Player Preview Mode"*

**RPT log file:**
* *http://pastebin.com/3vJnePJ5)*

**Comment by esteldunedain** [comment] 2016-02-29 22:14
Hey, this is a duplicate of this: https://github.com/acemod/ACE3/issues/3339

I'm sorry you've wasted your time debugging this. We'll be releasing ACE 3.5.0 with a hack to minimize the problem, but until BIS fix eden modules will not be 100% compatible.

**Closed by esteldunedain** 2016-02-29 22:14 UTC

**Comment by ender2078** [comment] 2016-02-29 22:17
Hey nice fast response, but crap!!! I wish I would have found this post!! Would've saved me a ton of time lol.... for future reference is there a good method to search these kind of things? A friend and I went through this page for hours and never saw the one you referenced. Thanks again and sorry to repost!

**Comment by ender2078** [comment] 2016-02-29 22:19
Also while ive got you here, Ive read through that same issue on the referenced link you sent, but is there a recommended work around at this point in time? I dont want to have to rebuild all my 3d edtior missions on 2d if i dont have to. Thanks again!

**Comment by esteldunedain** [comment] 2016-02-29 22:21
>  is there a good method to search these kind of things?

No, not really (which is unfortunate).

> Also while ive got you here, Ive read through that same issue on the referenced link you sent, but is there a recommended work around at this point in time?

Not atm. ACE 3.5 will release soon with a band aid to minimize the problem. Be aware that other things are broken in eden, including headless clients. Some of the things are already fixed on the dev version of Arma, so hopefully they'll release a patch soon.

**Comment by esteldunedain** [comment] 2016-02-29 22:22
Oh, forgot to mention: you can set settings in the desciption.ext file instead of using modules, and that should work perfectly.

**Comment by ender2078** [comment] 2016-02-29 22:41
Awesome @esteldunedain  you have been extremely responsive and helpful! Yeah I think I'll take other peoples advice and stay away from Eden for now.... as far as writing the settings in the description.ext file, is there a post written by ACE somewhere around here that shows how to do that? I will attempt to search and see what I can find, but if you know anything off the top of your head, that would be very helpful. Thanks again and thanks for providing this mod to us, we LOVE it!!

**Comment by ender2078** [comment] 2016-02-29 22:52
Disregard my question (unless this is incorrect) but I think this is probably where you would refer me: http://ace3mod.com/wiki/framework/settings-framework.html#changing-acesettings-dynamically-with-mission-parameters

**Comment by esteldunedain** [comment] 2016-02-29 23:04
Yeah, this is how I recommend you do it:

1- Start the 2D editor. 
2- Place all the modules you want with their desired settings
3- Run the mission
4- Export the settings to the clipboard using the instruction on section 3.1 of that link
5- On your missions, open the `description.ext` file and paste:

```
class ACE_Setting {
    // Paste the content of the clipboard here
};
```

**Comment by ender2078** [comment] 2016-02-29 23:06
thank you!! and just to confirm, this will work in an MPMission/Server Environment?

**Comment by esteldunedain** [comment] 2016-02-29 23:14
> this will work in an MPMission/Server Environment?

Yes. Doing this you can delete all the modules from your 3den missions and still enjoy whatever settings you chose.

**Comment by ender2078** [comment] 2016-02-29 23:15
Can I give you a kiss? You've made our Combat Medics very happy, hahahaha. Thanks again man, you've been a great help.

**Comment by esteldunedain** [comment] 2016-02-29 23:17
> Can I give you a kiss?

Luckily that's not how the internet works.

**Comment by ender2078** [comment] 2016-02-29 23:17
hahahahaha

**Comment by ender2078** [comment] 2016-03-01 03:03
I have tried this both as a description.ext and a serverconfig.hpp and it still will not reflect the 2D editor created advanced medical parameters. Not sure what is going on, the advanced ballistics work, and the settings work in single player, but not when uploaded to a server. Not sure what to do at this point.

**Comment by esteldunedain** [comment] 2016-03-01 03:05
1- Did you remove all the modules?
2- Does the server have the userconfig file?

**Comment by ender2078** [comment] 2016-03-01 03:06
yes, like i said i removed all the modules from the mission, and i can tell its getting info from server config because things like advanced ballistics (by checking weapon temp) are working.

**Comment by esteldunedain** [comment] 2016-03-01 03:07
Did you create the mission in the 2d editor from scratch or imported something saved in the 3d editor first?

**Comment by ender2078** [comment] 2016-03-01 03:10
It was something saved in the 3d editor, but i removed the modules....  i was hoping to avoid having to rebuild an entire mission, hence my reason for using the export feature.

**Comment by esteldunedain** [comment] 2016-03-01 03:12
> It was something saved in the 3d editor, but i removed the modules....

That should be enough, I'm not sure what's the problem. Please make 100% sure the mission that you're loading in the server doesn't have an extre medical module still lying around.

**Comment by ender2078** [comment] 2016-03-01 03:14
I just doublechecked that while waiting for your reply. Just to confirm the serverconfig.hpp goes into the "userconfig" in the root Arma 3 folder and enable the ace_server.pbo mod via @aceServer correct? Here is a link to the paste bin of the config if you would like to see 

http://pastebin.com/CCKPqUkU

**Comment by esteldunedain** [comment] 2016-03-01 03:15
That config is wrong. It should not contain `class ACE_Setting {` at the beggining nor the final `};` at the end. Those things ARE required when the settings are placen on `description.ext` though

**Comment by ender2078** [comment] 2016-03-01 03:16
ok i tried in the description.ext with no such luck either. let me just copy this over to a description.ext and see if the server likes that, standby.

**Comment by esteldunedain** [comment] 2016-03-01 03:17
Besides you should remove the 5 first lines that are only an example

**Comment by esteldunedain** [comment] 2016-03-01 03:18
While you're at it, paste the entire content of your description file on pastebin

**Comment by ender2078** [comment] 2016-03-01 03:19
ok, going back to a description.ext file and here is the paste

http://pastebin.com/z0tC8fqR

**Comment by esteldunedain** [comment] 2016-03-01 03:20
that looks good.

**Comment by ender2078** [comment] 2016-03-01 03:21
ok going to join server in just a moment.

**Comment by ender2078** [comment] 2016-03-01 03:21
you dont need the set medic class module still on the map correct? that is also reflected in the export?

**Comment by esteldunedain** [comment] 2016-03-01 03:22
you don't need any module on the mission

**Comment by ender2078** [comment] 2016-03-01 03:22
ok and i confirmed there arent any on the map

**Comment by ender2078** [comment] 2016-03-01 03:25
Still not working, thought the advanced ballistics module is working correctly because weapon temp is showing, medical menu, etc. But only have basic medic options. Epi, Morphine, Bloodbag, bandage.

**Comment by esteldunedain** [comment] 2016-03-01 03:26
do you have a console on the mission?

Get the value of this variable please `ace_medical_level`

**Comment by ender2078** [comment] 2016-03-01 03:28
ill have to add that on my ext file, give me a couple minutes to do that

**Comment by esteldunedain** [comment] 2016-03-01 03:33
I really need to get some sleep. I recommend you join us in the Slack chat tomorrow and we'll help you figure it out. Ask for an invite to Slack here: http://slackin.ace3mod.com/

**Comment by ender2078** [comment] 2016-03-01 03:34
no worries man just booting it up now, one last thing, can we manually change the ace_medica_level number to a diff value somewhere?

**Comment by ender2078** [comment] 2016-03-01 03:36
Value is 1 it shows, i just type it in "watch" as you typed it i assume, but the value shows 1

**Comment by Glowbal** [comment] 2016-03-01 10:35
You have ` ACE_Setting`. It should be: `ACE_Settings`.

Note; in the server config you do not wrap your settings in the `ACE_Settings` class.

**Comment by ender2078** [comment] 2016-03-02 01:21
Thanks for catching this Thomas. That is weird that it left the "S" off.
Not sure how that would happen as I copied everything exact?  Anyhow we
ended up getting it working with using another members export. Thanks guys

**Comment by esteldunedain** [comment] 2016-03-02 01:29
Sorry, it was my fault. I mispelled it above when I listed the instructions. I've now edited in case somebody else stumbles by this thread.

**Comment by ender2078** [comment] 2016-03-02 01:43
Lol you've ruiiiined meeeee. Jk it's all good!!
