### ISSUE TITLE
No Entry Errors

### ISSUE THREAD

**Issue by Gurkengewuerz** [acemod/ACE3#3822] opened 2016-05-24 22:27 UTC
**Arma 3 Version:** `1.58.135742` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Many "No Entry" Errors

**Where did the issue occur?**
- Dedicated - !!! ALTIS LIFE !!!

**Placed Modules:**
- Medical Settings [ACE]
- Advanced Medical Settings [ACE]
- Interaction System
- Name Tags
- Sitting

**RPT log file:**
- Client RPT https://gist.github.com/Gurkengewuerz/72ad948d611a3113e6aeb9db74eeaca7
- serverconfig.hpp https://gist.github.com/Gurkengewuerz/9e3e0c92b04077e803ea506a2297ab00
- ACE Debug: https://gist.github.com/Gurkengewuerz/a0285479c5d727fd3ac305d4654a6138

**Comment by commy2** [comment] 2016-05-25 00:29
Hello,

you said you only enabled CBA and ACE, but your RPT fragment shows that at least CUP was used too.

- can you please upload a full RPT file?

- please start a game in the editor and enter the following into the debug console:

```

_m = configFile >> "default";
_v = configFile >> "CfgVehicles" >> "default";

_r = [_m, _v] apply {[configName _x, _x, configSourceModList _x]};

copyToClipboard str _r;
systemChat str _r;
diag_log _r;

```

Then press "LOCAL EXEC". You will see a piece of code in the chat that will also be in your clipboard. Paste it here. Thanks!

**Comment by Gurkengewuerz** [comment] 2016-05-25 13:51
Sorry, I forgot to edit the mod section. There are a couple of mods wich we use (ModPack), i hope you can read them from the RPT file. If you need a detailed version i can create a better list. 

The output from the debug console is the following:
`[["Default",bin\config.bin/Default,[]],["",,""]]`

Full RPT file: https://gist.github.com/Gurkengewuerz/b2607e9211783f52f41a1dae1d27fcaf

The "No Entry" error appear after the loading from the mission.

**Comment by commy2** [comment] 2016-05-25 15:29
Thank you for that report.

You are using an addon that adds a base class or entry called "Default". This triggers a bug in the BI module framework that has been around since Arma 2. Any module - __even those not from ACE__ - will cause the same error message.

Solution is to remove the faulty addon.

Unfortunately my debug code couldn't find the faulty addon. You'll have to remove addon by addon and always check with my debug code.

Expected result is:
`[["",,""],["",,""]]`
which is what you will get with vanilla and CBA + ACE.

Please report back if you find that addon. It would potentially help solving this problem for others and we could contact that mods author.

duplicate of:
https://github.com/KoffeinFlummi/AGM/issues/480
https://github.com/KoffeinFlummi/AGM/issues/481
https://github.com/KoffeinFlummi/AGM/issues/620

**Comment by Gurkengewuerz** [comment] 2016-05-26 21:31
We will check the addons. I think it is the same as there: 
> Problem was produced by "Female 0.1 (Alpha / Modders Resource) by Icewindo", now everything is fine. I don't even know why this addon is in our clan pack lol. Thanks 
- https://github.com/KoffeinFlummi/AGM/issues/480#issuecomment-49224112

I keep you up to date!

**Comment by Gurkengewuerz** [comment] 2016-05-29 00:23
So, we've tested it and the problem was the "ice_a3_woman.pbo". 
Issue can be closed.

**Closed** 2016-05-29 00:23 UTC
Labels: BIS' fault, duplicate
