### ISSUE TITLE
Issues of Mines/Explosive Installation

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2487] opened 2015-09-17 14:21 UTC
ACE3 Version: 3.3.1
Stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
None

**Description:**
I've noticed a few problems with minelaying:

1. During the mine installation on the ground the Mine falls to the ground and flipped. Please note this. The soldier can't throw a mine on the ground! At least it looks strange. I think need a special animation within several sec, with manipulation hands on the ground level.

2. During the activation of mines (which is already lying on the ground) mine itself unfolds in an unpredictable direction. Thus, the directional mines (Claymore, SLAM) cannot be installed in a given direction, because during installation do not take into account the curent azimuth of the player.

3. If you try to dismantle a mine via interaction-menu, it will explode and kill the player.

4. There is no way to order the subordinate AI, to instal/blow up the mine. Or at best I didn't find such method. Strange...

**Steps to reproduce:**
Deploy in the editor player as explosive specialist with subordinates (also explosive specialist)
Try all manipulations with mines.

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by bux578** [comment] 2015-09-17 14:26
> If you try to dismantle a mine via interaction-menu, it will explode and kill the player.

SLAM Mines have an anti-tamper protection. That is why they just explode. Only solution is to use a counter charge.

**Comment by alganthe** [comment] 2015-09-17 14:59
It's an option in the explosives module, make sure to disable it.
And you're very unlucky since the chance that happens is very low.

**Comment by mickeymen** [comment] 2015-09-17 15:08
@alganthe What are you talking about? What module? Please explain

**Comment by alganthe** [comment] 2015-09-17 15:12
this ![explosives](http://puu.sh/keuIw/a7529ddd58.png)

**Comment by mickeymen** [comment] 2015-09-17 15:29
thanks, I'll try to deal with it

**Comment by mickeymen** [comment] 2015-09-17 16:50
I've noticed that my second paragraph now works correctly ( in version 3.3.1 )
Probably this has been fixed in this latest update!

**Comment by commy2** [comment] 2015-09-17 17:38
Yeah 3.3.0 was completely broken, due to a bug in the event system.

**Comment by SilentSpike** [comment] 2015-09-17 17:42
Not sure if it was due to settings or the code, but it was fixed anyway so closed :smile:

**Comment by mickeymen** [comment] 2015-09-17 17:54
closed... however, 1 and 4 item not resolved, remains

**Comment by SilentSpike** [comment] 2015-09-17 18:10
In that case

**Comment by mickeymen** [comment] 2015-09-17 19:04
I think item 1, is a not serious cosmetic problem, but better that after the installation to earth to mine were not moving. I hope you understand that it is not realistic. And how in ACE to order subordinate AI(explosive-specialist) to set/detonate mine? ( item 4)

**Comment by commy2** [comment] 2015-09-26 19:17
For point four:
duplicate of #57

**Closed** 2015-12-12 17:14 UTC
