### ISSUE TITLE
Cook off Compatibility. 

### ISSUE THREAD

**Issue by Pironesis** [acemod/ACE3#5102] opened 2017-04-23 14:02 UTC
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.2.1` (stable)
**ACE3 Version:** `3.9.1` (stable )

**Mods:**
- CBA_A3
- ace
- RHS

**Description:**

I apologize if my description here falls beyond the scope of ACE, i did inquire on the BI forums but found no response so i am posting here. 

My community has noticed inconsistencies that often leads to issues with the cook off system being applied to RHS vehicles. I was hesitant to report this here, as i don't know if this would fall into the compatibility that you provide with RHS or if it would be an  issue that RHS themselves need to solve. 

When using launchers on RHS vehicles, we run into circumstances where they do not explode or cook off. They clearly reach the damage threshold in which they should cook off, but they do not. They often, but not always have damaged systems but they will remain at a damage value of 0.89 and often will not explode or will take far more rockets than it should in order to destroy them. We have noticed this to a lesser degree with vehicles such as tanks firing on one another, but it is most noticeable with launchers. We will fire an AT-4 at a BTR and it will just tank it, which should not happen. Overall we notice that with the cook off system, RHS vehicles seem to be able to absorb more damage than they should.

I suppose my question is, do you think this is an issue between the RHS vehicles and the damage handlers set up by the cook off system that are not playing nice with one another? Obviously you provide a low level of compatibility between yourself and RHS, but depending on what the issue is i don't know if it is within your scope to provide this kind of compatibility.

**Steps to reproduce:**
- Using RHS Launcher fire at a variety of RHS vehicles. 
- Reproduction in the editor is difficult and unreliable.  
- Reproduction on  dedicated server, (at least in our experience) is more common.

**Where did the issue occur?**
- Dedicated  /  Editor (Singleplayer) / 

_edited broken markdown formatting ~commy_

**Comment by Twelvecaliber** [comment] 2017-05-26 18:02
RHS launchers on vanilla vics appear to be fine.

**Comment by Phyma** [comment] 2017-05-26 22:16
Could replicate with SMAW on BTR-70in the side. 4/4 got 0.89 damage but only 1/4 cooked off.
But Engine damage was 0 or almost like 0.04.
When they got hit again they all exploded.

If this isnt how you see it then please add more info.
What launcher?
What vehicle?
Where on the vehicle did you hit?
How far away where you?
How many times did you shoot it until it popped?

Run following and give data. Ofc vehicleName is the name of the vehicle like bob.
```
vehicleName getHitPointDamage "HitEngine";
damage vehicleName;
vehicleName getVariable ["ace_cookoff_isCookingOff", false];
```

Thank you!

**Comment by Twelvecaliber** [comment] 2017-05-27 11:44
M136 (Heat)
BTR-70
Front, left side, left side of turret.
100m
3

Shot 1:
0
0.89
false

Shot 2:
0
0.89
false

Shot 3:
0
0.89
true
============
M136 (Heat)
BMP - 2
Front, left side
100m
2

Shot 1:
1
0
false

Shot 2:
1
0
true
==========
RPG-26
BTR-80A
Front,left,front,left,right,rear,turret
100m
7

Shot 1:
0
0
false

Shot 2:
0.637382
0
false

Shot 3:
0.637382
0
false

Shot 4:
0.637382
0
false

Shot 5:
0.637382
0
false

Shot 6:
0.637382
0
false

Shot 7: (M136 HEAT, I ran out of RPG's at this point)
0.224468
0.89
true
==========
These were just the highlights of what i tested. In general it would seem that cookoff kicks in when the engine damage value hits a threshold, though not consistently. The strangest behavior of all was the RPG-26.

**Comment by Phyma** [comment] 2017-05-27 14:44
Okey have been testing alot now and cant say this is really a bug. The RHS tanks have mutch higher resistance than most of the vanilla tanks. MBT have resistance of 0.00547 and BTR-70 have resistance of: 0.018849.

And then if you dont hit hull, fuel, engine, ammolocation, turret or structural then the damage will just get put on the vehicle it self and not cookOff. If you hit a ammolocation then you need to get past this: 
` if (_damage > 0.5 && {random 1 < 0.7}) `
If that is true then it will cookoff. 

But yeah more resistance could be the reason that RHS vehicles dosent cookOff as mutch.

**Comment by Twelvecaliber** [comment] 2017-05-27 15:59
The problem with this is, in practice this causes gameplay issues. The vics having more resistance is fine, however in the cases where a sub section is not being damage and so the damage is just put on the vehicle it'self and we see the damage hang at 0.89, the crew will still be alive and do **_not_** bail out and the vic is apparently still fully functional and ends up sitting there murdering us as we pump rocket after rocket into it.

I'm not sure if there is anything that can be done. But this behavior doesn't seem right in practice. I agree with the breakdown of how the system works, and that if you hit things like the engine, or an ammo location then that should have a chance to cook off, but on some vehicles hitting those ends up being more down to chance than the skill of the shooter. 

Ideally if there was a way of better handling when that 0.89 threshold is hit, that would be ideal. If that is out of scope for the moment, then for our specific circumstances we will probably just disable cook off all together. Either way i do appreciate the insight into how the system works, and thank you for your time investigating.

**Comment by Phyma** [comment] 2017-05-27 17:26
#5212
Possible fix, devs need to check this to see if its proper behaviour but if this get in there, you will see more insta explosions and some occasions of cook off. But I'm not part of dev team so it might get denied.

**Comment by Mike-MF** [comment] 2023-09-11 00:41
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Closed by Mike-MF** 2023-09-11 00:41 UTC
