### ISSUE TITLE
Suggestion: More settings/customizability

### ISSUE THREAD

**Issue by Tennessee-Timmy** [acemod/ACE3#5850] opened 2017-12-04 04:37 UTC
Stuff like dispersion, jam rate, custom aim coef. could have a simple variable to change them per person. 

More features should be customizable similar to bleeding and pain coef. in the medical modules (per unit, defaults to global variable, defaults to setting/default value).

This would not impact 90% of the people, but would allow for the 10% to do some more advanced tweaking, for example simulating a poorer/less trained army, by setting dispersion and aim coef. to worse settings only for those players without a hustle and keeping it scenario specific.

**Comment by dedmen** [comment] 2018-11-18 13:16
Kind of duplicate of #5725 ?

**Comment by jonpas** [comment] 2018-11-18 16:00
Closed in favour of the other one - issues "merged".

**Closed by jonpas** 2018-11-18 16:00 UTC
Labels: kind/feature request
