### ISSUE TITLE
Kestrel 4500NV closes on its own when using "Show Kestrel"

### ISSUE THREAD

**Issue by Pipulci** [acemod/ACE3#9011] opened 2022-08-25 14:13 UTC
**Mods:**
- **Arma 3:** 2.10 Stable
- **CBA:** v3.15.7.220517
- **ACE3:** 3.15.0

**Description:**
When using the "Show kestrrel option", the device only shows for a second, then disappears from the screen.
It used to stay on screen until toggled off, allowing the user to turn around and face the wind, or open other devices at the same time (like the AtragMX).

"Open Kestrel" seems to work normally, but does not allow free movement with the device open (the option is meant for a different use anyway).

**Steps to reproduce:**

1. _ACE Self-Interact
2. _Select Equipment
3. _Hover on "Open Kestrel 4500" until another option shows up
4. _Hover on "Show kestrel 4500", release
5. The Kestrel device shows on the left side of the screen for a second, then disappears
6. Alternatively, use any key bound to "ACE Equipment/Show Kestrel 4500"

**Expected behavior:**
Normally, the Kestrel opens up on the left side of the screen and stays open until closed.

**Where did the issue occur?**
ACE Arsenal - Editor - Single Player mission - Multiplayer server

**Log Files:**
N/A

**Additional context:**
The Show Kestrel option is pretty important to long-range shooters, as it allows for quick estimates of the wind.
It also provides essential atmospheric information for the AtragMX, which has to be entered manually. Hence, keeping it open and having freedom to move is a nice QoL feature that allows the user to open both devices at the same time.

**Screenshots:**
N/A

**Comment by veteran29** [comment] 2022-08-25 15:16
Duplicate of #8954

**Closed by veteran29** 2022-08-25 15:16 UTC
Labels: kind/bug, status/duplicate
