### ISSUE TITLE
ace_medical_feedback_painEffectType "1" [Recurring blur effect] its not really works

### ISSUE THREAD

**Issue by Sheppard85oc** [acemod/ACE3#7828] opened 2020-07-31 02:06 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98
- **CBA:** `3.15.1
- **ACE3:** `3.13.3` 
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
I used under ace_medical_feedback_painEffectType the "1"  "Recurring blur" in German called "Wiederkehrede Unschärfe" and this Effect looks like its dont work perfecktly i just see this only if i got strong pain its work then (maybe) 1 or 4 Times and if i still have this its gone and comes not more back  the other effects have more working but that one its not really...i am not sure that its a Error, or another players have the same but i think that effect have a error. the other both works much better and with all typs of pains. 

**Steps to reproduce:**
1. Go to Arma
2. Go MP or Editor
3. do someting that you have Strong Painfuls with that effect type

**Expected behavior:**
I have thing the Effect should be so used like the other ones, e.g. that u see that effect if u have Light and medium pains that you see it a bit more and basically what the name of this effect promises, recurring pain effects with the corresponding grand amount of delights

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

MP and in Editor

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**
None
**Screenshots:**
None

**Comment by LinkIsGrim** [comment] 2023-10-24 22:23
Can't reproduce. Likely fixed in 3.14.0 if it was ever an actual ace issue.

**Closed by LinkIsGrim** 2023-10-24 22:23 UTC
Labels: kind/bug
