### ISSUE TITLE
Attachments turn off when switching firemode

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#3706] opened 2016-04-19 20:54 UTC
**Arma 3 Version:** `1.56` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Attachments turn off when switching firemode. Not gonna lie, I'm not sure if there's a command to detect if the attachment is activated.

**Steps to reproduce:**
- Take a weapon.
- Attach flashlight.
- Enable flashlight.
- Bind a primary weapon to a key (ACE weaponselect system).
- Press primary weapon key.
- Weapon switches firemode but the attachment turns off.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**Comment by commy2** [comment] 2016-04-19 23:45
Duplicate of https://github.com/acemod/ACE3/issues/210

**Closed by commy2** 2016-04-19 23:45 UTC
Labels: bug
