### ISSUE TITLE
Player Stays in the Unconscious Animation even while conscious 

### ISSUE THREAD

**Issue by cranki208** [acemod/ACE3#8076] opened 2021-01-20 23:41 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** Stable Version
- **CBA:** `3.15.1 Stable
- **ACE3:** `3.15.1` Stable

**Description:**
Please Note :  The issue is not consistently replicat-able, but deemed it worth reporting.

While playing, and players get shot and go unconscious, once healed back up on occasion, Player models stay in the unconscious state however can still move and shoot as normal. This means that to anyone looking at the previously unconscious player, the still appear as down. 

Rough Steps to Replicate are below.
**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1.  Load a missing with Ace, CBA and Advanced Medical Enabled.
2. While in a mission, have a player (player A)shot enough for them to go down.
3. Have a different player heal them back to health(Stitched and normal vitals)
4. Player A appears up and can talk, shoot etc but still has the 'Unconscious' animation

This can sometimes be fixed by : In zues making the player unconscious again and concious OR by being shot and downed again then healed.

**Expected behavior:**
Player animation should return to 'Conscious' State

**Where did the issue occur?**
- Dedicated  Server

**Comment by Zycorge** [comment] 2021-02-18 06:42
I was able to semi-consistently replicate this. It seems to only occur when a player gets knocked into an unconscious state, ragdolls, and then doesn't enter an unconscious animation but instead stays in the ragdoll state. Seems to also prevent dragging and carrying consistently with a return to the teleporting into the ocean and falling through the map bug.

**Comment by tbeswick96** [comment] 2021-02-27 11:42
Duplicate of #7893

**Closed** 2021-04-17 04:46 UTC
Labels: kind/bug, status/duplicate
