### ISSUE TITLE
ACE Compat - RHS Armed Forces of the Russian Federation causes data errors in RPK-74M

### ISSUE THREAD

**Issue by M829A3** [acemod/ACE3#8236] opened 2021-04-28 15:05 UTC
**Mods (complete and add to the following information):**
- **Arma 3: '2.04 stable' [e.g. 1.00 stable, rc,  dev]
- **CBA:** ` 3.15.3.210310` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.13.6` [eg. 3.0.0 stable, commit hash]

**Description:**
RHSAFRF RPK-74M using PKM's data when installed ACE Compat - RHS Armed Forces of the Russian Federation

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. _Go to Virtual Arsenal
2. _Choose RPK-74M
3. _See it is using PKM's ammo, sound and animation

**Expected behavior:**
RPK-74M use 5.45 magazine and correct animation

**Where did the issue occur?**
- Dedicated & Self-Hosted Multiplayer & Singleplayer & Editor (Singleplayer) & Editor (Multiplayer) & Virtual Arsenal

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**

**Screenshots:**
![107410_20210421152546_1](https://user-images.githubusercontent.com/79445049/116426786-fdf0f880-a875-11eb-9323-17ba8418d863.png)

**Comment by Drofseh** [comment] 2021-04-28 17:04
duplicate of #8221 fixed in #8223

**Closed** 2021-04-28 18:31 UTC
Labels: kind/bug, status/duplicate
