### ISSUE TITLE
Interaction under water

### ISSUE THREAD

**Issue by OnkelDisMaster** [acemod/ACE3#880] opened 2015-04-27 13:15 UTC
**Mods:**
* CBA
* ACE3

**Placed ACE3 Modules:**
None

**Description:**
Not sure if this has been stated before, but it would be nice to be able to interact under water. We did a diving mission, noticing that you cant treat yourself underwater, nor defusing or planting bombs or mines.

**Steps to reproduce:**
Go diving!

**Where did the issue occur?**
MP on dedicated Server

**Comment by alganthe** [comment] 2015-04-27 13:36
isn't that normal ?

**Comment by headedhorseman101** [comment] 2015-04-27 14:01
*alganthe said:*
> isn't that normal ?

It is implemented in vanilla arma, but I agree with OnkelDisMaster. In my opinion, a good way to implement this is to find a way to restrict what is usable underwater (for instance, having the option to use just demo blocks and satchel charges , but disable the placement types of landmines or IV interaction while underwater).

**Comment by OnkelDisMaster** [comment] 2015-04-27 14:10
The funny thing is, that if you swim to the surface, you can actually do all that stuff...while still swimming.

**Comment by alganthe** [comment] 2015-04-27 14:14
not implemented then.

**Comment by headedhorseman101** [comment] 2015-04-27 14:46
I was refering to being below the surface, but that is an interesting bug. The BI function must not try to detect the animation. My guess is that it most likely detects elevation above sea level (whether the player unit is above sea level) or whether the head is underwater.

**Comment by commy2** [comment] 2015-04-27 19:53
ODM, you are banned from reporting issues until you post the RPT-files for https://github.com/acemod/ACE3/issues/871

**Comment by jaynus** [comment] 2015-04-28 07:44
This is most likely ASL/ATL translation issues

**Comment by commy2** [comment] 2015-04-28 10:43
No. It's by design. Treating yourself underwater is just stupid.
Maybe we could add something about exlosives, but I'm not sure it makes much sense.

**Comment by headedhorseman101** [comment] 2015-04-28 12:49
*commy2 said:*
>Maybe we could add something about explosives, but I'm not sure it makes much sense.
It wouldn't be practical in vanilla arma because of the limitations of where you can place explosives, but with the ability to place explosives on vehicles and static objects/structures it now makes underwater demollitions a viable option (just as a few examples, small special ops groups or servers with ACE mandated (if those start appearing like they did in ArmA 2 OA)).

**Comment by BryanBoru** [comment] 2015-04-28 14:47
I agree that treating a wound underwater is just dumb. (pretty sure water proof gauze would be pointless)
However, we have a section of members in my unit dying to have water ops with SCUBA now available, but have been significantly limited to just recon due to the current lack of functions of ARMA3 with water bound demo and arms.

**Comment by OnkelDisMaster** [comment] 2015-04-28 14:56
Well treatment would be possible... You can apply a tourniquet in every situation, to at least stunt bleeding. That would help to not bleed to death under water even if it is not properly treated until you reached the surface etc.

**Comment by Jastreb** [comment] 2015-04-29 05:21
Bandaging would theoretically be possible under water, but less effective. Also in deeper water you will bleed slower because of the pressure, but once your body customizes to this pressure you will bleed again at normal rate if not treated. While it may be desirable option to have, I think it more of a backlog-to-do thing if ever.

Other than that explosives would be nice. Sticky to boats an such but other than that, nothing.

**Comment by BryanBoru** [comment] 2015-04-29 15:24
good point with the tourniquet @OnkelDisMaster. I have to be honest, I feel the explosives to water vehicles is a feature  more desired than any self-care in my opinion.

**Comment by jaynus** [comment] 2015-04-30 20:27
@esteldunedain This could be added by creating an extra allowance bool field for allowable underwater, and have it default false for everything. In the future we could then allow.

**Comment by esteldunedain** [comment] 2015-04-30 20:35
> @esteldunedain This could be added by creating an extra allowance bool field for allowable underwater, and have it default false for everything. In the future we could then allow.

That functionality is already in on ACE3: whatever action we want to be performable underwater should have the `"isNotSwimming"` exception added. Actions without that exception are already forbidden underwater.

**Comment by commy2** [comment] 2015-04-30 20:35
^ Was about to say that.

Although you have to check if the animations still work etc.

**Comment by commy2** [comment] 2015-04-30 20:36
Technically it should be called "isNotDiving", but whatever.

**Comment by CorruptedHeart** [comment] 2015-06-19 09:55
Closed via https://github.com/acemod/ACE3/pull/1688

**Closed by CorruptedHeart** 2015-06-19 09:55 UTC
Labels: feature request

**Comment by Tyrert** [comment] 2015-11-03 08:07
Yesterday I tried to play the second showcase mission (SCUBA diving) with ACE enabled, and I encountered this problem. I had to close the game, disable ACE and restart the mission.

It would be nice if ACE was better integrated with the single player stuff, for those of us who like to play on our own. For example, in the short bootcamp tutorial campaign, in a given moment you have to heal an injured NPC. You can't do this with ACE either, as it only works with the original medkit. Once again you have to disable ACE and start from scratch.

**Comment by commy2** [comment] 2015-11-04 09:34
Please don't revive months old, closed and unrelated issues for your problems.

**Comment by Tyrert** [comment] 2015-11-06 19:01
It may be 5 months old, and closed, but how can it be unrelated? It's the exact same issue the OP had... I played the game 3 days ago with the latest ACE and I wasn't able to defuse underwater mines.

**Comment by headedhorseman101** [comment] 2015-11-06 19:20
@commy2 @Tyrert does have a valid point. Divers are trained to disarm or do controlled detonations irl, plus it would add to gameplay.

**Comment by esteldunedain** [comment] 2015-11-06 19:24
@Tyrert, @headedhorseman101, single player missions not designed for ACE are not supported. Those missions were not programmed so the mines could be disabled, even if they could be IRL. It has nothing to do with this ticket (which was a bug preventing any interaction underwater) and hence it's unrelated as @commy2 said.

**Comment by Tyrert** [comment] 2015-11-06 19:33
"Those missions were not programmed so the mines could be disabled, even if they could be IRL"

Actually, the objective of the mission is to disable those 3 mines (among other things), so your character is a demolitions expert + diver, with a defusal kit. With ACE disabled, the mission can be completed OK.

"single player missions not designed for ACE are not supported."

It's an official BI mission. Does that mean that I won't be able to play the SP campaigns with ACE enabled? Because I would like to.

" It has nothing to do with this ticket (which was a bug preventing any interaction underwater)"

The OP said "We did a diving mission, noticing that you cant treat yourself underwater, nor defusing or planting bombs or mines" and that made me think that my comment would belong here. Actually I thought I would be berated if I opened a new ticket, but it seems I got berated anyway...

**Comment by esteldunedain** [comment] 2015-11-06 20:03
> Actually, the objective of the mission is to disable those 3 mines

Rigth, my mistake. I meant not defused with the ACE system.

> Does that mean that I won't be able to play the SP campaigns with ACE enabled? Because I would like to.

No, sadly that's not 100% possible. Most thing work alright, but a few game breaker problems exist. It's not feasable to fix them without modifying the missions themselves. Missions require some extra coding to support ACE fully.

> but it seems I got berated anyway...

Yeah sorry, it was not the intention; it's just that it's really not the same bug.
