### ISSUE TITLE
Action interrupted if selected with cursor

### ISSUE THREAD

**Issue by Krzmbrzl** [acemod/ACE3#2661] opened 2015-10-01 12:04 UTC
ACE version 3.3.2

Mods:
ace
CBA_A3

Modules:
None

Description:
I activated the cursor-selection for the self-interaction menu, but when I start an action (e.g. bandaging myself or opening any dialog) and then release left-ctrl and left windows button the action gets stopped / The dialog gets closed almost every time. If there is a delay between clicking on the action and releasing the keys there is a chance that this effect won't show but most of the time it does.

Occurance:
MP and Editor

RPT log:
~~~~~~~~~ACE Debug~~~~~~~~~
time = 103.803

------Performance------
diag_fps = 39.4089
count ace_common_waitAndExecArray = 0
count cba_common_perFrameHandlerArray = 28 (max 28)
count diag_activeSQFScripts = 8
count diag_activeSQSScripts = 0
count diag_activeMissionFSMs = 0

------Player------
typeOf = B_Soldier_F
animationState = amovpknlmstpsraswrfldnon

------ACE Settings------
ace_common_forceAllSettings - false
ace_common_checkPBOsAction - 0
ace_common_checkPBOsCheckAll - false
ace_common_checkPBOsWhitelist - []
ace_common_settingFeedbackIcons - 1
ace_common_SettingProgressBarLocation - 0
ace_common_displayTextColor - [0,0,0,0.1]
ace_common_displayTextFontColor - [1,1,1,1]
ace_finger_enabled - false
ace_finger_maxRange - 4
ace_finger_indicatorForSelf - true
ace_finger_indicatorColor - [0.83,0.68,0.21,0.75]
ace_frag_Enabled - true
ace_frag_SpallEnabled - false
ace_frag_maxTrack - 500
ace_frag_MaxTrackPerFrame - 50
ace_frag_EnableDebugTrace - false
ace_goggles_showInThirdPerson - false
ace_hitreactions_minDamageToTrigger - 0.1
ace_interact_menu_AlwaysUseCursorSelfInteraction - true
ace_interact_menu_cursorKeepCentered - false
ace_interact_menu_AlwaysUseCursorInteraction - false
ace_interact_menu_UseListMenu - false
ace_interact_menu_colorTextMax - [1,1,1,1]
ace_interact_menu_colorTextMin - [1,1,1,0.25]
ace_interact_menu_colorShadowMax - [0,0,0,1]
ace_interact_menu_colorShadowMin - [0,0,0,0.25]
ace_interact_menu_textSize - 2
ace_interact_menu_shadowSetting - 2
ace_interact_menu_actionOnKeyRelease - false
ace_interact_menu_menuBackground - 0
ace_interact_menu_addBuildingActions - false
ace_interaction_EnableTeamManagement - true
ace_inventory_inventoryDisplaySize - 0
ace_laserpointer_enabled - true
ace_magazinerepack_TimePerAmmo - 1.5
ace_magazinerepack_TimePerMagazine - 2
ace_magazinerepack_TimePerBeltLink - 8
ace_map_BFT_Interval - 1
ace_map_BFT_Enabled - false
ace_map_BFT_HideAiGroups - false
ace_map_mapIllumination - true
ace_map_mapGlow - true
ace_map_mapShake - true
ace_map_mapLimitZoom - false
ace_map_mapShowCursorCoordinates - false
ace_maptools_EveryoneCanDrawOnBriefing - true
ace_medical_level - 1
ace_medical_medicSetting - 1
ace_medical_enableFor - 0
ace_medical_enableOverdosing - true
ace_medical_bleedingCoefficient - 1
ace_medical_painCoefficient - 1
ace_medical_enableAirway - false
ace_medical_enableFractures - false
ace_medical_enableAdvancedWounds - false
ace_medical_enableVehicleCrashes - true
ace_medical_enableScreams - true
ace_medical_playerDamageThreshold - 1
ace_medical_AIDamageThreshold - 1
ace_medical_enableUnconsciousnessAI - 1
ace_medical_remoteControlledAI - true
ace_medical_preventInstaDeath - false
ace_medical_enableRevive - 0
ace_medical_maxReviveTime - 120
ace_medical_amountOfReviveLives - -1
ace_medical_allowDeadBodyMovement - false
ace_medical_allowLitterCreation - true
ace_medical_litterSimulationDetail - 3
ace_medical_litterCleanUpDelay - 0
ace_medical_medicSetting_PAK - 1
ace_medical_medicSetting_SurgicalKit - 1
ace_medical_consumeItem_PAK - 0
ace_medical_consumeItem_SurgicalKit - 0
ace_medical_useLocation_PAK - 3
ace_medical_useLocation_SurgicalKit - 2
ace_medical_useCondition_PAK - 0
ace_medical_useCondition_SurgicalKit - 0
ace_medical_keepLocalSettingsSynced - true
ace_medical_healHitPointAfterAdvBandage - false
ace_medical_painIsOnlySuppressed - true
ace_medical_painEffectType - 0
ace_medical_allowUnconsciousAnimationOnTreatment - false
ace_medical_moveUnitsFromGroupOnUnconscious - false
ace_medical_menuTypeStyle - 0
ace_medical_menu_allow - 1
ace_medical_menu_useMenu - 0
ace_medical_menu_openAfterTreatment - true
ace_microdagr_MapDataAvailable - 2
ace_missileguidance_enabled - 2
ace_mk6mortar_airResistanceEnabled - false
ace_mk6mortar_allowComputerRangefinder - true
ace_mk6mortar_allowCompass - true
ace_movement_useImperial - false
ace_nametags_defaultNametagColor - [0.77,0.51,0.08,1]
ace_nametags_showPlayerNames - 1
ace_nametags_showPlayerRanks - true
ace_nametags_showVehicleCrewInfo - true
ace_nametags_showNamesForAI - false
ace_nametags_showCursorTagForVehicles - false
ace_nametags_showSoundWaves - 1
ace_nametags_playerNamesViewDistance - 5
ace_nametags_playerNamesMaxAlpha - 0.8
ace_nametags_tagSize - 2
ace_optionsmenu_optionMenuDisplaySize - 0
ace_optionsmenu_showNewsOnMainMenu - true
ace_overheating_DisplayTextOnJam - true
ace_reload_DisplayText - true
ace_repair_DisplayTextOnRepair - true
ace_repair_engineerSetting_Repair - 1
ace_repair_engineerSetting_Wheel - 0
ace_repair_repairDamageThreshold - 0.6
ace_repair_repairDamageThreshold_Engineer - 0.4
ace_repair_consumeItem_ToolKit - 1
ace_repair_fullRepairLocation - 2
ace_repair_engineerSetting_fullRepair - 2
ace_repair_addSpareParts - true
ace_repair_wheelRepairRequiredItems - 0
ace_respawn_SavePreDeathGear - false
ace_respawn_RemoveDeadBodiesDisconnected - true
ace_respawn_BodyRemoveTimer - 0
ace_sitting_enable - false
ace_spectator_filterUnits - 2
ace_spectator_filterSides - 0
ace_spectator_restrictModes - 0
ace_spectator_restrictVisions - 0
ace_switchunits_EnableSwitchUnits - false
ace_switchunits_SwitchToWest - false
ace_switchunits_SwitchToEast - false
ace_switchunits_SwitchToIndependent - false
ace_switchunits_SwitchToCivilian - false
ace_switchunits_EnableSafeZone - true
ace_switchunits_SafeZoneRadius - 100
ace_vehiclelock_DefaultLockpickStrength - 10
ace_vehiclelock_LockVehicleInventory - false
ace_vehiclelock_VehicleStartingLockState - -1
ace_viewdistance_enabled - true
ace_viewdistance_viewDistanceOnFoot - 0
ace_viewdistance_viewDistanceLandVehicle - 0
ace_viewdistance_viewDistanceAirVehicle - 0
ace_viewdistance_limitViewDistance - 10000
ace_viewdistance_objectViewDistanceCoeff - 0
ace_weaponselect_DisplayText - true
ace_weather_enableServerController - true
ace_weather_useACEWeather - true
ace_weather_syncRain - true
ace_weather_syncWind - true
ace_weather_syncMisc - true
ace_weather_serverUpdateInterval - 60
ace_winddeflection_enabled - true
ace_winddeflection_vehicleEnabled - true
ace_winddeflection_simulationInterval - 0.05
ace_winddeflection_simulationRadius - 3000
ace_zeus_zeusAscension - false
ace_zeus_zeusBird - false
ace_zeus_remoteWind - false
ace_zeus_radioOrdnance - false
ace_zeus_revealMines - 0
ace_zeus_autoAddObjects - false
ace_captives_allowHandcuffOwnSide - true
ace_captives_requireSurrender - 1
ace_captives_allowSurrender - true
ace_cargo_enable - true
ace_explosives_RequireSpecialist - false
ace_explosives_PunishNonSpecialists - true
ace_explosives_ExplodeOnDefuse - true
ace_hearing_EnableCombatDeafness - true
ace_hearing_EarplugsVolume - 0.5
ace_hearing_UnconsciousnessVolume - 0.4
ace_hearing_DisableEarRinging - false
ace_hearing_enabledForZeusUnits - true
ace_advanced_ballistics_enabled - false
ace_advanced_ballistics_simulateForSnipers - true
ace_advanced_ballistics_simulateForGroupMembers - false
ace_advanced_ballistics_simulateForEveryone - false
ace_advanced_ballistics_disabledInFullAutoMode - false
ace_advanced_ballistics_ammoTemperatureEnabled - true
ace_advanced_ballistics_barrelLengthInfluenceEnabled - true
ace_advanced_ballistics_bulletTraceEnabled - true
ace_advanced_ballistics_simulationInterval - 0
ace_advanced_ballistics_simulationRadius - 3000

------Array Info (count >= 10)------
slx_xeh_other_events_full - ARRAY SIZE: 37
slx_xeh_other_events - ARRAY SIZE: 37
slx_xeh_other_events_xeh_players - ARRAY SIZE: 37
ace_interact_menu_textsettingsmatrix - ARRAY SIZE: 16
ace_markers_markerscache - ARRAY SIZE: 48
cba_common_pfhhandles - ARRAY SIZE: 35
ace_weaponselect_nonfragmuzzles - ARRAY SIZE: 17
ace_medical_woundclassnames - ARRAY SIZE: 24
ace_interact_menu_act_b_soldier_f - ARRAY SIZE: 14
ace_kestrel4500_entries - ARRAY SIZE: 14
ace_weather_tempday - ARRAY SIZE: 12
cba_common_addons - ARRAY SIZE: 658
cba_int_string_table - ARRAY SIZE: 1000
ace_weather_humidity - ARRAY SIZE: 12
ace_weaponselect_nonfragmagazines - ARRAY SIZE: 17
ace_weather_winddirectionprobabilities - ARRAY SIZE: 12
ace_weaponselect_allmuzzles - ARRAY SIZE: 20
ace_optionsmenu_clientsideoptions - ARRAY SIZE: 38
slx_xeh_other_events_xeh - ARRAY SIZE: 37
ace_weather_windspeedmin - ARRAY SIZE: 12
ace_weather_windspeedmax - ARRAY SIZE: 12
ace_medical_allavailabledamagetypes - ARRAY SIZE: 11
ace_interact_menu_act_camanbase - ARRAY SIZE: 12
cba_common_bis_functions_list - ARRAY SIZE: 1152
ace_common_hexarray - ARRAY SIZE: 256
ace_kestrel4500_directions - ARRAY SIZE: 16
ace_weather_windspeedmean - ARRAY SIZE: 12
ace_gforces_gforces - ARRAY SIZE: 30
ace_weaponselect_allmagazines - ARRAY SIZE: 20
cba_ktab - ARRAY SIZE: 128
slx_xeh_events_nat - ARRAY SIZE: 34
cba_ytab - ARRAY SIZE: 128
ace_atragmx_workingmemory - ARRAY SIZE: 18
ace_kestrel4500_total - ARRAY SIZE: 14
ace_kestrel4500_menus - ARRAY SIZE: 16
cba_keybinding_activebinds - ARRAY SIZE: 62
cba_common_perframehandlerarray - ARRAY SIZE: 28
slx_xeh_events_full_nat - ARRAY SIZE: 34
cba_wtab - ARRAY SIZE: 128
ace_common_oldplayerinventory - ARRAY SIZE: 20
ace_kestrel4500_outputdata - ARRAY SIZE: 15
ace_atragmx_gunlist - ARRAY SIZE: 25
slx_xeh_other_events_players - ARRAY SIZE: 37
ace_markers_markercolorscache - ARRAY SIZE: 11
ace_weather_tempnight - ARRAY SIZE: 12
ace_common_settings - ARRAY SIZE: 181
slx_xeh_machine - ARRAY SIZE: 16
cba_keybinding_dikdectostringtable - ARRAY SIZE: 135
ace_medical_allwoundinjurytypes - ARRAY SIZE: 24
ace_medical_menu_actionsadvanced - ARRAY SIZE: 25
ace_medical_minlethaldamages - ARRAY SIZE: 11
extended_firedbiseh on [BIS_fnc_objectVar_obj1] - ARRAY SIZE: 16

**Comment by jokoho48** [comment] 2015-10-01 12:06
Hey Thanks for repoting, i saw this question befor on armaworld, but could you please make your issue fit in your standarts. http://ace3mod.com/wiki/user/how-to-report-an-issue.html.

**Comment by PabstMirror** [comment] 2015-10-02 01:17
@Krzmbrzl 

Could you open the ace settings and hit debug to clipboard and then post the RPT (from C:\Users\YourName\AppData\Local\Arma 3)

That should include all your settings and should help us try to reproduce the issue.

One thing you can try is to make sure you release windows key before ctrl key as doing the other order  be interpreted as a new keyDown and close the progress bar.

**Comment by Krzmbrzl** [comment] 2015-10-02 11:56
@jokoho48 
Okay updated my post...Hope it now fits the proper format.

@PabstMirror 
Yes that has helped. If I release the window key before I release the ctrl key the action just keeps on going fine but the other way it gets interrupted

**Comment by commy2** [comment] 2015-10-02 12:03
Noticed that too. Releasing a modifier key should not trigger a new keydown event. Since we use CBA's key system, we can't fix it in ACE.

**Comment by commy2** [comment] 2015-10-02 12:06
@Krzmbrzl Can I rename the issue , so it better describes the general underlying issue at hand?

**Comment by Krzmbrzl** [comment] 2015-10-04 09:49
@commy2 
Sure

**Comment by Krzmbrzl** [comment] 2015-10-04 09:50
Does anybody know if the mistriggered key down event is known to the CBA_A3 developers?

**Comment by commy2** [comment] 2016-02-19 10:57
Closing in favour of this: https://github.com/CBATeam/CBA_A3/issues/213

**Closed by commy2** 2016-02-19 10:57 UTC
Labels: CBA's fault, duplicate
