### ISSUE TITLE
Micro dagger GPS stays full screen

### ISSUE THREAD

**Issue by cHip1987** [acemod/ACE3#2969] opened 2015-12-07 22:40 UTC
**ACE3 Version: 3.4.0 stable**

**Mods:**
* `@ace`
* `@ASDG_JR`
* `@Batavian`
* `@C17A3`
* `@camofaces`
* `@CBA_A3`
* `@cTab`
* `@fhq_accessories`
* `@hiddenidentitypack`
* `@hiddenidentityv2`
* `@JS_JC_FA18`
* `@lesh_tow`
* `@LLW`
* `@mbg_killhouses_a3`
* `@ned_pack`
* `@Nimitz`
* `@rh_acc`
* `@rh_m4_a3`
* `@SP Pack`
* `@task_force_radio`
* `@tf47_launchers`
* `@yoink_opfor_insurgents`

**Placed ACE3 Modules:**
* `Wind deflection`
* `Advanced ballistics`
* `Captive settings`
* `Explosive system`
* `Map elimination`
* `Interaction system`
* `Hearing`
* `Micro dagger map fill (full settilite + buildings)`
* `Advanced medical settings`
* `Medical settings`
* `MK6 settings`
* `Name tags`
* `Zeus settings`

**Description:**
When opening the micro dagger gps (to use in combination with the Vector 21) he stays up full screen, in stead of poping up in the right bottom of the screen.

Using Home does switch to control mode with the mouse, but pressing home again the micro dagger doesn't pop down. Ctrl+Home exits the microdagger again. This since last update of ACE3 / ARMA

**Where did the issue occur?**
In game during mission MP

**Comment by BaerMitUmlaut** [comment] 2015-12-07 23:22
Duplicate of #2936, already fixed.

**Closed** 2015-12-07 23:23 UTC
Labels: duplicate

**Comment by cHip1987** [comment] 2015-12-07 23:30
GPS location is in the right bottom, but still have the GPS fullscreen.
