### ISSUE TITLE
Player no gets damages at crash vehicles (Adv.Medical settings)

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2762] opened 2015-10-17 22:05 UTC
ACE3 Version: 3.3.2
Stable 1.52

**Mods:**
* `@CBA_A3`
* `@ace`
* `@DragonFyre`

**Placed ACE3 Modules:**
Basic and Advanced Medical settings
**Description:**

Hi all. The Advanced medical module offers the player settings the damage inside transport. I installed - "Yes", but it doesn't work.
Player no gets damages at crash vehicles. Even if the player makes a few somersaults through his head on quad bike or if at full speed the car crashed into a house! NO any damages/ I think this is not realistic and bad detail. I assume that damages are not working in any vehicle, be it tank, plane or Quad bike.

**Steps to reproduce:**
Place in the map the advanced medical settings with damage into vehicle and try create crash.

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by commy2** [comment] 2015-10-18 08:13
Duplicate of https://github.com/acemod/ACE3/issues/1811 
@Glowbal ?

**Comment by Glowbal** [comment] 2015-10-18 08:24
Yes, it's indeed a duplicate. I will close this and continue in #1811. 

Thank you for the report though, @mickeymen ! It contains a good description.

**Closed by Glowbal** 2015-10-18 08:24 UTC
Labels: duplicate

**Comment by mickeymen** [comment] 2015-10-18 08:39
Ok. I hope it will be solved
