### ISSUE TITLE
ACE 3 View Distance is not configurable

### ISSUE THREAD

**Issue by ErwinNoppe** [acemod/ACE3#6510] opened 2018-08-08 08:47 UTC
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.8.0` (stable)
**ACE3 Version:** `3.12.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- If i go into the editor and start build a mission i see that the view distance is reduced to 1000 meters, I save the mission and start configurating the ACE Viewdistance but how ever i do it nothing happens if i put it to on or off nothing happens, if i turn everything to maximum nothing happens. This error occurs mostly but sometimes it worked corectly. My mates reported to me that they have issues with the view distance but cant disable it because of the mission config of the Viewdistance.

**Steps to reproduce:**
- Load a Fresh Downloaded, unconfigured ACE version
- Go into the Editor
- Configure ACE Viewdistance, set it to DISABLED
- Set all to 10000
- Noting happens
- Set it to enabled put everything to max., nothing happend

**Where did the issue occur?**
- Dedicated/Self-Hosted Multiplayer /Singleplayer / Editor (Singleplayer/Multiplayer)

**Placed Modules:**
- No placed modules

**RPT log file:**
- https://gist.github.com/ErwinNoppe/dc1caa64f4814a1428bb9e1fe9ddd400

**Comment by madpat3** [comment] 2018-08-11 23:12
you said: ACE3 Version: 3.12.2 (stable)
we're at 3.12.3 (stable).
i don't remember, how it was with 3.12.2, but with the current version, i cannot reproduce.

**Comment by thojkooi** [comment] 2018-11-18 18:40
Closing since we cannot reproduce the issue (see comment by @madpat3). If you feel this is in error, please re-open this issue and we will investigate again. 

Thanks for your contribution.

**Closed** 2020-11-01 20:14 UTC
Labels: kind/bug, status/can't reproduce
