### ISSUE TITLE
Ace causes abnormal armor bulletproof of the RHS module

### ISSUE THREAD

**Issue by ZHANGTIANYAO1** [acemod/ACE3#9044] opened 2022-09-21 09:58 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** `2.10`
- **CBA:** `v3.15.8.220912` 
- **ACE3:** `3.15.1` 
- **RHSUSAF**`0.5.6`
- **RHSGREF**`0.5.6`
- **RHSAFRF**`0.5.6`
- 
**Description:**
When using ACE and RHS, the bullet rating of the RHS armor will be changed directly to the highest bullet rating. The armor cannot be penetrated with any 7.62 or 5.56 caliber round. No matter how many bullets are fired at the AI chest, it will not deal any damage other than contusion.

**Steps to reproduce:**
Load the above module and enter the game to test

**Expected behavior:**
Bulletproof data is realistic(like normal)

**Where did the issue occur?**
anywhere

**Video:**
https://youtu.be/hEypVxJ1vDY

**Comment by ZHANGTIANYAO1** [comment] 2022-09-24 03:21
Also using ACE Compat - RHS AFRF ACE Compat - RHS USAF ACE Compat - RHS: GREF at the same time

**Comment by acknowledge14** [comment] 2022-10-01 16:21
Maybe you can try Alegro Simple USAF Vests Armor fix
https://steamcommunity.com/sharedfiles/filedetails/?id=2831971321

**Comment by johnb432** [comment] 2022-10-02 18:01
I can't reproduce the described behavior (inside the ACE Arsenal mission) with the following modset:
- Arma 3: 2.10.149973 (profiling branch)
- CBA: v3.15.8 (steam workshop release)
- ACE3: 3.15.2 (steam workshop release)
- RHSUSAF (steam workshop release)
- RHSGREF (steam workshop release)
- RHSAFRF (steam workshop release)
- ACE-RHS compats for mods above (steam workshop releases)

The units are tanky, but they die as they normally do (since the biggest ACE medical - was it 3.15.0?). They die after about 10-12 7.62x39 tracer bullets to the chest with a 6B13 vest.

**Comment by rautamiekka** [comment] 2022-10-02 18:04
> 7.62x39 tracer

What about 5.56 NATO ?

**Comment by ZHANGTIANYAO1** [comment] 2022-10-03 11:06
> 

same

**Comment by ZHANGTIANYAO1** [comment] 2022-10-03 11:11
The real problem was that the RHS armor values were changed after the ACE was loaded, which made it impossible for any bullet to penetrate them. This is clearly at odds with reality

**Comment by johnb432** [comment] 2022-10-08 20:38
> Maybe it's because you adjusted the CBA Settings for ACE Healthcare, and I achieved the same effect by adjusting the Settings but that doesn't solve the underlying problem.

What settings are you using?
I am using tweaked settings, however the only setting that counts in this case is the "AI Critical Damage Threshold", which in my tests and daily usage is left at 1 (default).
I tried with it set to 25 and the AI took 147 bruises, then died (6B13, 7.62x39 (89) ammo).

> The real problem was that the RHS armor values were changed after the ACE was loaded, which made it impossible for any bullet to penetrate them. This is clearly at odds with reality

I don't understand what you are trying to say.
ACE does not change any armor values. It gets the Armor values when the game is fully loaded, so nothing in the config can/will change.


> Can confirm that both I and my unit mate can replicate this behaviour and have had this issue several times when playing DRO with ACE + RHS.

How? What medical settings?

**Comment by JFCO-Highlander** [comment] 2022-10-09 12:18
> 

Default, "out of the box" settings. I changed nothing for attempting to replicate this. Picked the exact same armour and weapons as shown in the OP's video. Unloaded a clip of 7N10 (7.62) at a 30m distance. Result:

6x Large Bruise
18x Medium Bruise

I am running the exact same mods as described in the OP:

ACE3
CBA
RHSAFRF
RHSUSAF
RHSGREF
ACE Compat - RHS AFRF
ACE Compat - RHS USAF
ACE Compat - RHS GREF

**Comment by johnb432** [comment] 2022-10-09 15:35
I screwed up when checking my settings when I tested previously.
I should have remembered that the "Fatal Damage Source" was not set to "Sum of trauma" by default,

With "Fatal Damage Source" set to "Only large hits to organs" (default), I can replicate the described behavior.

What I was trying to say with

> ACE does not change any armor values. It gets the Armor values when the game is fully loaded, so nothing in the config can/will change.



> -- Edit 2:
> 
> > I don't understand what you are trying to say.
> > ACE does not change any armor values. It gets the Armor values when the game is fully loaded, so nothing in the config can/will change.
> 
> I recreated the exact same test as described in edit 1 using only RHSAFRF, RHSUSAF, RHSGREF and the units died in 4 shots to the area shaded in red. So the issue only occurs when ACE is enabled.

**Comment by nightovizard** [comment] 2022-11-18 03:21
Can confirm this also happens with vanilla vests, specially the one used by the Nato grenadier, when using Only large hits to organs any hits on the chest deal no damage, if the settings is changed it will cause minor/medium bruises, this of course also affects other side mods other than RHS.

**Comment by zigaliro** [comment] 2023-01-19 20:22
Can confirm this is still happening. Hopefully its fixed soon as it makes the game unplayable making people complete tanks.

**Comment by PapaHuts** [comment] 2023-03-26 20:19
Yeah can confirm it's still happening, hope it's fixed in the next update

**Closed** 2023-09-23 17:07 UTC
Labels: kind/bug
