### ISSUE TITLE
Errors and missing Drone HUD

### ISSUE THREAD

**Issue by Rich513** [acemod/ACE3#5929] opened 2017-12-19 02:52 UTC
**Arma 3 Version:** `Current` stable
**CBA Version:** `3.5.0.171204` stable
ACE3 Version:** `3.11.0` stable

**Mods:**
- CBA_A3
- ace
-acex

**Description:**
![005](https://user-images.githubusercontent.com/18681374/34138417-04d4e8c2-e435-11e7-88d8-4c54d0d8cfee.png)

When shifting stuff around in the gear, or starting with a UAV controller in my inventory, get the error seen in the first attached screen
![005](https://user-images.githubusercontent.com/18681374/34138417-04d4e8c2-e435-11e7-88d8-4c54d0d8cfee.png)

When flying the drone (falcon) the HUD and other onscreen info disappears as seen below 
![006](https://user-images.githubusercontent.com/18681374/34138461-32f97e20-e435-11e7-8e28-38cf01747bb3.png)

**Steps to reproduce:**
- add uav operator to map
- add falcon drone to map
- start

**Where did the issue occur?**
-  Editor

**Placed Modules:**
- None

**Comment by bux** [comment] 2017-12-19 06:02
The error popping up is made by BI. It's already fixed on their dev version of the game.

With the ACE3 3.12.0 RC2 I can't reproduce the missing HUD. So I consider this issue fixed.

**Closed by bux** 2017-12-19 06:02 UTC
Labels: fault/BI

**Comment by Cuel** [comment] 2017-12-19 12:28
Can't reproduce in current stable either.
