### ISSUE TITLE
The AI is not attacking the nearest unconscious enemies.

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#3121] opened 2016-01-06 09:53 UTC
ACE3 Version: 3.4.1
Stable 1.54

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
Basic and Advanced Medical

**Description:**
Often seen such a situation. The AI hurt the player(at close range several meters) and the player loses consciousness. At this moment the AI turns his back to the unconscious player and stands like a statue or shoot other units. After a few seconds the injured player regain your consciousness and  can easily kill this "merciful" AI. I think, at least this situation is ridiculous. In order to avoid such moments the AI should always try to finish off the unconscious opponent who is close. Especially if the AI itself sent him to unconsciously condition.

**Steps to reproduce:**
Play in ACE3

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by Glowbal** [comment] 2016-01-06 10:22
This is actually by design to avoid AI that keep targetting an unconscious player. 

I think this behaviour balances well with how unconscious AI vs players plays out imo. I've seen plenty of times where an AI went unconscious and players left him for dead.

**Comment by mickeymen** [comment] 2016-01-06 10:53
Yes probably this is not a bug, but sometimes this detail creates not a realistic situations for the player. In ACE3, the player too quickly regain your consciousness, and also AI doesn't kill him in this situation. Thus the player after the loss of consciousness has the some superiority vs AI, who wouldn't consider it as a target

**Comment by Glowbal** [comment] 2016-01-06 12:13
Perhaps a better idea is to increase the time it takes for a player to regain consciousness. Add some kind of fade in effect.

**Comment by PabstMirror** [comment] 2016-01-06 16:13
Main problem is that `setCaptive true` has fairly fast effects but `setCaptive false` can take a while for the AI to re-engage.

Also, humans generally don't stop shooting at something just because it falls over. we could make the whole captive thing a setting that we could disable.  The downside is that a enemy patrol that goes near a unconsciousness body would start engaging it until they magically know he's dead which isn't realistic. 

I do like the idea of making waking up from unconsciousness a much slower process, and make the player completely worthless at fighting for ~15 seconds, which should be enough time for the AI to see as a threat again.

**Comment by esteldunedain** [comment] 2016-01-06 16:48
> I do like the idea of making waking up from unconsciousness a much slower process, and make the player completely worthless at fighting for ~15 seconds, which should be enough time for the AI to see as a threat again.

I think it would be great if players would recover the ability to see (blury maybe) and talk a few seconds before being able to move. Even better if they could look around, but I guess that's not possible.
Could also work when falling unconsious too.

**Comment by BaerMitUmlaut** [comment] 2016-01-06 19:22
>Also, humans generally don't stop shooting at something just because it falls over.

I think they would stop shooting if there is another person nearby that did not fall over, because it is obviously still a threat while the other person isn't.

**Comment by nic547** [comment] 2016-01-07 12:08
@PabstMirror 
> Also, humans generally don't stop shooting at something just because it falls over.
Article 41 of Protocol I, the Amendment to the Geneva convention, says that you shall not make a unconscious person the target of an attack. (Unfortunately only 174 states have ratified Protocol I)

I would rather prefer a solution like making it possible to surrender before you lose your status as hors de combat and AI trying to take unconscious persons as POWs rather than having them just shoot you.

**Comment by BaerMitUmlaut** [comment] 2016-01-07 16:29
>AI trying to take unconscious persons as POWs

While this may sound good in theory, it would not work out in practice. Telling the AI when to take prisoners and especially what to do with them (in a realistic and appropriate way) would be extremly difficult. What should they do with you? Carry you around? Just handcuff you and leave you where you are? Leave someone to guard you behind, weakening their own force?

Consider the current state of Armas AI and then compare that to what you are asking for.

You'd probably end up standing handcuffed all alone in some field far away from combat or friendlies, waiting for the mission to end, or you'd confuse the AI and block combat in some way or another. And interacting with an AI kidnapper is probably as interesting as talking to a wall.

**Comment by mickeymen** [comment] 2016-01-10 10:51
I think you need to create a short "detection radius", at which the AI will always to check the presence of an unconscious with an interval of every 5 seconds for exampe. This AI will shoot at the all of lost consciousness if they exist inside of detection radius. It may seem realistic, since it will be just like a control shot in a fallen enemy

**Comment by Glowbal** [comment] 2016-02-19 11:48
Closing for #3124

**Closed by Glowbal** 2016-02-19 11:48 UTC
Labels: by design, feature request
