### ISSUE TITLE
Unable to unload patients/captives from vehicles

### ISSUE THREAD

**Issue by MHenley3019** [acemod/ACE3#4862] opened 2017-01-30 21:19 UTC
**Arma 3 Version:** `Dev/Stable
**CBA Version:** 3.1.2 Dev/Stable
**ACE3 Version:** 3.8.2 Dev/Stable
**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- I can load patients/captives into all vehicles but when I unload them the option is not there. I go Interaction > Passengers > (Passenger's name). The only option I have is to check weapon temperature and nothing else. 

**Steps to reproduce:**
- Shoot someone until they pass out or arrest someone. Drag them to a vehicle, load them in and then try to unload them.

**Where did the issue occur?**
- Self-Hosted Multiplayer/Single player/Editor.

**Placed Modules:**
- None.

**RPT log file:**
- No mention of this issue.

**Comment by PabstMirror** [comment] 2017-02-02 19:58
RPT would be very useful.
Passengers should only show `MainActions`
The "Check Weap Temp" isn't part of main actions.

This should not happen with just cba and ace, is there another mod adding or changing actions?

**Comment by TorsteinE** [comment] 2017-02-07 23:43
My group has been having this issue for some time now. If someone is incapacitated in a vehicle, there are no options to unload them. The only treatment options are to bandage, but not specified what you are bandaging.

**Comment by bux** [comment] 2017-02-08 07:36
@MHenley3019 @TorsteinE 
> RPT would be very useful.

**Comment by TorsteinE** [comment] 2017-02-09 23:00
Here is my latest [.RPT](https://github.com/acemod/ACE3/files/765221/arma3_2017-02-07_21-01-42.zip)

Going back I believe this issue was introduced some time after 3.8.0, the timeline (in our group) suggests this.

**Comment by PabstMirror** [comment] 2017-02-10 01:37
Thanks @TorsteinE 
It seems to be caused by a mod load order problem.
It should be fixed properly soon, in the meantime you might have luck by moving ace up in the mod list (but I'm not sure about this).

**Closed** 2017-02-10 18:49 UTC
Labels: bug
