### ISSUE TITLE
Other side after Unconscious

### ISSUE THREAD

**Issue by C0kkie** [acemod/ACE3#6187] opened 2018-03-07 21:03 UTC
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.6.1.180131` (stable)
**ACE3 Version:** `3.12.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Sometimes we have the problem after someone was Unconscious or dead, that he switches the site after reviving or respawn to another playerside Oo

**Steps to reproduce:**
- Cant produce specific steps

**Where did the issue occur?**
- Self-Hosted Multiplaye

**Comment by BaerMitUmlaut** [comment] 2018-03-09 12:50
Are you sure you're running just ACE and CBA when that happens? We'd need at least an RPT file from both the server and the client when that happens if you don't have an reproduction steps.

**Comment by BaerMitUmlaut** [comment] 2018-05-20 17:55
You seem to use a life mission which might cause that problem too - there's no way for us to tell. ACE does not switch a unit's side unless the unit gets loaded into a vehicle.

Unless somebody can reproduce this with just ACE and CBA, or at least can provide a way to reproduce the problem reliably we can't really help.

I'm closing this for now since OP has not responded since 2 months.

**Closed by BaerMitUmlaut** 2018-05-20 17:55 UTC
Labels: status/need more info

**Comment by YoannFR** [comment] 2018-05-20 18:29
Sorry to reopen this post, but, can me explain this : ACE does not switch a unit's side unless the unit gets loaded into a vehicle.

The medic load the patient into a vehicle for a transport in the hospital, so, the patient get the playerside Independent when is load in a vehicle ? 
 
in ace_common\functions\fnc_loadPerson : 
[_unit, true, GROUP_SWITCH_ID, side group _caller] call FUNC(switchToGroupSide);

What is the utilities of change the GroupSide ?

**Comment by BaerMitUmlaut** [comment] 2018-05-21 08:49
You can't load people into vehicles of a different side. The side will switch back once unloaded.
