### ISSUE TITLE
ACE 3 interaction menu not showing up 

### ISSUE THREAD

**Issue by Pelaez14** [acemod/ACE3#1494] opened 2015-06-03 18:55 UTC
When im playing, the ace 3 interaction menu doesnt show up, it only shows the red circle on the middle but nothing else happens it doesnt shows option and i tried reseting the ace 3 options on the main menu but it didnt fix it. what could be the problem, also i have everything updated and that is happening to everyone in my community and me.

**Comment by ViperMaul** [comment] 2015-06-03 19:11
One of the reasons why we ask people to use  [this form](http://ace3mod.com/wiki/user/how-to-report-an-issue.html) for any issues is because we actually cannot help you without know which Unit, which mission, which mod you are using. 

So all I can say this until you do. 
Update your CBA mod to the latest CBA 7 Hotfix (v1.1.22.x) 
Then try to use the same units or missions without any mods if you can. 
Gives the details we need to see where the problem is.

**Comment by Pelaez14** [comment] 2015-06-03 19:18
We use this mods on our dedicated server that is basically only with zeus. 
![11416964_10153231727116273_1795030645_o](https://cloud.githubusercontent.com/assets/12735345/7969284/6fc4ba2a-09fb-11e5-95b0-f17d6656433a.jpg)

**Comment by Winter259** [comment] 2015-06-04 12:43
http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by reoxdk** [comment] 2015-06-06 14:44
We had the same problem we fixed it with rolling back to cba 6 hotfix

**Comment by ViperMaul** [comment] 2015-06-06 15:13
This is fixed by CBA 7 Hotfix 2 
You can get it here -> https://github.com/CBATeam/CBA_A3/pull/58#issuecomment-109172004
This will be release in the next 24 hours or so. Sunday morning most likely.

**Comment by ViperMaul** [comment] 2015-06-06 17:50
@reoxdk 
Thanks for posting in the CBA github stating that the CBA 7 hotfix 2 solved this problem. 
I am closing this as a result.

**Closed by ViperMaul** 2015-06-06 17:50 UTC
Labels: need more info
