### ISSUE TITLE
Stuck when two players tried to carry a player at the same time. 

### ISSUE THREAD

**Issue by ViperMaul** [acemod/ACE3#1934] opened 2015-07-28 17:33 UTC
>Got stuck when two of us accidentally tried to carry the same person, used playMove in console to get out of it, this is needed as not everyone has console access.  --  Cyruz143

**Comment by SilentSpike** [comment] 2015-08-29 20:08
As discussed:

Can fix by checking conditions local to downed player rather than carrier (ask their client for permission to act)

**Comment by commy2** [comment] 2015-09-01 16:04
Shouldn't be possible to carry someone while another one is accessing him. Can't reproduce with local host.
Will try again on dedi eventually.

```
[player, bob] call ace_common_fnc_canInteractWith
-> false
```

**Comment by commy2** [comment] 2015-09-26 16:32
Can't repro this : /

**Comment by brokenhands** [comment] 2015-10-20 18:37
Had a likely related issue occur yesterday. Patient was unconscious, tried to carry them out of line of fire. He bled out mid-animation and was kicked to the respawn menu. I was frozen at the end of the carry animation unable to move (outside of head-tracking). There was no release option on the scroll menu and no interact point available for the ACE menu. I was ventilated by the same GMG shortly thereafter, so I don't know if this would have self-resolved on some timeout.

**Comment by commy2** [comment] 2015-10-20 19:24
Well thats a different issue then. Will try to reproduce that.

**Comment by ace3mod** [comment] 2016-08-21 22:38
Hello!

We're automatically closing this issue since it has not received any updates or comments in the past 14 days. We therefore assume that the original reporter has lost interest or the issue has been resolved.

If this has been closed in erorr,  please create a comment below and we can reopen this issue. Note that you may need to provide additional information that was requested. 

Thanks!

**Closed by ace3mod** 2016-08-21 22:38 UTC
Labels: bug, can't reproduce
