### ISSUE TITLE
Data Base

### ISSUE THREAD

**Issue by TheMidnightCrow** [acemod/ACE3#6317] opened 2018-04-29 21:29 UTC
**Arma 3 Version:** `1.82x` (stable / rc / dev)
**CBA Version:** `3.6.1.180131` (stable / dev + commit hash)
**ACE3 Version:** `3.12.2` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
With Ace 3 turned on the server does not connect to the DB. The loaded profile does not connect to the db and receive its money and items. This has been tested with and with out ACE and just wand with out just CBA. It works like it should until Ace is used.

**Steps to reproduce:**
Make a DB and use ACE 3

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
None

**RPT log file:**
https://gist.github.com/TheMidnightCrow/6f0a5b6a54142022355d9c92de971f29

**Comment by commy2** [comment] 2018-04-29 21:38
How are you using that Database thing?
Btw. this is an issue tracker for ACE3, not a how do I setup my server support hotline.

**Comment by TheMidnightCrow** [comment] 2018-04-29 21:44
Thanks for being a smart ass thats real cool man. If you read it, it clearly says Ace is the cause of the issue making it an Ace problem. I know how to set up the server other wise how would i know it works with Ace turned off. Now if you are not gonna be helpful i would like you to move on.

**Comment by commy2** [comment] 2018-04-29 21:45
ACE is not the cause for your broken scripts.
Post them, and I'll maybe be able to fix them or point out the problem.

**Comment by TheMidnightCrow** [comment] 2018-04-29 21:50
How are they broken when they work just fine with out ace? Also they are not my scripts to post.

**Comment by commy2** [comment] 2018-04-29 21:52
They apparently don't work as they break when sneezed at.
You cannot expect help if you don't post the scripts. Sorry, but we can close this if you're unable to.

**Comment by TheMidnightCrow** [comment] 2018-04-29 21:56
All i can do is send you a like to down load them im not uploading another mans work.. https://github.com/Ppgtjmad/SimpleShops

**Comment by commy2** [comment] 2018-04-29 22:07
I can't find anything obvious. You should open an issue report on this missions issue tracker instead.

**Comment by BaerMitUmlaut** [comment] 2018-04-29 22:07
ExtDB3 is working just fine according to your RPT:
```
2018/04/29, 15:36:43 "extDB3: Version: 1.031"
2018/04/29, 15:36:43 "extDB3: Connected to Database"
2018/04/29, 15:36:43 "extDB3: ID Genereated: 7470"
2018/04/29, 15:36:43 "extDB3: Initalized SQL_CUSTOM Protocol"
2018/04/29, 15:36:43 "extDB3: Locked"
```
You didn't add ExtDB3 to the list of mods, by the way.

**Comment by TheMidnightCrow** [comment] 2018-04-29 22:10
I asked the scripter directly all he said is he does not use ace. I did add ExtDB3 but the server may not have loaded it. I will move it above ace and see if that fixes it, i don't think it will but i'm running out of ideas.

**Comment by BaerMitUmlaut** [comment] 2018-04-29 22:30
I meant in the issue text. Your ExtDB3 seems to be both running and working.

**Closed** 2018-04-30 14:50 UTC
Labels: fault/Mission
