### ISSUE TITLE
Ace advanced ballistics negative head wind.

### ISSUE THREAD

**Issue by Timo155** [acemod/ACE3#7263] opened 2019-11-02 20:48 UTC
Arma 3 and Ace fully updated.

**Description:**
Can't enter a negative headwind into the Atrax
It'll Always default a -1 for example to a 0 whilst the krestrel says headwind -1
Thus you can't correct for a negative headwind as far as i know.

**Steps to reproduce:**
Always.

**Expected behavior:**
Able to apply a negative head wind

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Comment by dedmen** [comment] 2019-11-02 21:52
why would you enter a negative headwind? negative wind means the wind is coming from the opposite direction.

**Comment by Timo155** [comment] 2019-11-02 21:55
Negative headwind is the wind that comes from behind you. Thus it assists the bullet (Higher velocity/less drop) Which means you'll always miss your target if you don't compensate for this. (Your bullet will fly OVER your target)

**Comment by Blutze** [comment] 2019-11-02 22:04
So you have wind from your 6 o'clock. Why don't you just enter it like that?

**Comment by Timo155** [comment] 2019-11-02 22:10
If you have a wind from your 6 you enter 12 because that is where the wind is going. Though i tried what you are suggesting it makes no difference. You enter your click to determine the wind direction left to right or the other way around. It doesn't compensate for the elevation that you overshoot..

**Comment by Blutze** [comment] 2019-11-02 22:22
No, you enter the clock direction the wind is coming from. That goes for both the full wind, and wind "components" (as in, the two separate Kestrel pages). 

If shift+K tells you the wind is coming from your rear right, you run the absolute value of the crosswind page as coming from 3 o'clock to get your windage, and the absolute of the headwind as coming from 6 o'clock for elevation. Alternatively, make sure your direction of fire is a multiple of 30° and enter the actual windspeed (the smallprint on both Kestrel pages) as coming from wherever its coming from.

**Comment by Timo155** [comment] 2019-11-02 22:53
Still not solving the actual issue... The issue is compensating a rear wind.. even if you would enter the 6 instead of the 12 this does not change anything..

**Comment by commy2** [comment] 2019-11-02 23:04
>even if you would enter the 6 instead of the 12 this does not change anything

How so? That means the wind is coming from the opposite direction, which seems exactly what you want. It is the same as a negative sign.

**Comment by Timo155** [comment] 2019-11-02 23:06
The elevation you enter into your scope does NOT change. So you're NOT compensating at all. You still CAN'T enter a negative headwind into your atragx

**Comment by commy2** [comment] 2019-11-02 23:28
This is embarrasing.

**Comment by dedmen** [comment] 2019-11-02 23:37
You should probably watch a "sniping with ACE for amateurs" tutorial and let it explain how you measure wind to you.

**Comment by Laid3acK** [comment] 2019-11-03 10:31
* From the ACE3 Wiki : 
  * [Kestrel 4500 CROSSWIND / HEADWIND Feature
](https://ace3mod.com/wiki/feature/kestrel4500.html#22-crosswind--headwind-feature) with an official Kestrel video to learn exactly how it works. The wind arrow must be enabled.
  * [Wind Direction with the AtragMx](https://horusvision.com/download/manual_Horus_ATrag-v385.pdf#page=16)
  * From the AtragMx manual : [Parameter Limits page 17](https://github.com/acemod/ACE3/blob/master/extras/manual_Horus_ATrag-v385.pdf)

You should take a look to the ACE3 Wiki and the AtragMx manual,
you have already many information on it.
A lot of tutorial videos are incomplete, outdated and sometimes wrong.

**Comment by commy2** [comment] 2019-11-03 11:21
Not a bug.

**Comment by Timo155** [comment] 2019-11-03 11:57
@Laid3acK Thank you. First one to give a usefull answer then. 

Now i'm not sure how this is still not going correctly then. 
https://steamcommunity.com/sharedfiles/filedetails/?id=1905463373
https://steamcommunity.com/sharedfiles/filedetails/?id=1905463007
https://steamcommunity.com/sharedfiles/filedetails/?id=1905462814

Everything is entered correctly this time. It doesn't compensate to the right enough.. Target still standing..

**Comment by bux** [comment] 2019-11-03 12:28
Closing, because it's not an issue with ACE.
Further questions please go to our public chat: https://slackin.ace3mod.com/

**Closed** 2019-11-03 12:27 UTC
Labels: kind/question
