### ISSUE TITLE
Tank crew getting damage by near explosion of a vehicle

### ISSUE THREAD

**Issue by Jastreb** [acemod/ACE3#683] opened 2015-04-17 01:48 UTC
ACE3 Version: e12831bee474814bee5fd4f02f4dc10a9ccb40b6

**Mods:**
- @cba_a3
- @ace3

**Placed ACE3 Modules:**

None/Unkown - ACE test mission Stratis

**Description:**

Tank, or just any armored vehicle crew gets hurt and set unconscious if a nearby explosion of any vehicle occurs. Affects both AI and player. This should not happen, at least I cant recall things working like this in Arma, although I dont use armored vehicles much. Possibly a bug with medical system or just missing crew protection from ACE2?

**Steps to reproduce:**
- Load the ACE Test mission on Stratis in MP hosted
- Pick any playable slot and order your units from group to board a Merkava or FV510
- Move your vehicle close to any vehicle, switch to gunner and fire one AP round to it
- Observe the vehicle blowing up, and you getting damage and set unconscious, along with AI

**Where did the issue occur?**

Hosted MP

**RPT log file:**
http://pastebin.com/cg6nkj0j

**Comment by jaynus** [comment] 2015-04-17 02:29
Mobile fail. Sorry guys

**Comment by Glowbal** [comment] 2015-04-17 05:51
Possibly an issue with overpressure.

**Comment by PabstMirror** [comment] 2015-04-17 07:02
I feel like there is some kind of problem with locality/mp with explosions damage handleing.
For tripflares, I have an very very low damage explosion happening.  In a local MP test (non dedicated) the server has never gotten knocked out from this explosion, but the non-server client has about a 40% chance to get knocked out.

**Comment by PabstMirror** [comment] 2015-04-17 07:49
I can reproduce this `tripFlareTest` branch:

```
[] spawn {
_bomb = "ACE_APERSTripFlare_Wire_Ammo" createVehicle (getpos player);  
_dropPos = getpos player;
 _dropPos set [2, 0]; _
bomb setPos _dropPos; 
sleep 1; 
_bomb  setDamage 1;};
```
Never knocks out server, client gets knocked out most of the time.

Server:
 `
handleDamage_advanced.sqf:30","EXPLODE_6 _this: _unit=GrpNATO_A1_0, _selectionName=head, _amountOfDamage=2.11593e-005, _sourceOfDamage=<NULL-object>, _typeOfProjectile=ACE_APERSTripFlare_Wire_Ammo, _newDamage=2.11593e-005"]
`

Client: 
`
handleDamage_advanced.sqf:30","EXPLODE_6 _this: _unit=GrpNATO_A2_0, _selectionName=head, _amountOfDamage=2.0353e-005, _sourceOfDamage=<NULL-object>, _typeOfProjectile=ACE_APERSTripFlare_Wire_Ammo, _newDamage=2.0353e-005"]
`

**Comment by jaynus** [comment] 2015-04-17 18:47
Explosion simulation may be indetermisitic, yielding different results

**Comment by Jastreb** [comment] 2015-04-17 21:03
Could be fire effect when vehicle gets set on fire. But for some reason you get damaged even if you are inside a 60T/whatever armored vehicle. 

Could fire be just removed? Just for testing and then well see. Hm?

Ill try with RHS loaded, and will monitor the health while trying to reproduce.

**Comment by Glowbal** [comment] 2015-04-17 21:20
Taking damage is probably be due to fragmentation. The unconscious part had some issues and taking damage inside vehicles for advanced threw a script error; those have been fixed in #717

**Comment by Jastreb** [comment] 2015-04-17 21:45
Splendid ( no pun ). :banana:

Will test and report back tonight.

**Comment by jaynus** [comment] 2015-04-18 00:33
This increases new VD (tee her) priority. I might make a weekend of it

**Comment by jaynus** [comment] 2015-04-20 17:30
@Jastreb: RHS has its own independent vehicle damage system, it does not apply for testing or have anything to do with ACE.

**Comment by jaynus** [comment] 2015-04-20 17:32
This is due to penetration only applying to velocity of the projectile entering + thickness of the armor; because material type etc does not apply the penetration model fails.

**Comment by Jastreb** [comment] 2015-04-20 23:02
Yeah @jaynus I know that, that's why I used RHS to test it. Vanila VC are efd, but I dont care much cause I dont use them at all. Just wanted to report it in case of ABCD...

If you get to handle vanilla vehicles differently, and disable the explosion (d)effect on destruction this would not happen or sometimes in rare cases. The whole blowup on critical damage is retarded anyway.

**Comment by jaynus** [comment] 2015-04-21 04:52
yah understood; it will get resolved with ACE vehicle damage; hopefully RHS model continues to avoid it

**Comment by bux578** [comment] 2015-04-25 17:39
Vanilla:
https://www.youtube.com/watch?v=65vZ5BcbYfM


ACE: (*Distance in ACE is important*)
http://puu.sh/hqs6F/633893b0e5.jpg

**Comment by jaynus** [comment] 2015-05-13 02:48
#1062

**Comment by vlad8011** [comment] 2016-04-04 17:20
Video is deleted (vanilla), i've got mine :
https://www.youtube.com/watch?v=s2rUA8wLJNY&list=PLbBKN48L5CjQsDYyoX3RH2v43qR_HBt1L&index=5

**Closed** 2023-09-10 23:52 UTC
Labels: kind/bug, fault/BI, kind/outdated
