### ISSUE TITLE
Arsenal does not open when called before player is fully loaded (race condition)

### ISSUE THREAD

**Issue by markusa380** [acemod/ACE3#8749] opened 2021-12-21 19:27 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06.148470`
- **CBA:** `3.15.6`
- **ACE3:** `3.14.1`

**Description:**
Calling `[player, player, true] spawn ace_arsenal_fnc_openBox;` on init does not (always) open the Arsenal. (Same with `call`).

**Steps to reproduce:**

1. Create a new mission.
2. Place a player unit
3. In either the unit init, `init.sqf`, `initPlayerLocal.sqf`, ... paste `[player, player, true] spawn ace_arsenal_fnc_openBox;`
4. Run the mission

**Expected behavior:**
The arsenal opens when called in the init code.

**Where did the issue occur?**
- On multiplayer or singleplayer, the issue occurs if the line is called anywhere before the briefing map is closed and the player is actually fully loaded in. There's no good mechanism to check when the player is fully loaded into the game.

**Comment by Salluci** [comment] 2021-12-21 23:30
Pretty sure that function should be called, not spawned. But either way, try using [getClientState](https://community.bistudio.com/wiki/getClientState) >= 10 as a condition in a waitUntil.

**Comment by BaerMitUmlaut** [comment] 2021-12-22 20:22
I don't see how we're supposed to solve this. The briefing probably closes all dialogs, including the arsenal.

**Comment by markusa380** [comment] 2021-12-22 21:02
@BaerMitUmlaut from my perspective as a developer (not Arma) all I can say is that I would expect the function to either wait or return an error. Just silently doing nothing (from the outside perspective at least) seems like a bad behaviour.

**Comment by BaerMitUmlaut** [comment] 2021-12-22 21:12
Thing is, it's not doing nothing. The problem is that something else is closing it. There's plenty other opportunities where this would be intentional and, in my opinion, the behaviour here is correct. The init field is not made for opening dialogs, it's made for initializing a unit.

If you need a dialog to open after the briefing, then open it after the briefing, not before the briefing.

**Comment by markusa380** [comment] 2021-12-22 21:14
@BaerMitUmlaut Okay, I see your point. I just doubt that there's a well defined "after dialog" hook anywhere.
I am now using
```
waitUntil { getClientStateNumber >= 10 || getClientStateNumber == 0; };
```
(thanks @Salluci ) but that's clearly still kind of a hack.

**Comment by BrettMayson** [comment] 2021-12-22 21:14
Had a similar issue calling https://community.bistudio.com/wiki/BIS_fnc_guiMessage just the other day, adding a simple `CBA_fnc_waitUntilAndExecute` for something like `time > 1` or `getClientState >= 10` works just fine.

**Closed** 2021-12-22 21:17 UTC
Labels: kind/conflict
