### ISSUE TITLE
wrong hud of gasmasks 

### ISSUE THREAD

**Issue by topden** [acemod/ACE3#8169] opened 2021-03-15 15:43 UTC
Mods (complete and add to the following information):

    Arma 3: 2.00.146.773 [stable]
    CBA: 3.15.3 [stable]
    ACE3: 3.13.6 [stable]

Description:

you added hood to the gas masks. but in a gas masks
 "G_AirPurifyingRespirator_02_black_F" 
"G_AirPurifyingRespirator_02_olive_F"
"G_AirPurifyingRespirator_02_sand_F"

thin is turned over, as it seems to me 

Steps to reproduce:
go to the arsenal

Log Files:
no

Screenshots:
http://joxi.ru/52aBgKlCkY7ogA
http://joxi.ru/DmBZ8dPU4pMo5m

**Comment by Salluci** [comment] 2021-03-15 19:27
Duplicate of #8127.

**Closed** 2021-03-15 22:24 UTC
Labels: kind/bug
