### ISSUE TITLE
 Red circle around ace integration node not align properly on 21:9 Screen

### ISSUE THREAD

**Issue by Mattifine** [acemod/ACE3#8687] opened 2021-11-17 15:30 UTC
Hi the Red circle around ace integration node not align properly. This happed after the latest update and I think it has to do with my ultrawide (21:9) screen since it only a problem for me and I am the only one in my unit with a 21:9 screen (It is1440p if that makes any difference) . See the attached pictures
![Untisssssssssstled](https://user-images.githubusercontent.com/77750642/142230146-abd3a3dc-28ee-4599-ad47-2c1f0625b0e3.png)
![sssssssssssssss](https://user-images.githubusercontent.com/77750642/142230155-963d7ca3-fa4d-4d2e-aa1a-d5914f5d7947.png)
![Untsssssssitled](https://user-images.githubusercontent.com/77750642/142230164-e903329f-5d43-4775-a374-d78a960f7313.png)
.

**Comment by BrettMayson** [comment] 2021-11-17 15:51
Also been having this on master for months

**Comment by Timi007** [comment] 2021-11-17 16:57
Duplicate of #8613

**Closed** 2021-11-18 10:20 UTC
Labels: status/duplicate
