### ISSUE TITLE
ACE3 RHS: AFRF compatibility patch wrong base for RPK-74M

### ISSUE THREAD

**Issue by chazbotic** [acemod/ACE3#8442] opened 2021-09-16 08:03 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** 2.04.14779
- **CBA:** 3.15.5.210713
- **ACE3:** 3.13.6
- **RHSAFRF:** 0.5.6

**Description:**
class rhs_weap_rpk74 has wrong base class. without ACE Compat - RHS Armed Forces of the Russian Federation compatibility patch, magazines are correct for RPK-74M and RPK-74N. after loading patch, magazines are switched to PKM.

**Steps to reproduce:**
1. load CBA, ACE3, RHSAFRF, ACE Compat - RHS Armed Forces of the Russian Federation.
2. start 3den editor, place OSN infantry unit with RPK
3. magazine is missing, config entry for rhs_weap_rpk74m (and rhs_weap_rpk74n) shows PKM magazines

**Expected behavior:**
Correct magazines to be configured.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- n/a

**Additional context:**
in @ACE Compat - RHS Armed Forces of the Russian Federation\addons\ace_compat_rhs_afrf3\z\ace\addons\compat_rhs_afrf3\CfgWeapons.hpp line 70 is:

    class rhs_weap_rpk74: rhs_weap_pkp {
        ACE_barrelTwist = 195.072;
        ACE_barrelLength = 589.28;
    };

when probably should be:

    class rhs_weap_rpk74_base;
    class rhs_weap_rpk74: rhs_weap_rpk74_base {
        ACE_barrelTwist = 195.072;
        ACE_barrelLength = 589.28;
    };

**Screenshots:**
https://imgur.com/sKZmz2c

**Comment by BaerMitUmlaut** [comment] 2021-09-16 08:55
Duplicate of #8221 and #8228. Fixed in #8223.

**Closed by BaerMitUmlaut** 2021-09-16 08:55 UTC
Labels: kind/bug
