### ISSUE TITLE
CPR not working for cardiac arrest because of blood loss

### ISSUE THREAD

**Issue by Artac** [acemod/ACE3#2728] opened 2015-10-11 00:26 UTC
ACE3 Version: 3.3.2

Mods:

@cba_a3
@ace3
Placed ACE3 Modules:
http://pastebin.com/82xK67Hj

Description:
https://github.com/acemod/ACE3/issues/2099
Glowbal wrote:
"Try to give a patient that is not injured 3x epinephrine. The patient will go into a cardiac arrest state. This is when you are able to revive using CPR."

Did this, worked flawlessly.

"This is just one case, of course. Extended periods of bloodloss could also trigger the cardiac arrest state. I'd go with if the vitals of a patient are the cause of the patient to go unconscious, it's most likely that the patient is in the cardiac arrest state."

When the extend period of blood loss/pressure drop causes the heart rate to goto 0/cardiac arrest I am unable to restore the heart rate using CPR, even after bandaging all the wounds and using 1000ml bloodbags to raise pressure, I've gotten the pressure as high as mid 80's with still no return of heart rate using CPR. If I am understanding what you said, does the extended period of bloodloss put them in a cardiac arrest state, thus not requiring the PAK to revive the patient?

Steps to reproduce:
Set up you modules like in the config. Shoot a player. When unconscious let the pressure drop until approximately 35 systolic. Check for pulse, no pulse.

Where did the issue occur?
In Multiplayer on a dedicated Server

**Comment by rebelvg** [comment] 2015-10-12 16:35
Yep, tried this on AI. According to the code of the CPR function it should have a 60% chance of returning the pulse to 40, pressure to 70/50 and exiting the cardiac arrest but it never happened. I watched the variables for the patient, but they only switch for one frame, next frame unit is back in cardiac arrest and no heart rate.

**Comment by Th3Cr0w** [comment] 2015-10-12 17:49
@rebelvg this "flickering" of the Heart rate sounds a lot like the unit was in revive state.
 Experienced it myself.

**Comment by headedhorseman101** [comment] 2015-10-28 11:55
Just a question, but did you @rebelvg and @Th3Cr0w, but were you transfusing a saline  splution while performing car? If we was going into cardiac arrest be of hemorrhagic shock, then he would need the fluids the hear to be able to maintain a mildly sustainable systolic blood pressure.

**Comment by headedhorseman101** [comment] 2015-10-28 12:03
>According to the code of the CPR function it should have a 60% chance of returning the pulse to 40, >pressure to 70/50 and exiting the cardiac arrest but it never happened.

That is with a full blood volume on a medically stable patient. If the patient has lost to much blood, then a seperate function takes over again calling on the fnc_setCardiacArrest function.

**Comment by rebelvg** [comment] 2015-10-28 13:28
@headedhorseman101 If I remember correctly I tried bunch of different scenarios, like when patient is stable and with full blood or with patient not even touched. Result was the same, CPR didn't revive the guy, just added more time to his death timer.

**Comment by headedhorseman101** [comment] 2015-10-28 13:33
Yeah that mighty be by design, but I am unsure. Anyways, would still recommend doing the debug mode I suggested to see what is going on with the function variables.

**Comment by headedhorseman101** [comment] 2015-10-28 13:34
Also, please supply an rpt log if possible

**Comment by rebelvg** [comment] 2015-10-28 17:04
@headedhorseman101 Yeah, it jumped and then in the next frame was reset to 0. I'll upload an RPT if I'm going to do more tests.

**Comment by headedhorseman101** [comment] 2015-10-29 11:54
>Yeah, it jumped

@rebelvg Which one of the variables jumped?

**Comment by rebelvg** [comment] 2015-10-29 13:29
@headedhorseman101 Afaik it was player getVariable ["ace_medical_heartRate"].

**Comment by headedhorseman101** [comment] 2015-11-09 13:15
>CPR didn't revive the guy, just added more time to his death timer.
Took a look at the function, it is by design.

**Comment by Glowbal** [comment] 2016-06-15 11:04
Is this still present?

**Comment by Artac** [comment] 2016-06-15 23:59
As of 3.5.1, yes it is.

**Comment by ulteq** [comment] 2016-12-10 10:35
This issue is gone in the medical rewrite.

**Comment by Don79** [comment] 2017-03-07 18:41
I' dont understand.
ACE 3.9.0 CPR don't work.
Problem is the CPR give 40bpm heartrate on 40%...,but the game 
immediately delte  all heratrate under 60 to 0(zero) 
I dont understand why this issue is...
Shooting the target and befor hit the ground the heartrate is 0!
Blood pressure is not possible by 0 hertrate! 0 heartrate = dead (no blood pressure!)
Systole= the heart is pumping 
Diastole= The heart is in relax
which update includes this issue fixes?
THX!

**Comment by dragonspride1995** [comment] 2018-02-04 02:35
So my medic and I recovered my afk AT rifleman from the field. For 40 minutes we sat there next to a medical facility in a chopper (couldn't unload patient for whatever reason) Waiting for the Blood IVs to pump in at 0 heart rate, and 0 blood pressure. Began giving cpr at 97/65 with nothing, finally gave up and gave him a personal aid kit. I am confused why it takes so long to actually revive someone. Is this working as intended?

**Comment by kotaco** [comment] 2018-02-11 20:46
If they have a blood pressure, then they technically aren't in cardiac arrest to being with.

**Comment by dragonspride1995** [comment] 2018-02-12 07:24
@kotaco Is the only way to revive them using a personal aid kit from that point then?

**Comment by kotaco** [comment] 2018-02-12 09:27
I was speaking to actual medical care, ace is a different story so you're guess is as good as mine

**Comment by TheMagnetar** [comment] 2019-03-30 21:29
Fixed in rewrite

**Closed by TheMagnetar** 2019-03-30 21:29 UTC
Labels: kind/bug
