### ISSUE TITLE
ACE Ammo Cook off occurring randomly with few bullets fired and low temperatures

### ISSUE THREAD

**Issue by GeorgeBAS** [acemod/ACE3#8616] opened 2021-10-25 02:29 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06`
- **CBA:** `Latest stable`
- **ACE3:** `3.14 stable`

**Description:**
Weapons have been cooking off at low temperatures. On our server last night, we had around 10-15 people experiencing random weapon cook off about an hour into the operation.  Cook off settings were set to default. Other users @TyroneMF, @pterolatypus, and @JoramD0 reported the same issue under the same circumstances

**Steps to reproduce:**
Unable to reproduce both with modset from operation as well as only CBA + ACE. 

**Expected behavior:**
Weapons should not cook off until the weapon reaches the appropriate temperature 

**Where did the issue occur?**
- Dedicated

**Log:**
https://files.slack.com/files-pri/T04889UCE-F02JUTVEM18/download/arma3_x64_2021-10-04_17-15-42__1_.rpt
WARNING: Very messy, has all of our unit mods loaded

**Screenshots:**
Nil

**Comment by ghost-in-the-zsh** [comment] 2021-11-09 05:23
My friends and I have run into this problem multiple times, including immediately after respawning and before having fired any shots with the rifles.

**Comment by Drofseh** [comment] 2021-11-09 05:37
> My friends and I have run into this problem multiple times, including immediately after respawning and before having fired any shots with the rifles.

Heat was not previously cleared on death or respawn, but that will be accounted for in the next update.

**Comment by PabstMirror** [comment] 2021-11-11 19:45
Closed by #8617 ?

**Comment by Salluci** [comment] 2021-11-11 19:52
Needs testing. A lot of stuff was touched by #8617.

**Comment by Drofseh** [comment] 2021-11-11 20:53
> Closed by #8617 ?

Not sure. I was never able to repro the issue, and so far no one else has given me repo steps.

**Comment by Drofseh** [comment] 2021-12-04 09:08
Is anyone able to reproduce this with the ace 3.14.1?

**Comment by pterolatypus** [comment] 2021-12-04 15:07
I haven't even seen it happen since that one mission.

**Comment by OlivierMorelle** [comment] 2021-12-12 13:35
Just giving my feedback on the subject:

I've tryed setting on the ammo cook off in the last 2 weeks as a Game Master but i won't enable it again cause i don't think it's balanced properly. 

With even low setting factor (0.5). Some shot happened after shooting a single magazine. The gun having only 3 dots on the heat scale. I was expecting only machine guns to experience cook off. Not semi-automatic weapons cooking-off bullets once per second, 5 minutes after shooting for real.

**Comment by Drofseh** [comment] 2021-12-12 19:18
> Just giving my feedback on the subject

This is a report about a specific issue, please don't make off topic comments.
If you want to give feedback use the Ace3 Slack, if you have a bug report make a new issue.

**Comment by olimolly** [comment] 2021-12-12 20:09
So you're telling me it's the behavior cook off you expected when developping it ?

**Comment by Drofseh** [comment] 2021-12-12 20:29
Pretty much everything you've said is expected behavior, I don't think you're experieriencing the issue reported here at all.

> With even low setting factor (0.5).

I don't know which setting you've changed. If you changed `cookoffCoef` to 0.5, then you've reduced the ammo temp required for a cookoff.

> Some shot happened after shooting a single magazine. The gun having only 3 dots on the heat scale.

Nitrocellulose ignites are 200 deg Celcius. 3 dots/bars on the scale is 300 deg Celcius, so a cookoff can definitely happen. I don't know what weapon or ammo you were using, but if it's a lightweight weapon with a large magazine or a very powerful/heavy bullet then you could potentially get the temp that high from one mag.

> I was expecting only machine guns to experience cook off.

I don't know why you'd assume this.
Machine guns are mostly open bolt which means there is no round in the chamber, these weapons cannot cook off unless there have a failure to fire type jam that leaves a round in the chamber to heat up. 

> Not semi-automatic weapons cooking-off bullets once per second, 5 minutes after shooting for real.

Heat takes time to move from the weapon to the ammo, the lower the weapon temp the longer it takes.

> balanced properly

I added half a dozen new settings that you can adjust to make it fit well for you. Want weapons to heat up more slowly, decrease the heatCoef; want them to cool down faster, increase the coolingCoef; want cook offs to require more heat, increase cookoffCoef.

**Comment by Salluci** [comment] 2021-12-13 21:39
Too late to change the variable name, but might be a good idea to change the setting display name to something like Cookoff Temperature Coefficient. Current name is a bit confusing if you don't read the description. I'd expect increasing Cookoff Coefficient to increase the amount of cookoff I see, not the opposite.

**Comment by johnb432** [comment] 2024-07-26 12:58
Is this still an issue?

**Comment by johnb432** [comment] 2024-07-27 17:14
I'm going assume this has been resolved by #8617. If anyone has the bug again, open a new ticket with detailed reproductions steps.

**Closed by johnb432** 2024-07-27 17:14 UTC
Labels: kind/bug
