### ISSUE TITLE
Medical: Some Interaction points missing on dead units

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#869] opened 2015-04-26 12:14 UTC
ACE3 Version: 71f29466d71f8db944ffa7a5cd1a74798292304d

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* Medical set to advanced

**Description:**
After killing an AI unit and using interaction on it there are some interaction menus missing. These were mostly "Head", "Torso", "Left Arm" and "Right arm".

**Steps to reproduce:**
* Place AI
* Kill AI
* Use Interact Menu on AI
* Head and/or Arms and/or Torso missing

![2015-04-26_00004](https://cloud.githubusercontent.com/assets/1235520/7337128/1e39e9b4-ec1e-11e4-8cd8-d0e8aa0964f7.jpg)
(Notice how only the leg points are displayed)

**Comment by commy2** [comment] 2015-04-26 12:18
I think the description is wrong.

**Comment by alganthe** [comment] 2015-04-26 12:18
yep it is

**Comment by bux578** [comment] 2015-04-26 12:21
copy paste ^^ I'll update it.

**Comment by bux578** [comment] 2015-04-26 13:48
Happens with Basic as well

**Comment by alganthe** [comment] 2015-04-26 16:00
seriously can't reproduce it, do you have more precision on how you got that ?

**Comment by Glowbal** [comment] 2015-04-26 17:08
I noticed this last night as well. Same selections for me, though torso was always available.

**Comment by commy2** [comment] 2015-04-26 17:35
_Might_
Might be fixed in https://github.com/acemod/ACE3/commit/5320f4c6b70a0b73dc6514381207d3a54790fc30

I'm not sure though.

**Comment by dixon13** [comment] 2015-04-29 06:02
I can confirm that this is still an issue. Shot 6 Blufor units and only 2 of them worked fine when dead. The rest had at lease one interaction menu missing from the body.

**Comment by PabstMirror** [comment] 2015-04-29 07:38
Partial fix: enable skipping LOS check if <1 m

But, the core problem is that there's an intersection with the ground container.  Not really sure how to solve besides using the dreaded `lineIntersectsWith`.
![2015-04-29_00002](https://cloud.githubusercontent.com/assets/9376747/7386356/869b05be-ee18-11e4-9dae-2af3a0f1ae1d.jpg)

**Comment by PabstMirror** [comment] 2015-04-29 07:45
Could we change the
`model = "\A3\Weapons_f\dummyweapon.p3d";` 
to something that doesn't block LOS (could that break other things?)

**Comment by commy2** [comment] 2015-04-29 11:07
How does it break LOS?

**Comment by esteldunedain** [comment] 2015-04-30 12:05
I think @PabstMirror should fix this (actually he restored the original design, it was a typpo on my part).

**Comment by Glowbal** [comment] 2015-05-21 18:32
Is this already resolved? I remember a discussion on slack about this.

**Comment by esteldunedain** [comment] 2015-05-21 18:36
Yes, it's resolved. It was due to weapon holders "obstructing" the visiility check to the action point. Now the action points show regardless if you are close enough

**Closed by esteldunedain** 2015-05-21 18:36 UTC
Labels: BIS' fault, bug
