### ISSUE TITLE
Player will be 100% damaged (all body parts red), when only taking minor damage.

### ISSUE THREAD

**Issue by AppleSapje** [acemod/ACE3#1978] opened 2015-08-01 20:36 UTC
title explains itself

**Comment by MaHuJa** [comment] 2015-08-01 20:45
Possible duplicate of #1946

**Comment by SilentSpike** [comment] 2015-08-02 11:25
Known issue, will be fixed in a hotfix soon :+1:

**Closed by SilentSpike** 2015-08-02 11:25 UTC
Labels: duplicate
