### ISSUE TITLE
ace main requires addon a3_data_f_exp_b

### ISSUE THREAD

**Issue by isenhand** [acemod/ACE3#3653] opened 2016-04-03 07:27 UTC
**Arma 3 Version:** `latest Linux version installed via Steam`
**CBA Version:** `2.3.1` (stable / dev + commit hash)
**ACE3 Version:** `3.5.0` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
@cup_terrains
@asdg_jr
@chernarus_winter_a3_v1.11
@hiddenidentitypackv2
@pook
@rhsafrf
@sam
@sfp
@sfp_islands
@sfp_objects
@tacticalbeards
@BC-Phoenix
@ASR_AI3
@task_force_radio

**Description:**
- error message: Addon 'ace_main' requires addon 'a3_data_f_exp_b' after a while I get error message: Bad version 70 in p3d file 'z\ace\addons\attach\data\ace_irstrobe.p3d'
Then the game closes. 

**Steps to reproduce:**
- install steam under linux (I am using debian 8.1).
- install ARMA 3
- play ARMA 3

**Where did the issue occur?**
- during start up. 

**Placed Modules:**
- none. Application fails to start.

**RPT log file:**
- can't find that under linux.

Additional: the mod appears to work fine under linux for the server. I run both server and client (on different machines) under linux with the same mods.

**Comment by PabstMirror** [comment] 2016-04-03 07:35
Ref #3137

Linux version of arma is 1.54, current release of ace is targeting 1.56.
We also do not have .so (linux dlls) for some modules.

**Comment by commy2** [comment] 2016-04-03 07:37
Linux build is not supported. Close as duplicate of 3137

**Closed by commy2** 2016-04-03 07:37 UTC
