### ISSUE TITLE
Medical - Autocannon rounds cause wrong wounding style

### ISSUE THREAD

**Issue by Blutze** [acemod/ACE3#7401] opened 2020-01-05 11:10 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96`
- **CBA:** `3.13.0`
- **ACE3:** `3.13.0 release`

**Description:**
Both direct and indirect hits from autocannon HE rounds are causing single gunshot wounds (velocity/avulsion) instead of the expected explosive behavior (multiple wounds per attack, spread across the body, including crushed tissue/scrape and cut/laceration/puncture, even without ACE Fragmentation).
Decent body armor will allow AI to even shrug off multiple direct hits (with the usual bleedout caveat, but that doesn't stop them from ending the mission for you in the next 30 seconds when they should instead be trying to stuff their intestines back into their bodies).

**Where did the issue occur?**
- Editor (Singleplayer)

**Log Files:**
- RPT: https://gist.github.com/Blutze/b8e94f66561a30d89f33c80c70fb10bf
- Settings: https://gist.github.com/Blutze/35100528afaa20ff036119667776cbd2

**Additional context:**
Verified happening (and generated RPT) with just CBA+ACE and using vanilla assets, but also happens with modded stuff (Redd&Tank cannon, RHS vests)

**Screenshots:**
Vanilla Bardelas, exactly 20 rounds fired, some direct hits, rest impacting a wall ~3 meters behind the target
![image](https://user-images.githubusercontent.com/37950828/71778731-cd66ba80-2fb1-11ea-8a56-ab0c757e75fe.png)

Vanilla Badger, single indirect hit
![image](https://user-images.githubusercontent.com/37950828/71778827-ee7bdb00-2fb2-11ea-8d01-f407ffcd8d56.png)

Vanilla Badger, three indirect hits, EOD Vest + ECH, one velocity wound on leg
![image](https://user-images.githubusercontent.com/37950828/71778895-d8224f00-2fb3-11ea-98b5-b9e8d51d3026.png)

**Comment by dedmen** [comment] 2020-01-05 16:20
explains what I heard yesterday, a dozen shots in chest with 20mm autocannon for AI to die.
Guess they were handled as normal bullets, and got stuck in the vest.

**Comment by PabstMirror** [comment] 2020-02-22 22:24
Hoping #7415 will help, will investigate further after that is merged

**Comment by pterolatypus** [comment] 2020-03-18 16:19
I think the issue is that autocannon rounds inherit from `BulletBase` so are treated as bullets in [getTypeOfDamage](https://github.com/acemod/ACE3/blob/be3d69ff251a4db5b7e7124722b14be31294de6b/addons/medical_damage/functions/fnc_getTypeOfDamage.sqf#L21)
Simple solution is to add exceptions to that function for specific ammo types, but would it be better to have some config-based system for compatibility?

**Closed** 2020-04-08 02:52 UTC
Labels: kind/bug
