### ISSUE TITLE
In ACE3 AI not react on any explosion (not switch in the danger mode)

### ISSUE THREAD

**Issue by ghost** [acemod/ACE3#2654] opened 2015-09-30 09:16 UTC
ACE3 Version: 3.3.2
Stable version 1.52

**Mods:**
- `@CBA_A3`
- `@ace`
- `@DragonFyre`

**Placed ACE3 Modules:**
None

**Description:**
At first I thought it was a problem of the vanilla game, but when I turned off the ACE3 mod, I saw that there is no problem! No doubt in ACE3, the AI does not react to a explosion next to him and does not switch to danger mode. I think this is a big problem. 

**Steps to reproduce:**
Download my repro-mission from here: https://yadi.sk/d/KPz1aXEujRBAj
Try my repro mission with ACE3 and without ACE3 . You will see, that the vanilla AI in the game, will react to the explosion, but in the ACE3 will not. The patrol will continue walk in safe mode, even after the explosion.

1) set under plane your explosive charge with timer 40 sec
2) move from explosion area far
3) open camera and watch the enemy AI reaction (after big explosion with death aircraft)

**Where did the issue occur?**
Editor

**RPT log file:**
https://yadi.sk/d/NdOzbStXjRcfJ

**Comment by alganthe** [comment] 2015-09-30 12:43
I can't reproduce, can you provide a RPT to check if there's no errors ?

**Comment by mickeymen** [comment] 2015-09-30 12:52
"I can't reproduce" 

OMG! What's the problem? I provided repro-mission! Load this mission and check.
You also can create repro mission independently, within one minute. 
Place in your map the enemy patrol  with moving in safe mode, and blow up explosive charge.

**Comment by alganthe** [comment] 2015-09-30 12:54
Well yeah, and with only CBA and ACE3 they enter danger mode right away,

**Comment by mickeymen** [comment] 2015-09-30 13:01
I only use 3 mods. CBA, ACE3, DragonFyre(!only sound mod).
If I use all this mods, then my AI doesn't react to the explosion and does not go into danger mode. But if I disable CBA and ACE3, then everything works correctly! 
No need to finish Harvard University to understand what the the problem is in the CBA, ACE3 mods.

**Comment by bux578** [comment] 2015-09-30 13:11
@mickeymen Please stop behaving like a douche. If @alganthe can't reproduce it with only cba and ace3 it might be because of Dragonfyre. Dragonfyre is known to cause some wierd behavior in Arma 3 in general. There's a reason why we have: 

```
If you have found an issue with ACE3 please make sure that ACE3 is really the cause of the problem. To do this try to reproduce the issue with using only @CBA_A3 and @ace on a newly created mission.
```

on our page "How to report an issue" page: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

We appreciate your feedback. But please stick to a friendly tone.

**Comment by mickeymen** [comment] 2015-09-30 13:14
@bux578 please watch his speech. The "douche" is sitting in your head

**Comment by alganthe** [comment] 2015-09-30 13:16
Sorry if you felt offended, that wasn't my intention.
I'm trying to help you find the source of your issue, nothing else.

**Comment by mickeymen** [comment] 2015-09-30 13:17
I'm not insulting people, why insult me? I just want to make ACE3 better and don't deserve insults

**Comment by jonpas** [comment] 2015-09-30 13:18
I'd just close this issue, the reporter does not deserve help with that kind of behaviour.

**Comment by Glowbal** [comment] 2015-09-30 13:20
Hi @mickeymen,

Please try to see if this issue also occures without Dragonfyre. This would help us assess whatever or not there is a conflict. Unfortunally there is not much we can do without this information. 

I'd also like to request an RPT log file.

Thanks.

**Comment by mickeymen** [comment] 2015-09-30 13:26
Hi @Global, Ok I will provide this information later

**Comment by Glowbal** [comment] 2015-09-30 13:27
Thank you @mickeymen

**Comment by alganthe** [comment] 2015-09-30 13:32
Made some more tests just to be sure, and I found why I couldn't spot the issue previously.
If some shrapnel hit them they will go into combat mode, if they are unharmed they will ignore the explosion.
Issue confirmed.
Tested with CBA_A3 2.0, ACE3.3.2 stable and Arma 3 1.52 stable

**Comment by mickeymen** [comment] 2015-09-30 13:47
@Glowbal And yet I was right.
I have test without DragonFyre, but with CBA and ACE3 mod and the problem was still present.
my rpt can be loaded from here: https://yadi.sk/d/NdOzbStXjRcfJ

**Comment by ViperMaul** [comment] 2015-09-30 13:50
@mickeymen 
I get the following screen when I click your link 
https://gyazo.com/c7d41ff1c9b36dbff72cd0723c82ef79

**Comment by mickeymen** [comment] 2015-09-30 13:54
@ViperMaul 
this is a temporary Problem with the site. Please tell me where I can upload a repro mission, and my rpt and I'll do it

**Comment by ViperMaul** [comment] 2015-09-30 14:00
The RPT link works now.

**Comment by mickeymen** [comment] 2015-09-30 14:10
excellent. please fix this issue

**Comment by Glowbal** [comment] 2015-09-30 14:48
I've been able to reproduce this. This seems to be caused by a difference between the engine based explosives and the ACE explosives. We use `createVehicle` for the explosive. This does not seem to trigger any reaction from near by AI.

**Comment by mickeymen** [comment] 2015-09-30 15:00
Anyway the problem may be only in ACE3 or CBA. Probably need time to understand why.

**Comment by Glowbal** [comment] 2015-09-30 15:08
Yes, as I mentioned the issue is caused by ACE explosives. We will look into this some more and fix it if it's feasable.

**Comment by mickeymen** [comment] 2015-09-30 15:33
Thank you

**Comment by PabstMirror** [comment] 2015-09-30 17:50
Core problem is a BIS issue, AI should react to an explosion; even if it is scripted.

Possible workaround would be to have the player (or maybe a fake game logic?) do
```
ace_logic selectWeapon "DirectionalMineRemoteMuzzle";
ace_logic fire ["DirectionalMineRemoteMuzzle", "DirectionalMineRemoteMuzzle", "ClaymoreDirectionalMine_Remote_Mag"];
```

That might get the game to recognize it as a "real" explosive??
If you just put an exploisives named x down in the editor and then do `x setDamage 1;` do the AI react as they should?

To be honest I would much rather BIS fix this than have us try to hack together a workaround. I would suggest making a bug report (http://feedback.arma3.com/).

**Comment by gienkov** [comment] 2015-09-30 18:12
With ASR AI 3 you get reactions to explosions and shoots fired etc.
30 wrz 2015 19:50 "PabstMirror" <notifications@github.com> napisał(a):

**Comment by mickeymen** [comment] 2015-12-12 14:37
THIS BUG STILL NOT FIXED! - (version ACE3 -3.4.1)

**Comment by jokoho48** [comment] 2015-12-12 14:41
@mickeymen this is not a ACE issue please this is a BI issue that mean we CAN NOT fix this please report this to BI

**Comment by mickeymen** [comment] 2015-12-12 14:42
It is not clear why is it BIS fault? Because In vanilla game works correctly, I see the error only in ACE3!

**Comment by jokoho48** [comment] 2015-12-12 14:45
https://github.com/acemod/ACE3/issues/2654#issuecomment-144489312

**Comment by mickeymen** [comment] 2015-12-12 14:54
I already tried to understand it, but I can't( 
I know one. Before ACE3 I had no such problem

**Comment by commy2** [comment] 2015-12-12 15:34
>Without ACE3 I don't have this problem. Then the problem is in ACE3

This is a non-sequitur.

**Comment by mickeymen** [comment] 2015-12-12 17:10
My friend, If the problem is in BIS, but not in ACE3 and you understand this issue, then it will be better to report the problem to you, not me/ Again non-sequitur, or not? 

Please create a special ticket here http://feedback.arma3.com/

**Comment by ace3mod** [comment] 2016-12-16 00:00
Hello @acemod/maintainers. This ticket has been open for over 369 days without any activity.

**Comment by commy2** [comment] 2016-12-16 12:00
Still an issue and still potentially solvable by using
https://community.bistudio.com/wiki/createMine
https://community.bistudio.com/wiki/addOwnedMine
https://community.bistudio.com/wiki/Arma_3_Actions#TouchOff

**Comment by Mike-MF** [comment] 2023-09-11 00:40
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Closed by Mike-MF** 2023-09-11 00:40 UTC
Labels: fault/BI
