### ISSUE TITLE
Mk6 mortars break when rearming the entire static from a rearm point.

### ISSUE THREAD

**Issue by StormCircuit** [acemod/ACE3#9179] opened 2023-03-29 18:26 UTC
Mods (complete and add to the following information):
    Arma 3: 2.12.150301
    CBA: 3.15.8
    ACE3: 3.15.2

**Description:**
Mk6 mortars break when using the wrong reload option from an ammo truck. In other words, an ammo truck gives a user, who is close enough to a mortar, the option to rearm the mortar vehicle even with CSW reloading enabled (see screenshots).

**Steps to reproduce:**
Enable ammo handling for CSW
Plop mortar and ammo truck down somehow (or assemble, both had issue)
Move mortar near truck (or otherwise get it there)
Try to rearm the entire mortar "vehicle". In other words, you should have the option to rearm the actual mortar vehicle  IN ADDITION to the working option of just pulling out a certain type of round.
Observe that mortar no longer can be reloaded by the barrel or any other way after rearming the vehicle from the rearm point

**Expected behavior:**
For the truck to not present the reload option for the entire mortar when using CSW ammo handling

**Where did the issue occur?**
Dedicated

**Log Files:**
Let me know if you need them as digging up logs is a pain for my system. Can do if asked though.

**Additional context:**
Tried in Overthrow Altis and in KP Liberation, both had issue.

**Screenshots:**
https://imgur.com/a/612W4Da

**Comment by StormCircuit** [comment] 2023-03-29 19:08
Discussion occured on ACE discord where someone more talented than me managed to find the magazines actually loaded in the weapon (I think? I don't actually understand arma scripting):
https://discord.com/channels/976165959041679380/976224710385877002/1090707911493296158

**Comment by killerswin2** [comment] 2023-03-29 19:27
https://youtu.be/GbpCPKPzDHc video of reproduction

**Comment by markooff** [comment] 2023-04-01 10:41
The same problem, but NOT THE SAME REASON :) 

The situation (described ABOVE)  - has a reason in not working features for handling the ammunition  - in MK6 MORTAR  !! (in other types of mortars like RHS M252 or Podnos - everything work OK )

Even if You want to rearm Your Mk6 MANUALLY (!) - you cannot find a point (ACE3 - interaction point) for ammunition handling on it. 

Below is a video showing this problem precisely  :
https://youtu.be/2d_S3QHm4g4

On the left there is Mk6 (placed from Zeus) - in center there are 2 ammunition crates (each filled with 20 shells) - and on the right side there is M252 mortar where everything works fine

**Comment by markooff** [comment] 2023-04-01 10:49
UPD: Below you have some screenshots with the ACE3 settings on which these tests were performed:



https://markooff.net/obrazki/PGM/bledy_army_ACE_itp/Mortar_Mk6_ammo_handling_error/Arma3_x64_2023-04-01_12-41-32-86.jpg


https://markooff.net/obrazki/PGM/bledy_army_ACE_itp/Mortar_Mk6_ammo_handling_error/Arma3_x64_2023-04-01_12-41-44-36.jpg


https://markooff.net/obrazki/PGM/bledy_army_ACE_itp/Mortar_Mk6_ammo_handling_error/Arma3_x64_2023-04-01_12-41-51-48.jpg

**Comment by markooff** [comment] 2023-04-01 11:13
SO solution for TODAY - is NOT TO USE MK6 mortar in JOPs 

" If You have a problem and You'll need to use mortar-fire :) - just use RHS MORTARS INSTEAD :) :D "

**Comment by Wakbub** [comment] 2023-04-06 20:25
This is known for three years and a dupe of #7372.

**Comment by markooff** [comment] 2023-06-28 10:43
[qu] " Unable to reload MK19 mortar "  [/qu]
:) not quite - but indeed looks similiar ... 
And - perhaps this has the same reason then ammo-handling problem in Mk6.

Moreover AFAIR - together with my Team - I don't remember a time more than 3-4 months ago that such a problem affected the Mk6. It may sounds a bit strange (I know) :) but indeed, during last 3-4 years of using an our mortar componnent (sometimes masively) in JOPs and trainings - I think, we should find it earlier....

**Closed** 2023-08-18 17:10 UTC
Labels: kind/bug
