### ISSUE TITLE
water barrel config issue

### ISSUE THREAD

**Issue by heavymetalwelds** [acemod/ACE3#8693] opened 2021-11-21 22:23 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.x.x` [eg. 3.0.0 stable, commit hash]

**Description:**
on start up i get and issue
filez\ace\addons\fieldrations\cnfgvehicles.hpp blahblah blah at the end it says ( encountered instead of=

i deleted the pbo manually, and then another came up instead, wound up being like 10 pbos that were corrupt . i got the game to play without them but would crash. game was running ok i would get an outdated error on ace but its all up to date tried reinstalling it didnt help

i do have a bunch of mods but they havent ever conflicted with ace before and i was able to single it out to ace. even if its the only mod loaded
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. _Go to ..._
2. _Click ..._
3. _See ..._

**Expected behavior:**

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**

**Screenshots:**

**Comment by veteran29** [comment] 2021-11-21 23:31
Most likely a duplicate of #8570

See: https://github.com/acemod/ACE3/issues/8570#issuecomment-948989112

No RPT, closing as invalid.

**Closed by veteran29** 2021-11-21 23:31 UTC
Labels: kind/bug, status/invalid
