### ISSUE TITLE
Interaction Menu sometimes opens when releasing the Self-Interaction Menu Key Combo

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#767] opened 2015-04-19 09:14 UTC
ACE3 Version: custom 17.04.2015

Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
No, checked in VR.

Description:
Sometimes you see the "Bandage" or "Morhine" or ... but when you choose it, the process halts (you see the animation and used bandages/morphine injectors/epipens on the ground but healing not occur).
Here is the video of bug: https://mega.co.nz/#!WJEgEaaY!weS9vn6ppNwURPrgu54oI-_c1Pf_GH3KjkVrOkeJ72I

Steps to reproduce:
Don't find 100% conditions.  Probably occurs if you too close to the patient.

Where did the issue occur?
Checked in VR, multiplayer (don't know what kind of modules there were).

RPT log file:
No

**Comment by commy2** [comment] 2015-04-19 09:32
Thanks for reporting.

Can you choose a more descrptive issue title, please? It's easier to distinguish different issues if they don't have such inexpressive names like: "Medical Bug".

**Comment by Glowbal** [comment] 2015-04-19 09:42
I will need an rtp log, please.

**Comment by ruPaladin** [comment] 2015-04-19 09:46
Here it is https://mega.co.nz/#!XJMF0B7J!vPMwpHR5Zj64LDEU6Z-m1bbHCB3ia5O342HKb1DHFGM

**Comment by ruPaladin** [comment] 2015-04-19 09:58
Done https://mega.co.nz/#!TN8HGbZb!HJsPc10K6YhfMali9i3KCd6p-K9p5GIWtMHPZ81KcEA
Bug was reproduced. First treatment was ok, but then it failed three times.

**Comment by jaynus** [comment] 2015-04-19 15:51
Is this reproduced without custom malloc? Those are known to cause issues.

**Comment by ruPaladin** [comment] 2015-04-19 16:41
Yes, check my second link.

**Comment by Glowbal** [comment] 2015-04-19 16:46
I cannot reproduce this.

**Comment by ruPaladin** [comment] 2015-04-19 17:19
Ok, I found the problem and steps to reproduce. Sorry for you time, devs.
I changed keybindings in ACE settings.
Windows - self-interaction key
Ctrl+Windows - interaction with others
To start treatment you have to release keys Ctrl+Windows.
When you release Windows key and then Ctrl key - everything is ok.
When you release Ctrl key first and then Windows key - you will get this problem.
That is the problem.

**Comment by Glowbal** [comment] 2015-04-19 17:41
Ok, probably means this:
* Upon release of ctrl, treatment starts, since interaction is closed
* Detects windows key is pressed. Start self interaction
* progress bar detects interaction started, cancels progress resulting in treatment failed.

**Comment by ruPaladin** [comment] 2015-04-19 17:58
Yes, it is. Sorry for my english.

**Comment by NouberNou** [comment] 2015-04-20 06:37
So is this a CBA issue then? Or is it even a problem.

It comes down to a question of how key-combos should break... Hmmm....

**Comment by Glowbal** [comment] 2015-04-20 07:33
This is most likely a CBA issue. I believe @jaynus said it's a known issue.

**Comment by ulteq** [comment] 2015-04-20 07:46
The same issue exists when you try to open a device (microDagr, ATragMX, ...).
You have to release the Windows key first or the tool will not open.

**Comment by esteldunedain** [comment] 2015-04-20 13:53
> Ok, probably means this:
Upon release of ctrl, treatment starts, since interaction is closed
Detects windows key is pressed. Start self interaction
progress bar detects interaction started, cancels progress resulting in treatment failed.

The thing is: for this to happen CBA must be sending a KeyDown event for the Win Key, which is wrong.

>So is this a CBA issue then? Or is it even a problem?
> It comes down to a question of how key-combos should break... Hmmm....

@NouberNou, yes that's an issue. No KeyDown event should be ever raised when releasing keys.

------------- 

I could install some workaround on the interact_menu to prevent this (e.g., forbid opening the interaction menu if self interaction was closed the frame before), but this should be also fixed in cba.

**Comment by jaynus** [comment] 2015-04-20 16:15
I dont think that its wrong though; you are releasing the keys and then are, in fact, hitting the windows key so therefore the key is being pressed so its a valid key press.

This would mean that CBA is incorrect in the assumption that it should always send key events, and should somehow filter them; which is not true. 

The crux of the issue is frist you are pressing A+B, which is a bind. Then you are pressing just B, which is also a keybind. Alterative, A could be another. 

Are we suggesting that CBA filter, and not trigger A or B if A+B was released in the same key press?

**Comment by esteldunedain** [comment] 2015-04-20 16:44
Imagine this operation:

1- User press and holds A
2- User press and holds B
3- User releases B
4- User releases A

CBA is apparently throwing a keyDown event for A on step 3. IMO that's wrong, cause keyDown should only through the moment a key is pressed (cause allow holding = false), and no key was pressed at that moment.

**Comment by jaynus** [comment] 2015-04-20 19:01
Ah so its re-firing? Yah - i dont think it should, it should *always* be a single fire. @NouberNou

**Comment by ViperMaul** [comment] 2015-05-26 15:09
This appears to be fixed in the next release of RC7

**Comment by ruPaladin** [comment] 2015-05-29 07:40
It is a pity but the problem is not solved. It is still an issue. Please re-open.

**Comment by esteldunedain** [comment] 2015-05-29 11:52
Can anybody else reproduce?

**Comment by SilentSpike** [comment] 2015-05-29 12:27
I've experienced this occasionally while testing the GM menu I'm working on

**Comment by ViperMaul** [comment] 2015-05-29 13:23
@SilentSpike 
Give us your specific repo steps. 
@ruPaladin 
How about your specific situation? Is it fixed or still an issue?

**Comment by SilentSpike** [comment] 2015-05-29 13:27
I don't have specific repo steps other than what's already been discussed as it doesn't happen often enough for me to really know, though I can confirm I'm using the latest CBA (RC7)

**Comment by ruPaladin** [comment] 2015-05-29 13:31
I will post a video in 1-2 hours.

**Comment by ruPaladin** [comment] 2015-05-29 13:54
Here it is: https://mega.co.nz/#!Gc1UgTBZ!3x0cRdnfcyHeWj-CIi8eDOouhs4B7_x3eylzd_58iXs
On 0:04 you may see versions of CBA and ACE3.
1:05 I release Left Control but Windows key is still pressed.
1:16 the same situation.
1:21 I release Windows key and Ctrl key is still pressed.
You have to release Windows key first otherwise the process halts cause self-Interaction menu opens.
1:42 my keybindings showed. Windows key - self-interaction and LCtrl+Windows key - interaction menu.

**Comment by commy2** [comment] 2015-12-09 14:51
Close: https://github.com/CBATeam/CBA_A3/issues/213

**Closed by commy2** 2015-12-09 14:51 UTC
Labels: bug, CBA's fault
