### ISSUE TITLE
Black magazines don't work with MX* weapons

### ISSUE THREAD

**Issue by krieghof** [acemod/ACE3#7001] opened 2019-05-16 16:04 UTC
**Arma 3 Version:** `x.xx` (stable)
**CBA Version:** `3.x.x` (stable)
**ACE3 Version:** `3.x.x` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The MX* weapons don't work with the 6.5 mm 30 RnD Black magazines.
https://imgur.com/a/7DyhRVn

**Steps to reproduce:**
- Use the Armory in the Campaign.

**Where did the issue occur?**
- Singleplayer

**Additional information:**
- I think "30Rnd_65x39_caseless_black_mag"is missing in ballistics/CfgWeapons.hpp

**Comment by Blutze** [comment] 2019-05-16 18:19
Duplicate of https://github.com/acemod/ACE3/issues/6973, fixed in https://github.com/acemod/ACE3/pull/6974.

**Comment by jonpas** [comment] 2019-05-16 18:27
Thank you @Blutze.

**Closed by jonpas** 2019-05-16 18:27 UTC
Labels: status/duplicate
