### ISSUE TITLE
Mine detector plays detection sound without headphones connected

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#4381] opened 2016-09-11 21:02 UTC
**Arma 3 Version:** `1.62`
**CBA Version:** `3.0.0`
**ACE3 Version:** https://github.com/acemod/ACE3/commit/a9b82513f7de0e53003bad7187a466a36613da9b

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Mine detector will play detection sound even without headphones being connected:

https://youtu.be/3Q44Ge19MtY

**Steps to reproduce:**
- Grab a mine detector, activate it
- Go near a mine so you can start hearing the detector sound
- Try switching headphones on/off - doesn't affect anything

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- 

**RPT log file:**
-

**Comment by PabstMirror** [comment] 2016-09-11 21:05
I think no-headphones means that the sound is played though the devices speaker.
Which means that other players can hear as well.

So you will hear it almost the same in either mode, IIRC

**Comment by gienkov** [comment] 2016-09-11 21:10
Oh, I didn't knew that. Thanks!

**Comment by gienkov** [comment] 2016-09-11 21:28
Still, shouldn't wearing such massive headphones at least decrease environment sound by some % ?

**Comment by bux578** [comment] 2016-09-11 21:32
> massive

why massive?

**Comment by gienkov** [comment] 2016-09-11 21:36
![](http://i.imged.pl/wykrywacz-metali-garrett-at-pro-sluchawki-zestaw.jpg)

Well they look like they are able to attenuate environment sounds.

**Comment by esteldunedain** [comment] 2016-09-12 11:55
I don't think we should attenuate sounds; it's not worth the trouble imo.

**Comment by esteldunedain** [comment] 2016-09-12 11:55
BTW, I remember seeing a video of a not-so-modern military minesweeper on youtube, similar to the one in ACE. and the headphones were cheap crap, like lifted off a walkman.

**Comment by Glowbal** [comment] 2016-09-13 10:35
By design. Closing.

**Closed by Glowbal** 2016-09-13 10:35 UTC
Labels: by design
