### ISSUE TITLE
Game becomes unresponsive (crash) on medical treatment

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#1463] opened 2015-06-01 08:59 UTC
ACE / CBA RC7

Happened in session while applying a morphine.  On releasing the key the game became unresponsive (window spin/sandtimer)

Reproducing constantly in basic and advanced:
Get a stack of bandages, try to make yourself a mummy.

Advanced Medical it happened while checking pulse - as first interaction of the game

Even when it does work fine I do notice some occasional lag//hesitation when releasing the self-interact key.

Video of Basic Medical while bandaging (maybe 10th bandage):
https://www.youtube.com/watch?v=LQoNfWOkYkM

Normal bandage in video (there's a lot of custom trace/debug):
```
 2:28:19 [19019,252.664,71.712,"z\ace\addons\interact_menu\functions\fnc_render.sqf:25","render: ace_interact_menu_openedMenuType=1"]
 2:28:19 [19020,252.679,71.727,"z\ace\addons\interact_menu\functions\fnc_render.sqf:25","render: ace_interact_menu_openedMenuType=1"]
 2:28:19 [19021,252.693,71.742,"z\ace\addons\interact_menu\functions\fnc_render.sqf:25","render: ace_interact_menu_openedMenuType=1"]
 2:28:19 [19021,252.699,71.742,"z\ace\addons\interact_menu\functions\fnc_keyUp.sqf:19","keyUP: _calledByClicking=false"]
 2:28:19 [19021,252.699,71.742,"z\ace\addons\interact_menu\functions\fnc_keyUp.sqf:28","GVAR(actionSelected): ace_interact_menu_actionSelected=true"]
 2:28:19 [19021,252.7,71.742,"z\ace\addons\interact_menu\functions\fnc_keyUp.sqf:46","checkFunction: 4=4"]
 2:28:19 [19021,252.7,71.742,"z\ace\addons\medical\functions\fnc_treatment.sqf:25","treatment: _className=Bandage"]
 2:28:19 [19021,252.7,71.742,"z\ace\addons\interact_menu\functions\fnc_keyUp.sqf:51","called Function: 5=5"]
 2:28:19 [19021,252.7,71.742,"z\ace\addons\interact_menu\functions\fnc_keyUp.sqf:68","keyUP: ace_interact_menu_openedMenuType=-1"]
 2:28:19 [19022,252.703,71.757,"z\ace\addons\medical\functions\fnc_treatment.sqf:25","treatment: _className=Bandage"]
 2:28:24 [19507,257.707,76.698,"z\ace\addons\medical\functions\fnc_handleCreateLitter.sqf:6","EXPLODE_3 _this: _litterClass=ACE_MedicalLitter_bandage2, _position=[1738.6,5720.09,0], _direction=336.519"]
```

Crash bandage:
```
 2:28:27 [19726,260.562,79.546,"z\ace\addons\interact_menu\functions\fnc_render.sqf:25","render: ace_interact_menu_openedMenuType=1"]
 2:28:27 [19727,260.576,79.561,"z\ace\addons\interact_menu\functions\fnc_render.sqf:25","render: ace_interact_menu_openedMenuType=1"]
 2:28:27 [19728,260.591,79.576,"z\ace\addons\interact_menu\functions\fnc_render.sqf:25","render: ace_interact_menu_openedMenuType=1"]
 //key release - unresponsive
 //6 minutes later, vmem crash:
 2:34:04 EPE manager release (0|0|0)
 ```
Note that fnc_keyUp never seems to be called
6 minutes later, this popped up this and hard crashed:
![untitled](https://cloud.githubusercontent.com/assets/9376747/7909151/dcce4f16-080f-11e5-83af-71d77743524e.png)

So it looks like somewhere between CBA Keybinds -> Interact Menu -> Medical there's something going into an endless loop?

**Comment by Glowbal** [comment] 2015-06-01 10:38
Checking pulse and a treatment action go through different functions on the medical aspect. Common factor in this is the usage of the `remoteExec` function and interaction.

**Comment by esteldunedain** [comment] 2015-06-01 17:30
Hold on, is this reproduceable in SP?

**Comment by PabstMirror** [comment] 2015-06-01 17:31
SP and MP

**Comment by esteldunedain** [comment] 2015-06-01 17:33
@PabstMirror, if you can repro I think you need to litter that code with `diag_log`, so we can pinpoint which code is getting reached and which it isn't

**Comment by esteldunedain** [comment] 2015-06-01 17:39
The thing is supposed to work like this:

1. Key is released
2. FUNC(keyUp) is called
3. On that function:
  3.1. All interact menu caches are cleared
  3.2. The selected action condition is reevaluated to see if it still applicable
  3.3. The selected action statement is called
  3.4. Caches are cleared again to make things ready for the next menu opening
  3.5. The "interactMenuClosed" event is raised

We need to determine at what stage of the thing execution is halting. I'm not sure how, because keyUp function is obviously being called (nothing would happen otherwise), and it's not showing on the log, probably due to file write cache not being flushed before the crash

**Comment by PabstMirror** [comment] 2015-06-01 17:59
Treatment was calling this:
```
if (uiNamespace getVariable [QEGVAR(interact_menu,cursorMenuOpened),false]) exitwith {
    [{
        _this call FUNC(treatment);
    }, _this, 0, 0] call EFUNC(common,waitAndExecute);
};
```

And with the changes to waitAndExecute, that can cause an endless loop (or 10,000?) because there is no frame delay anymore and the delay is "0".

```
Frame 20220 - Treatment Start
Frame 20220 - Delaying treatment because menu open
Frame 20220 - Treatment Start
Frame 20220 - Delaying treatment because menu open
Frame 20220 - Treatment Start
Frame 20220 - Delaying treatment because menu open
Frame 20220 - Treatment Start
Frame 20220 - Delaying treatment because menu open
```

switching to execNextFrame seems to fix, going to do more testing.

**Comment by esteldunedain** [comment] 2015-06-01 18:04
Well done debugging that! tbh I'm glad it's not a problem with the IM.

BTW, I'm pretty sure that whole code can be scrapped. I think it was in place to avoid the interact menu  closing the progress bar just after it was created, but now the IM deletes it's dialog before calling the action so it shouldn't be neccesary.

**Closed** 2015-06-01 18:14 UTC
Labels: critical bug
