### ISSUE TITLE
RHS/BWMod ATGMs broken with ACE

### ISSUE THREAD

**Issue by rlex** [acemod/ACE3#857] opened 2015-04-25 17:26 UTC
ACE3 Version: master

**Mods:**
* @cba_a3
* @ace3
* @RHSAFRF
* @RHSUSAF
* @BWMOD

**Placed ACE3 Modules:**
* None

**Description:**
* Compatibility issue. ATGM rockets acts weird with ACE installed. Affected: Puma from BWMod, BMD-4A from RHS (at least). Maybe new missile guidance is somehow related.

**Steps to reproduce:**
* Install listed mods. 
* Place Puma / BMD-4A in editor. 
* (Most likely other vehicles with ATGM affected as well)
* Switch to ATGM for main gun
* Fire missile
* Drunken missiles FTW! Impossible to hit anything with them.

**Where did the issue occur?**
* VR, SP Editor, MP

**RPT log file:**
* No RPT for now.

**Comment by jaynus** [comment] 2015-04-25 17:39
I am re-working the AMG config entires; it turns out most mod makers are inheriting from Titan's.

**Comment by commy2** [comment] 2015-04-25 17:47
BWMod will change that with the next release though. (If that ever comes out)

**Comment by QuintusGARS** [comment] 2015-04-27 12:31
Same problem with BMP 2's konkurs missiles.

**Comment by jaynus** [comment] 2015-04-28 07:24
@commy2 the problem is the mixture of inheriting random crap, so the missile and launchers don't match.

I've disabled inheritance on these configs now

**Comment by commy2** [comment] 2015-04-28 10:46
So is this fixed now?

**Comment by jaynus** [comment] 2015-04-28 15:09
Not yet, I need to test and PR today

**Closed** 2015-05-01 14:00 UTC
Labels: bug, Next Milestone?
