### ISSUE TITLE
ACE_SwitchUnits AI turns invincible

### ISSUE THREAD

**Issue by captainblaffer** [acemod/ACE3#1725] opened 2015-06-22 20:08 UTC
ACE3 Version: 3.1.1

Mods:
@CBA_A3;@ace;

Placed ACE3 Modules:
ACE_ModuleSwitchUnits

Description:
When a player leaves an AI he controlled using ACE_SwitchUnits, there is a high chance that AI becomes invincible. The AI keeps behaving normally except it being invincible. 

Using the command '_x setdamage 1' locally does not kill it. Executing setdamage 1 on the server does kill it(this was after I made sure all AI is owned by server using 'allAI = allUnits - playableUnits; {group _x setGroupOwner 2}foreach allAI;')

Steps to reproduce:
1.Create mission with SwitchUnits module.
2.Run mission on Dedicated server
3.Spawn AI on server using .sqf script.
4.Control an AI with SwitchUnits.
5.Switch to a different AI.
6.Try to kill the previous AI.

Where did the issue occur?
Dedicated

RPT log file:
http://pastebin.com/MCnr2XvG

Mission file (shouldn't be required to debug):
https://drive.google.com/file/d/0B-pcqje99exHaC1QRjh5Z1YyMHc/view?usp=sharing

**Comment by captainblaffer** [comment] 2015-06-22 20:58
Also occurs on ACE 3.1.1

**Comment by bux578** [comment] 2015-06-23 04:49
Could you please try it with a cba and ace3 only?

**Comment by captainblaffer** [comment] 2015-06-23 07:27
Will do tonight, will also check with a simpler test mission.

**Comment by captainblaffer** [comment] 2015-06-23 20:42
The issue still occurs when the server and client are just running ACE and CBA, and the mission is a completely new empty mission with just editor placed player, AI and switchunits module.

I've updated the post above.

RPT: http://pastebin.com/jSdFJyxe

**Comment by alganthe** [comment] 2015-06-25 18:52
can confirm on 3.1.1 only cba and ace3, dedicated.

**Comment by bux578** [comment] 2015-07-26 05:59
I can't reproduce. Following the steps provided the units are not invincible.

**Comment by captainblaffer** [comment] 2015-07-27 10:31
The frequency of the issue is not 100%.
Try switching between units and killing the unit you previously controlled 5-10 times. 

I'll make a video capture of the bug when I got the time.

**Comment by alganthe** [comment] 2015-07-27 13:51
Had the same issue, the unit could only be killed by setting it's HP to 0 in zeus.
No other source of damage had any effect on target
(ACE 3.1.1 stable)

**Comment by captainblaffer** [comment] 2015-07-27 20:12
Here is a video, first attempt:
https://www.youtube.com/watch?v=qm_BMvRdohA&feature=youtu.be

Using a mission with just editor placed Switchunits players and editor placed AI

At the second attempt it took me a while to get it. Try to switch between two units 4-6 times quickly, then shoot one of them.

**Comment by captainblaffer** [comment] 2015-11-29 14:16
re-upload of video from Jul 27: https://www.youtube.com/watch?v=QCFbDHbKa98&feature=youtu.be

**Comment by ace3mod** [comment] 2016-08-21 22:38
Hello!

We're automatically closing this issue since it has not received any updates or comments in the past 14 days. We therefore assume that the original reporter has lost interest or the issue has been resolved.

If this has been closed in erorr,  please create a comment below and we can reopen this issue. Note that you may need to provide additional information that was requested. 

Thanks!

**Closed by ace3mod** 2016-08-21 22:38 UTC
Labels: bug, can't reproduce
