### ISSUE TITLE
Explosives M112. I can not change the menu and twist it.

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#3499] opened 2016-03-02 10:24 UTC
**Arma 3 Version:** `1.56`

**ACE3 Version:** `3.5.0`

**Mods:**
* `@CBA_A3`
* `@ace`
* @ RHS

**Placed Modules:**
* *No modules.*

**Description:**
* *https://youtu.be/z1Xa0_5hWIo*

**Where did the issue occur?**
* *"Editor"*

**RPT log file:**
* *Add a link (pastebin.com) to the client and/or server RPT file. An instruction to find your RPT files can be [found here](https://community.bistudio.com/wiki/Crash_Files#Arma_3)*

**Comment by Kartaviy** [comment] 2016-03-02 11:31
With the same trenches

**Comment by commy2** [comment] 2016-03-02 12:43
requires RPT file

**Comment by Kartaviy** [comment] 2016-03-02 14:38
Well, what else can I show? Mina lowered to the ground I can not twist them, I can not either. Cancel operation, I can not either. When digging the trench and press ESC, the cancellation does not occur.

**Comment by jonpas** [comment] 2016-03-02 14:39
@commy2 it's the addAction hook issue we were talking about yesterday.

**Comment by esteldunedain** [comment] 2016-03-02 14:39
> @commy2 it's the addAction hook issue we were talking about yesterday.

I don't think it is

**Comment by gienkov** [comment] 2016-03-02 15:15
I can repro this.
02.03.2016 12:31 PM "Kartaviy" <notifications@github.com> napisał(a):

**Comment by esteldunedain** [comment] 2016-03-02 15:21
Please somebody upload a RPT log.

**Comment by Kartaviy** [comment] 2016-03-02 15:52
rpt - http://pastebin.com/h9bWsAqC

**Comment by jonpas** [comment] 2016-03-02 16:25
`ACE_Modifier` is always `0`, that's the cause, known CBA issue.

**Comment by esteldunedain** [comment] 2016-03-02 16:29
@Kartaviy, try rebinding the ACE modifier key once. That should prevent the bug in cba and make it work again.

This will probably be fixed soon in CBA.

**Comment by jonpas** [comment] 2016-03-02 16:43
And rotating objects will be fixed with #3507

**Comment by Radeni** [comment] 2016-03-02 19:18
This is the same issue that i had in past which i submitted but it turned out that it was only the issue in a specific mission so i tought it wasnt Ace's problem but mine.Im glad that this is going to get changed. the whole Mouse buttons and wheel system should be replaced with keybinds.

**Comment by commy2** [comment] 2016-03-02 20:17
It might have the same effect, but it is a different bug. The modifier key handling was rewritten (https://github.com/acemod/ACE3/blob/master/addons/common/init_handleModifierKey.sqf#L19), but unfortunetly CBA removes all keyDown and keyUp event handlers unless they are delayed by a sleep.
Which is a bug, I also fixed, but the fix isn't part of 1.3.1. I must've been operating under that fixed branch when testing this. Sry.

**Comment by commy2** [comment] 2016-03-02 22:16
Fixed in https://github.com/acemod/ACE3/pull/3507

**Closed by commy2** 2016-03-02 22:16 UTC
Labels: bug, CBA's fault
