### ISSUE TITLE
Scopes are locked when not using Adv. Ballistics

### ISSUE THREAD

**Issue by JBartlett108** [acemod/ACE3#5039] opened 2017-03-26 21:38 UTC
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.2.1` (stable)
**ACE3 Version:** `3.9.1` (stable)

**Mods:**
- CBA_A3
- ace
- RHS USAF 4.2.1 (sometimes used and tested)
- RHS AFRF 4.2.1 (sometimes used and tested)
- RHS GREF 4.2.1 (sometimes used and tested)
- RHS SAF 4.2.1 (sometimes used and tested)

**Description:**
- With advanced ballistics module placed, but everything on OFF, high power scopes cannot range and are locked at 100m. Same thing happens when there are absolutely NO MODULES on the mission, or when it is configured to my unit's liking (medical, logistics, etc.)

**Steps to reproduce:**
- Add playable player with any sniper rifle (M107, M200, M24, etc.) and give any high power scope (M84A1, AMS, LPRS, etc.). Add in Advanced Ballistics module and turn EVERYTHING off. Off for everyone, off for snipers, off on full-auto, everything. No matter what way you try to play it, you cant zero your scope. The number stays locked at 100m, and there's no movement when ADSing. Try it with any combination of weapon, scope... hell, even ammo. It stays locked. The same happens if you delete the module, save the mission, open another mission, and then re-open the original (to clear it from Eden). Also tried with and without RHS and their compats, to no avail.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Singleplayer) / Editor (Multiplayer)

It occurred on our dedicated "Operations" server, with and without a headless client, when I exported it to MP and hosted it on LAN, and when I ran it from Eden in both singleplayer and multiplayer.

**Placed Modules:**
- Advanced Ballistics, none, and nearly all of them (tested with each config, same result).

**RPT log file:**
- Will get ASAP

**Comment by AACO** [comment] 2017-03-27 15:17
When you're ADS do you hear clicking? And when you're not zoomed in, do you get an adjustment knob with a number readout? If so, that's part of the scopes framework (not advanced balistics) https://github.com/acemod/ACE3/tree/master/addons/scopes

You'll have to place the scopes module down and disable those settings from there.

**Comment by JBartlett108** [comment] 2017-03-27 15:22
Negative on both, there's simply no adjustment period

**Comment by PabstMirror** [comment] 2017-03-29 22:28
Check your keybinds for scope adjust
Controls -> Configure Addons -> Ace Scope Adjust
Should default to PageUp/Down

Pressing up should bring up the adjust info like this:
![image](https://cloud.githubusercontent.com/assets/9376747/24479482/28d5a398-14a5-11e7-8733-6dcfa1c10d3c.png)

**Comment by JBartlett108** [comment] 2017-03-29 22:41
> Pressing up should bring up the adjust info like this:

That would be great of it were true. It's like I'm saying, it doesn't pop up. I have 20+ other people that can also verify this, so this isn't some one-off corrupt install or something. Besides, it SHOULD be reverting to BASIC ballistics, ie REGULAR RANGING PER 100 METERS.

**Comment by bux** [comment] 2017-03-30 04:31
Findings:
* It works fine with vanilla weapons and scopes.

**Comment by MAD-BUG** [comment] 2017-04-10 23:34
Looks like deleting ace_scopes.pbo cause this effect. After deleting this pbo vanilla scopes start working with vanilla ranging but rhs scopes do not and stays at 100m. Only RHS scopes that have settings like this:
        class ItemInfo: InventoryOpticsItem_Base_F {
            class OpticsModes {
                class dedal_520 {
                    discreteDistance[] = {100};
                    discreteDistanceInitIndex = 0;
                };
            };
        };

**Comment by jonpas** [comment] 2017-04-10 23:58
Remove the RHS compat PBO as well then, pre-3.9.0 required separate config for scopes, compats were not updated as of yet afaik, so your result is expected @MAD-BUG

**Comment by MAD-BUG** [comment] 2017-04-11 00:28
So is there any way to not use mil dot system but still have compat pbo?

**Comment by Drift91** [comment] 2017-04-28 12:18
The module causing the problem is "_ace_scopes_ModuleSettings_" **NOT** "ace_advanced_ballistics_ModuleSettings".

@bux Before step 5 place a "ace_scopes_ModuleSettings" and do the following:
![image](https://cloud.githubusercontent.com/assets/2638764/25528267/ecda34c8-2bea-11e7-8122-91cae220e523.png)
The mildot will not work, as expected. However nor will the vanilla Zeroing, which is the problem.

**Comment by Stritt57** [comment] 2017-06-26 16:56
My group is having the exact same issue.

We want to use ACE for everything except for adv ballistics and scopes. If I disable adv ballistics and/or scopes, the vanilla zeroing no longer works and all optics are stuck at 100m.

**Comment by JaithWraith** [comment] 2017-07-20 02:56
> We want to use ACE for everything except for adv ballistics and scopes. If I disable adv ballistics and/or scopes, the vanilla zeroing no longer works and all optics are stuck at 100m.

My group is also experiencing this issue. All optics are stuck at 100m and changing keybindings does not help. We have been making missions with closer range encounters to try and avoid this.

**Comment by bux** [comment] 2017-07-20 05:33
@Stritt57 @JaithWraith what do you mean by "disable adv ballistics and/or scopes". And what mods are you using?

**Comment by Stritt57** [comment] 2017-07-20 10:32
Just like the OP, when I create a mission and place the ballistics module and disable it the scopes module locks all scopes to 100m zero and the ace turret mode.

If I disable ace scopes by placing a scope module and disabling it, then all scopes are locked to 100m and cannot be zeroed.

My group would like to be able to use standard arma "vanilla" zeroing. The t

I can confirm that it still in fact happens with cba_a3, ace, and all of the rhs mods. I will see if I get this same issue when just running cba_a3 and ace this evening.

**Comment by Laid3acK** [comment] 2017-07-23 10:05
The Scope Framework has a `discreteDistance[] = {100};` and all scopes are configured like that:
https://ace3mod.com/wiki/framework/scopes-framework.html

For this reason, the vanilla scope zeroing can't work when the Scopes module is disabled.

It could be possible to fix that by deleting this `discreteDistance[] = {100};`.

In this case, all vanilla scopes' `discreteDistance` should be updated with `discreteDistance[] ={100,200,300,...};` as the RHS scopes.

But it could be very confusing after with the Scopes module enabled because the player will have 
the Scopes module zeroing (default 100 meters) and the vanilla zeroing at the same time in-game.

If the player changes accidentally the `discrete Distance` (default keys Ctrl+mouse wheel Up/Down), 
the zeroing in-game (default 100 meters) will be incorrect (the shots too).

The new `discreteDistance` updates also the range card `ZERO` and the bullet drop (for the both ballistics).

It could be a feature if the player uses it carefully ... or a big problem for him.

But, by this way, the vanilla zeroing can be restored with a Scopes module disabled.

At this time, i'm experimenting this possibility with a Bnae scopes compat for my personal use and for test.

There is no problem only if the ACE scope adjustment and the Zeroing Up/Down have got exactly the same keybinds in the CONTROLS Options.

Deleting the default keys `Ctrl+mouse wheel Up/Down` (Zeroing Up/Down) in the Weapons Controls Options seems to be a good solution to avoid conflicts between Scopes module zeroing and Vanilla zeroing with the Scopes module enabled.
(`Page Up/Down` has an effect only on the sniper scope, not on the vanilla zeroing)

I can make a quick PR if you want. Maybe only with the RHS compats for test ?

**Comment by jonpas** [comment] 2017-07-23 12:25
I thought https://github.com/acemod/ACE3/pull/4642 was supposed to get rid of `discreteDistance`?

**Comment by Stritt57** [comment] 2017-07-23 15:40
I thought it was too... 

The real question is why there an option to disable ace scopes adjustments in the scopes module if it doesn't work? What does that dropdown even do right now?

If the ace scopes module is disabled, then the functionality that the module controls should be disable and returned to vanilla, period.

The fact that server owners running ace have to do their own code manipulations and then also have to have their players do the same is just asking for problems.

**Comment by Laid3acK** [comment] 2017-07-25 08:21
> I thought #4642 was supposed to get rid of `discreteDistance`?

It does:
- If the option `Overwrite zero distance` is `enabled` (default `disabled`) in the Scopes Module.
- And/or the sniper scope configured with a `ACE_ScopeZeroRange` (Scopes Framework).

But in fact and in all case, changing the `discreteDistance` (intentionally or accidentally) has a little effect on the bullet trajectory in-game with the both ballistics (Scopes module enabled).
Maybe the raison of this `discreteDistance[] = {100};` ?

(checked result after tests with different compats' config for the Bnae scope)

A solution to this issue could be:
- enabling `Overwrite zero distance` as default (ACE zeroing)
- deleting `discreteDistance[] = {100};` for all scopes (vanilla zeroing)
- advising that the `discreteDistance` must be never changed and always the same: `100` (ACE zeroing)
- Always checking the `ZERO` on the range card (ACE zeroing)

**Comment by ulteq** [comment] 2017-09-10 17:26
> The real question is why there an option to disable ace scopes adjustments in the scopes module if it doesn't work?

@Stritt57, it's technically not possible to completely disable the scopes module without actually removing the files.

> What does that dropdown even do right now?

It disables every aspect the scopes module, aside from the fixed vanilla zeroing, because that's not possible.

**Comment by ace3mod** [comment] 2017-11-18 12:53
Hello @JBartlett108! There has been no activity on this ticket for over a period of 68 days. I am automatically replying to let you know we will close this ticket within 1 week due to inactivity and consider this resolved.

If you believe this is in error, please reply with the requested information.

Thank you. :robot:

**Comment by Stritt57** [comment] 2017-11-19 10:31
Just because there has been no discussion on this issue does not mean it was fixed. The issue still remains despite the inactivity on this ticket.

**Comment by VileAce** [comment] 2017-11-21 20:00
I do not see a solution to this issue.  I am using ACE3 and I would like to use standard (vanilla) Arma 3 ranging. I do not want ACE "turrets"and I can not seem to find a way to do this.  

I have tried using the Advanced Ballistics module with everything to disabled and the scopes module with every combination.  In all cases I either get the turrets which I do not want or no range adjustment at all.

How can I use ACE3 and not change the way scopes work?

**Comment by PabstMirror** [comment] 2017-11-21 20:46
We have a PR that will add a simplified ranging system as an option (https://github.com/acemod/ACE3/pull/5787)
This will work pretty much like vanilla, pressing page up/down will go up and down in meters

We have to make config level changes to arma, so we can't offer pure vanilla zeroing, but for now you can remove ace_scope.pbo.

**Comment by PabstMirror** [comment] 2017-11-29 18:02
Fixed via #5787

**Closed by PabstMirror** 2017-11-29 18:02 UTC
Labels: kind/feature request

**Comment by KalleK-OPT** [comment] 2018-02-09 15:49
hi, there - sorry for "reopening" this, but we have a similar problem except for it is happening for small arms scopes such as ACO SMG and pistol scopes... aim is totally off (going way higher than aimed for starting with distances of 20m and more).
we are using the latest ace3 version with the ballistics system disabled in the cba/ace3-settings. no matter if I turn on or off the "correct zeroing"(for small arms) in the ace3-scopes-settings, still the same problem.
Deleting the ace3_scopes.pbo however resolves the issue! Deleting only ace3_smallarms.pbo does not do the trick. any ideas how to fix it via the settings or is it maybe not fully functional yet?

**Comment by AACO** [comment] 2018-02-09 15:53
Was reported already in https://github.com/acemod/ACE3/issues/6123
Should be fixed by https://github.com/acemod/ACE3/pull/6128

**Comment by KalleK-OPT** [comment] 2018-02-09 15:53
ok. thanx, my mistake! keep up the great work
