### ISSUE TITLE
CTD when missile (launcher based) impact a Man class

### ISSUE THREAD

**Issue by Mickyleitor** [acemod/ACE3#4595] opened 2016-10-24 22:49 UTC
**Arma 3 Version:** `stable / 1.64`
**CBA Version:** `3.1.1.161012`
**ACE3 Version:** `3.8.0.10`

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Here is a issue reported in FFAA MOD [feedback tracker](http://feedback.arma3.es/view.php?id=242) (tested later with ACE/CBA only).
Just before a missile impact a class man based then arma 3 do a CTD, giving no information about the error, only the classical [0xCFFFFFFF - APPLICATION_HUNG](https://community.bistudio.com/wiki/Arma_3_Unusual_process_exit#0xCFFFFFFF_-_APPLICATION_HUNG) error.

RPT log through no information about that so I can't tell so much about that.
I think the issue could be in the way ammo is handle when impacting infantry at short distances.

**Steps to reproduce:**
- Open Virtual Arsenal.
- Equip with NLAW.
- Find and target the objective at 100 meters away. (Bear in mind the ballistic of the missile, because it will fall quickly)
- Fire and wait missile to reach the target (If no error happen just be sure the missile cross the man body and not arms, head or legs, I usually failed hitting it).
- The game will get frozen just before the missile hit the man body. And the only way to exit is directly closing arma 3, throwing the 0xCFFFFFFF error.

**Where did the issue occur?**
- Singleplayer / Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- https://gist.github.com/Mickyleitor/cf22536cf6c142f49ec182aad89cc02f

**Comment by commy2** [comment] 2016-10-24 22:51
duplicate of https://github.com/acemod/ACE3/issues/4571

**Closed by commy2** 2016-10-24 22:51 UTC
