### ISSUE TITLE
Script errors when using task defend / patrol 

### ISSUE THREAD

**Issue by ShizCalev** [acemod/ACE3#4949] opened 2017-02-25 21:42 UTC
**Arma 3 Version:** `1.66.140454` (stable)
**CBA Version:** `3.2.0` (stable)
**ACE3 Version:** `3.9.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- ACE hasn't been updated to reflect the latest changes to CBA's task arrays, resulting in script errors during the usage of ACE AI orders. https://github.com/CBATeam/CBA_A3/commit/8dba84c89b82dd3bc527d3b1f42609ab54da1cce

**Steps to reproduce:**
- Spawn AI
- Use Ace AI order

**Where did the issue occur?**
- All

**Placed Modules:**
- Game master

**RPT log file:**
- http://pastebin.com/ZKEHwP56

**Comment by PabstMirror** [comment] 2017-02-25 23:56
Caused by CBA 3.2
Should be fixed in next CBA release - https://github.com/CBATeam/CBA_A3/pull/602

**Closed** 2017-02-26 06:31 UTC
Labels: CBA's fault
