### ISSUE TITLE
Counter-measures of land vehicle against AT-Missiles are useless

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#7239] opened 2019-10-12 22:45 UTC
**Mods (ACE3, CBA, JSRS SoundMod):**

- **Arma 3:** `1.94` [stable]
- **CBA:** `3.12.1.190812` [stable]
- **ACE3:** `3.12.6` [stable]

**Description:**
The smoke screen has no obvious effect -  When I hear a beep warning of a approaching AT-missile, I release smoke screen and slightly shift my tank or APC, but always and always the approaching AT-missile will find my vehicle! OMG! how i'm tired of this shit!!! Any smoke screens are useless against guided missiles (hand Titan Launcher, APC-AT-Launcher weaponry, static-AT)

This problem has existed in the game and I do not understand why it cannot be fixed. **Every time I hear a signal of an approaching rocket, it means that you will die in the coming few seconds. The best way in this case - is to jump out of the vehicle and run away, because smoke screens will always and always be useless!** but this is not normal.

Please Note! **When I wrote this problem on BIS devBranch forum, then majority users told me that this is ACE3 mod problem and that they have no problems with this in a vanilla game**! You can read this topic here - https://forums.bohemia.net/forums/topic/223317-counter-measures-against-at-missiles-are-worthless/ I am still not sure whether this is so or not, since I tried to do tests without ACE3 and I did not see a mega big difference! Only in a few cases did it seem to me that vanilla game makes this a better. **It seems like counter measures works in vanilla but not quite perfect, but with ACE3 it doesn't work at all!**  I know that ACE3 mod uses own system for guided AT-missiles, so why can't you fix this?  Or do you not see this problem?  I do not understand.  It just kills the vehicles gameplay of the game!

**ACE3 team! Please make smoke screens an effective way to protect!  Please Disassemble your own system for AT-Missiles, finally understand that it does not work. This is a complete zero! The AT-Missile must lose its target after the smoke has been released and if the player moved his vehicle, then this missile must not find this target again!** 

**Steps to reproduce:**
Play in Arma3 with ACE3

**Expected behavior:**
The AT-Missile must lose its target after the smoke has been released and if the player moved his vehicle, then this missile must not find this target again. She must fly to the starting point!

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by TheCandianVendingMachine** [comment] 2019-10-14 00:01
Should be fixed with #7014. Just not released yet

**Comment by commy2** [comment] 2019-10-14 04:27
Close?

**Comment by dedmen** [comment] 2019-10-14 10:02
Duplicate of #7012
Weirdly enough, posted by the same user.

**Comment by ZeusWrath** [comment] 2019-10-14 12:43
> Duplicate of #7012

1.since it was closed without any explanation
2. since not fixed so far (21 May)

I would like to know if this can be fixed/improved in ACE3? or still not worth the hope?

**Comment by dedmen** [comment] 2019-10-14 14:30
> 1.since it was closed without any explanation
![firefox_2019-10-14_16-29-45](https://user-images.githubusercontent.com/3768165/66759073-d73fbc80-ee9f-11e9-987d-06970efc5c6a.png)
As you can see there, it was closed because it was fixed in a Pull request.

2. It was fixed though.

**Comment by commy2** [comment] 2019-10-14 14:41
-.-

**Closed by commy2** 2019-10-14 14:41 UTC
Labels: status/invalid
