### ISSUE TITLE
BIS_DeathBlur persists in Spectator

### ISSUE THREAD

**Issue by Cyruz143** [acemod/ACE3#5708] opened 2017-10-29 11:41 UTC
**Arma 3 Version:** `1.76.143.281` (profiling)
**CBA Version:** `3.4.1.170912` (stable)
**ACE3 Version:** `3.11.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- acre
- Mission framework (https://github.com/kami-/hull3)
- Part that calls spec (https://github.com/Cyruz143/ark_inhouse/blob/master/ark_ace_spectator/client_preinit.sqf)
```

**Description:**
- When calling `[true] call ace_spectator_fnc_setSpectator;` from the KilledEH, it doesn't clear the vanilla BIS death blur when moving the player in to spectator.

**Steps to reproduce:**
- We're using a custom respawnTemplates entry, so perhaps the default ones cover this which is why people haven't reported it? The template emits an event for general scripting use, and calls the following:

```
[2, _attacker, -2, _attackerPos] call ace_spectator_fnc_setCameraAttributes;
[true] call ace_spectator_fnc_setSpectator;
```

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None, server.hpp below:

```
class ace_spectator_enableAI {
    value = 1;
    typeName = "BOOL";
    force =1 ;
};
class ace_spectator_restrictModes {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_spectator_restrictVisions {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
```

**RPT log file:**
- Nothing in the RPT

**Fix**
I've added the following to our killedEH script, seems to resolve it fine, unsure if it's something you'd want mod-side though in case it catches out other users

```
BIS_DeathBlur ppEffectAdjust [0.0];
BIS_DeathBlur ppEffectCommit 0.0;
```

**Comment by Cyruz143** [comment] 2017-10-29 11:45
Forgot to add screenshot: https://i.imgur.com/uSwf13k.jpg

**Comment by SilentSpike** [comment] 2017-10-30 23:31
Very nice bug report 👍 Haven't seen it myself so not sure of the exact reproduction case, but I think it's pretty safe to shove those two lines of code at the top of `fnc_ui.sqf` after the bit closing open dialogs.

That is assuming the `pp` commands don't script error in the case where the provided handle is `nil` (wrap in an `if isNil` if not).

**Comment by SilentSpike** [comment] 2017-10-30 23:35
I wonder if this is what `BIS_fnc_feedback_allowPP = false;` was handling in the old script. I removed it because I couldn't see that it had an effect, but if that's the case would be better to toggle that variable as part of `fnc_ui.sqf`

**Comment by AACO** [comment] 2017-10-31 17:08
@SilentSpike when I was testing the spectate system BIS_fnc_feedback_allowPP only needed to be used in certain edge conditions. Mainly if you used the ArmA escape menu `Respawn` button.

**Comment by jonpas** [comment] 2017-11-11 19:33
Yup, had that happen today as well.

**Comment by Cyruz143** [comment] 2017-11-27 12:02
Quick side note, we're still seeing some stamina-like ppEffect when dead, edges of the screen greying out. Possibly linked to `BIS_fnc_feedback_allowPP` now being missing?

**Closed** 2017-12-03 16:35 UTC
Labels: kind/bug
