### ISSUE TITLE
Rearm bug

### ISSUE THREAD

**Issue by ramblasos** [acemod/ACE3#6579] opened 2018-09-17 13:26 UTC
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.8.8` (stable)
**ACE3 Version:** `3.12.3` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Certain attack helicopters with dynamic loadout where you can assign a pylon to a turret, like Mi-48 Kajman or AH-99 Blackfoot, cannot be rearmed correctly (in rearm mode Amount based on caliber). 

If a pylon is empty before rearm then the assignment of a pylon will be reset to default after rearm. 

Seems like the issue is in the function [ace_common fnc_getPylonTurret](https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_getPylonTurret.sqf)

Line 36:
`private _inPilot = _targetMag in (_vehicle magazinesTurret [-1]);`

Command `magazinesTurret` does not return empty magazines when ammo is depleted in a pylon that was assigned to a pilot. It will return default turret, which is usually a gunner turret ([0]).

As a possible fix we can use another function in line 36: 
`private _inPilot = _targetMag in (((magazinesAllTurrets _vehicle) select {(_x#1) isEqualTo [-1]}) apply {_x#0});`

`-----------------------------------------------------
Full ammo in pylon:
private _inPilot = _targetMag in (_vehicle magazinesTurret [-1]);
Result: _inPilot -> True

private _inPilot = _targetMag in (((magazinesAllTurrets _vehicle) select {(_x#1) isEqualTo [-1]}) apply {_x#0});
Result: _inPilot -> True

-----------------------------------------------------
Empty ammo in pylon:
private _inPilot = _targetMag in (_vehicle magazinesTurret [-1]);
Result: _inPilot -> False
  
private _inPilot = _targetMag in (((magazinesAllTurrets _vehicle) select {(_x#1) isEqualTo [-1]}) apply {_x#0});
Result: _inPilot -> True
-----------------------------------------------------`

**Steps to reproduce:**
- Rearm mode Amount based on caliber. Place a Kajman and an Tempest Ammo in editor. Change default assignment of turrets to pilot (instead of gunner). Preview, get to pilot seat, fire to deplete ammo. Try to rearm. After rearm pylons get assigned to default (gunner).

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**Comment by Mike-MF** [comment] 2023-09-19 01:41
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Comment by LinkIsGrim** [comment] 2023-09-27 12:34
Closed in #8087

**Closed by LinkIsGrim** 2023-09-27 12:34 UTC
Labels: kind/bug
