### ISSUE TITLE
Optics module breaks Zeus camera PostInit

### ISSUE THREAD

**Issue by kerckasha** [acemod/ACE3#2773] opened 2015-10-20 11:03 UTC
ACE3 Version: 3.3.2 Stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
None

**Description:**
Upon loading a mission as Zeus, Zeus' camera will be deleted and the game will revert to the virtual zeus unit's camera.

Upon investigation, removing the optics mod from the modset solved the issue.

Lines 8 through 13 of XEH_postinit.sqf are the likely culprit.

**Steps to reproduce:**
Place Zeus virtual unit down and game master module, set to forced interface. Preview mission.
Or use repro mission:
https://www.dropbox.com/s/qjvitsn3tc59xfh/zeus_testmission.Stratis.zip?dl=0

**Where did the issue occur?**
* Happened in Multiplayer(dedicated) and Editor

**RPT log file:**
N/A

**Comment by commy2** [comment] 2015-10-20 17:12
fixed in https://github.com/acemod/ACE3/pull/2645

**Comment by commy2** [comment] 2015-10-20 17:14
Closing because already fixed in master.

**Closed by commy2** 2015-10-20 17:14 UTC
Labels: duplicate

**Comment by commy2** [comment] 2015-10-20 17:18
Oh and this is not caused by `camDestroy GVAR(camera);`, but by an engine bug with `camCreate` that kicks the unit out of already existing cameras.

**Comment by kerckasha** [comment] 2015-10-21 05:36
Ahah, wasn't aware of that issue. Good to know, thanks.
