### ISSUE TITLE
Captives persist after death

### ISSUE THREAD

**Issue by ThatSnipingGamer** [acemod/ACE3#1849] opened 2015-07-13 08:09 UTC
ACE3 Version: 3.1.1

Happens on Stable, Dev and RC Builds of ArmA

**Mods:**
* @cba_a3
* @ace3

If a player who is restrained by zip ties dies or respawns they remain restrained and can not be unrestrained. Requires them to re-log onto server to fix the problem

**Steps to reproduce:**
1) Zip tie another player
2) Kill the zip-tied player or have them respawn
When the zip-tied player respawns the are permanently zip tied until they log off the server

Multiplayer Bug

*edit* when my friends get on tomorrow I can record the problem if that helps*

**Comment by bux578** [comment] 2015-07-13 08:13
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by ThatSnipingGamer** [comment] 2015-07-13 08:21
sorry about that new to github, wanted to report the problem. I will fix it right away

**Comment by ThatSnipingGamer** [comment] 2015-07-13 08:49
Ok Let me know if you need more info and what, like i said i will try to get the bug on video if it helps.

**Comment by bux578** [comment] 2015-07-13 09:00
Thanks.

**Comment by alganthe** [comment] 2015-07-13 11:42
Tested on dedicated with respawn template base, the variable doesn't persist.

**Comment by bux578** [comment] 2015-07-13 11:45
https://github.com/acemod/ACE3/blob/master/addons/captives/functions/fnc_handleKilled.sqf

Yeah, the variable will be reset on death.

**Comment by alganthe** [comment] 2015-07-13 12:22
it may be his respawn template then, an example mission would be good.

**Comment by ThatSnipingGamer** [comment] 2015-07-13 12:57
Ok, a friend makes missions for my group, ill ask him about respawn scripts. thanks guys!

**Comment by ThatSnipingGamer** [comment] 2015-07-13 14:18
Ok, my friend uses the base respawn script for arma, he uses no event handlers for respawn. This is probably the cause. Is there any other important scripts that should be put into a mission running ace so it does not encounter any issues. Thanks and Great work so far on ACE. :)

**Comment by alganthe** [comment] 2015-07-13 22:37
the sqf above is pretty much what happen on the death of a unit, if you could provide a mission where this happen it would be very useful to find where the issue is.

**Comment by HTSean** [comment] 2015-07-15 13:52
Yeah, my friends and I experienced this issue as well. I don't have the mission file so I can't help you guys out further. Just backing his statement that it happens in some missions

**Comment by commy2** [comment] 2015-09-01 15:43
I'll take a look.

**Comment by commy2** [comment] 2015-09-01 17:40
Found the issue:
https://github.com/acemod/ACE3/blob/master/addons/captives/functions/fnc_handleRespawn.sqf#L27-L32

With respawn time set to 0 the new unit gets copied with all it's variables. Including isCaptive = true. The killed eventhandler is not fast enough and only overwrites the dead unit.
The respawn handler then resets the animation.

Apparently this was done to fix some issues with group respawn. No idea what that is.

@jokoho48 Any idea how to solve this?

**Comment by SilentSpike** [comment] 2015-09-01 17:49
You could check the respawn type and change the behaviour based on that

**Comment by PabstMirror** [comment] 2015-09-01 18:09
I thought of this race, but in my testing killed always happened before respawn.

I will look into saving the unit object on the unit, because they won't match on killed respawn but will on "JIP respawqn"

**Comment by SilentSpike** [comment] 2015-09-01 18:12
Wouldn't it be more simple to use the respawn type? :stuck_out_tongue:

**Comment by SilentSpike** [comment] 2015-09-12 12:28
Documenting stupid stuff to keep myself on track:

- When respawn delay is 0, the dead unit in the killed EH is not the player unit and so setting a variable on it doesn't persist through respawns
- When the respawn delay is above 0 (tested down to 0.1) then the dead unit is the player for that period of time

Possible solution:
- Simply reset all the captive status stuff on respawn rather than on death, I'm not sure if this would have any adverse effects though (we can still account for group and side respawn by explicitly checking the respawn type - since you respawn into an entirely different unit there will never be a case where variables set on the old one persist)

**Comment by commy2** [comment] 2015-09-12 13:57
>When respawn delay is 0, the dead unit in the killed EH is not the player unit and so setting a variable on it doesn't persist through respawns

Could be related, but the real issue I think is, that the variables are copied over to the new unit before the killed eventhandler is executed.

```
unit killed -> killed eventhandler triggers -> wait respawn delay -> new unit created with copied variables
unit killed -> new unit created with copied variables -> killed eventhandler triggers
```

>I'm not sure if this would have any adverse effects though.

I don't think so.

Will test this later today and probably merge.

**Comment by SilentSpike** [comment] 2015-09-12 14:40
What I meant by "not the player unit" is that the player has technically left that unit for the new one at that point, so it's just a dumb corpse :+1:

**Comment by commy2** [comment] 2015-09-15 14:37
Fixed in https://github.com/acemod/ACE3/pull/2406

**Closed by commy2** 2015-09-15 14:37 UTC
Labels: bug
