### ISSUE TITLE
Make.py doesn't clean up old deprecated .dll files

### ISSUE THREAD

**Issue by Cephel** [acemod/ACE3#1038] opened 2015-05-07 12:44 UTC
---
ACE3 Version: Doesn't matter

**Mods:**
* Not a PBO issue

**Placed ACE3 Modules:**
* Doesn't matter

**Description:**
This is what I put in the title already

**Steps to reproduce:**
Use the build.py, again, in the title

**Where did the issue occur?**
See above

**RPT log file:**
Invalid

---
Please, this is doing more harm than good.

**Comment by BaerMitUmlaut** [comment] 2015-05-07 17:33
I really think you should follow [the guidelines] (https://github.com/acemod/ACE3/blob/master/documentation/user/how-to-report-an-issue.md) for creating issues.

**Comment by Cephel** [comment] 2015-05-07 17:38
What a *splendid* suggestion

**Comment by bux578** [comment] 2015-05-09 05:33
Able to reproduce:
![image](https://cloud.githubusercontent.com/assets/1235520/7548880/b42b0f8a-f61d-11e4-97c2-4adc3a160506.png)

**Comment by jaynus** [comment] 2015-05-09 07:50
@cephel please follow the guidelines moving forward or I'll be auto closing. Thanks.

**Comment by Cephel** [comment] 2015-05-09 12:42
@jaynus I understand that you want to keep a unified reporting scheme for regular bug reports, but if you can explain everything that needs to be said in the title and any other information doesn't matter or is a waste of space, why insist on it?

Here. I'll demonstrate what this issue WOULD have looked like with the template:
---
ACE3 Version: Doesn't matter

**Mods:**
* Not a PBO issue

**Placed ACE3 Modules:**
* Doesn't matter

**Description:**
This is what I put in the title already

**Steps to reproduce:**
Use the build.py, again, in the title

**Where did the issue occur?**
See above

**RPT log file:**
Invalid

---
Please, this is doing more harm than good.

**Comment by jonpas** [comment] 2015-05-09 15:44
Having unified issue reporting scheme is very very helpful, simply because you can quickly see things as you know where to search for them. The scheme might be long especially in cases like this, but the easiness of reading it is way more helpful, additionally it provides a way of knowing what to post if that part is available.

**Comment by ViperMaul** [comment] 2015-05-09 19:28
To be honest, I originally added the need more info but I realized quickly I didn't need one for this ticket. And it was a good feature request. I was just too busy to remove the tag. @Cephel, thanks for following the requests for proper format.

**Closed** 2015-05-10 18:47 UTC
Labels: feature request
