### ISSUE TITLE
Potential bug in the weather module (custom settings)

### ISSUE THREAD

**Issue by ulteq** [acemod/ACE3#1052] opened 2015-05-08 09:27 UTC
Module Settings:
![](http://puu.sh/hCHVv/681bd332d4.jpg)
Watch the trees: https://www.youtube.com/embed/SWRsWKwrTBY

Can anyone reproduce the random wind direction changes?

**Comment by jaynus** [comment] 2015-05-08 13:59
Historically I remember this being due to a specific setting in the mission, which was the 'auto' on a bunch of fields. Prior to our weather changes, it would cause shit to randomly change direction *all* the time. 

It appears to be back. I'd guess this means our sync/update intervals arn't fast enough now.

**Comment by BullHorn7** [comment] 2015-05-25 09:29
I can't reproduce this specifically for a number of reasons:
When I set ACE Weather to No, the game won't accept my weather change from MCC for Wind.
When I set ACE Weather to Yes, the mission is permanently raining, even if I place an Environment -> Weather module and set Rain, Overcast and Fog to `0`.

**Comment by ulteq** [comment] 2015-05-25 10:25
@BullHorn7, did you use latest master? Or the latest public release?

**Comment by BullHorn7** [comment] 2015-05-25 10:29
3.0.1 public.. Would you like me to test the master?

**Comment by ViperMaul** [comment] 2015-05-25 11:52
@BullHorn7 if you can please.

**Comment by BullHorn7** [comment] 2015-05-25 12:15
Happens with latest master too..

My issue is more with the settings not really working as you expect them to - and especially the inability to actually disable the ACE Weather module. I tried setting all of the module settings to `No` which then allowed me to change Fog, Rain, Overcast via MCC but Wind always remained disabled completely, even when it's set to 100% in MCC.

**Comment by BullHorn7** [comment] 2015-05-25 23:23
When you set the weather via the 2D editor, ACE3 Weather handles it fine, but you cannot change it on-the-fly. MCC Weather sliders are incompatible. There's too many bugs that appear randomly and I can't reproduce effectively and repeatedly, it's just unusable. With MCC, I was forced to set ACE Weather and ACE Propagation to `off`.

Regarding the weird wind transition, yes, that happens with 3.0.1 and latest master when Interval is set to a very low number like `1`.

**Comment by ulteq** [comment] 2015-05-26 07:01
@BullHorn7, did you test this in singleplayer?

**Comment by BullHorn7** [comment] 2015-05-26 09:12
No, all tests were done on a listen server.

**Comment by esteldunedain** [comment] 2015-05-26 19:41
Apparently this was due to bad mission setup. Marking it as resolved

**Comment by BullHorn7** [comment] 2015-05-26 19:45
@esteldunedain @ulteq's report is real however - foliage jerks around when weather settings are updating too often. I sort of took over with my own issues which are probably a bug in MCC.

**Comment by bux578** [comment] 2015-05-26 20:06
^

**Comment by Kilo1-1** [comment] 2015-06-06 00:17
I would also like to add that this issue is occurring for me too.  I am also an MCC user but we aren't setting the weather via MCC so I am not 100% sure if there is a correlation.

**Closed** 2016-01-22 20:56 UTC
Labels: bug
