### ISSUE TITLE
New ZEUS modules are not reliable

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1665] opened 2015-06-17 23:28 UTC
ACE3 Version: 3.1.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *None*

**Description:**
*There are three new ACE modules in Zeus GUI, those are:*
* *Toggle capitulation, which only works on players, not on AI*
* *Toggle unconscious, which works only on AI and not on player*
* *Toggle prisoner, which works only on player for the first time, and not on AI*

**Steps to reproduce:**
* *Above modules seems to work only for the first time.*
* *Trying using them again on the same unit will do nothing*

**Where did the issue occur?**
*"Multiplayer", dunno about "Singleplayer"*

**RPT log file:**
*-*

**Comment by SilentSpike** [comment] 2015-06-17 23:29
Wait, wut? Are you running dedicated? (Not that it should make a difference)

**Comment by gienkov** [comment] 2015-06-17 23:30
Yes its dedicated.

**Comment by gienkov** [comment] 2015-06-17 23:31
I will record it and upload video.

**Comment by SilentSpike** [comment] 2015-06-17 23:33
Hmm...I don't think it can be because of the dedicated, otherwise the ACE event system wouldn't work.

I wonder if it's related to the use of curatorCanAttach (although that would produce an error message saying the module must be placed on a unit if it failed).

**Comment by gienkov** [comment] 2015-06-17 23:52
http://youtu.be/ZLH0aRRXESs

**Comment by bux578** [comment] 2015-06-18 05:17
Video tells that you're not using only cba and ace3 ...

**Comment by gienkov** [comment] 2015-06-18 08:49
Ok I have tested without them, only CBA+ACE on dedi, same issue on vanilla units.

**Comment by SilentSpike** [comment] 2015-06-18 14:10
Can anyone reproduce this? I can't seem to

**Comment by esteldunedain** [comment] 2015-06-18 15:46
Keep in mind @gienkov apparently is applying the modules to his own unit. IDK if that makes a difference.

**Comment by gienkov** [comment] 2015-06-18 17:07
You were doing this on dedicated @SilentSpike ?

**Comment by SilentSpike** [comment] 2015-06-18 23:01
Yes, although the dedicated was hosted on my own machine (but that shouldn't change anything).

@esteldunedain Also did that

**Comment by SilentSpike** [comment] 2015-07-12 00:20
Was able to reproduce this, except I have no idea how I reproduced it.

However, I think I know what the issue is and will change the code to see if it fixes the problem.

**Comment by SilentSpike** [comment] 2015-07-20 20:16
I believe 186d4d0 should fix this, but since I can't consistently reproduce it I'll need you to confim @gienkov

**Comment by SilentSpike** [comment] 2015-07-28 21:27
Something weird is stopping these modules from working properly on dedicated servers. Investigating.

**Comment by SilentSpike** [comment] 2015-07-28 22:33
Did some testing on dedicated:

Modules aren't working at all. However, duplicating the entire module code, setting it on a delay and then hovering the cursor over a unit in curator ran the code as expected. So it's something weird with the modules themselves.

Server rpt of that session only included errors:
```
23:11:37 Server: Object 4:12 not found (message Type_91)
23:11:37 Error: Object(4 : 10) not found
23:11:37 Error: Object(4 : 11) not found
23:11:37 Server: Object 4:13 not found (message Type_383)
23:11:37 Server: Object 4:14 not found (message Type_112)
23:11:38 Error: Object(4 : 12) not found
```

Client rpt included: `23:09:07 WARNING: Function 'name' - L Alpha 3-1:1 REMOTE (bis_curatorUnit) has empty name`

**Comment by SilentSpike** [comment] 2015-07-29 11:26
It was indeed a locality thing :smile: 

I've found out through some painful debugging that the module is running on the server rather than the local client. Interesting module framework BI :wink: 

Fixed in master

**Closed by SilentSpike** 2015-07-29 11:26 UTC
Labels: bug
