### ISSUE TITLE
ace_fastroping Causing Strange Helicopter Landing Behavior

### ISSUE THREAD

**Issue by E-Ledere** [acemod/ACE3#4746] opened 2016-12-04 17:41 UTC
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.8.2` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When an AI Helicopter is landing, it may not land when ace_fastroping is included. As the helicopter begins to land, it will get about 5-10 meters above the ground, at which point it will increase its altitude again, move 10-20 meters in a random direction that doesn't have any obstacles and attempt to land again. This second attempt ends in 3 ways:
1. The helicopter gets 5-10 meters above the ground, throttles up, attempts to return to the first landing spot, gets 5-10 meters above the ground and attempts to return to the second landing spot. In my personal testing, it repeated this behavior for over 10 minutes with no signs of stopping.
2. The helicopter will get 5-10 meters above the ground and abruptly lower its collective for a somewhat hard, but safe landing.
3. The helicopter will do the same as 2, but smash itself into the ground with such force as to disable the helicopter.

**Steps to reproduce:**
1. Place down player, helicopter, and landing pad.
2. Give helicopter waypoint to land.
3. If positioned correctly (and this happens in a surprisingly wide variety of locations, even locations completely devoid of obstacles for hundreds of meters, ie. airfields) the helicopter will display the behavior above.
4. Remove ace_fastroping.pbo, reload the mission, and see the above behavior not replicated.

Due to this bug being slightly location dependent, I highly recommend using the test mission I created to replicate these results:

[Test_Mission.Altis.zip](https://github.com/acemod/ACE3/files/629689/Test_Mission.Altis.zip)

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
None

**RPT log file:**
[Arma3_2016-12-04_09-21-25.txt](https://github.com/acemod/ACE3/files/629690/Arma3_2016-12-04_09-21-25.txt)

**Comment by XDfort** [comment] 2017-06-11 04:14
Hello, I have to add that using the ALIVE addon, it happens exactly the same, the pilot descends but within a few meters of taking the LZ abort and retakes height.

I think the problem is the object that is created by adding FRIES to helicopters like the UH-80 GhostHawk. When the AI detects the object aborts the LZ to avoid colliding with it. Using the Zeus and eliminating that object the helicopter landed without problems, but eliminates the option to do fastrope.

Sorry for the grammatical errors, but I had to use Google Translator.

Thank you.

**Comment by jonpas** [comment] 2018-11-18 15:40
Doesn't sound like anything we can do really, without affecting other AI behaviour or introducing issues for AI mods.

**Comment by Mike-MF** [comment] 2023-09-11 00:50
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Closed by Mike-MF** 2023-09-11 00:50 UTC
Labels: status/pending
