### ISSUE TITLE
Titan seperate implementation per Spike guidance/locking/mechanics.

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#1059] opened 2015-05-08 16:06 UTC
@gienkov has a person with details

**Comment by gienkov** [comment] 2015-05-08 16:09
![cross-section](http://zapodaj.net/images/5ebd1ea0a374d.jpg)

**Comment by gienkov** [comment] 2015-05-08 17:12
* Range is 200-4000 meters for HR (High Range) and 200-8000 meters for LR rocket (Long Range) and 200-2000 meters for MR rockets (Medium Range), Polish army does use only HR version, you can fire further than 4km and still be able to hit the target but after 4km you lose video from rocket
* Launcher from vanilla A3 uses lightweight rockets that have range of 50-800 meters
* Generation 3+ (better than Javelin which is 3)
* Guided by fibrewire allows operator to view what rocket sees in real time:
https://www.youtube.com/watch?v=tXrVFj2KFeg
* Two modes of fire, Javelin has only "Fire and forget" - Spike too but beside that one you can change target mid-flight:
https://www.youtube.com/watch?v=BvBXrlK5-PU
https://www.youtube.com/watch?v=EkYtjMJ_nNw
* Two modes of locking target - "LockOn" - https://www.youtube.com/watch?v=tXrVFj2KFeg ; and "Manual" https://www.youtube.com/watch?v=PjzqspesGeI
    * LockOn requires operator to place crosshair on target, then you press "LockOn" button and 3 dots show up (like in video), then you are allowed to fire
    * Manual - https://www.youtube.com/watch?v=PjzqspesGeI - is more like emergency mode for when you cannot lock target using "LockOn" mode, you just shoot without locking target and you can steer the rocket in-flight, but its has very maneuverability in this mode
* Two rocket trajectories you can select - High and Low, high makes rocket hit target from top to down,
* http://imageshack.com/e/p5aMES7Yj - it has 2 cameras for operator, first is day camera - that one you see on videos above, second is thermal camera, they both have *digital* zoom, thermal camera have also NFOV (image has 1,5 degree height and 2 degree width) and WFOV (image has 4,5 degree height and 6 degree width), day sight is always at NFOV view box and its fixed in that field of view
* There is no tank that will survive hit of this Spike rocket, it has penetration of 800mm+, first warhead does burn armor raising temperature of its surface to 1200 Celsius, it also make small hole in tank armor, then second warhead flies inside and increase pressure inside to enormous value that makes every living person inside fly outside that little hole first warhead made. You can even destroy smaller ships with this launcher.
https://www.youtube.com/watch?v=PRrLrTu1Chw
* 13,3kg HR rocket weight
* CLU + TS (Thermal Sight) weight is 9,5kg, battery weights 1kg so 10,5kg sum
* Tripod weights 2,8kg
* AT Spike team (2 persons) can carry maximum of 2 rockets
![AT Spike team](http://www.altair.com.pl/files/news/photos/5/5927/i-i11-03-141team.jpg)
* Its almost impossible to shoot without tripod or without resting whole launcher on some obstacle
* Backblast has 60m lenght at 45 degree angle to the left and to the right
* Rocket arms itself after 20 meters of flight
* Rocket speed is 130-180m/s, target at 4000m will be hit after 36 seconds, target at 2500m will be hit after 15,5 seconds 
* Launcher on tripod can rotate at 360 degree angle, elevation is from -10 degree to +30 degree angle
* You have only 85 seconds to fire rocket after turning on rocket thermal camera, when you have 45 seconds left then progress bar will show up and decrease as shown on second image below. When that time ends you cannot shoot using thermal sight optics but you can still use day sight optics.

And some VERY useful info from Steel Beasts Pro Spike implementation which is very accurate
Day sight:
![Day sight](http://www.steelbeasts.com/sbwiki/images/a/a6/SPIKE-LR_CCD_WFOV_activated.jpg)
Thermal sight (but in RL image is black white - black is hot): 
![Thermal sight](http://www.steelbeasts.com/sbwiki/images/3/3c/SPIKE-LR_IIR_NFOV_activated.jpg)
Rocket cross-section:
![Rocket](http://www.steelbeasts.com/sbwiki/images/8/8a/Spike_cutaway_diagram.jpg)
You can read about it here too: http://www.steelbeasts.com/sbwiki/index.php?title=SPIKE_LR
Shooting in SB:
https://www.youtube.com/watch?v=M74OzSsxhyE

**Comment by VKing6** [comment] 2015-05-11 06:36
When you say MR, HR, and LR, do you mean MR, LR, and ER? There's a Spike-NLOS with even longer range, but I've never seen a Spike-HR.

From what I can see [here](http://defense-update.com/photos/mini_spike.html) and [here](http://www.army-technology.com/news/newsrafael-launches-mini-spike-missile-system-eurosatory-2012), the Mini-Spike that we have in Arma has the same camera as the bigger spikes, but it's a very tiny 4kg missile, so I doubt there's a very good anti-tank version of it (the article calls it an anti-personnel weapon) although it does say it has a range of 1200 metres and three flight profiles.

**Comment by gienkov** [comment] 2015-05-11 07:38
Real life Mini-Spike
http://sistemasdearmas.com.br/pgm/spikemini.html

**Comment by VKing6** [comment] 2015-05-11 07:45
I can't read that, but it looks like a translation of the first link I posted.

**Comment by alienzo4** [comment] 2015-05-11 09:21
That I helped gienkov in description of SPIKE system. I introduced him astray, so sorry for that :)
There is 4 basic spike missiles
SR - Short Range  50m-800m Fire&Forget ONLY using by single infantry soldier
MR - Medium Range 200m-2500m F&F and F&O using by 2 soldiers crew (on tripod like on the picture above)
LR - Long Range 200m-4000m F&F F&O 2 soldiers crew (most popular version also mounted on IFV's)
ER - Extreme Range 400m-8000m F&F F&O 2 soldiers crew for infantry also mounted on IFV's and some helicopters. 

The rest of the information described by gienkov is the most authentic and correct :) Trust me, I'm specialist ;)

**Comment by cych** [comment] 2015-05-11 22:46
Fiber optic communication with camera guidance only start with the Spike LR. (4000m range)

the Spike MR (2500m) has only Fire é forget IR lock-on.

**Comment by alienzo4** [comment] 2015-05-12 05:42
http://www.rafael.co.il/Marketing/343-998-en/Marketing.aspx

You're wrong. MR is F&O too. MR is only ligther version of LR missile, all other functions are identical.

**Comment by headedhorseman101** [comment] 2015-05-12 14:51
>The Spike-MR has an optional Fire, Observe and Update mode of operation for the modern, multi-faceted battle. 

Both MR and LR versions have Fire and Observe as an optional feature.

**Comment by Mike-MF** [comment] 2023-09-11 00:39
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Closed by Mike-MF** 2023-09-11 00:39 UTC
Labels: kind/enhancement, kind/task
