### ISSUE TITLE
Killed Event is fired twice

### ISSUE THREAD

**Issue by kiwirives** [acemod/ACE3#7673] opened 2020-04-28 16:32 UTC
### Description:

Killed event handler is fired twice (aka: [james bond was right]( https://www.imdb.com/title/tt0062512/)! )

### Steps to reproduce: (mission attached: [killed_twice.Altis.zip](https://github.com/acemod/ACE3/files/4547120/killed_twice.Altis.zip))

1. Go to Editor
2. Add unit (let's call him Sean Bean) with the following init script:
```
this addEventHandler ["Killed", { 
 params ["_unit", "_killer", "_instigator", "_useEffects"]; 
 systemChat "im dead";
}];
```
3. Add unit, set to player
4. Test in SinglePlayer/MP
5. Kill Sean (couldn't be any other way)

### What happens:

Message is shown twice

### What is expected to happen:

Message is shown once (you only die once!)

**Running game without mods or with CBA seems to work properly.**

### ACE Version:

Stable. I don't know how to get the version (missing Changelog file), so here is the content of **ace_3.13.2.49.bikey** 
```
6163 655f 332e 3133 2e32 2e34 392d 6131
3766 3130 3865 0094 0000 0006 0200 0000
2400 0052 5341 3100 0400 0001 0001 00f1
8537 f7c3 3f52 c45e 2f11 a95f 9aa5 364d
7ce4 fdeb 93ae 9052 0ea0 d5cb 39a8 f12e
980c 11af 53bc 45ed 7738 9e26 b30f f360
3ea0 3561 e80c 5ed2 3549 a8ba b9ab 14fd
2955 7e66 9917 38f2 0bcf be0d c89e 6f53
4266 0798 37d9 8f13 c9f0 2dfa d533 43c2
7833 91a1 82b9 f03a 4e5c c35c 20d6 eb6a
d6a6 84ed df68 94ac d28d a4ba b398 bc
```

**Comment by PabstMirror** [comment] 2020-04-28 16:36
Use
```
this addEventHandler ["Killed", { 
    params ["_unit", "_killer", "_instigator", "_useEffects"];
    if (isNull _unit) exitWith { systemChat "ignore because unit is null" };
    systemChat format ["im dead: %1", _this];
}];
```

**Comment by kiwirives** [comment] 2020-04-28 16:37
that might be considered as a workaround...but shouldn't be event invoked just once?

**Comment by PabstMirror** [comment] 2020-04-28 16:39
ref #7561
because of how the game works the killed EH will fire twice (this may be fixed in the future)
so the best thing we can do is to null out the params for the 2nd EH

**Comment by commy2** [comment] 2020-04-28 16:40
Close?

**Comment by kiwirives** [comment] 2020-04-28 19:23
I don't want to sound rude, but the game actually invokes just once, so:
> because of how the game works the killed EH will fire twice (this may be fixed in the future)

should be transcripted to:
> because of how ACE works the killed EH will fire twice (this may be fixed in the future)

If the game works properly, as CBA does, the issue is clearly on how ACE handles this!
I'll try to have a look on the code.

Anyway, I see there's an open BIS issue: https://feedback.bistudio.com/T149510.
Would you mind to left this open to track the changes?

**Comment by commy2** [comment] 2020-04-28 19:45
> I'll try to have a look on the code.

You won't find a fix for it, as the issue is in the base game and can only be fixed by BI.

> Would you mind to left this open to track the changes?

There is no point to as the issue can only be fixed by BI.

**Comment by kiwirives** [comment] 2020-04-29 00:04
Let me double-check if I understood correctly after reading a bit...

Consider neither Vanilla/CBA use HandleDamage event. When a unit is shoot on the head, the unit dies and only one message is printed. (so far so good)

ACE, on the other hand, invokes "setDamage 1" within HandleDamage which somehow triggers killed event. **Is that right?** 
This makes sense, as explained in [wiki](https://community.bistudio.com/wiki/setDamage):
>Sets an object's damage value in the range 0..1, 0 meaning fully functional and 1 completely destroyed / dead.

Would it make sense for you "setDamage 1" it's causing a concurrent thread to kill the unit once it's already dead, hence second message with NULL values?

As stated by [wiki](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#HandleDamage):
> If code provided returns a numeric value, this value will overwrite the default damage of given selection after processing.

In fact, tried these with CBA loaded:
```
this addEventHandler ["HandleDamage", { 
  param [0] setDamage 1;
}]; 
this addEventHandler ["Killed", { 
    systemChat str ["Killed", _this]; 
}];
```
Results in
> ["Killed",[B Alpha 1-1:1,B Alpha 1-1:1,<NULL-object>,true]]

While:
```
this addEventHandler ["HandleDamage", { 
  1
}]; 
this addEventHandler ["Killed", { 
    systemChat str ["Killed", _this]; 
}];
```
Results in:
["Killed",[B Alpha 1-1:1,B Alpha 1-1:2 (kiwirives),B Alpha 1-1:2 (kiwirives),true]]

Considering the above, wouldn't avoiding setDamage in favor of {x} could solve the issue?

**Comment by commy2** [comment] 2020-04-29 03:37
It would not or it would create other issues. Close?
You will not be able to solve this. You are wasting your time.

**Comment by dedmen** [comment] 2020-04-29 08:17
> Stable. I don't know how to get the version (missing Changelog file), so here is the content of ace_3.13.2.49.bikey

FYI, the version is 3.13.2.49 you just posted it with the bikey filename.

**Closed** 2020-05-01 22:55 UTC
Labels: fault/BI, status/wontfix
