### ISSUE TITLE
I can't unload prisoners

### ISSUE THREAD

**Issue by majinisinpu** [acemod/ACE3#4891] opened 2017-02-11 14:05 UTC
I can't unload prisoners because their Interact menus don't have "Unload Captive".

**Comment by bux** [comment] 2017-02-11 14:51
Please take the time to fill out the issue template.
If not we ~won't~ can't help you.

**Comment by PabstMirror** [comment] 2017-02-11 15:50
Is this related to #4862 - Do you see bandage/diagnose options for the unit?
Screenshot/RPT would help.

**Comment by majinisinpu** [comment] 2017-02-11 15:54
Yes.
I see Bandage/diagnose options .

**Comment by PabstMirror** [comment] 2017-02-11 16:01
We think the root cause is a mod load order problem.
If you can move ace up to the front, it may solve it.
e.g. `-mod=@CBA_A3;@ace;@otherMods....`

Otherwise we will have a proper fix in 3.9.1

**Comment by PabstMirror** [comment] 2017-02-14 22:28
Dupe of #4862
Will be properly fixed in 3.9.1

**Closed by PabstMirror** 2017-02-14 22:28 UTC
Labels: duplicate
