### ISSUE TITLE
ACE Arsenal Training Mission is missing content

### ISSUE THREAD

**Issue by chazbotic** [acemod/ACE3#7604] opened 2020-03-15 16:47 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** 1.96.146114
- **CBA:** 3.14.0.200207
- **ACE3:** 3.13.1.46

**Description:**
Missing all VR units from ACE Arsenal training mission. The mission has "Save and Exit" instead of "ACE Arsenal".

**Steps to reproduce:**
- Go to Training from the main menu
- Click on ACE Arsenal
- Witness the missing units.

**Expected behavior:**
The ACE Arsenal mission should perform similarly to previous incarnations, and similarly to the BIS VR Arsenal, where O_Soldier_VR_F are present. currently only the VR obstacles, vehicles are present as well as the player. initPlayerLocal appears to be read in, as portions are used to generate the mission starting area, obstacles, vehicles, and also the script to grab the display, but the units themselves do not appear and the button to save and exist isn't replaced with return to ace arsenal.

**Where did the issue occur?**
- Virtual Arsenal

**Log Files:**
9:10:01 Error in expression <ex];
["O_Soldier_VR_F", _position] call ace_arsenal_fnc_createTarget;
} forEach >
 9:10:01   Error position: <ace_arsenal_fnc_createTarget;
} forEach >
 9:10:01   Error Undefined variable in expression: ace_arsenal_fnc_createtarget
 9:10:01 File z\ace\addons\arsenal\missions\Arsenal.VR\initPlayerLocal.sqf..., line 16

**Additional context:**
fnc_createTarget.sqf is in z\ace\addons\arsenal\missions\Arsenal.VR instead of z\ace\addons\arsenal\functions

not sure if that's intentional, but it appears that arma isn't finding that script. when i tried customizing ace_arsenal.pbo locally to see if copying the script to the alleged correct location would fix the issue, i ran into problems with CBA XEH breaking for the pbo.

**Comment by jonpas** [comment] 2020-03-15 16:49
Duplicate of #7584, already fixed for next update.

**Closed by jonpas** 2020-03-15 16:49 UTC
Labels: kind/bug, status/duplicate
