### ISSUE TITLE
ACE 3 doesn't work during mission after full game reset

### ISSUE THREAD

**Issue by joshuajbouw** [acemod/ACE3#980] opened 2015-05-02 02:45 UTC
ACE Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* All modules.

**Description:**
* When plays a mission, ACE 3 works as intended. Upon saving and closing of the game then coming back at a later time, the ACE interaction menu can not be interacted with on the same game.

**Steps to reproduce:**
* Create mission / start mission.
* Play mission
* Save and exit mission
* Close Arma 3
* Reopen Arma 3
* Load up saved mission

**Where did the issue occur?**
* Occurs both in Singleplayer and Multiplayer.

**RPT log file:**
* http://pastebin.com/wJEQmxM4

**Additional Notes**
* I initially thought that it was a problem with MCC + ACE 3 compatibility but I and another have confirmed that it is happening with just ACE 3 and CBA. I have updated to reflect this as I can confirm it is a problem with ACE 3 base.

**Comment by bux578** [comment] 2015-05-02 04:58
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by joshuajbouw** [comment] 2015-05-02 05:55
Done.

**Comment by bux578** [comment] 2015-05-02 08:52
> I should note that I have not tested this with ACE 3 alone yet, however I will do this later. Something I should have done first.

Yeah, please do that. If the problem only occurs with MCC in the mix then please report the bug with   shay_gman/mcc devs. They are already working on ACE3 compatibility.

**Comment by esteldunedain** [comment] 2015-05-02 13:13
So the issue is loading saved games? Sadly there's no full support on ACE3 for that, at least yet. There has been some discussion about this, on wether we want to take the time to solve this soon or not, given that our enphasis is on multiplayer. That's probably something the Project Managers need to make a final decision about.

**Comment by ulteq** [comment] 2015-05-02 14:24
I can reproduce this with CBA + ACE only.

**Comment by joshuajbouw** [comment] 2015-05-03 08:14
Thanks for confirming that it is just with ACE, I'll setup a dedicated server or something for the time being I guess.

**Comment by jaynus** [comment] 2015-05-10 16:14
Related work items:
#1091 #1098 #1099

**Comment by joshuajbouw** [comment] 2015-05-14 09:58
jaynus you are a boss.

**Comment by jmcamara** [comment] 2015-08-10 12:14
Hi, I'm suffering all the time with this bug. When I save the mission if I reset the game , later I can not interact with the menu, but two times I could recover the intearction 
In two missions in the arma 3 campaing 'Win' I could interact again after the problem. I dont know why but in the two missions I recovered the iteration with the menu after an autosave in a waypoint. I am not trying reproduce this in the editor . I only post this comment If it could be useful to get a solution in some way

**Comment by commy2** [comment] 2015-09-01 15:32
This is covered by https://github.com/acemod/ACE3/issues/1098 . Closing as dup.

**Closed by commy2** 2015-09-01 15:32 UTC
Labels: duplicate, task
