### ISSUE TITLE
Titan AA requires AT locking and shouldn't

### ISSUE THREAD

**Issue by Arkblade2015** [acemod/ACE3#620] opened 2015-04-15 15:10 UTC
Mods:

    @cba_a3
    @ace3

Placed ACE3 Modules:
ace_javelin
ace_missileguidance

Description:
launchers can't fire except titan AT/AP

Steps to reproduce:
none

Where did the issue occur?
"Singleplayer"*

**Comment by rlex** [comment] 2015-04-15 15:15
looks like dupe of #603

**Comment by Arkblade2015** [comment] 2015-04-15 15:23
titan AA, RPG32, others....

**Comment by jaynus** [comment] 2015-04-15 16:18
No repro in latest master on any launchers except the Titan AA. The Titan AA is a wierd case, because its all the exact same shit and it really shouldn't be.  

Renaming ticket to figure out some mythical air locking method to use for this.

**Comment by Arkblade2015** [comment] 2015-04-15 17:29
i also No repro in latest master on any launchers except the Titan AA.
thank you.

**Closed** 2015-04-18 17:32 UTC
Labels: enhancement
