### ISSUE TITLE
Gunlights turn off on medical actions & safety switching

### ISSUE THREAD

**Issue by derbismarck** [acemod/ACE3#3821] opened 2016-05-24 06:16 UTC
**Arma 3 Version:** `1.58` (stable / rc / dev)
**CBA Version:** `2.3.1` (stable / dev + commit hash)
**ACE3 Version:** `3.5.1` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
If you have a flashlight on your weapon which is turned on, using any ACE Medical (self or otherwise) function will turn the flashlight off on completion of the medical animation. Additionally toggling safe weapons mode on and off also turns off the flashlight.

**Steps to reproduce:**
1.) Start night mission.
2.) Equip player with weapon and corresponding gunlight attachment.
3.) Turn on the gunlight.
4.) Self interact and use any medical action, or toggle weapon safety.
5.) See gunlight turn off on completion of the triggered animation.

**Where did the issue occur?**
In all environments.

**Placed Modules:**
None.

**RPT log file:**
RPT file is not relevant as no error is thrown.

**Comment by commy2** [comment] 2016-05-24 07:18
duplicate of #210

The part about medical actions (the animations are the real reason) will have to be fixed by Bohemia.
See: https://forums.bistudio.com/topic/190687-bug-script-command-magazinesdetail-doesnt-include-all-magazines/?p=3024384

**Closed by commy2** 2016-05-24 07:18 UTC
Labels: BIS' fault, duplicate

**Comment by derbismarck** [comment] 2016-05-24 07:31
Ah, gotcha thanks for the information!
