### ISSUE TITLE
Can't move acex icons

### ISSUE THREAD

**Issue by bababoombatman** [acemod/ACE3#8663] opened 2021-11-05 07:30 UTC
**Mods:**
- **Arma 3:** 2.06
- **CBA:** 3.15.6
- **ACE3:** 3.4.1

**Description:**
After the recent acex merge, you can't move the hunger and thirst icons.

**Steps to reproduce:**
1-Go to the Virtual Arsenal
2-Open the layout settings
3-Move the icons to any position you want
4-Restart the game
5-Nothing has changed

**Expected behavior:**
The icons should move to the specified position

**Where did the issue occur?**
- Everywhere

**Additional context:**
I don't know if it can be relevant, but i've used to move the icons before the two mods where merged. The old position is saved but the icons stay where they are

**Screenshots:**
![20211105082925_1](https://user-images.githubusercontent.com/14316469/140474043-3207db99-d9cc-4748-a12a-7563eb45255e.jpg)

**Comment by jonpas** [comment] 2021-11-05 09:08
Duplicate of #8644. Already fixed for next release.

**Closed by jonpas** 2021-11-05 09:08 UTC
Labels: kind/bug
