### ISSUE TITLE
ACE3 Slideshow Issues (Transparent Screen)

### ISSUE THREAD

**Issue by Indisus** [acemod/ACE3#3843] opened 2016-05-31 00:22 UTC
**Arma 3 Version:** `1.60.136406'

**CBA Version:** `Current Updated'

**ACE3 Version:** `Current Updated'

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Slideshow shows fine for me, however the 'screen' is transparent for viewing players ... this is fixed when the players interact with the controller themselves, but the screen is then transparent for me as well as everybody else. 

**Steps to reproduce:**
- Create slideshow
- have other players attempt to view it in MP

**Where did the issue occur?**
- Self-Hosted multiplayer 

**Placed Modules:**
- ACE hearing
- ACE sitting
- ACE slideshow

**Comment by jonpas** [comment] 2016-05-31 00:36
Did that happen before 1.60 as well?

Upload RPT as well please.

**Comment by Indisus** [comment] 2016-05-31 01:04
Sorry Im new to this ... 

I cant tell you im afraid as its the first time ive tried this module, so all usage has been prior to 1.60 

Hopefully this is the right RPT. 

Thanks :) 


[arma3_2016-05-30_21-59-09.txt](https://github.com/acemod/ACE3/files/290186/arma3_2016-05-30_21-59-09.txt)

**Comment by jonpas** [comment] 2016-05-31 01:12
This is most likely the reason it's not working:
```
23:03:46 Warning Message: Cannot load texture mpmissions\__cur_mp.altis\slideshow\intro0.jpeg.
23:03:55 Warning Message: Cannot load texture mpmissions\__cur_mp.altis\slideshow\intro1.jpeg.
23:04:03 Warning Message: Cannot load texture mpmissions\__cur_mp.altis\slideshow\intro3.jpeg.
```

Look at the note in red [here](http://ace3mod.com/wiki/missionmaker/mission-tools.html#the-module-explained).

Also, you have a lot of script errors in that mission.

**Comment by jonpas** [comment] 2016-06-04 19:10
@Indisus has this been resolved with the above or is the issue deeper?

**Comment by jonpas** [comment] 2016-06-07 15:07
Closing due to inactivity, https://github.com/acemod/ACE3/issues/3843#issuecomment-222572416 is most likely the cause.

**Closed by jonpas** 2016-06-07 15:07 UTC
Labels: bug, need more info
