### ISSUE TITLE
Decrease delay for placing down explosives

### ISSUE THREAD

**Issue by ulteq** [acemod/ACE3#1223] opened 2015-05-15 13:10 UTC
Decrease the time it takes to place down explosives. And increase the time to attach triggers.

**Comment by esteldunedain** [comment] 2015-05-15 13:32
I'll do this. I'm going to use the PutDown animation.

**Comment by bux578** [comment] 2015-05-15 13:39
Duplicate of #1021

**Closed by bux578** 2015-05-15 13:39 UTC
Labels: enhancement, task
