### ISSUE TITLE
Stutter issue with explosive ammo persists

### ISSUE THREAD

**Issue by jayjay213** [acemod/ACE3#2532] opened 2015-09-19 18:16 UTC
I made a video of the stutter issue with the newest ace version 3.3.1. The problem is still there! In the beginning and at the end you can see it very clearly. The Fps counter was not recorded but the frames were dropping to 2-7.

http://www.filedropper.com/a3-ace

**Comment by PabstMirror** [comment] 2015-09-19 20:04
Dupe of #2351

**Closed by PabstMirror** 2015-09-19 20:04 UTC
Labels: duplicate
