### ISSUE TITLE
Cant revive Player with CPR, just with PAK

### ISSUE THREAD

**Issue by Meiestrix** [acemod/ACE3#2099] opened 2015-08-10 10:31 UTC
ACE3 Version: 3.2.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
http://pastebin.com/82xK67Hj

Mission sqm: https://www.dropbox.com/sh/vcu00v2pq8owm3f/AABMTKbJHWIWIdOfhnj2wRAna?dl=0

**Description:**
When a plyer is unconscious, has no pulse but everything else is fine. (No pain, No wounds, No blood loss) Your are not able to fix them up. Using CPR does not help to fix the pulse, even with epi you are not able to fix the pulse. The only way is to use a PAK.

**Steps to reproduce:**
Set up you modules like in the config. Shoot a player. When unconscious shot again.
Fix all wounds fast. Check for pulse. If no pulse. Try to fix the pulse.

**Where did the issue occur?**
In Multiplayer on a dedicated Server

**Comment by Glowbal** [comment] 2015-08-10 11:19
You are playing with `enableRevive` enabled. This means sometimes units will be considered in a state where only advanced medical treatment will save a patient. This is simulated through the usage of a PAK.

**Comment by Meiestrix** [comment] 2015-08-10 11:24
Ok but when it is only possible to fix the pulse with a PAK, which use has the CPR?

**Comment by Glowbal** [comment] 2015-08-10 11:28
Try to give a patient that is not injured 3x epinephrine. The patient will go into a cardiac arrest state. This is when you are able to revive using CPR. 

This is just one case, of course. Extended periods of bloodloss could also trigger the cardiac arrest state. I'd go with if the vitals of a patient are the cause of the patient to go unconscious, it's most likely that the patient is in the cardiac arrest state.

**Comment by Meiestrix** [comment] 2015-08-10 13:58
When the patient has no pulse it ssems like he cant go into cardiac arrest.
3x epinephrine does not change anything still no pulse.
So it looks like the only way to revive with no pule is the PAK.

**Comment by xJenny99x** [comment] 2015-08-12 07:02
I can confirm this happens to the guys I play with aswell.

Maybe adding defibrillators would add a more logical solution to the issue.

Because as of right now people are still confused about how to properly use the advanced medical as we are not sure if something is a bug or a feature!

**Comment by havena** [comment] 2015-08-14 12:07
i confirm too. something strange. IRL, CPR can work.

**Comment by Meiestrix** [comment] 2015-08-15 21:38
I also think that the revive time you get with CPR is to small, i am not sure if I found the right code part but it looks like you get a random time between 0 and 20 seconds for 1 CPR, added to your revive time.
In my opinion i would be better if you get 5 senconds + random 0-15 seconds.

**Comment by havena** [comment] 2015-08-20 00:57
@Glowbal fixed

**Comment by SilentSpike** [comment] 2015-08-20 01:08
Fixed in 33ef602

**Closed by SilentSpike** 2015-08-20 01:08 UTC
Labels: bug

**Comment by Artac** [comment] 2015-10-07 22:43
Glowbal wrote:
"Try to give a patient that is not injured 3x epinephrine. The patient will go into a cardiac arrest state. This is when you are able to revive using CPR."

Did this, worked flawlessly.

"This is just one case, of course. Extended periods of bloodloss could also trigger the cardiac arrest state. I'd go with if the vitals of a patient are the cause of the patient to go unconscious, it's most likely that the patient is in the cardiac arrest state."

When the extend period of blood loss/pressure drop causes the heart rate to goto 0/cardiac arrest I am unable to restore the heart rate using CPR, even after bandaging all the wounds and using 1000ml bloodbags to raise pressure, I've gotten the pressure as high as mid 80's with still no return of heart rate using CPR. If I am understanding what you said, does the extended period of bloodloss put them in a cardiac arrest state, thus not requiring the PAK to revive the patient?
