### ISSUE TITLE
Sitting doesnt work after last update

### ISSUE THREAD

**Issue by SSG-Kalle** [acemod/ACE3#8694] opened 2021-11-22 12:43 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06`
- **CBA:** `3.5.6.211004` 
- **ACE3:** `3.14.0` [

**Description:**
Since the last update sitting doesnt work. Even with Sittingmodule activated in settings it wont identify chairs as sittable objects.

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. Activate module in ACE CBA settings 
2. Place different kind of chairs
3. Try to sit down and only get the move object interaction.

**Expected behavior:**
Be able to sit down

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal <-- All of these

**Log Files:**
- n/a

**Comment by jonpas** [comment] 2021-11-22 12:54
Duplicate of #8576, already fixed for next release.

**Closed by jonpas** 2021-11-22 12:54 UTC
Labels: kind/bug, status/duplicate
