### ISSUE TITLE
Switching scopes for the PIP RCO causes blur to stay

### ISSUE THREAD

**Issue by Cephel** [acemod/ACE3#1124] opened 2015-05-12 16:14 UTC
ACE3 Version: ab580dd1c7bb0dba710a42f0193bb312eceac0c0

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *None*

**Description:**
*Switching from longrange to shortrange scope on the PIP RCO, while zoomed in will cause the blur effect to simulate the lens in long range mode to stay for the reflex sight.*
![](http://puu.sh/hKHo7/65801255da.jpg)
*Issue does not seem to happen on the 2D RCO because there's no blur. Possible new issue because of lack of consistency?*

**Steps to reproduce:**
* *Equip PIP RCO*
* *Zoom in using the right mouse button*
* *Press `CTRL`+`RMB` to switch to shortrange reflex sight*

**Where did the issue occur?**
*Editor*

**RPT log file:**
*Invalid*

**Comment by jonpas** [comment] 2015-05-12 16:17
Duplicate of #1029

**Comment by jaynus** [comment] 2015-05-12 16:17
This is a BI Bug as resolved in #1029

**Closed by jaynus** 2015-05-12 16:17 UTC
Labels: BIS' fault, duplicate
