### ISSUE TITLE
.338 BadNews Lapua , Noreen Muzzle Attatchments (FlashSuppressor does not attatch)

### ISSUE THREAD

**Issue by dvdbrewster** [acemod/ACE3#3344] opened 2016-02-19 03:53 UTC
**Arma 3 Version:** `1.56`
*( stable, *)

**ACE3 Version:** `3.4.2`
*(indicate if stable or dev, if dev indicate the commit the version is based on)*

**Mods:**
* `@CBA_A3`
* `@ace`
*  @mao_bloodmist_a3
*  @EWK_CIGS
*  @CUP-Terrains CORE
*  @CUP-Terrains MAPS

**Placed Modules:**
* *spectator settings, designate medical vehicle,friendly fire messages.*

**Description:**
* *InGame MP missions  CTI altis,Obtain a .338 Flash Suppressor from ACE Support Box, try to attatch FlashSuppressor .338 to Noreen Lapua.   The item is stowed in your inventory.
Attatchment are working for 6.5 muzzles. *

**Steps to reproduce:**
* *any combination of weapon attatchment .338 muzzle(flashSuppressor from ACESupport crate to NoreenLapua .338.*

**Where did the issue occur?**
* *Local MP , DED Server, Steam MP"*

**RPT log file:**
* https://www.dropbox.com/s/yib9c5dgbqswdjz/arma3_2016-02-19_08-09-10.rpt%20%20%20%20%20ACE%20%20%20becti.txt?dl=0

*
see 8:56,     8:00,

**Comment by esteldunedain** [comment] 2016-02-19 04:12
I took a look at our configs and I couldn't find anything wrong:

[Code:](https://github.com/acemod/ACE3/blob/master/addons/flashsuppressors/CfgWeapons.hpp#L65-L71) 
```c++
    class DMR_02_base_F: Rifle_Long_Base_F {
        class WeaponSlotsInfo: WeaponSlotsInfo {
            class MuzzleSlot: MuzzleSlot {
                compatibleItems[] += {"ACE_muzzle_mzls_338"};
            };
        };
    };
```

However I can't test it in-game because I don't own the DLC.

**Comment by dvdbrewster** [comment] 2016-02-19 06:18
It never did this b4, Now the crates lose all functionality after a coulple of respawns.   MayB the new cba is different.   I figured you didn't edit out the .338 on accident.   .00.

**Comment by bux578** [comment] 2016-02-19 07:19
Yeah, confirmed with Arma 3 1.56 and ACE3 3.4.2

![2016-02-19_00002](https://cloud.githubusercontent.com/assets/1235520/13168895/88015bc6-d6e1-11e5-9439-74a624cddc2e.jpg)

**Comment by dvdbrewster** [comment] 2016-02-19 08:52
Nice, I don't suppose u would guess why my ace supply crates (all) seem to "time out" as well ?

**Comment by dvdbrewster** [comment] 2016-02-20 01:59
Please revisit the issue I”ve sent an RPT of the ACE crates and some Medical Functions crashing at the same time.

**Comment by dvdbrewster** [comment] 2016-02-20 02:10
Would you revisit the issue Ove posted an RPT if some problem, same issue, 
seems the whole ACE mod might b crashing

**Comment by commy2** [comment] 2016-02-21 22:47
Can't reproduce bug after https://github.com/acemod/ACE3/pull/3345
@bux578 Can you confirm that it's fixed on master? Thanks

**Closed** 2016-02-21 22:46 UTC
Labels: bug
