### ISSUE TITLE
Possible conflict with new NVIDIA drivers.

### ISSUE THREAD

**Issue by EstariaValens** [acemod/ACE3#3546] opened 2016-03-06 04:29 UTC
**Arma 3 Version:** `hotfix 1.56` (stable) (updated March 3)
**CBA Version:** `A3` (stable)  (Updated Feb 20)
**ACE3 Version:** `3.5.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When ACE3 is enabled, any mission, scenario, or campaign cannot be resumed or loaded.  If I attempt to resume or load a mission, scenario, or campaign, the game CTDs and an error report is produced. It appears that this only happens when you start the mission, scenario, or chapter of the campaign with ACE3 enabled.  If ACE3 is enabled after the mission, scenario, or chapter is started, I am able to resume the mission, scenario, or chapter like normal.  

I say this might be an NVIDIA driver issue, because this issue has been known to happen when NVIDIA drivers are updated; however, since I only use NVIDIA, I cannot say for certain.  NVIDIA updated their drivers on March 2, and the new Arma hotfix uploaded on March 3.  The last time I was able to save was March 2.

**Steps to reproduce:**
- Load ACE3 and CBA only and start the game.  I have been using the first mission of Survive to isolate the problem, but I double checked against a few other missions at each stage to ensure it wasn't a problem unique to Bohemia's campaign.  I used Resist, and the new Navy Seals: Blood Brothers by Helios.

**Where did the issue occur?**
- I only tested it in single player.

**Placed Modules:**
- none

**RPT log file:**
-
[arma3_2016-03-05_19-40-52.zip](https://github.com/acemod/ACE3/files/160159/arma3_2016-03-05_19-40-52.zip)

**Comment by PabstMirror** [comment] 2016-03-06 04:35
There seems to be a problem with 1.56 and loading large arrays from save games.

**Comment by EstariaValens** [comment] 2016-03-06 04:56
I'm not a programmer, so I may be misunderstanding; but I successfully loaded a save with TPW (all modules active) and vcom AI active.  I guess that "arrays" can be large in a light mod or small in a heavy mod?  Because it certainly has nothing to do with load.  I run 45+ fps with ACE3 installed (GTX 980Ti, ultra everything, 5000 draw distance, 2000 object draw distance), but only 20 fps with TPW and vcom active.

**Comment by commy2** [comment] 2016-03-06 05:20
duplicate of https://github.com/acemod/ACE3/issues/3397
Has nothing to do with specs. Or the size of the arrays technically.
1.56 broke nested array serialization. We are working on a solution.

**Closed by commy2** 2016-03-06 05:20 UTC
Labels: BIS' fault, duplicate
