### ISSUE TITLE
Pylon Interface PixelGrid

### ISSUE THREAD

**Issue by tbeswick96** [acemod/ACE3#5663] opened 2017-10-24 12:11 UTC
Change Pylons interface to use pixelGrid to solve layout issues as discussed in https://github.com/acemod/ACE3/pull/5661

**Comment by dedmen** [comment] 2018-11-18 13:15
Milestone is ongoing. Thus don't close this you bot.

**Comment by Mike-MF** [comment] 2023-09-11 00:37
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Closed by Mike-MF** 2023-09-11 00:37 UTC
Labels: kind/enhancement, kind/task
