### ISSUE TITLE
when ace_nightvision_disableNVGsWithSights is on -  very bright flashes apears when you try to aim

### ISSUE THREAD

**Issue by BlackburnUTG** [acemod/ACE3#8249] opened 2021-05-09 03:31 UTC
Arma 3: 2.02.147359
    CBA: 3.15.3
    ACE3: 3.13.6

Description:
if ace_nightvision_disableNVGsWithSights is on
when aim the gun - you NVG turning off, and if after that youstop aiming - you can see this bright flashes from old a3 vanila effect for a second  https://youtu.be/BDcNQDf4IK8

Steps to Reproduce
turn on ace_nightvision_disableNVGsWithSights and try to aim with nvg googles,

it is very annoying. I hope you can remove those flashes. if you can't - maybe you should prevent ability to aim when nvg is on

**Comment by Drofseh** [comment] 2021-05-09 04:36
Fill out the issue template in full

**Comment by commy2** [comment] 2021-05-09 06:00
Isn't that how the game looks when toggling vision modes? If no one has a feasible fix for this, I'd close this issue.

**Comment by BlackburnUTG** [comment] 2021-05-09 20:48
> 
> 
> Isn't that how the game looks when toggling vision modes? If no one has a feasible fix for this, I'd close this issue.

nope. Here is a togling vision mods and everything is fine. https://www.youtube.com/watch?v=l4SvTSUmwgA&feature=youtu.be
The problem with ace_nightvision_disableNVGsWithSights - is when you aim and nvg and stops aimning - there is vanila a3 nvg effect appears on the second, and then ace nvg effect. vanila effect is much brighter then ace3 , and don't have borders https://www.youtube.com/watch?v=BDcNQDf4IK8&feature=youtu.be

**Comment by BlackburnUTG** [comment] 2021-05-11 13:08
if it cannot be fixed. Maybe a good idea will be to remove ability to aim in nvg at all, if ace_nightvision_disableNVGsWithSights is on

**Comment by commy2** [comment] 2021-05-11 22:48
No, that is a terrible idea. People would not know what the hell is going on and assume everything broke.

**Comment by commy2** [comment] 2021-05-11 23:49
No text on screen. No blocking player input making the game more clunky.

**Comment by Salluci** [comment] 2021-08-25 12:53
Might be able to be addressed in 2.06 with [addUserActionEventHandler](https://community.bistudio.com/wiki/addUserActionEventHandler)

**Comment by Mike-MF** [comment] 2023-09-19 01:05
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Closed by Mike-MF** 2023-09-19 01:05 UTC
Labels: kind/bug

**Comment by LinkIsGrim** [comment] 2023-09-19 01:40
@LinkIsGrim note to self: make new issue, fix with OpticsModeChanged EH
