### ISSUE TITLE
New medical system still broken, people don't die from limb shots

### ISSUE THREAD

**Issue by Brumes-Wolf** [acemod/ACE3#7590] opened 2020-03-10 16:06 UTC
**Mods (complete and add to the following information):**
- **CBA:** Steam version
- **ACE3:** Steam version

**Description:**
A Limb shot will never kill, you can put several mags into the legs, and they won't die. I reported this right after the medical rework, went to see if it was fixed after the recent update, but the issue still exists.

**Steps to reproduce:**
Place AI
Shoot AI
If AI goes uncon shoot their legs
AI Wont die unless shot in torso or head

**Expected behavior:**
The SUM DAMAGE setting should have an ai die after a certain treshold of damage all over the body is reached, like the pre rewrite system.

**Where did the issue occur?**
SP

**Log Files:**
https://pastebin.com/iBj6kz9w

**Additional context:**
Introduced with the medical rewrite, still present and preventing us from using the live version of ACE

**Screenshots:**
Old video, but problem is the same
https://youtu.be/UdF9xk6dfPo

**Comment by BaerMitUmlaut** [comment] 2020-03-10 16:34
Duplicate of #7358.

**Closed by BaerMitUmlaut** 2020-03-10 16:34 UTC
Labels: kind/bug
