### ISSUE TITLE
Medical (3.3.2.0) - Multiple issues

### ISSUE THREAD

**Issue by W4R-PYR4T3** [acemod/ACE3#2580] opened 2015-09-23 18:07 UTC
Just a few comments...

1. Using bandages inside a building on the 2nd floor always puts the bandages on the floor below
(Would be nice to have bandages attached to players rather than littering the map, but whether that's possible is another thing entirely. Maybe when they are removed leave them on the floor unless interacted with to put them in your backpack as used...?)

2. Healing yourself after being shot ; let's say your right arm and head are injured. Healing yourself with bandages will randomly add torso damage that wasn't there to start with.

3. Bandages are floating about 2-4 inches above the floor.
![floating](https://cloud.githubusercontent.com/assets/14365298/10053867/381671e4-6226-11e5-8b19-94a3e42f2214.JPG)

4. Double deaths per player kill still present, but only if killed by AI. If blown up inside a vehicle or you do something dumb to kill yourself this only adds a single kill.

**Comment by Dobakjang** [comment] 2015-09-24 09:42
still can't revive people when they are in unconscious

also none heart beat rate

**Comment by Th3Cr0w** [comment] 2015-09-24 10:34
@Dobakjang 
Is this related to "CPR would never succeed when patient was in revive state (#2099)" ?
If so the Changelog is misleading:
It's intentional that player in revivestate can only be healed by applying a PAK
What got changed was that CPRlocal now runs till the end and successful writes a log.

**Comment by PabstMirror** [comment] 2015-10-11 04:11
For 2. What medic settings basic/advanced)?  Can you always reproduce consistantly?

**Comment by PabstMirror** [comment] 2016-01-02 00:07
1,3,4 have been explicitly fixed.
I can't reproduce 2 and I think it's probably been fixed by #2646

Can probably close

**Closed** 2016-02-20 09:18 UTC
Labels: bug
