### ISSUE TITLE
Advanced Vehicle Damage makes RHS ERA too strong

### ISSUE THREAD

**Issue by grimsurgent** [acemod/ACE3#8816] opened 2022-02-10 02:17 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** 2.06.148470 latest stable
- **CBA:** 3.15.6
- **ACE3:** latest stable steam workshop release
- RHS AFRF
- RHS AFRF ACE COMPAT

**Description:**
Advanced Vehicle Damage makes RHS ERA and SLAT too strong, if not invincible.

**Steps to reproduce:**

1. Start an empty mission, place down any vehicle with ERA modules. (RHS T-90 was used)
2. Get in another tank and shoot at the ERA module.
3. If advanced vehicle damage is enabled, the ERA modules will not be destroyed when you shoot at it with AP rounds. (RHS 3BM46 from T-72 was used, but same with other rounds used.) When advanced vehicle damage is disabled, the ERA will be destroyed after the first hit, and stops providing additional protection.

**Expected behavior:**
ERA was supposed be destroyed, but stayed intact.

**Where did the issue occur?**
Singleplayer

**Additional context:**
This makes some RHS vehicles stronger then they are supposed to be, as the one time protection of ERA is now unlimited.

**Screenshots:**
ERA being destroyed with 1 shot whilst advanced vehicle damage is disabled
https://cdn.discordapp.com/attachments/460561001125773312/941154735552098314/20220209201036_1.jpg

ERA still intact after being shot 5+ times with same tank and ammo as before with advanced vehicle damage enabled
https://cdn.discordapp.com/attachments/460561001125773312/941154736013451304/20220209200839_1.jpg

**Comment by rautamiekka** [comment] 2022-02-10 15:02
> * **ACE3:** latest stable steam workshop release

'latest' is an Invalid version.

> RHS T-90
> T-72

RHS T-90 is heavily a WIP and I also tested some T-72's which showed a similar problem, which I think they said was also a WIP. In fact on loading a mission you'll get scripting or other errors with T-90 if you enabled the errors and debug mode in the launcher.

**Comment by grimsurgent** [comment] 2022-02-11 01:19
> > * **ACE3:** latest stable steam workshop release
> 
> 'latest' is an invalid version.
> 
> > RHS T-90
> > T-72
> 
> RHS T-90 is heavily a WIP and I also tested some T-72's which showed a similar problem, which I think they said was also a WIP. In fact on loading a mission you'll get scripting or other errors with T-90 if you enabled the errors and debug mode in the launcher.

Did some more research and it happens with ERA on USAF vehicles as well, but I narrowed it down to APFSDS not triggering it. Heat rounds and RPGs will trigger the ERA, any APFSDS round won't have an effect.

**Comment by severgun** [comment] 2022-02-11 06:34
Seems like already discussed
https://github.com/acemod/ACE3/issues/8720

**Comment by johnb432** [comment] 2024-07-11 09:40
Essentially a duplicate of https://github.com/acemod/ACE3/issues/8720.

**Closed by johnb432** 2024-07-11 09:40 UTC
Labels: kind/bug
