### ISSUE TITLE
The website ace3mod.com is down ?

### ISSUE THREAD

**Issue by osfrance** [acemod/ACE3#8869] opened 2022-04-08 19:36 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.x.x` [eg. 3.0.0 stable, commit hash]

**Description:**
The website https://ace3mod.com/ is down ? I'd an error : PR_END_OF_FILE_ERROR 
(since like when a frontend nginx reverse-proxy server redirect in HTTPS to a backend webserver in HTTP....)

**Steps to reproduce:**

1. _Go to [..._](https://ace3mod.com/)

**Expected behavior:**

**Where did the issue occur?**
- In Website

**Log Files:**

**Additional context:**

**Screenshots:**

**Comment by jonpas** [comment] 2022-04-08 19:38
Duplicate of #8865

Should be back during or after the weekend. :crossed_fingers:

**Closed by jonpas** 2022-04-08 19:38 UTC
Labels: kind/bug
