### ISSUE TITLE
Compat GM - Some Vehicles Wheels can not be re-attached

### ISSUE THREAD

**Issue by PulsarNeutronStar** [acemod/ACE3#9514] opened 2023-10-18 03:28 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14`
- **CBA:** `3.16.0` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.16.0 stable` [eg. 3.0.0 stable, commit hash]

**Description:**

For some Vehicles of the Global Mobilisation DLC, the ACE Action to "Change Wheel" is not available.

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. Editor, place GM Vehicle (for example, UAZ, 0.5t Jeep, 2t Truck, 5t Truck, M111 (Beetle),...
2. Remove or destroy wheel
3. Aquire sparewheel
4. Try to attach spare wheel to vehicle
5. Fail.

Vehicles that had have been able to replace their wheels: VW T3, Merc Limosine, Motorcycle

**Expected behavior:**
Being able to attach a sparewheel to every wheeled vehicle

**Where did the issue occur?**
Just tested on Single Player, but it happend before on an Event which ran on a dedicated server.

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**

**Screenshots:**
https://streamable.com/b70vsg

**Comment by LinkIsGrim** [comment] 2023-10-18 04:32
Upload your RPT file please

**Comment by PulsarNeutronStar** [comment] 2023-10-18 07:31
[Arma3_x64_2023-10-18_05-08-01.txt](https://github.com/acemod/ACE3/files/12998024/Arma3_x64_2023-10-18_05-08-01.txt)

**Comment by johnb432** [comment] 2023-10-18 18:07
@LinkIsGrim Repair interactions for GM vehicles are generally scuffed.

See https://github.com/acemod/ACE3/issues/7718#issuecomment-1697772935.

**Comment by LinkIsGrim** [comment] 2023-10-18 18:21
So this isn't new to 3.16.0 then?

**Comment by johnb432** [comment] 2023-10-18 19:14
> So this isn't new to 3.16.0 then?

No, this was already present in 3.15.2 (or whatever the last version was). I got wheel repair interactions in e.g. windows.

**Comment by PulsarNeutronStar** [comment] 2023-10-18 19:40
> Does this happen for all wheels on affected vehicles, or just specific ones? Do the other repair interactions work?
If the vehicle is scuffed, its the case for all of them.



> So this isn't new to 3.16.0 then?
Noticed it before about a year ago if not more, so its pre 3.16.0

**Comment by johnb432** [comment] 2024-03-25 10:35
Given it's a duplicate of #7718, this will be closed.

**Closed by johnb432** 2024-03-25 10:35 UTC
Labels: kind/bug, status/duplicate
