### ISSUE TITLE
Interaction menu follows sea level

### ISSUE THREAD

**Issue by Best2nd** [acemod/ACE3#1024] opened 2015-05-05 19:08 UTC
ACE3 Version: 3.0.0.2-NOGIT

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
None

**Description:**
http://youtu.be/U5Jd7dZ01ic

**Steps to reproduce:**
Simply stand on a dock or a pier during bad weather and have SI cursor disabled.

**Where did the issue occur?**
SP editor

**RPT log file:**
None

**Comment by alganthe** [comment] 2015-05-05 19:12
are you on drugs sir ? more seriously I can't reproduce it, the menu don't move an inch.

**Comment by PabstMirror** [comment] 2015-05-05 19:14
I've reprodued this, will look into it

**Comment by alganthe** [comment] 2015-05-05 19:16
did some testing, the issue appeared with 1698a6330ca8a13a8057b5653c97131e11f4f08e

**Comment by Best2nd** [comment] 2015-05-05 19:27
Do note you need to disable the cursor for the interaction menu, if it's on the menu will stay still.

**Comment by alganthe** [comment] 2015-05-05 19:30
yeah I did, I could reproduce the issue, problem is it's hard to reproduce (or at least for me)

**Comment by esteldunedain** [comment] 2015-05-05 20:13
Yeah, I think I've observed this before. IIRC it only happens with the self interact menu, and it's caused by the difference in wave height between the camera and a place a couple of meters in front of the camera (the position of the menu). I think it was easily reproducible on the pier on Stratis.

I didn't consider it very serious at that time, but it's something to fix eventually.

**Comment by PabstMirror** [comment] 2015-05-11 20:55
positionCameraToWorld / modelToWorld all work on ATL / ASLW.

I think what's happening is the wave heights are different at camera / projection position and I have no clue how to account for that.  I don't see any `waveHeightAt` commands.

It fairly rare, only carriers and piers:

To mitigate you can look down when self interacting as it minimizes the horizontal distance.
We could just force cursor mode if over water as that mode works fine.

**Comment by esteldunedain** [comment] 2015-05-11 20:58
Yeah pabst, that's exactly what I was trying to describe above. 

I'll try to find a solution for this eventually. For now I'm calling it a feature: realistic sea sickness simulation.

**Comment by jaynus** [comment] 2015-05-11 23:26
Only way to currently get this is to spawn a local object and move it around

```
_getWaveHeightAt = {
    _position = _this select 0;
    _object = "Logic" createVehicleLocal [0,0,0];
     setPosASL _position;
    
    (((ASLToATL getPosASLW _object) vectorDiff (getPosATL _object)) select 2)
};
```

**Comment by esteldunedain** [comment] 2015-05-11 23:30
Yeah, I've thought of that, but it seemed overkill. But anyway, I can't think of any other way atm, so maybe that's the way:

```sqf
_getWaveHeightAt = {
    _position = _this select 0;
    _object = "Logic" createVehicleLocal [0,0,0];
     setPosASL _position;

    ((getPosASLW _object) select 2) -  ((getPosASL _object) select 2)
};
```

**Comment by jaynus** [comment] 2015-05-11 23:36
If we are going to do that, we should probably just have a static single spawned logic ready for it at all times. Just spawn it globally once to a GVAR and use it for the duration of the game.

**Comment by esteldunedain** [comment] 2015-05-11 23:38
yup, that sounds good

**Comment by jaynus** [comment] 2015-05-13 04:16
@Best2nd this is fixed in latest master

**Closed** 2015-05-13 04:15 UTC
Labels: bug
