### ISSUE TITLE
RPT spammed with "Client/Server: Object not found"

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#343] opened 2015-04-06 14:09 UTC
Stolen the RPT from @bux578. Does anyone knows what is this related too and if it is caused by ACE3 at all?

CBA_A3_Dev
ACE_Dev: 83c6705
tfar

RPT: http://pastebin.com/Y97bZDWu

```
15:25:32 Server: Object 14:1144 not found (message Type_115)
15:25:32 Server: Object 14:1145 not found (message Type_115)
15:25:33 Client: Object 13:330 (type Type_122) not found.
15:25:37 Client: Object 13:332 (type Type_90) not found.
15:25:37 Client: Object 13:331 (type Type_90) not found.
15:25:37 Server: Object 16:925 not found (message Type_115)
15:25:37 Server: Object 16:924 not found (message Type_90)
15:25:37 Server: Object 16:923 not found (message Type_115)
15:25:37 Client: Object 13:330 (type Type_122) not found.
15:25:39 Server: Object 13:635 not found (message Type_90)
15:25:39 Server: Object 13:636 not found (message Type_115)
15:25:40 Client: Object 13:330 (type Type_121) not found.
15:25:41 Client: Object 13:330 (type Type_122) not found.
15:25:41 Client: Object 13:330 (type Type_150) not found.
15:25:45 Error: Object(13 : 331) not found
15:25:45 Client: Object 13:332 (type Type_90) not found.
15:25:45 Client: Object 13:331 (type Type_115) not found.
15:25:45 Client: Object 13:331 (type Type_90) not found.
15:25:45 Client: Object 13:330 (type Type_122) not found.
15:25:47 Error: Object(13 : 332) not found
15:25:47 Client: Object 13:332 (type Type_115) not found.
15:25:47 Error: Object(16 : 927) not found
15:25:47 Error: Object(16 : 926) not found
15:25:49 Client: Object 13:330 (type Type_121) not found.
15:25:49 Client: Object 13:330 (type Type_122) not found.
15:25:51 Client: Object 13:330 (type Type_150) not found.
15:25:51 Server: Object 16:932 not found (message Type_90)
15:25:51 Server: Object 16:933 not found (message Type_115)
15:25:51 Server: Object 16:931 not found (message Type_115)
15:25:53 Client: Object 13:332 (type Type_90) not found.
```

**Comment by jaynus** [comment] 2015-05-18 16:07
I have confirmed this is caused by createVehicleLocal.

Reproduction in a mission from debug console:

Run this locally in debug - it will cause RPT spam on server/other clients. 

```
_player = allUnits select 0;
_fragment = "ACE_frag_spall_huge" createVehicleLocal [0,0,10000];
_fragment setPosASL [((getPosASL _player) select 0), ((getPosASL _player) select 1), ((getPosASL _player) select 2)+10];

_dir = (getPosASL _fragment) vectorFromTo (getPosASL _player);
_dir = _dir vectorMultiply 5000;

_fragment setVelocity  _dir;
```

**Comment by esteldunedain** [comment] 2015-05-18 16:23
Ok, nice. So you're saying we can't fix it? What if we create them on the server with createVehicle?

**Comment by jaynus** [comment] 2015-05-18 16:45
createVehicle on the server also makes them appear still, it seems to be spawned CfgAmmo classes cause the errors regardless.

**Comment by jaynus** [comment] 2015-05-21 22:12
I'm closing this out as BI Fault.

**Closed by jaynus** 2015-05-21 22:12 UTC
Labels: BIS' fault, question
