### ISSUE TITLE
RPK-74 from mod RHSAFRF uses PKM magazines.

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#8228] opened 2021-04-22 20:28 UTC
**Mods (complete and add to the following information):** 
CBA_A3 	 
ace 	 	
RHSAFRF 	 	
RHSUSAF
RHSGREF 	 	
Jbad 	 	
LYTHIUM 	 	
CUP Terrains - Core 	 
CUP Terrains - Maps 	 	
CUP Terrains - Maps 2.0 	 
VSM - ACE3 Compatibility 	 
VSM All-In-One Collection 	 	
Al-Fallujah v 1.3 [Rebuild + Interiors] 	
Island Panthera 	 	
ACE Compat - RHS Armed Forces of the Russian Federation 	 	
ACE Compat - RHS United States Armed Forces 	 	
ACE Compat - RHS: GREF 
3CB Factions
- **Arma 3:** `2.02` 
- **CBA:** `3.15.` 
- **ACE3:** `3.13.6`

**Description:** 
The RPK-74 incorrectly uses 7.62 PKM mags instead 5.45 AK mags.
This is a problem ace compabilite rf mod, because the basic class of rpk is incorrectly
class rhs_weap_rpk74 : rhs_weap_pkp 
**Screenshots:**
https://cdn.discordapp.com/attachments/189399686766002176/834885818584662069/4533cdbee6cd819c.jpg

[Screen from vanilla](https://cdn.discordapp.com/attachments/189399686766002176/834884259701194783/www.jpg)

**Comment by Drofseh** [comment] 2021-04-22 21:33
duplicate of #8221 fixed in #8223

**Closed** 2021-04-22 21:36 UTC
Labels: kind/bug, status/duplicate
