### ISSUE TITLE
Medical State persists after respawn in the test mission

### ISSUE THREAD

**Issue by ViperMaul** [acemod/ACE3#5512] opened 2017-09-15 22:50 UTC
Testing the medical rewrite with untreated wounds we found the following.
Our test mission was configured to respawn immediately in the same spot where you died. 

**Observations:**
Medical State persists after respawn in the test mission
Possible related to #5020

**Expected:** 
Player to respawn in full health like the start of a mission.

**Comment by PabstMirror** [comment] 2017-09-27 02:12
Do you mean the actual medical state-machine state?

I remember seeing some weird stuff with 0 delay instant respawn in the past, were your settings like this?
```
respawn = "INSTANT";
respawnDelay = 0;
```

**Comment by commy2** [comment] 2017-09-27 16:50
```
respawnDelay = 0;
```
Causes the new object (including respawn eventhandler) to be created before the killed eventhandler of the corpse is executed. This causes problems with carried over object namespace variables as variables are copied before they're changed by a killed event.

**Comment by SilentSpike** [comment] 2018-04-08 16:53
Can confirm what commy posted, is this still an issue?

I can't figure out why #5020 wouldn't solve this since the state should still be reset to default

**Comment by TheMagnetar** [comment] 2018-04-08 21:15
I did a quick test two weeks ago with medical rewrite. While we did respawn at west marker, all injuries were "healed" after respawn.

**Comment by Phyma** [comment] 2018-08-10 06:49
@ViperMaul Is this still a thing?

**Comment by SilentSpike** [comment] 2018-08-11 15:10
This got re-broken as it looks like we accidentally removed the respawn code in our big restructure.

Will submit a fix 👍

**Comment by PabstMirror** [comment] 2019-04-12 23:00
Confirmed fixed by #6518

**Closed by PabstMirror** 2019-04-12 23:00 UTC
Labels: kind/bug
