### ISSUE TITLE
ace_compat_rhs_usf3.pbo now requires ace_goggles.pbo

### ISSUE THREAD

**Issue by Pergor** [acemod/ACE3#4030] opened 2016-06-30 22:46 UTC
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.4.1.160606-b8145500` (stable)
**ACE3 Version:** `3.6.0` (stable)

The optionals usually did not require much beside the mods they were made for, not even ace_hearing or something like that. 
With the requirement of ace_goggles.pbo (which is, by the way, not listed in requiredAddons-Array - https://github.com/acemod/ACE3/blob/master/optionals/compat_rhs_usf3/config.cpp) you now need to use ace_goggles.pbo in order to use ace_compat_rhs_usf3.pbo with rhsusaf without getting errors.

Hopefully that requirement can somehow be removed.

**Comment by PabstMirror** [comment] 2016-06-30 22:57
Depboed ace_compat_rhs_usf3 from release.zip:

`requiredAddons[] = {"rhsusf_c_weapons","rhsusf_c_troops","rhsusf_c_m1a1","rhsusf_c_m1a2","RHS_US_A2_AirImport","rhsusf_c_m109","rhsusf_c_hmmwv","rhsusf_c_rg33","rhsusf_c_fmtv","rhsusf_c_m113","RHS_US_A2Port_Armor","ace_javelin","A3_UI_F","ace_goggles"};`

I think we had a problem with this in CBA.  MikroTools are trying to help and automaticly adds entries it think we need.  There is no real requirment for `ace_goggles`.

@Glowbal - I think the gui of pboProejct we will want to uncheck "Rebuild Addons" which will then take effect when using command line tools.

**Comment by Pergor** [comment] 2016-06-30 23:10
That's sort of funny, but good to know. ;)

Looking forward to the change.

**Comment by esteldunedain** [comment] 2016-06-30 23:40
> MikroTools are trying to help

If it only did what it was told too...

**Comment by commy2** [comment] 2016-07-01 00:05
:ARMAKE: 

fuck these tools that are trying to outsmart the user - all they do is cause bugs

**Comment by Glowbal** [comment] 2016-07-01 09:37
Absolutly wonderful. We will sort this out with the 3.6.1 release.

**Comment by TheConen** [comment] 2016-07-03 16:10
Just disable the option "rebuild requiredAddons[]" in pboProject.....

**Comment by jonpas** [comment] 2016-07-03 16:11
@TheConen Yes we know, as you can read above. Doesn't change the fact a tool causes a bug like this though.

**Comment by TheConen** [comment] 2016-07-03 16:16
I always wanted to say this with it being actually true: It's not a bug, it's a feature. :sunglasses:

**Comment by commy2** [comment] 2016-07-03 17:09
feature my ass

**Comment by Glowbal** [comment] 2016-07-11 10:09
Should be fixed for 3.6.1

**Closed by Glowbal** 2016-07-11 10:09 UTC
Labels: bug, tools
