### ISSUE TITLE
PIP/2D optics lack night vision compatibility when their vanilla counterpart has it

### ISSUE THREAD

**Issue by Orum** [acemod/ACE3#3225] opened 2016-01-26 14:02 UTC
Sorry if this should be reported as a feature request and not a bug.

ACE3 Version: 3.4.2.0 (stable)

**Mods:**
* `@BaBe_midTex`
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* *None*

**Description:**
* Some 3D scopes are compatible with night vision (e.g. RCO, ARCO).  However, when I try to use night vision with the ACE3 variations on those scopes (PIP/2D), it will not work when sighting down the scope.

**Steps to reproduce:**
* Enter a map, preferably during the night, and make sure you have access to several different types of a given scope that typically works with night vision in the vanilla game (RCO, ARCO, etc.), a weapon to mount them on, and night vision.
* Mount the 3D (vanilla ArmA 3) scope on the gun, sight down it (most magnified view, not the red dot or iron on the top), and attempt to toggle night vision.  For some of the scopes this will work.
* Test the same scope's 2D or PIP version from ACE3 on the weapon, again sighting down it and attempting to toggle night vision.  For those scopes where it worked with the 3D version, it unexpectedly does not work with the 2D/PIP version.

**Where did the issue occur?**
* I tested it in single player only, but I assume this happens regardless of game mode.

**Comment by commy2** [comment] 2016-01-26 14:52
Duplicate of https://github.com/acemod/ACE3/issues/2977
Working as intended

**Closed by commy2** 2016-01-26 14:52 UTC
Labels: duplicate

**Comment by Orum** [comment] 2016-01-26 22:25
Ah, okay.  Well, looking at the other issue, it appears to be possible to enable NV on the optic itself, but how does one go about doing that?

**Comment by commy2** [comment] 2016-01-27 14:23
N. If that doesn't work then the optic isn't mean to work night vision goggles.

**Comment by Orum** [comment] 2016-01-27 15:25
Ah okay, I was confused as that other thread shows an ARCO working with it, but that was in 3.4.1, so it must have been disabled for that optic since then.  It does work on the RCO though.  Thanks!
