### ISSUE TITLE
ace_spectator: Unit list: virtual player appears + duplicate squads

### ISSUE THREAD

**Issue by voiperr** [acemod/ACE3#2677] opened 2015-10-03 20:56 UTC
ACE3 Version: 3.3.2 Stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* ace_spectator, with `GVAR(filterUnits) = 3`

**Description:**
* On starting spectator, the player's virtual character briefly shows up in the unit list. The player can be selected and followed (usually invisible, out in the ocean).
* After a few seconds, it disappears, and odd behaviour can happen, usually with one of the real speccable squads being duplicated.

**Steps to reproduce:**
* Send the player into spectator mode through
```
ace_spectator_fnc_setSpectator;
[player, true] call ace_spectator_fnc_stageSpectator
```

(do not call it through the debug console; it will crash the game)
* Repro mission: https://www.dropbox.com/s/f70zd9md0vmc1js/ace_spectator_bugs.Stratis.pbo?dl=0

**Where did the issue occur?**
Everywhere

**Comment by alganthe** [comment] 2015-10-04 09:10
Can confirm I experience this issue from time to time.

**Comment by SilentSpike** [comment] 2015-10-04 11:40
:+1: Good report, will investigate

**Comment by SilentSpike** [comment] 2015-11-18 15:04
Not entirely sure what's causing this one. Looked through the code a few times and it checks out as far as I can see.

**Comment by SilentSpike** [comment] 2016-01-10 17:06
Just to update, can definitely reproduce this, still not sure what is causing it.

**Comment by Cyruz143** [comment] 2016-01-18 10:42
Just to clarify, is this why if a unit dies, you still have 4 people listed in a fireteam but it just repeats one name, for example:

```
Pre-death:
    A1 ->
        John
        Thomas
        Oliver
        Dave

Post Oliver's death:
    A1 ->
        John
        Thomas
        Dave
        Dave
```

Hit escape to force reload spec UI seems to clear it.

**Comment by SilentSpike** [comment] 2016-01-18 18:33
It's most likely related, in fact, your post is a little more specific with regards to reproduction and might help me to track down the cause

**Comment by esteldunedain** [comment] 2016-02-23 17:39
Fixed in #3147

**Comment by SilentSpike** [comment] 2016-02-24 19:04
Only partially fixed! :smile:

**Comment by SilentSpike** [comment] 2016-02-24 19:20
Since I'm quite busy at the moment and don't have much development time I'll write down my current thoughts on this issue in case anybody else wants to take a look:

- Remaining issue is that there are seemingly arbitrary duplicate units/groups in the tree
- [Here](https://github.com/acemod/ACE3/blob/804456c722b39e2f33c26a29da47eb57b4e6617b/addons/spectator/functions/fnc_handleInterface.sqf#L332-L414) is the code that updates the tree control
- I notice that on line 348, there is no `- 1` like the similar lines 340 and 341. Probably worth investigating that.
- If Cryuz134's comment above is accurate, it seems that when a unit dies, his node in the tree is taken by the next unit in the group (I assume this wouldn't happen if his name was last) and the unit's old node is left behind.
- I've just looked through that code again and it all seems fine except for the discrepancy I mention above. I don't think that's intentional because I would have wrote a comment to make it clear.

**Comment by jonpas** [comment] 2016-02-24 20:58
2 notes for using the repro mission provided by @voiperr:
- module won't work with current implementation in Eden, must use description.ext:
```
class ACE_Settings {
    class ace_spectator_filterUnits {
        typeName = "SCALAR";
        value = 3;
    };
};
- `ace_spectator_fnc_setSpectator` must be called with empty array `[]`, otherwise `_this` will carry over from `spawn` due to scope and be executed like `0 call ace_spectator_fnc_setSpectator`, causing RPT error (since 1.54, it will still continue executing though)
```

**Comment by SilentSpike** [comment] 2016-05-11 21:52
Duplicates should be fixed by #3781 :hammer:

**Comment by Cyruz143** [comment] 2016-05-12 07:16
Quick test with 4 people shows https://github.com/acemod/ACE3/pull/3781 working without any side effects, will run it on Saturday with 40+ and see how it handles that.

**Comment by SilentSpike** [comment] 2016-05-18 15:41
This issue appears to be fixed and the changes have been merged to master, closing! :tada:

**Closed by SilentSpike** 2016-05-18 15:41 UTC
Labels: bug

**Comment by Cyruz143** [comment] 2016-05-18 16:23
Worked fine with larger numbers, forgot to update this :banana:
