### ISSUE TITLE
Mapmarker can't be placed in direct communication

### ISSUE THREAD

**Issue by 0dr** [acemod/ACE3#5915] opened 2017-12-15 01:39 UTC
**Arma 3 Version:** 1.80.143830 (Profiling)
**CBA Version:** CBA_A3 v3.5.0.171204
**ACE3 Version:** 3.12.0 RC1

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Map markers in mp can't be placed to the direct com channel.
The "Show to:" dropdown has all the channels but direct com.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer)

**Placed Modules:**
 *none*

**Comment by 0dr** [comment] 2017-12-15 01:47
I only now noticed that this feature is BI. 

fault/BI

**Comment by 0dr** [comment] 2017-12-15 01:57
question is, can this be fixed by ace?

**Comment by madpat3** [comment] 2017-12-15 16:49
i think, it's intendet, because this is a temporarly channel, which is only present to people within a certain distance to each other. if your further away, you can't hear / (see map markers etc.) of other people within this channel.

**Comment by PabstMirror** [comment] 2017-12-15 17:00
Marker syncing is handled by the engine
I really don't think this is something we can fix

**Comment by madpat3** [comment] 2017-12-15 17:59
i don't know what you mean with syncing, but the option to place a in "direct channel" don't show up in the tabs, where you can select the channel, the marker should be placed in.

**Comment by 0dr** [comment] 2017-12-15 18:24
the intention is to be able to place marker either local to the unit or at least only visible to units close by. (just like it was) 
We're playing realistically without technology that would allow us that information sharing the other channels provide.

**Comment by commy2** [comment] 2017-12-15 21:34
>i don't know what you mean with syncing

Making it so that other people can see them. Including people that join later.

**Comment by commy2** [comment] 2017-12-15 22:17
This is not fixable. One would have to create markers with script commands, and those aren't deleted by the players. Behave too differently. I'd say out of scope of the current system, and not a bug.

**Closed by commy2** 2017-12-15 22:17 UTC
Labels: fault/BI, kind/feature request
