### ISSUE TITLE
ace3 map manipulation  deadzone (contact dlc)

### ISSUE THREAD

**Issue by thorxism** [acemod/ACE3#7654] opened 2020-04-20 14:09 UTC
Mods:
- Arma 3: 1.19.146303
- CBA: v3.15.0
- ACE3: 3.13.1

Dlc:

- Contact
- all other dlc

Description:

Can't manipulate the map in the middle section of the screen with the "Contact dlc" loaded, like there is some kind of deadzone in the middle (see screenshot)

- drag to move
- scroll to zoom
- place markers

when I try these things outside of the deadzone (on the edge areaof  the map works fine)

I can:

- drag to move
- scroll to zoom
- place markers

also starting to drag on the edge area and continueing through the middle works also fine

the map in the uav terminal works without issues
and the map in mcc4 works also without issues

when disablling contact or ace3 seperately the map works fine

Steps to reproduce:

- start editor
- place player
- start scenario
- open map (m)

Expected behavior:

without contact dlc the map can be used normally

Where did the issue occur?
 Singleplayer / Editor (Singleplayer)

hope this helpful
and thanks in advance

regards,

Rob

screenshot:

![Arma3_x64-2020-04-20-15-25-22-03](https://user-images.githubusercontent.com/64020004/79758542-d0e23f80-831d-11ea-9c76-1e963d4aa418.jpg)

**Comment by commy2** [comment] 2020-04-20 14:48
ACE is not compatible with Contact DLC.

**Comment by thorxism** [comment] 2020-04-20 19:57
removing ace_map.pbo does the trick thanks!

**Comment by BaerMitUmlaut** [comment] 2020-04-22 08:46
Should we fix this or consider it out of scope?

**Comment by PabstMirror** [comment] 2020-04-22 14:25
I don't own contact, but I will try to take a look at ace_map

**Comment by thorxism** [comment] 2020-04-22 17:40
I just realised all assets from contact are still in the game even when unchecked in the launcher, so for me its not really a problem anymore and I can use ace_maps again

**Comment by Mike-MF** [comment] 2023-09-19 01:41
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Closed by Mike-MF** 2023-09-19 01:41 UTC
Labels: kind/bug
