### ISSUE TITLE
Unholstering weapon not working and ace3 interaction menu greyed out

### ISSUE THREAD

**Issue by JohnFromSteam** [acemod/ACE3#1532] opened 2015-06-07 13:15 UTC
ACE3 Version: 3.0.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *None*

**Description:**
*Pressing 0 holsters your weapon, but does not unholster. Coming back to a scenario seems to grey out the ace3 interaction menu (windows key).*

**Steps to reproduce:**
* *First, grab a scenario like Pilgrimage, then start it up and try to holster/unholster your gun. Save the progress, restart ArmA 3, then resume gameplay of that scenario and try using the ace3 interaction menu.*

**Where did the issue occur?**
*Singleplayer*

**RPT log file:**
*No clue what that is*

**Comment by esteldunedain** [comment] 2015-06-07 13:44
Unholstering issue is a duplicate of https://github.com/acemod/ACE3/issues/1208.

As for saving/loading, that's not yet supported in ACE.

**Closed by esteldunedain** 2015-06-07 13:44 UTC

**Comment by JohnFromSteam** [comment] 2015-06-07 14:17
Will saving/loading be supported in the future?

**Comment by esteldunedain** [comment] 2015-06-07 14:21
It has already been requested. TBH ACE focus is not on SP, so saving support is low priority. I'd like to see it happen though. We are implementing certain framework changes that should make it possible, so we'll see.

**Comment by JohnFromSteam** [comment] 2015-06-07 14:21
Alrighty, thank you!

**Comment by F0restperson** [comment] 2017-10-15 16:15
Has this issue been fixed? ACE 3 provides an amazing improvement to ArmA3 and Pilgrimage is my favorite way to play. It would be great if they worked together.

**Comment by PabstMirror** [comment] 2017-10-15 17:23
There should be compatiblity with saved games now in ace: #1098

**Comment by F0restperson** [comment] 2017-10-16 02:08
When loading a saved game of Pilgrimage (RHS Chernarus) with ACE3 installed, it get this failure message: "You cannot play/edit this mission; it is dependent on downloadable content that has been deleted. a3_weapons_f_mod, r3f_armes_c, etc." What is up this is?

**Comment by PabstMirror** [comment] 2017-10-16 05:03
a3_weapons_f_mod is http://steamcommunity.com/sharedfiles/filedetails/?id=669962280
r3f_armes_c I think is http://steamcommunity.com/sharedfiles/filedetails/?id=911191183
