### ISSUE TITLE
Bloodbags do nothing to raise a patient's blood level

### ISSUE THREAD

**Issue by SkyeGuy** [acemod/ACE3#4502] opened 2016-10-03 00:36 UTC
**Arma 3 Version:** `1.64` stable
**CBA Version:** ` 3.1.0` stable - new update
**ACE3 Version:** `3.7.0` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Whenever a man is shot to the point where significant bleeding has occurred bloodbagging does not affect their blood status - i.e. in the medical menu the patient when diagnosed states "Lost a lot of blood" and 10 1000mL (the largest volume BB's) given do nothing - patient still says "Lost a lot of blood". This is severely affecting milsim operations as men essentially have to respawn to be functional in the battlefield - waking up with Epi gets them up but due to their blood status they pass out immediately. 

**Steps to reproduce:**
- Tested this using just the newest CBA (which upon load in gives a red error dialog saying "f(x) f(x) [ACE] (interact_menu) ERROR - Failed to add action" that takes up most of the player's FOV, but disappears after 10 seconds or so. This doesn't seem to affect the interaction menu at all but this is seen in game. Tested in a multiplayer server environment with no other mods besides CBA and ACE to ensure third-party mods are ruled out. We just shot another player to the point where they went unconscious and did the normal bandage/bloodbag/morphine/epinephrine process to no avail. ACE modules were used in the mission scenario to tweak medical settings (essentially the ones used in the milsim)

**Where did the issue occur?**
- Dedicated server environment

**Placed Modules:**
- Advanced Ballistics, Advanced Fatigue, Advanced Throwing, Check PBO's, Explosive System, Hearing, Interaction System, Map, Map Gestures, Name Tags, Pointing Settings, Captives Settings, User Interface, Wind Deflection, Zeus Settings, Blue Force Tracking, Respawn System, Mk6 Settings, Nightvision, Friendly Fire Messages, Medical Settings, Basic Medical Settings, Medical Menu Settings, Revive Settings, Repair Settings, Refuel Settings, Rearm Settings, Cargo Settings, Assign Engineer, Set Medic Class, Zeus Gamemaster Module and Slingload module from vanilla Arma 3.

**RPT log file:**
- Will add in RPT log file when possible, unavailable at this time unfortunately.

**Comment by alganthe** [comment] 2016-10-04 09:49
Remember that IVs take time to complete, around 2-5 minutes for 500 mL.
Any wound in that mean time (especially avulsions) reopening or occurring will also affect the blood volume, possibly negatively.

**Comment by Glowbal** [comment] 2016-10-05 10:19
This is happening due to a change in behaviour as a result of merging both medical systems. We will address this in the medical rewrite.

**Comment by Gaspasar** [comment] 2016-10-05 15:37
thanks for looking into.
we are playing with basic medic settings and since 3.7 it takes about 6-8 liter of blood for a  heavy wounded. before it was about 1-2 liter.

is there a workaround for the moment? yesterday it was some kind of plot  stopper.

**Comment by Glowbal** [comment] 2016-10-05 15:45
The difference you are seeing is that before with basic medical, when using a blood IV the volume was raised instantly. At the moment, the blood volume is being raised over an extended period. 

This means it will take longer for the same amount of blood to be fully added to the blood volume of a patient. It may be possible that the volumes are slightly different as well, but I do doubt that.

Either way, we will make sure this behaves as intended with the medical rewrite.

**Comment by Gaspasar** [comment] 2016-10-05 16:02
Thanks for the reply. 
So its more a feature than a bug. Sry we didnt understand. Just played one round with 3.7 yet.
We give it a try, maybe its even more fun that way. Is there any visual feedback how long the blood raises?

**Comment by alganthe** [comment] 2016-10-05 16:22
No visual feedback, but more IVs increase the flow rate.

**Comment by Glowbal** [comment] 2016-10-05 17:13
> but more IVs increase the flow rate

Not true. They stack and will handle it one by one in the current system.

**Comment by SkyeGuy** [comment] 2016-10-05 18:40
Thank you for replying guys - I'll let the rest of my unit know. Just by chance, do you know what is the target blood volume for a non-injured soldier? Be nice to know to tell medics to bring "x amount of bloodbags for x casualties"...

**Comment by NomadVR** [comment] 2016-10-08 15:18
So, what's actually happening in this process with 3.7? If you give say, 1000ml to someone who has lost a lot of blood. It will just take longer for it to take action unlike before which was instantly? Is there any way to modify this?

**Comment by Glowbal** [comment] 2016-10-09 10:55
It takes 6 seconds for 250ml to be added in basic medical. 1000ml will take 4x as long.

Total blood volume is 7000ml. Minimum blood volume level is 30% (anything lower as the patient dies) and you are unconscious with anything below 60%.

**Comment by NomadVR** [comment] 2016-10-09 16:42
Did the total blood volume increase in recent patches? (We had skipped a few ACE updates til last week) It never seemed like it took that much before. It seems that even if you have lost "a lot" of blood you can still regain consciousness. When does "a lot" get triggered instead of "some" blood, is that under 60%?

I've had times where I gave a patient well over the amount needed. I'm sure I gave him 4000ml+ and he still had lost a lot even when fully bandaged and not in pain anymore.

**Comment by commy2** [comment] 2016-10-19 19:16
fixed in rewrite

**Closed by commy2** 2016-10-19 19:16 UTC
Labels: Focus Feature
