### ISSUE TITLE
Lower the main action point on the rally point flag

### ISSUE THREAD

**Issue by HydroBull3T** [acemod/ACE3#837] opened 2015-04-24 12:22 UTC
ACE 3 with CBA 

In editor:
Placed Rallypoint module.
Placed 2 flags, 1 to base and 1 to deployed rally.
Synced the module to one soldier.

In game:
Spawned and tried to interact with those flags.
Cannot archive interaction with flags.

Works:
Via self interaction can deploy rally point.

**Comment by jonpas** [comment] 2015-04-24 12:24
Please follow guidelines at http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by alganthe** [comment] 2015-04-24 12:31
is it even supposed to work that way ?

**Comment by HydroBull3T** [comment] 2015-04-24 13:45
yes, from AGM.

On Fri, Apr 24, 2015 at 3:31 PM, Josuan Albin <notifications@github.com>
wrote:

> is it even supposed to work that way ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acemod/ACE3/issues/837#issuecomment-95918195>.
>



-- 
Igal M

**Comment by commy2** [comment] 2015-04-24 16:40
First of all:
>Please follow guidelines at http://ace3mod.com/wiki/user/how-to-report-an-issue.html

I can use the rallypoints to teleport without problem.

![http://i.imgur.com/HxCTdAT.png](http://i.imgur.com/HxCTdAT.png)

You might want to look up a bit. The flagpoles from vanilla have no selections in their memory LOD I could use as position for the action. The menu position defaults to the center of the model, which is a bit hight on an objects as tall as an pole.
There is a PR from ED that changes the position to an offset. The rallypoints are set up to support that method, but the PR isn't finished / merged yet.

**Comment by esteldunedain** [comment] 2015-04-24 17:03
> There is a PR from ED (esteldunedain) t

I'll be rewritting that code in the next few days, but it'll totally fix this. 

I'll rename the issue as a reminder

**Comment by HydroBull3T** [comment] 2015-04-24 17:06
Thanks and sorry my bad about the bad report guidelines.

On Fri, Apr 24, 2015 at 8:03 PM, Nicolás Badano <notifications@github.com>
wrote:

> There is a PR from ED (esteldunedain) t
>
> I'll be rewritting that code in the next few days, but it'll totally fix
> this.
>
> I'll rename the issue as a reminder
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acemod/ACE3/issues/837#issuecomment-95993149>.
>



-- 
Igal M

**Comment by jonpas** [comment] 2015-04-24 18:07
No probs, try to use it next time, ACE3 issue tracker is very crowded and without proper unified reporting it gets really hard to manage.

**Comment by dixon13** [comment] 2015-04-30 15:36
FYI this is still an issue and also, the text should say "Teleport to Base" and not "Teleported to Base". Same goes for the other rallypoint flagpole.

**Comment by HydroBull3T** [comment] 2015-04-30 18:18
Thanks for the informing

**Comment by commy2** [comment] 2015-04-30 20:47
Changed strings in https://github.com/acemod/ACE3/commit/2ae5538df5948c922e2877d8456e3c5736a91653

**Comment by commy2** [comment] 2015-04-30 20:48
>FYI this is still an issue

Yeah, thats why the issue is still open.

**Comment by esteldunedain** [comment] 2015-05-01 04:54
![image](https://cloud.githubusercontent.com/assets/7674951/7426809/f6ce6654-efa4-11e4-938e-e0ed64210e54.png)

**Comment by bux578** [comment] 2015-05-01 04:57
Looks good. Close?

**Closed** 2015-05-01 04:58 UTC
Labels: task
