### ISSUE TITLE
Adv. Bal.: Flight path discrepancy between clients

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#3353] opened 2016-02-19 20:32 UTC
**Arma 3 Version:** 1.56

**ACE3 Version:** `3.4.2` stable

**Mods:**
* `@CBA_A3` 2.3.0
* `@ace`

**Placed Modules:**
* Adv. Bal.
![image](https://cloud.githubusercontent.com/assets/1235520/13188095/a07bed9c-d74f-11e5-8113-9491596f11e5.png)

**Description:**
* When shooting a sniper rifle (e.g. M200) the bullet drops differently for people watching and for the shooter himself

Video from the spotter:
https://youtu.be/rNcQAUgYE9g

Images from the shooter:
![2016-02-19_00003](https://cloud.githubusercontent.com/assets/1235520/13188207/3a0f26ae-d750-11e5-97c6-47f0120b9e53.jpg)
![2016-02-19_00002](https://cloud.githubusercontent.com/assets/1235520/13188208/3a110dca-d750-11e5-9597-2870fb4b697d.jpg)

**Steps to reproduce:**
* Place 2 snipers and equip them with M200
* Have 2 people join
* Assign 1 as shooter and 1 as spotter
* Let the shooter set the Vertical Scope Adjustment to 10
* enable `BIS_fnc_traceBullets`
* observe bulltet trace effect vs. the traced flight path.

**Where did the issue occur?**
* "Dedicated Server"

**RPT log file:**
* Server: http://pastebin.com/z02hvK1J
* Client: http://pastebin.com/rYmvBMyz

**Comment by esteldunedain** [comment] 2016-02-19 20:34
I'll take a look.

**Comment by bux578** [comment] 2016-02-19 20:58
Misson we used: https://dl.dropboxusercontent.com/u/8832727/_Jo/ACE/advBalTest.Altis.pbo

**Comment by esteldunedain** [comment] 2016-02-20 15:30
@bux578, I cannot replicate this in current master, which is good. I'll try 3.4.2 next

**Comment by esteldunedain** [comment] 2016-02-20 18:18
Well, the problem is that EFUNC(common,setVariablePublic) is broken in 3.4.2. Hence the scope adjustments were not propagating properly between clients. However, it was fixed on master on Dec 28 by @PabstMirror, who merged some old commits of mine.

Hence, this is working properly on current master and will be fixed on 3.5.0.

PD: While diagnosing this my main PC died; I'll try my best to finish what's left for 3.5.0 but I cannot guarantee I'll be able too.

**Closed by esteldunedain** 2016-02-20 18:18 UTC
Labels: bug
