### ISSUE TITLE
Can't run dedicated server with modname different than @ace

### ISSUE THREAD

**Issue by rlex** [acemod/ACE3#517] opened 2015-04-12 15:52 UTC
ACE3 Version: master, commit id https://github.com/acemod/ACE3/commit/d6ec8d771e934a51bff550ca7b78ab688f16a805

**Mods:**
* @cba_a3
* @ace3 (customized, some modules removed)
* @RHSUSF
* @RHSAFRF
* @ALiVE

A3 performance server binary

Full list of mods in RPT...
**Placed ACE3 Modules:**
* None

**Description:**
* Started server, can't connect with ACE enabled - stuck at map loading screen

**Where did the issue occur?**
* MP, dedicated server

**RPT log file:**
* https://gist.github.com/rlex/fcc737558824bd0d83ce - last line is my attempt to connect and then pressing enter. 

Server works fine with ace disabled.

**Comment by rlex** [comment] 2015-04-12 15:55
Also, server process will not die after i close A3 server window, it's still sitting in system, hogging 20-25% CPU

**Comment by rlex** [comment] 2015-04-12 15:57
Tried with "full" ace version, it working. Seems there is some issue with removing specific modules. I'll try to track what module exactly causing server issues.

**Comment by rlex** [comment] 2015-04-12 16:10
Ok. it's not related to any mods. I keep my "modified" ace with name @ace-le, and if i run server with that mod, it doesn't work. Renamed folder to @ace and BAM. Everything works now!

**Comment by commy2** [comment] 2015-04-12 16:26
Did you binarize with the make.py or did you only pacl via build.py?

You have to binarize, otherwise the macros / includes / filepaths / tetures won't be there if you change the filenames or directory.

**Comment by rlex** [comment] 2015-04-12 16:26
I build whole release with make.py to test ACE on my server with friends.

**Comment by commy2** [comment] 2015-04-12 16:30
Can you upload the RPT file of the server?

**Comment by rlex** [comment] 2015-04-12 16:31
https://gist.github.com/rlex/fcc737558824bd0d83ce

**Comment by commy2** [comment] 2015-04-12 16:45
Can't reproduce.

1. The addons you mentioned in the opening post dont match what is printed in the RPT file.
2. The test should be repeated with CBA and ACE enabled only.
3. You posted the same RPT twice. There has to be a client RPT too.

**Comment by rlex** [comment] 2015-04-12 17:02
Ok, i'll do the test a bit later.

**Comment by rlex** [comment] 2015-04-13 20:22
Tested https://github.com/acemod/ACE3/commit/ada62fca7dee01cd63873f055cc86f96f6ba4311 with same modpack and same modname. Not happening anymore.

**Comment by commy2** [comment] 2015-04-13 22:29
Good to hear. Who knows, maybe an error in the build that is now fixed.

**Closed by commy2** 2015-04-13 22:29 UTC
Labels: bug, can't reproduce
