### ISSUE TITLE
explosives don't stay attached to surfaces after you set up a trigger

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#863] opened 2015-04-25 22:25 UTC
built 2015-04-26 at 0h15m UTC+1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
none

**Description:**
Explosives float in the air after you set up a trigger for them.

for example if I attach an explosive charge to the trunk of an offroad and start driving around the charge stay sticked to the trunk, but If I set a trigger for the charge when I start driving the it float in the air at the position it was set.

**Steps to reproduce:**
* place an explosive specialist
* place a vehicle of any sort
* place an explosive charge on the vehicle and drive / fly around a bit notice that it stays on
* set up the trigger and start moving notice that the charge stays floating where you set up the trigger.

**Where did the issue occur?**
MP, SP, editor

**RPT log file:**
none

**Comment by jaynus** [comment] 2015-04-26 02:22
duplicates #365

**Comment by esteldunedain** [comment] 2015-04-26 02:48
I'm not sure this is a duplicate. Let me reopen it to keep as reference until we diagnose it properly.

**Comment by alganthe** [comment] 2015-04-27 12:44
any input on what need testing ?

**Comment by CorruptedHeart** [comment] 2015-04-29 08:41
I do believe https://github.com/acemod/ACE3/issues/365 is a duplicate of this. Testing with #909 should prove it.

**Comment by ulteq** [comment] 2015-04-29 20:09
Fixed: https://github.com/acemod/ACE3/pull/909

**Closed by ulteq** 2015-04-29 20:09 UTC
Labels: bug, duplicate, need more info, needs testing
