### ISSUE TITLE
Bipod deploying animations didn't work

### ISSUE THREAD

**Issue by narrundo** [acemod/ACE3#2953] opened 2015-12-06 05:02 UTC
ACE3 Version: 3.4.0
-

Mods:
-

@CBA_A3
@ACE
@AllinArmaTerrain
@MCCSandbox

Placed ACE 3 Modules : 
-
none

Description:
-
when deploying bipod there is no animation even bipod already deployed but in my vision the bipod stay undeployed.

Steps to reproduce:
-
Deploy bipod while prone 

Where did the issue occur?
-
"Multiplayer", "Editor" or "Singleplayer"

**Comment by narrundo** [comment] 2015-12-06 06:09
fixed problem caused by mcc sandbox mod

**Comment by commy2** [comment] 2015-12-06 09:22
Nope. Bug in ACE. Duplicate of https://github.com/acemod/ACE3/issues/2933

**Comment by narrundo** [comment] 2015-12-06 09:31
oh I thought it was caused by other mod

**Comment by commy2** [comment] 2015-12-06 10:10
Close as dup. Fix soon.

**Closed by commy2** 2015-12-06 10:10 UTC
Labels: bug, duplicate
