### ISSUE TITLE
Zeus Cannot Respawn When Killed While Unconscious

### ISSUE THREAD

**Issue by Punchington** [acemod/ACE3#9945] opened 2024-04-10 23:02 UTC
**Mods:**
- **Arma 3:** `2.16.151618` stable
- **CBA:** `3.17.0` stable
- **ACE3:** `3.17.0` stable

**Description:**
In multiplayer scenarios where a player character has access to the Zeus interface, if they go unconscious and the animation fully completes (i.e., player is in one of the unconscious poses), then if they are killed, they do not return to the respawn menu properly. Instead, the menu never opens and their camera remains on their body.

The player can attempt to open Zeus but the menu will fail to stay open, which is normal (that's what usually happens when you try to open Zeus while dead). Sometimes the player is able to use text chat. The player can also still open the 'escape menu' and attempt to respawn again, but nothing will happen.

Ultimately, there is nothing the player can do except return to the lobby and/or reconnect (haven't actually tested this yet, but I don't see why this wouldn't fix it), which is of course extremely problematic for those hosting listen servers.

**Steps to reproduce:**

1. Open the Eden editor and create a MP scenario featuring a playable unit, a **Zeus** Game Master module, and Respawn Position module set for the playable side.
2. Set the Owner of the Zeus module to `#adminLogged`.
3. In the Init of the playable unit, add `call {{_x addCuratorEditableObjects [[this], true];} forEach allCurators;};` so that the unit will be accessible by the Zeus module.
4. Under the Attributes tab, go into Multiplayer. Set the Respawn mode to `Respawn on Custom Position`. Enable `Select respawn loadout` and `Select respawn position`. Disable `Show respawn counter`, as it's not necessary. Also, be sure to set the Respawn Delay to something reasonable (eg. 5 seconds).
5. Host the scenario, either as a listen server or as a dedicated server.
6. Select the playable unit in the role assignment screen.
7. Start the scenario.
8. Once in the game, spawn in on the respawn position.
9. Open the Zeus interface (default: y).
10. Place the ACE Medical _Toggle Unconscious_ module on your player character.
11. Wait for the animation to complete.
12. Get killed. Can be by another character shooting at you, force respawning, whatever works.

Result: the respawn menu will only appear for a few brief frames before hiding itself, and you will be stuck dead.

**Expected behavior:**
On death, the screen should fade to black, with the scoreboard visible for a couple seconds until the respawn menu opens, allowing you to respawn. Whether or not you are in the Zeus interface and/or killed while unconscious should not have any effect on this normal respawn behaviour.

**Where did the issue occur?**
- Dedicated
- Self-Hosted Multiplayer

**Log Files:**
- https://gist.github.com/Punchington/c21b632b43f364556f20c86b16be9c4f

**Additional context:**
Bug came with the most recent ACE update which included changes to prevent player bodies from ragdolling on death when unconscious. Discovered this bug while testing this new change out. Bug seems to only occur if the unconscious animation finishes playing.

My friend group has a bad habit of killing the Zeus while they are preparing missions, so this bug is, as far as I'm concerned, "game breaking" until fixed. Not to mention I tend to access Zeus while unconscious because what else am I going to do? It's a good time to quickly Zeus things since I'm not able to do anything until I die or am revived. But of course, I can't do that safely anymore with this bug.

However, there is a small workaround I found. The following can be executed shortly after death to get the respawn menu to open:
`["close"] call BIS_fnc_showRespawnMenu;`
`["open"] call BIS_fnc_showRespawnMenu;`
However, you'll find that respawning is disabled, so you'll also need to run:
`setPlayerRespawnTime 3;`
This script can be added to a scenario's onPlayerKilled.sqf file, but may need to be spawned and feature sleep commands before both respawn functions are called (I use 0.3 second delays).

I haven't tested this bug with other people yet, but I have little motivation to try Zeusing with others until this bug is fixed. I've observed this bug happening on my dedicated server (launched with TADST), albeit I had other mods also enabled when testing for it on there.

Last thing to note is that I have changed a lot of my Addon Options, so if you need a copy of my settings, I'd be happy to provide them upon request.

**Videos:**
- https://youtu.be/KRJtn_FB8Vk?si=Pi-qHE6x5ntu9-lk

**Comment by johnb432** [comment] 2024-04-11 08:02
I was able to reproduce with ACE 3.17.0.

Can you test with https://steamcommunity.com/sharedfiles/filedetails/?id=1882627645? It should already be fixed in there.

**Comment by Punchington** [comment] 2024-04-14 20:49
Unfortunately, no, not for a while.  I was only able to find just enough time to squeeze this report out and won't be able to do further bug testing until next week.

Upon reviewing my report, I want to make it clear that this bug only seems to happen when the Zeus is killed **while in the Zeus interface**, as demonstrated in the provided video.

**Comment by Punchington** [comment] 2024-04-22 21:59
Just did a quick test.  Replaced _ace_ with the _Anrop ACE3 Master_ mod you linked. Launched the game with and without all my normal mods. Confirming that the bug does not appear to occur with that version of ACE.

What's the story behind that mod? Should I switch over to that build until ACE's next update, or keep using the official mod expecting a fix to be released soon?

**Comment by johnb432** [comment] 2024-04-23 08:08
Don't expect anything, we'll release 3.17.1 when it's ready.

Anrop ACE3 Master, whilst not maintained by the ACE team, is officially endorsed by the ACE team. I'm unsure about the origins and reasons behind it. but it allows for more easy testing of the current ACE master branch. You don't have to bother building it yourself, you can just subscribe to a mod.

**Comment by johnb432** [comment] 2024-04-23 08:12
Closing the issue because it's been addressed for 3.17.1.

**Closed by johnb432** 2024-04-23 08:12 UTC
Labels: kind/bug
