### ISSUE TITLE
Bug in vehicle crashes (ace_medical_enableVehicleCrashes)

### ISSUE THREAD

**Issue by SzwedzikPL** [acemod/ACE3#1811] opened 2015-07-06 21:38 UTC
ACE3 Version: 3.1.2.0 (latest master https://github.com/acemod/ACE3/commit/86a8fb0b647afba724d6dde3e7cad08a0fdfb1f9)

Arma 3 Version: 1.46 Stable 

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
http://pastebin.com/AjbtdiJR

**Description:**
https://www.youtube.com/watch?v=YVXw3AL1tU4

**Steps to reproduce:**
*video*

**Where did the issue occur?**
*Multiplayer, Singleplayer*

**RPT log file:**
*n/a*

**Comment by Glowbal** [comment] 2015-07-07 09:36
So.. what is the bug? What behaviour do you expect?

**Comment by SzwedzikPL** [comment] 2015-07-07 09:49
So auto eject **after** plane crushes and pilot have **no injures** is by design?

**Comment by bux578** [comment] 2015-07-31 06:02
Can't reproduce. I'm unconcious while and after ejecting.

**Comment by SzwedzikPL** [comment] 2015-07-31 10:53
Like i told @bux578 on slack:

I think we should think about is ejecting is actually needed in 100% situations. Now i always see pilot "in the air" when some plane crash.  This vehicle crashes ale awesome for helis and land vehicles couse it push players in coop to rescue missions but what chances jet pilot have in any kind of crash?

Thats first. Second is that in my community after testing this crashes we saw that in 100% of crashes pilot and crew survives crash and some part of crew dies in flames after "eject". I think it should be changed to random chances to survive crash depend on kind of crash and medical module should eject them and "lay" in distance that is safe from fire (to actually let them have chance to survive and maybie been rescued)

**Comment by bux578** [comment] 2016-01-31 07:40
Closing in favor of https://github.com/acemod/ACE3/issues/3134

**Closed by bux578** 2016-01-31 07:40 UTC
Labels: can't reproduce, need more info, needs testing, Next Milestone?
