### ISSUE TITLE
ace_advanced_ballistics.dll cause game crash at startup

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1042] opened 2015-05-07 17:01 UTC
ACE3 Version: 3.0.0.2 newest master as of writing

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Non relevant*

**Description:**
*Well... game crashed at startup:*
![crash](http://i.imgur.com/5fcn1dt.jpg)

**Steps to reproduce:**
* *Launched game and it crashed*

**Where did the issue occur?**
*"Singleplayer"*

**RPT log file:**
*Link to .bidmp, .mdmp and .rpt here:*
https://www.dropbox.com/s/n98jeqsa2lwypbt/ace_error.zip?dl=0

**Comment by alduric** [comment] 2015-05-07 17:37
Oh error noticed by arma3coop.pl :P sended to Gienkov, cheers!

**Comment by jaynus** [comment] 2015-05-07 19:57
This is probably due to the illegal instruction case of optimized builds.

**Comment by jaynus** [comment] 2015-05-07 19:58
Confirmed, it is a compiler bug.
Unhandled exception at 0x5572B2EC (ace_advanced_ballistics.dll) in arma3_2015-05-07_18-50-00.mdmp: 0xC000001D: Illegal Instruction.


5572B2EC  vxorps      ymm1,ymm1,ymm1  


He's processor says it supports vx instructions, but it is failing on an illegal instruction here. We'll need to tweak the compiler flags for this.

**Comment by esteldunedain** [comment] 2015-05-07 20:01
> Confirmed, it is a compiler bug.

**Comment by jaynus** [comment] 2015-05-07 22:26
One in a couple thousand, its ~0.5% of users. I really don't want to turn off VX instructions for them though, we may provide alternative builds for them. The optimizations we get out of them are significant.

**Comment by esteldunedain** [comment] 2015-05-07 22:47
> One in a couple thousand, its ~0.5% of users.
Mmm

**Comment by jaynus** [comment] 2015-05-13 00:17
#1111 this is fixed in the build process in vehicledamage currently.

This was related to loop vectorization by default in later versions of MSVC

**Comment by Smokey2k3** [comment] 2015-05-13 15:22
is this a fix that is still to be pushed out? 3 guys in our group have run into the same problem when trying to run ACE for the first time today.

**Comment by jaynus** [comment] 2015-05-13 18:21
Please test the extensions here and report back: 
https://github.com/acemod/ACE3/tree/extBuildFix

**Comment by Smokey2k3** [comment] 2015-05-13 19:25
early signs are good, it appears to have solved the issue. 2 out of 3 of our guys are sorted, the 3rd guy is going to try it out in the next 30mins.

**Comment by jaynus** [comment] 2015-05-13 19:28
:thumbsup:

**Comment by Smokey2k3** [comment] 2015-05-14 04:27
100% hit rate, 3 out of 3 sorted, nice work guys.. its so good to have ACE back, feels like ARMA 3 has finally arrived..

**Comment by bux578** [comment] 2015-05-14 05:12
Happy to hear that.

**Closed** 2015-05-14 05:12 UTC
Labels: bug
