### ISSUE TITLE
IR lasers not working beyond certain distance in heavy fog

### ISSUE THREAD

**Issue by zartko** [acemod/ACE3#8947] opened 2022-06-24 20:49 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** `2.08.149102` 
- **CBA:** `3.15.7.220517` 
- **ACE3:** `3.15.0` 

**Description:**
IR lasers do not work unless pointed at an object that is seemingly close enough to be optically visible through the fog.
See example: https://imgur.com/a/D7prVVW

**Steps to reproduce:**
Load up Arma with just ACE and its dependencies, go into editor and set up a very intense fog (can't see further than a few meters away). Play as someone with NVGs and an IR laser. Activate IR laser, point at sky - the "line" of the laser should disappear. 

**Expected behavior:**
The IR laser line to remain visible no matter where it's pointed.

**Where did the issue occur?**
Editor (Singleplayer)

**Comment by dedmen** [comment] 2022-06-24 23:16
ACE doesn't do IR Lasers, thats base Arma.
And cannot reproduce. I just pointed IR lasers into the sky today.

**Comment by zartko** [comment] 2022-06-25 00:45
Apologies - this is might then be a mistake on my part.
I'll do some more digging in the next few days and try to figure it out (and remove this altogether if it doesn't have anything do to with ACE).

**Comment by BaerMitUmlaut** [comment] 2022-07-01 18:46
I'm closing this because it's very unlikely that it's caused by ACE. If it is, feel free to reopen.

**Closed by BaerMitUmlaut** 2022-07-01 18:46 UTC
Labels: kind/bug
