### ISSUE TITLE
Implement zeus teleport module along with getModuleDestination

### ISSUE THREAD

**Issue by klemmchr** [acemod/ACE3#5285] opened 2017-06-17 13:58 UTC
**Description:**
- As `ace_zeus_fnc_getModuleDestination` is a really nice way to assign a target what about implementing the teleport module along with it? https://github.com/acemod/ACE3/pull/5284 also includes the state of alt, shift and ctrl when selecting the position
- There are 2 solutions coming to my mind when thinking about teleporting a unit with it's whole group
    - 2 different modules (one for single teleport, one for group teleport)
    - Teleporting the group when pressing ctrl, shift or alt while selecting the position
- Imo it's easier to select the player and select the target position like this

**Comment by SilentSpike** [comment] 2017-06-17 14:18
Good idea, technically a feature request but I won't close the issue as I would be interested in this too.

The only limitation here is that you wouldn't be able to teleport a player to a set altitude (unless targeting a plane via #5215)

**Comment by chris579** [comment] 2017-06-17 14:21
Also the question is how to handle if you teleport a player on a pier or an other object. Aligning the teleported unit to the ground would mean that it will be stuck in it.

**Comment by Mike-MF** [comment] 2023-09-11 00:52
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Closed by Mike-MF** 2023-09-11 00:52 UTC
Labels: kind/enhancement, kind/feature request, help wanted
