### ISSUE TITLE
ACEX Sitting bug

### ISSUE THREAD

**Issue by Kile467** [acemod/ACE3#6723] opened 2018-12-09 14:35 UTC
**Arma 3 Version:** `1.88 stable` (stable / rc / dev)
**CBA Version:** ` v3.9.0.181012` (stable / dev + commit hash)
**ACE3 Version:** `3.12.5 stable` (stable / dev + commit hash)
**ACEX Version:** `3.4.1 stable` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- ACEX
```

**Description:**
- ACEX animation for sitting is the same all the time, and sometimes it clips with the back of the chair depending of the type of chair.

**Steps to reproduce:**
- Sit down in any chair avalaible for sitting.

**Where did the issue occur?**
- Dedicated, Self-Hosted Multiplayer, Singleplayer

**Additional information:**
- With the wicker chair the animation is slightly moved to the right, not in the middle of the chair.

**RPT log file:**
Graphic bug, not necessary.

**Comment by Kile467** [comment] 2018-12-10 00:57
Okay!!

**Comment by alganthe** [comment] 2018-12-10 01:35
duplicate of the similarly named issue on the ACEX repo.

**Closed by alganthe** 2018-12-10 01:35 UTC
