### ISSUE TITLE
Rank icon not updating

### ISSUE THREAD

**Issue by serialtasted** [acemod/ACE3#3072] opened 2015-12-23 17:29 UTC
I have searched the Issues page and haven't found anything related to this.
The rank icon that appears on top of the player name doesn't update accordingly to the player's rank. It's always corporal.
I'm setting the ranks using the "player setRank" command.

**Comment by jonpas** [comment] 2015-12-24 08:52
Looking at the code rank icon is retrieved inside Draw3D so it should work.

Try going to ACE Options, disable Name Tags and then enable them again, that should force the update.

**Comment by bux578** [comment] 2015-12-24 11:11
I just tried it with AI units with only cba and ace3 in the editor. I couldn't reporoduce.
Please provide more information like your RPT and mission file.

**Comment by commy2** [comment] 2015-12-24 20:35
![http://i.imgur.com/TqSyv1k.png](http://i.imgur.com/TqSyv1k.png)
![http://i.imgur.com/qXL949T.png](http://i.imgur.com/qXL949T.png)
![http://i.imgur.com/xwaraps.png](http://i.imgur.com/xwaraps.png)
![http://i.imgur.com/VKOFbJL.png](http://i.imgur.com/VKOFbJL.png)
![http://i.imgur.com/LoVWpDX.png](http://i.imgur.com/LoVWpDX.png)
![http://i.imgur.com/U7FsUpK.png](http://i.imgur.com/U7FsUpK.png)
![http://i.imgur.com/6E27hGx.png](http://i.imgur.com/6E27hGx.png)

When changing the rank while the inventory display is opened, the rank is not adjusted. Closing and reopening the inventory solves this. Same in Vanilla (we don't change the rank's control at all in ACE)

Tested with `0 spawn {sleep 5; player setUnitRank "PRIVATE"}`

This needs repro steps and a RPT as it's apparently not trivial to reproduce.

**Comment by serialtasted** [comment] 2015-12-30 19:47
![gbloz](https://cloud.githubusercontent.com/assets/1916666/12056414/0d530616-af2e-11e5-9ceb-f3bc96c9f67b.jpg)
![2015-12-30_00001](https://cloud.githubusercontent.com/assets/1916666/12056413/0d5138ae-af2e-11e5-8929-b221d47fda70.jpg)

As you can see the rank is correctly set but doesn't show on ace nametag. No errors are shown on RPT. Code tested and worked fine on previous version of ace.

**Comment by jokoho48** [comment] 2015-12-30 19:54
this is a locality issue i think

**Comment by serialtasted** [comment] 2015-12-30 20:03
Same code, worked before.

**Comment by jokoho48** [comment] 2015-12-30 20:08
@serialtasted its can not work befor if you did this the same because setRank is a local command that mean it never worked befor but i take a look to fix this

**Comment by serialtasted** [comment] 2015-12-30 20:13
Is there a way I can spread the unit rank through the rest of the players?

**Comment by PabstMirror** [comment] 2015-12-30 20:18
`[player, "PRIVATE"] remoteExec ["setRank"]` 

should have global effects

**Comment by jokoho48** [comment] 2015-12-30 20:19
@PabstMirror what about build a automatic Sync in? with the new setVariablePublic function that you build?

**Comment by jokoho48** [comment] 2015-12-30 20:21
`[player, "PRIVATE"] remoteExec ["setRank", 0, true];`

**Comment by serialtasted** [comment] 2015-12-30 20:23
Going to try this way: [player, _unitrank] remoteExec ["setRank", 0, true];

**Comment by serialtasted** [comment] 2015-12-30 20:24
Like jokoho48 said lol

**Comment by PabstMirror** [comment] 2015-12-30 20:25
When someone JIPs it might sync the current value from the server, but I haven't tested.

ACE never modifies rank, so I'd rather leave it to mission makers to do it right than adding a PFEH to handle syncing.  

CBA does handle fire-team color syncing, but that is far more common than rank.

**Comment by jokoho48** [comment] 2015-12-30 20:29
@PabstMirror on my test its not get Synced. its take the Rank what the unit was on spawn.

**Comment by serialtasted** [comment] 2015-12-30 20:31
It works with the code I posted there. Goin to test the JIP

**Comment by serialtasted** [comment] 2015-12-30 20:38
Works with JIP too

**Comment by commy2** [comment] 2015-12-30 23:11
Ranks are stored in mission.sqm and therefore won't be synched JIP (the mission.sqm never changes)
The persistent remoteExec does work, but creating huge JIP stacks should be avoided.

bla, bla, bla - not ACE, close

**Closed by commy2** 2015-12-30 23:11 UTC
Labels: Mission's fault
