### ISSUE TITLE
ACE 3 Personal Aid Kits do not heal any longer

### ISSUE THREAD

**Issue by DJKITTS** [acemod/ACE3#3410] opened 2016-02-25 05:10 UTC
**Arma 3 Version:** Most Recent

**ACE3 Version:** `3.4.2`

**Mods:**
* `@CBA_A3`
* `@ace`
* `@alive`

**Placed Modules:**
All Medical Modules needed to basic revive in co-op

**Description:**
I have added the modules same as I always have for months. I use personal aid kits to heal friends when they are down. I am heavily experienced with using this and I am 100% sure I have used the modules correctly they worked a few days ago.

**Steps to reproduce:**
Add the necessary modules for reviving AI (and/or) Players using the most basic possible. The personal aid kit no longer renders a revive. Note (I am using the new arma editor Eden I have tried the 2D and it did not work) 

**Where did the issue occur?**
Single player, and non dedicated server

I would like to know if anyone else is having this problem or if it is just from the updates and needs a fix.

**Comment by PabstMirror** [comment] 2016-02-25 05:20
Was the mission made in the 3d editor?
RPT would be useful

**Comment by DJKITTS** [comment] 2016-02-25 06:28
Yes I stated that in the steps to produce. I am very new and I just wanna play the damn game sorry I really don't know much about this site. It was a last resort.

**Comment by Sparfell** [comment] 2016-02-25 12:38
Hi. I think I experienced the same issue yesterday during a coop mission (created with 2D editor). It looked like the vanilla hitpoint were not healed by the PAK (we use it only to fix "broken" legs and arms). I'll try to test it properly in the evening but I can't promise.

**Comment by DJKITTS** [comment] 2016-02-25 13:24
Can you revive anyone anymore? I tried CBA and ACE  alone and still couldn't revive anyone. I set the modules up perfectly in both single and multiplayer.

**Comment by foxdeuce** [comment] 2016-02-27 10:50
Hello! Our server and missions are having the same problem after the Eden Update, pretty sure that ACE Team needs to come out with a Hotfix. A buddy of mine and myself, well versed in ArmA/OFP Logic, tried several different combinations of new and older versions of CBA and ACE with no luck obviously. Also going in to the different modules trying combinations of options, allowing the use of PAKs and Surgical Kits for everyone and just about every other combination in all the ACE Medical Modules. Bottom line even though you have a PAK(s), and Surgical Kits, there is no option to use them anywhere, in the Medical Menu, or 3D Menu.

Good News though Basic Medical Works... Yeah

Hope the info was valuable, next step is to sift through the server logs to see if I can find any hints.

**Comment by ender2078** [comment] 2016-02-29 22:08
Hey guys, please see my issue that was just posted, Foxdeuce and I have been working on this issue for days trying to narrow down the problem, and a possible workaround. I'm happy to report we found the issue, hopefully this might also solve any problems you are having right now. Please visit this link to get the details https://github.com/acemod/ACE3/issues/3478

**Comment by esteldunedain** [comment] 2016-02-29 22:15
Duplicate of #3478

**Closed by esteldunedain** 2016-02-29 22:15 UTC
Labels: need more info
