### ISSUE TITLE
The MAR-10 is able to use 7,62 ammo

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#914] opened 2015-04-29 12:14 UTC
ACE3 Version: 3.0.0.1 last commit d149db61e8ca98384a19e7b1381c9bc2f68452a5

**Mods:**
- @cba_a3
- @ace3

**Placed ACE3 Modules:**
- none

**Description:**
The MAR-10 "noreen bad news" is able to use the following 7,62 magazines
7,62mm 20Rnd Mag (Mk248 Mod 0)
7,62mm 20Rnd Mag (Mk248 Mod 1)
7,62mm 20Rnd Mag (Berger Hybrid OTM)

**Steps to reproduce:**

go to the virtual arsenal
equip the "noreen bad news"
notice that you can use the mags listed above

optional
place a unit in the editor
obtain a "noreen bad news"
obtain one of the previous magazines
reload one of those

**RPT log file:**
nothin'

**Comment by ulteq** [comment] 2015-04-29 14:44
We deliberately chose to allow the use of calibers which would normally require rechambering of the weapon (barrel/bolt change).

The Noreen "Bad news" URL can shoot **.338 Lapua Magnum** and **.300 WinMag**:
http://world.guns.ru/sniper/sniper-rifles/usa/noreen-e.html

It can not shoot 7.62 NATO.

**Comment by Brisse89** [comment] 2015-04-29 17:54
I think this will confuse a lot of players. How about some kind of scripted solution where the barrels and bolts are actual items and you can do a barrel swap using the interaction system? Barrel and bolt could be the same item, perhaps called "rechambering kit"?

**Comment by dixon13** [comment] 2015-04-29 17:59
^yeah that would be nice. But for now the feature should be kept for realism.

**Comment by ulteq** [comment] 2015-04-29 19:40
> Barrel and bolt could be the same item, perhaps called "rechambering kit"?

Example: http://www.barrettrifles.com/c-541-mrad.aspx

![](http://www.barrettrifles.com/images/Product/large/14283.jpg)

**Comment by jaynus** [comment] 2015-04-30 20:27
I don't understand how allowing players to use a few types of ammo is more confusing than making them go through a random barrel swapping mechanism for only a specific weapon?

**Comment by Brisse89** [comment] 2015-04-30 21:15
It's confusing because people think it is a bug. If there's a proper game mechanic for converting to another caliber, then it will be clear that it is in fact a feature. It's a better way to present the feature to the player. As it is right now, it's not presented at all. Me and you both know it's not a bug jaynus, but I'm pretty sure we are representing a very small percentage of players in that regard.

**Comment by ulteq** [comment] 2015-04-30 22:37
An additional weapon (MAR-10 .300 WinMag) would be good enough for me. Having a conversion kit would be just the icing.

**Comment by Harakhti** [comment] 2015-05-01 18:05
Conversion mechanism: Replace player's held weapon with the other (different caliber) weapon using the different ammunition type (Leaving you with enough useless "old caliber" ammunition to make a stack out of), and have a dedicated item help perform the action intent.

**Comment by brainslush** [comment] 2015-05-03 09:50
Or how about just creating a second weapon? Mar10 300WinMag or something like that. I think no one will start chaning the barrel of a high precission weapon mid-mission.

**Comment by Harakhti** [comment] 2015-05-03 10:19
@brainslush What I roughly covered down implies a second weapon already implemented and usable if necessary, given that's what such a script would switch to. Have to agree that covariants would be nice with or without such a feature.

**Comment by Salluci** [comment] 2021-11-02 21:30
Addressed by #8410 and #8395.

**Closed** 2021-11-02 21:51 UTC
Labels: kind/enhancement, status/discussion
