### ISSUE TITLE
Cannot find base )ace_medical_openwounds for /value/Item2/data/value/Item1/data/type/

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#543] opened 2015-04-13 08:37 UTC
Testing Session 2015 04 12

`Cannot find base )ace_medical_openwounds for /value/Item2/data/value/Item1/data/type/`

**Comment by jaynus** [comment] 2015-04-13 15:01
I can only guess this is a typo in a macro expansion on a dynamic class lookup somewhere. Probably can find it with looking for GVAR(openWounds) and looking for the typo. I'm not sure where we do class reads for this tho

**Comment by Glowbal** [comment] 2015-04-13 16:15
We shouldn't. OpenWounds is not supposed to be used for any config look ups; it's just a variable. 

I did a search through master and couldn't find any openWounds with either incorrect macros or config reads.

**Comment by Glowbal** [comment] 2015-04-14 09:31
We discussed this last night:

* May be caused by to large arrays for object setvariables. Suspected because of messages found in my rtp logs from the test session on sunday. 
`Unexpected array size (size=6242 message struct NetworkMessageObjectSetVariable, item value)`,
`Value type not matching:  != Array`
* I will do a test on a dedi this week and see if I can reproduce.
* A work around for this would be going back to the event based synchronization approach.

**Comment by jaynus** [comment] 2015-04-14 21:48
After investigating with @glowbal more, it seems this is probably due to network stack corruption. Most likely, this was caused by packet loss on the server side corrupting everyones inbound messages; Eventually causing crashes. 

This is a documented set of errors from BI which is usually caused by memory corruption.

**Comment by Glowbal** [comment] 2015-04-17 19:29
Closing this as it doesn't appear to be our fault.

**Closed by Glowbal** 2015-04-17 19:29 UTC
Labels: bug
