### ISSUE TITLE
Issues with non adjustable scope zeroing

### ISSUE THREAD

**Issue by SGarcia78** [acemod/ACE3#6123] opened 2018-02-05 20:46 UTC
**Arma 3 Version:** `1.80` (stable / rc / dev)
**CBA Version:** `3.6` (stable / dev + commit hash)
**ACE3 Version:** `3.12.1` (stable / dev + commit hash)

**Mods:**
ACE 3
RHS USAF
RHS AFRF
RH M4/16
ARES
- CBA_A3
- ace

**Description:**
I understand only long range scopes can be zeroed, ace works fine with zeroing them, my issue is with non zeroing scopes such as ERCO, MRCO, RED DOT SIGHTS AND PISTOLS being zeroed at 200-300-350 meters without being able to adjust or lower to 100 meters manually. Let me try to explain, ANY pistol with a zeroing of 50m in the upper right corner shooting at a targets head 50m away will miss, aiming center mass or slightly lower at said target will head shot. The same goes for any non zeroing sights as mentioned above,  for example the ERCO starts with a 300m zeroing in the upper right corner and cannot manually adjust it, so you have to basically aim at the bellybutton to hit a head shot, red dot sights are starting at 200m upper right corner, same effect, cannot manually adjust. I've tried different settings in ace scopes settings with only minor success being pistol sights are on target and main sights are off target, or both are off target. Also weapons with NO scope attachment base zeroing works fine with page up/page down. I'm not sure if I've made my issue clear enough, but if anyone can shed some light on this I'd much appreciate it.
Thank You

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
Self Hosted Multiplayer and Eden Editor

**Placed Modules:**
None

**RPT log file:**
I apologize I don't know where to find this Log.

**Comment by xrufix** [comment] 2018-02-06 07:02
Combat optics like RCO, ERCO, MRCO, ARCO are not meant to be zeroed by design. The reticle has markings for different distances. It is necessary to aim lower if you shoot at nearer targets. Most of the mentioned sights have markings for 200m, and below that range, hitting a target with 2x magnification should really not be a problem. 

Red dot sights like ACO or the backup sights on RCO etc., are zeroed for 200m and again, by design, are not meant to be zeroed otherwise.

Iron sights are, however, meant to be zeroed to different distances and IRL as well as on the model have knobs etc. to do so.

Everything fine imo.

**Comment by PabstMirror** [comment] 2018-02-06 08:14
Which specific handgun where you using?
None of the ones I tried listed what their zero was and seemed to fire normally.

There is a settings `ace_scopes_correctZeroing` "Correct zeroing" that you might want to try disabling.

**Comment by BaerMitUmlaut** [comment] 2018-02-06 18:16
I can confirm pistols will miss with simplified zeroing and I've created s seperate issue for that (#6126). I'm dead on with ACO, ERCO, MRCO and DMS though (magnified sights were tested at 100m, 400m and 600m).

**Comment by SGarcia78** [comment] 2018-02-06 19:18
I understand that the ERCO, HAMR, RCO, etc cannot be adjusted. What I mean with those is that the zero is off on them, for instance the ERCO has a half circle then you’ve got your vertical line with your range marks, when I fire with a range of 300m my shot fires from above the half circle. 

As for what pistols I was using they were RHS PM, 1911, M9 and a couple others from that pack. 

Also the correct zeroing is a setting I was playing with turning off and on to test the issue, but for me it only fixed the pistols issue of being off target, it had no effect on combat optics.

**Comment by PabstMirror** [comment] 2018-02-06 19:35
SGarcia78 - are you using the simplfied zero setteing?

**Comment by SGarcia78** [comment] 2018-02-06 19:43
Yes, I was.

**Comment by SGarcia78** [comment] 2018-02-07 03:57
Just got in from work and turning off the simplified zeroing setting has fixed this issue for me, but obviously the simplified zeroing feature is broken.

Thanks for the responses so quickly and helping me figure this issue out. I love ACE and couldn’t imagine playing ARMA without it, keep up the good work guys.

**Comment by PabstMirror** [comment] 2018-02-08 18:01
I think this will be fixed by #6128
Will try to do more testing

**Comment by PabstMirror** [comment] 2018-04-18 02:55
Should be fixed with next release (3.12.2)

**Closed** 2018-04-18 02:55 UTC
Labels: kind/bug
