### ISSUE TITLE
Bug report about ACE medical system

### ISSUE THREAD

**Issue by Dobakjang** [acemod/ACE3#1465] opened 2015-06-01 16:00 UTC
ACE3 Version: 3.0.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
hearing
explosive system
blue force tracking
respawn system
weather
advanced ballistics
mk6 settings
wind deflection
micro dagr map fill
medical settings
revive settings
advanced medical settings
set medic class
set medical vehicle
set medical facility

**Description:**
I'm not sure is it bug or not

1. sometimes when i get shot i have no injuries in ACE interaction and can see visually that my body is injured but can't run, you can run after apply PAK but if you being hit again you will walk again
i highly assume that it's happening because falling damage, i can rapdly seeing this symptom when people get falling damage.

2. and sometimes i can't revive my team mate, his pulse and blood pressure is on stable no bleeding but can't revive him he just lie down there, we can make him with PAK but we should wake him with out PAK.

3.  i can hear medical treatment sound that keep over looping, the only solution about this is respawn and come back

**Steps to reproduce:**
being shot and watch the symptom 

**Where did the issue occur?**
"Multiplay", host by in multiplay session not like TADST or other dedicated server tool 
but it's also happening in dedicated server too. 

**RPT log file:**
none

**Comment by ulteq** [comment] 2015-06-01 17:08
Most likely a duplicate of this: https://github.com/acemod/ACE3/issues/1354

**Comment by Glowbal** [comment] 2015-06-01 17:15
It is but it also contains 2 other bug reports.

Could you please be more specific about the sometimes? Could you describe the situation? Got any numbers for the vitals? 

Also I would like an rtp log and the settings used, as well as some more concrete steps to reproduce this.

@PabstMirror The issue number 3 here might be related to #1463

**Comment by ArcanumSK** [comment] 2015-06-02 06:25
Our group can experience the second one. We can bandage all wounds, stich it up witch surgical kit (its still showing as bandaged, don't know if it should ?). Start the heart, get pulse on 90ish, refill blood, get rid of pain. Guy is completly ok but unconcious, cannot perform CPR or whatever. Sometimes works atropine overdose combined with epi. 
Modules config:

class ace_common_forceAllSettings {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_frag_enabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_interaction_EnableTeamManagement {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_magazinerepack_TimePerAmmo {
    value = 1.5;
    typeName = "SCALAR";
    force = 1;
};
class ace_magazinerepack_TimePerMagazine {
    value = 2;
    typeName = "SCALAR";
    force = 1;
};
class ace_magazinerepack_TimePerBeltLink {
    value = 8;
    typeName = "SCALAR";
    force = 1;
};
class ace_map_BFT_Interval {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_map_BFT_Enabled {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_map_BFT_HideAiGroups {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_map_mapIllumination {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_map_mapShake {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_map_mapLimitZoom {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_map_mapShowCursorCoordinates {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_maptools_EveryoneCanDrawOnBriefing {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_microdagr_MapDataAvailable {
    value = 2;
    typeName = "SCALAR";
    force = 1;
};
class ace_mk6mortar_airResistanceEnabled {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_mk6mortar_allowComputerRangefinder {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_mk6mortar_allowCompass {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_nametags_showCursorTagForVehicles {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_nametags_PlayerNamesViewDistance {
    value = 5;
    typeName = "SCALAR";
    force = 1;
};
class ace_nametags_PlayerNamesMaxAlpha {
    value = 0.8;
    typeName = "SCALAR";
    force = 1;
};
class ace_respawn_SavePreDeathGear {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_respawn_RemoveDeadBodiesDisconnected {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_respawn_BodyRemoveTimer {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_switchunits_EnableSwitchUnits {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_switchunits_SwitchToWest {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_switchunits_SwitchToEast {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_switchunits_SwitchToIndependent {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_switchunits_SwitchToCivilian {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_switchunits_EnableSafeZone {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_switchunits_SafeZoneRadius {
    value = 100;
    typeName = "SCALAR";
    force = 1;
};
class ace_vehiclelock_DefaultLockpickStrength {
    value = 10;
    typeName = "SCALAR";
    force = 1;
};
class ace_vehiclelock_LockVehicleInventory {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_vehiclelock_VehicleStartingLockState {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_weather_enableServerController {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_weather_useACEWeather {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_weather_syncRain {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_weather_syncWind {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_weather_syncMisc {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_weather_serverUpdateInterval {
    value = 120;
    typeName = "SCALAR";
    force = 1;
};
class ace_winddeflection_enabled {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_winddeflection_vehicleEnabled {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_winddeflection_simulationInterval {
    value = 0.05;
    typeName = "SCALAR";
    force = 1;
};
class ace_winddeflection_simulationRadius {
    value = 3000;
    typeName = "SCALAR";
    force = 1;
};
class ace_explosives_RequireSpecialist {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_explosives_PunishNonSpecialists {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_hearing_EnableCombatDeafness {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_hearing_EarplugsVolume {
    value = 0.5;
    typeName = "SCALAR";
    force = 1;
};
class ace_hearing_UnconsciousnessVolume {
    value = 0.4;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_level {
    value = 2;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_medicSetting {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_enableFor {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_enableOverdosing {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_bleedingCoefficient {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_painCoefficient {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_enableAirway {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_enableFractures {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_enableAdvancedWounds {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_enableVehicleCrashes {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_enableScreams {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_playerDamageThreshold {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_AIDamageThreshold {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_enableUnconsciousnessAI {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_preventInstaDeath {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_enableRevive {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_maxReviveTime {
    value = 600;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_amountOfReviveLives {
    value = -1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_allowDeadBodyMovement {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_allowLitterCreation {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_litterCleanUpDelay {
    value = 1800;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_medicSetting_PAK {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_medicSetting_SurgicalKit {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_consumeItem_PAK {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_consumeItem_SurgicalKit {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_useLocation_PAK {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_useLocation_SurgicalKit {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_keepLocalSettingsSynced {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_healHitPointAfterAdvBandage {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_allowUnconsciousAnimationOnTreatment {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_moveUnitsFromGroupOnUnconscious {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_menuTypeStyle {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_advanced_ballistics_enabled {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_alwaysSimulateForSnipers {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_disabledInFullAutoMode {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_onlyActiveForLocalPlayers {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_ammoTemperatureEnabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_barrelLengthInfluenceEnabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_bulletTraceEnabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_simulationInterval {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_advanced_ballistics_simulationRadius {
    value = 3000;
    typeName = "SCALAR";
    force = 1;
};;

**Closed** 2015-06-11 08:25 UTC
Labels: bug
