### ISSUE TITLE
ACE 3 Advanced Ballistics Game Crash

### ISSUE THREAD

**Issue by JinougaF** [acemod/ACE3#6058] opened 2018-01-17 14:47 UTC
**Arma 3 Version:** `1.80` (stable / rc / dev)
**CBA Version:** `3.5.0` (stable / dev + commit hash)
**ACE3 Version:** `3.12.1` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- When using the Advanced Ballistics Module shooting a gun will cause a game crash with the error "String STR_A3_Fighter_03_Canopy_name not found
 String STR_A3_Fighter_03_Canopy_name not found"
Reinstalling ACE 3, ARMA 3, and CBA could not fix this issue. it is only present when the Advanced Ballistics Module is placed and enabled.

**Steps to reproduce:**
- start Arma 3, Open Editor, Place Advanced Ballistics Module, Start Scenario, Shoot, Crash.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- ACE 3: Advanced Ballistics

**RPT log file:**
https://gist.github.com/JinougaF/46ee5fe6482dd54b0701be15210a581c

**Comment by dedmen** [comment] 2018-01-17 15:41
Duplicate of #5976

**Closed** 2018-01-17 16:12 UTC
Labels: status/duplicate
