### ISSUE TITLE
Medical options on the Windows Keys Menus made Optional. (Toggle able on/off on the Config Menu)

### ISSUE THREAD

**Issue by lsvalmont** [acemod/ACE3#6735] opened 2018-12-16 00:00 UTC
**Arma 3 Version: Stable, latest.
**CBA Version:** Stable, latest.
**ACE3 Version:** Stable, latest.

**Mods:**
- CBA_A3
- ace

**Description:**
- Since the implementation of the Medical Menu (H) the need for both the self interaction medical menus and the interactions with other units' medical options should be made optional.

**Steps to reproduce:**
- Not an issue, but a suggestion. 

**Where did the issue occur?**
- All Scenarios. 

**Additional information:**
- If you check out most of the streamers videos in twitch/youtube etc you can confirm that a great percentage of them just use the Medical Menu (H) since it is faster and easier to understand and also allows for both self medical attention as well as giving medical attention to others.

Because of that I want to suggest to make the self interact and regular menu (windows keys) medical options... optional. Just like Group Management and Gestures can also be disabled from the Ace Config Menu.

That way we will have less clutter and we can add more actions to both the windows keys menus.

Thanks and keep up the amazing work!

**Comment by PabstMirror** [comment] 2018-12-16 01:07
You can disable the menu for other people 
Ace medical->Style of menu (Medical)->Disabled

We would probably have to add a new setting for self-interaction medical menu

**Comment by severgun** [comment] 2018-12-17 11:52
interaction menu offer more situation awareness than big black window.

**Comment by lsvalmont** [comment] 2018-12-21 11:09
Yes, that is why it should be made optional, players who want to keep it in their interaction menu just shouldn't check the option in the settings. Most of us just use the H menu since in reality you would be focusing on healing the wounded fast and not really checking for enemies at that particular time. Have you ever seen a medic on a real battlefield applying a bandage to a wounded soldier while also checking for enemies?

**Comment by Drofseh** [comment] 2018-12-21 20:57
I don't understand the point of this.
If you don't want to use the interaction menu medical then just don't use it.
Making a setting to disable it will just add bloat and confuse people.

**Comment by jonpas** [comment] 2018-12-21 21:05
@Drofseh interaction you never use because you instead use the other menu is bloat. This is a duplicate of https://github.com/acemod/ACE3/issues/3829

**Closed** 2019-01-12 02:58 UTC
