### ISSUE TITLE
Please delete any unnecessary interaction with destroyed units.

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2671] opened 2015-10-03 11:29 UTC
ACE3 Version: 3.3.2
Stable version 1.52

**Mods:**
* `@CBA_A3`
* `@ace`
* `@DragonFyre`

**Placed ACE3 Modules:**
None

**Description:**
Any destroyed/dead unit  in the ACE3 (corpses, vehicles, turrets etc), continues to have interaction with the player via interaction menu. For example, after the destruction of the static turrets, interaction menu offers the player can check the number of munition and shows the presence and quantity of ammunition inside destroyed turret!
Or in the interaction menu with a dead soldier, there is a possibility of bandage a dead body, with the indicators of damage of individual parts of the body. If the soldier died, it makes no sense to treat it. In this case, every dead soldier creates a meaningless lists in interaction menu, which complicates the player control.
Or if car M-ATV is completely destroyed and only fragments remain, then the interaction menu shows the availability of the cargo compartment.  If vehicle fully destroyed, then this unit, already no has a cargo compartment.
This details  at least it looks absurd and also creates meaningless information for the player. Please delete any unnecessary interaction with destroyed or dead units.

**Steps to reproduce:**
Interact via interaction menu with destroyed/dead unit  in the ACE3 and you will see a lot of senseless actions.

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by jokoho48** [comment] 2015-10-03 11:32
http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html

**Comment by commy2** [comment] 2015-10-03 14:51
I'm pretty sure the bandaging part is by design.
Check ammo can certainly be removed on kaputt static weapons.
cargo is already fixed in dev.

Did you notice anything else?

- [ ] disable ammo check on destroyed static weapons

**Comment by jokoho48** [comment] 2015-10-03 14:53
@commy2 i think for Medical we can add a setting if its shown on dead Objects what did you think?

**Comment by commy2** [comment] 2015-10-03 14:57
Too many settings distracting from more useful stuff. Not immediately seeing that someone is dead, because certain menu options don't pop up is a design decission. Then again, medical is not my domain, so don't ask me.

**Comment by dvdbrewster** [comment] 2015-10-03 15:11
Its good to check status  of down bodies. They have not despawned so it would be cheating if you did not have to check to see if they are alive.

**Comment by mickeymen** [comment] 2015-10-03 16:34
"I'm pretty sure the bandaging part is by design"
My friend this is bad design and meaningless design. Sometimes a dead soldier can lie next to another object or allied soldier. Or for example, next to launcher. In this case, the apeared menu of interaction, prevents the player to understand what exacly to choose. I think, there is no reason to do the interaction with dead units.

"Did you notice anything else?"
Now can't remember. I think it makes no sense to check each dead unit for bugs with the menu of interaction. It is NECESSARY simply to deprive all the dead objects interact with the player. It will be a radical treatment for all bugs ;)

**Comment by commy2** [comment] 2015-10-03 17:29
>It is NECESSARY simply to deprive all the dead objects interact with the player. It will be a radical treatment for all bugs ;)
I disagree. There certainly are some actions, maybe future ones, that should be enabled on dead bodies and maybe even destroyed vehicles.

**Comment by mickeymen** [comment] 2015-10-03 17:33
The owner is always king for your mod. It's just my opinion:/ I report only my experience. These details are bothering me.

**Comment by commy2** [comment] 2015-10-03 17:55
Well you are certainly right about the Cargo and Check ammo actions. No comments to medical, because that's not my forte.

**Comment by SilentSpike** [comment] 2015-10-04 11:51
I agree that:
- Too many settings just over-specifies the system (i.e. are unnecessary)
- Having medical actions on the dead makes sense because it makes for a consistent player experience

**Closed** 2015-10-06 17:36 UTC
Labels: bug
