### ISSUE TITLE
.50 cal damage - it takes up to 8 limb shots to kill

### ISSUE THREAD

**Issue by Gwynblade** [acemod/ACE3#3167] opened 2016-01-15 21:05 UTC
ACE3 Version: 3.4.2
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
- `@CBA_A3`
- `@ace`

**Placed ACE3 Modules:**
None

**Description:**
It takes a lot of limb shots to kill someone with .50 cal (also .408). Most times it's 4-5, up to 8. In **very** rare cases it kills in one leg shot. Causes medium to large velocity and avulsion wounds.

https://www.youtube.com/watch?v=g5ZOVqrSWuo&feature=youtu.be

The weird thing is, after .50 cal I tested it with a 9mm pistol. It seems to be exactly the same situation, units can take a lot of shots to the limbs, maxing it out around 8 like .50 cal. Also it sometimes manages to kill a unit with 1 leg shot. The wounds it causes are same - medium to large (velocity/avulsion).

Which might mean the .50 cal is not the only problem, maybe shots to the limb don't take caliber into the account?

**Where did the issue occur?**
Tested in editor

**Comment by PabstMirror** [comment] 2016-01-16 15:26
Do you use basic or advanced medical?

I have noticed this as well, I believe the idea behind the design is that limb kills don't kill in real life from the impact, but through blood loss.

Looking at determineIfFatal, limbs have a very low chance of directly causing death.

We might want to look at making blood loss non-linear for the damage done to the part.  A 50cal shot that would probably destroys a major artery should make the target combat ineffective within seconds.

**Comment by Gwynblade** [comment] 2016-01-16 16:18
This was recorded in advanced, but it's pretty much the same on basic from what I saw.

I do like that design (limb shots not killing easily). But in this case, with .50 BMG - it should be more severe. 

I don't think you could bandage yourself alone after getting shot in the leg with it (if there was much left to bandage). So my suggestion would be to force the guy unconscious (not being able to wake up - after one limb shot), and have him bleed out pretty fast (like you said). 

If you really want to make it survivable, I'd say make it only possible if the teammates react fast and help him.

- Only my opinion ofcourse.

**Comment by Glowbal** [comment] 2016-01-16 20:54
I will investigate this soon and see if we can come up with some ideas.

**Comment by Gwynblade** [comment] 2016-01-16 21:41
:thumbsup:

**Comment by TheGrandVizier** [comment] 2016-01-27 09:09
I have noticed this while sniping with 3CB 50cal sniper rifle (pardon, do not recall the name).
It took more than 5 shots to kill an individual, regardless of where i hit him.

**Comment by Gwynblade** [comment] 2016-01-27 21:19
Weird, maybe you have some other mods that cause problems?
For me this only happens with limbs, torso shots are instant kills.

**Comment by DLEGION** [comment] 2016-10-21 19:50
hello. 
a new patch...and still this problem. 
seriously guys... for me and my team its game-breaking. Its a total unrealistic nosense that a soldier takes 7-8 shots of 7.62x51mm caliber in each leg or an arm for a grand total of a full magazine and still go around being able to shoot back! try being shot by a 9mm handgun, then you tell me if you can still fight!
everytime a patch is almost ready this problem get shifted to next milestone....i'm a bit tired of fix it myself everytime. and i did it in few hours just becasue i didnt knew the code! for you its a 1 second fix!
please , please, please, fix it once for all! huge thanks !

**Comment by commy2** [comment] 2016-10-21 20:58
@DLEGION the medical-rewrite isn't done yet. Whining won't help the progress.

**Comment by Phyma** [comment] 2017-05-26 11:39
Im not 100% what "_projectile" is but if it is the bullet like "B_408_Ball" then you could take out the caliber part of it and just scale that with the damage in fnc_handle_Damage"?

so after private _typeOfDamage you could do a:

`private _caliber = if( isNumber(configFile >> "CfgAmmo" >> _projectile >> "caliber") then { getNumber(configFile >> "CfgAmmo" >> _projectile >> "caliber");};`

and then use that somehoe  in your damage calculation?

Take care!

**Comment by jonpas** [comment] 2019-09-28 21:37
Closing as it's old and does not seem to happen as directly in rewrite - unconsciousness and blood loss will kill the victim quickly, however direct limb shots will not (by design).

**Closed by jonpas** 2019-09-28 21:37 UTC
Labels: kind/Focus Feature, status/discussion
