### ISSUE TITLE
Cannot interact with respawn gui when dying from unconsciousness

### ISSUE THREAD

**Issue by Arcanum417** [acemod/ACE3#7356] opened 2020-01-02 11:50 UTC
**Mods:**
- **Arma 3:** `1.96.146114` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.13.0`
- **ACE3:** `3.13.0`
_Made sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
When dying from unconsciousness you cannot interact with respawn UI. Unconsciousness restrictions on iteraction do not end on death. I consider this a game breaking bug.

**Steps to reproduce:**
- Run arma with ACE3 and CBA only
- (optional) create new profile so you can run default ace settings
- Create new multiplayer mission in editor
- Place one BLUFOR unit, set variable name `test_sld`
- create one marker with cariable name `respawn_west`
- create one zeus game master module set `owner` as `test_sld`
- ensure you have default ACE settings set
- save the mission
- Create `description.ext` in the folder of the mission
- Paste this in description.ext
```
respawn = 2;
respawnDelay = 1;
respawnTemplates[] = {"MenuPosition","MenuInventory","Tickets","Spectator"};
```
- run the mission in listen server multiplayer
- click on respawn
- spawn BLUFOR AI from zeus
- shoot your character once in the chest (make him go unconscious but not outright dead)
- wait 10s
- shoot your character until it dies
- be presented with the respawn screen but be unable to click respawn or anything else

**Expected behavior:**
Be able to click respawn after dying from unconsciousness.

**Where did the issue occur?**
- Dedicated and Self-Hosted Multiplayer

**Comment by zharf** [comment] 2020-01-02 18:28
Are you sure this isn't because you were remote controlling another character when you died? Try pressing zeus key on the map again to see if that helps

**Comment by Arcanum417** [comment] 2020-01-02 18:29
Nope, also tested on a dedicated server without any zeus involvement (killed by another player the same way).

**Comment by JANXOL** [comment] 2020-01-02 21:51
Can confirm, also experienced the issue. Tested on a dedicated server with multiple people, no remote control involved. When shooting an uncosncious character and killing him, that player is unable to respawn or interact with UI, and has to be kicked and rejoin.

**Comment by TheRealSpaceHippo** [comment] 2020-01-03 02:16
I'm experiencing the same issue.

**Comment by chazbotic** [comment] 2020-01-03 04:55
my unit and i are also experiencing this issue. this issue occurs regardless if the player dies from cardiac arrest or is instantly killed (by script or applied damage from a very large explosion, for example).

a mission where the player is forced to respawn results in the respawned unit having the same injuries they had when they died.

**Comment by drmattsuu** [comment] 2020-01-04 23:42
We're also experiancing this exact issue (Updated the server 2 days ago, took us a while to figure it out).

**Comment by commy2** [comment] 2020-01-05 00:20
Not a single RPT log file.

**Comment by zharf** [comment] 2020-01-05 13:33
Here you go, but I'm telling you there's nothing in there.
[Arma3_x64_2020-01-05_15-24-18.txt](https://github.com/acemod/ACE3/files/4023421/Arma3_x64_2020-01-05_15-24-18.txt)

I did notice that it seemed to happen when the eyes were trying to open... I'll do some more testing and see if I can come up with a script to reproduce it

**Comment by zharf** [comment] 2020-01-05 13:59
```sqf
["ace_medical_knockOut", player] call CBA_fnc_localEvent;
[{ player setDamage 1; }, [], 3] call CBA_fnc_waitAndExecute;
```

will reproduce this every time

**Comment by zharf** [comment] 2020-01-05 15:10
```sqf
["ace_killed", { ["unconscious", false] call ace_common_fnc_setDisableUserInputStatus; }] call CBA_fnc_addEventHandler;
```

Running this fixes it, the problem is that when unconscious ACE disables user input but only gives it back after the player receives a new unit to play with, in this case however, the user doesn't get a new unit until they press the respawn button on the display.

**Comment by SilentSpike** [comment] 2020-02-04 11:18
This should now be fixed on master, will close once confirmed

**Comment by Arcanum417** [comment] 2020-02-04 16:05
I will try to test it today.

**Comment by SilentSpike** [comment] 2020-02-04 17:05
Thanks, would usually test this stuff myself but don't have my computer setup for arma development at the moment

**Comment by jonpas** [comment] 2020-02-22 22:18
Will be re-evaluated after 3.13.1 release.

**Comment by PabstMirror** [comment] 2020-03-10 03:13
Let us know if this is still an issue after today's patch

**Comment by WolffeUS** [comment] 2020-03-11 19:28
Looks fixed after testing in local MP using the code from @zharf

**Comment by Arcanum417** [comment] 2020-03-11 19:33
Indeed, seems fixed to me.

**Comment by chazbotic** [comment] 2020-03-11 19:59
can confirm, both respawning and playing around with spawn settings (select custom position, type base, type instant, et c) seem to be working as expected.

**Closed** 2020-03-11 20:08 UTC
Labels: kind/bug

**Comment by Lohwan** [comment] 2021-12-31 22:32
Hello,
Not sure if this issue has been fixed on the official release of ACE but me and my buddies are still experiencing this issue. Some help would be greatly appreciated.

**Comment by bux** [comment] 2022-01-01 06:52
@Lohwan 
Please don't revive old issues. [Open a new one](https://github.com/acemod/ACE3/issues/new/choose) and fill out the issue template and don't forget the RPT file.

**Comment by warlocc** [comment] 2023-02-16 21:39
This issue has not been fixed.
